### ISSUE TITLE
mongodb timeout from agent

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1035]
```
Traceback (most recent call last):
  File "/scratch/users/osg/gram_scratch_zXSv1H/glide_ERr9RQ/execute/dir_460/ve_xd-login/rp_install/bin/radical-pilot-agent-multicore.py", line 672, in <module>
    bootstrap_3()
  File "/scratch/users/osg/gram_scratch_zXSv1H/glide_ERr9RQ/execute/dir_460/ve_xd-login/rp_install/bin/radical-pilot-agent-multicore.py", line 481, in bootstrap_3
    _, mongo_db, _, _, _  = ru.mongodb_connect(cfg['mongodb_url'])
  File "/scratch/users/osg/gram_scratch_zXSv1H/glide_ERr9RQ/execute/dir_460/ve_xd-login/rp_install/lib/python2.7/site-packages/radical/utils/misc.py", line 92, in mongodb_connect
    mongo = pymongo.MongoClient (host=host, port=port, ssl=ssl)
  File "/scratch/users/osg/gram_scratch_zXSv1H/glide_ERr9RQ/execute/dir_460/ve_xd-login/lib/python2.7/site-packages/pymongo/mongo_client.py", line 377, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: timed out
```

Probably something we want to handle better.

**Comment by andre-merzky** [comment]
closing in favor of #1129
