### ISSUE TITLE
DB name resolving Error

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1036]
Should this at least retry for a couple of times?

```
2016-06-02 16:25:52,390: radical.pilot       : MainProcess                     : Thread-3       : DEBUG   : uworker Thread-3 stopped otransfer OutputFileTransferWorker-2
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/iparask/VirtualEnvs/LeafletExps/local/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 236, in run
    unit_list = self._dbs.get_compute_units(unit_manager_id=self.uid)
  File "/home/iparask/VirtualEnvs/LeafletExps/local/lib/python2.7/site-packages/radical/pilot/db/database.py", line 428, in get_compute_units
    for obj in cursor:
  File "/home/iparask/VirtualEnvs/LeafletExps/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1076, in next
    if len(self.__data) or self._refresh():
  File "/home/iparask/VirtualEnvs/LeafletExps/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1020, in _refresh
    self.__uuid_subtype))
  File "/home/iparask/VirtualEnvs/LeafletExps/local/lib/python2.7/site-packages/pymongo/cursor.py", line 933, in __send_message
    res = client._send_message_with_response(message, **kwargs)
  File "/home/iparask/VirtualEnvs/LeafletExps/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1199, in _send_message_with_response
    sock_info = self.__socket(member)
  File "/home/iparask/VirtualEnvs/LeafletExps/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 928, in __socket
    "%s %s" % (host_details, str(why)))
AutoReconnect: could not connect to ds031671.mlab.com:31671: [Errno -3] Temporary failure in name resolution
```

**Comment by andre-merzky** [comment]
A failure in resolving a DNS address is usually not solvable by retrying, it indicates an error in network setup or connectivity.  RP resilience against interruptred connections on MongDB level is already covered by other tickets, so I am going to close this one.
