### ISSUE TITLE
Client running out of memory while initializing session

### ISSUE THREAD

**Issue by solejar** [radical-cybertools/radical.pilot#1037]
Hi All,

Was trying to run the leaflet_finder.py script from the MIDAS repo, and ran into this error as the session was initializing:

```
2016-06-07 18:26:41,929: radical.pilot       : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
2016-06-07 18:26:41,929: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      pid: 19038
2016-06-07 18:26:41,929: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2016-06-07 18:26:41,930: radical.pilot       : MainProcess                     : MainThread     : INFO    : radical.pilot        version: v0.40.1-38-ga1e892c@feature-spark
Creating a session
Traceback (most recent call last):
  File "submit_bot.py", line 83, in <module>
    session = rp.Session()
  File "/home/sean/sparkTestEnv/local/lib/python2.7/site-packages/radical/pilot/session.py", line 90, in __init__
    saga.Session.__init__ (self)
  File "/home/sean/sparkTestEnv/local/lib/python2.7/site-packages/saga/session.py", line 230, in __init__
    default_session     = _DefaultSession ()
  File "/home/sean/sparkTestEnv/local/lib/python2.7/site-packages/radical/utils/singleton.py", line 32, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/sean/sparkTestEnv/local/lib/python2.7/site-packages/saga/session.py", line 139, in __init__
    default_ctxs = info['adaptor_instance']._get_default_contexts ()
  File "/home/sean/sparkTestEnv/local/lib/python2.7/site-packages/saga/adaptors/context/ssh.py", line 157, in _get_default_contexts
    if  not subprocess.call (["sh", "-c", "grep ENCRYPTED %s > /dev/null" % key]) :
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
  File "/home/sean/sparkTestEnv/local/lib/python2.7/site-packages/radical/utils/atfork/atfork.py", line 170, in os_fork_wrapper
    pid = _orig_os_fork()
OSError: [Errno 12] Cannot allocate memory
```

It seems to be a client issue with not having enough memory to start the RP processes.
Curiously enough, I was able to find a slightly hacky solution in the form of:

`echo 1 > /proc/sys/vm/overcommit_memory`

Even still, I thought it was worth creating a ticket.

**Comment by andre-merzky** [comment]
Indeed, thanks for opening the ticket!

This is a very unexpected error...  Would you mind attaching the script (`submit_bot.py`)?  On what machine are you running it, and how much memory does that have?  How much is free?

Thanks, Andre.

**Comment by iparask** [comment]
Here is [simple_bot.py](https://github.com/radical-cybertools/midas/blob/master/leaflet_finder/Spark/Spark-networkx/submit_bot.py)

**Comment by solejar** [comment]
I am running the script on my HP Pavilion laptop which has roughly 5.8GB of total mem, with about 1.4GB free. I was attempting to run on Comet.

**Comment by andre-merzky** [comment]
thanks guys!

Between lines 50 and 80, what is the memory allocation required by those data partition steps?  Would you mind adding the following before and after that section, and post the output?

```
import resource 
print resource.getrusage(resource.RUSAGE_SELF)
```

Thanks!

**Comment by solejar** [comment]
Results are as follows:

```
This is the resouce usage before partition: 

resource.struct_rusage(ru_utime=0.20388299999999998, ru_stime=0.059965, ru_maxrss=33120, ru_ixrss=0, ru_idrss=0, ru_isrss=0, ru_minflt=9565, ru_majflt=0, ru_nswap=0, ru_inblock=0, ru_oublock=0, ru_msgsnd=0, ru_msgrcv=0, ru_nsignals=0, ru_nvcsw=33, ru_nivcsw=64)

This is the resouce usage after partition: 

resource.struct_rusage(ru_utime=14.56635, ru_stime=0.8429129999999999, ru_maxrss=1184808, ru_ixrss=0, ru_idrss=0, ru_isrss=0, ru_minflt=297267, ru_majflt=47, ru_nswap=0, ru_inblock=107432, ru_oublock=3440, ru_msgsnd=0, ru_msgrcv=0, ru_nsignals=0, ru_nvcsw=376, ru_nivcsw=774)

```
Thanks!

**Comment by andre-merzky** [comment]
you said you had about 1.4GB free, and the partitioning seems to use 1.2GB (`ru_maxrss=1184808`).  I would assume that you in fact *do* run out of memory.   What happens on a smaller data set, or on a machine with larger memory?  Can you try to free more memory on the machine you use?

**Comment by solejar** [comment]
That analysis seems right, the script ran without problem when I have no other background processes running. For now, it shouldn't be a problem for me, but it might be useful to add a small footnote to the documentation that overly ambitious application mem usage can cause hiccups on the client's end. 

Thanks Andre!

**Comment by andre-merzky** [comment]
Given that the original message was `OSError: [Errno 12] Cannot allocate memory`, I think any additional message would only be redundant ;)
