### ISSUE TITLE
RuntimeError('LRMS has no nodes left to run units') on BlueWaters

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1040]
Hello!

I wrote a dummy script that runs /bin/sleep for some amount of time. It works when I submit to other machine like Comet and Stampede, but does not work when I submit it to BlueWaters. I get the following error. I originally tried to solve it by submitting more CUs. That work for one session, but all subsequent sessions also gave the same error.

Software Version:
RP 0.40.3 (master)
RU 0.40.1
SAGA 0.40.1

```
Traceback (most recent call last):
  File "/mnt/c/scratch/sciteam/ha1/radical.pilot.sandbox/ve_bw/rp_install/bin/radical-pilot-agent-multicore.py", line 553, in bootstrap_3
    logger = log)
  File "/mnt/c/scratch/sciteam/ha1/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 219, in create
    return impl(cfg, logger)
  File "/mnt/c/scratch/sciteam/ha1/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/torque.py", line 19, in __init__
    LRMS.__init__(self, cfg, logger)
  File "/mnt/c/scratch/sciteam/ha1/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 135, in __init__
    raise RuntimeError('LRMS has no nodes left to run units')
RuntimeError: LRMS has no nodes left to run units
2016-06-15 04:04:27,383: agent_0.bootstrap_3 : MainProcess                     : MainThread     : DEBUG   : agent agent_0 finalized
2016-06-15 04:04:27,383: agent_0.bootstrap_3 : MainProcess                     : MainThread     : ERROR   : FAILED startup
2016-06-15 04:04:27,383: agent_0.bootstrap_3 : MainProcess                     : MainThread     : ERROR   :   File "/mnt/c/scratch/sciteam/ha1/radical.pilot.sandbox/ve_bw/rp_install/bin/radical-pilot-agent-multicore.py", line 553, in bootstrap_3
    logger = log)
  File "/mnt/c/scratch/sciteam/ha1/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 219, in create
    return impl(cfg, logger)
  File "/mnt/c/scratch/sciteam/ha1/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/torque.py", line 19, in __init__
    LRMS.__init__(self, cfg, logger)
  File "/mnt/c/scratch/sciteam/ha1/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 135, in __init__
    raise RuntimeError('LRMS has no nodes left to run units')
```

**Comment by marksantcroos** [comment]
> raise RuntimeError('LRMS has no nodes left to run units')

Points to the fact that the LRMS has no nodes let to run units :)
Please increase the core count of the pilot.

**Comment by mingtaiha** [comment]
I checked my logs and found that the problem only occurred when I submitted jobs using 32 cores. Is that not enough?

**Comment by marksantcroos** [comment]
With the default configuration that is indeed not enough, try 64.

**Comment by mingtaiha** [comment]
I see. So I should submit 64+ core jobs I guess. Is this problem caused by RP or by the BlueWaters resource manager?

**Comment by marksantcroos** [comment]
In the default config we reserve one node for RP so that innocent users don't blow up the MOM node.

**Comment by mingtaiha** [comment]
So if I wanted to use one node, RP actually asks for two nodes? Is it possible to change the use only one node altogether?

**Comment by marksantcroos** [comment]
Change https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/agent_cray.json#L53 to `local`.

**Comment by mingtaiha** [comment]
Oh cool. I'll change agent_default and let you know how that goes

**Comment by mturilli** [comment]
> In the default config we reserve one node for RP so that innocent users don't blow up the MOM node.

Would using ORTE make this any different? I seem to remember that the problems we had with MOM were one of the reason to move to ORTE. More generally, is the alternative scheduler going to be available in the upcoming PR release?

**Comment by marksantcroos** [comment]
> Would using ORTE make this any different? I seem to remember that the problems we had with MOM were one of the reason to move to ORTE.

This is already with ORTE, but with the CLI. When we switch to using ORTE LIB, we can drop this +1 node reservation.

> More generally, is the alternative scheduler going to be available in the upcoming PR release?

No, but that's also unrelated.

ps. the +1 node can be considered a feature for the informed ;-)

**Comment by andre-merzky** [comment]
@mingtaiha: please do remember though that we move the agent to a node for good reasons: as Mark said, it keeps RP from overloading the MOM node.  That is no problem if you indeed want to only run small pilots -- but please don't use `local` for larger experiments...

**Comment by mingtaiha** [comment]
Yes sir. I only intend to submit 1 CU that runs /bin/sleep. I'll keep you posted on it

**Comment by mingtaiha** [comment]
I made the cautiously suggested change and things seems to be working out alright. Even for 32 cores, the CU on the pilot reaches the Executing stages. I'll keep you posted, as the /bin/sleep might run for a fair amount of time.

**Comment by andre-merzky** [comment]
So, what became of the plan to use synapse instead of sleep?  Or is that a different set of experiments?

**Comment by mingtaiha** [comment]
This is for another set of experiments. I'm still down for using synapse!

**Comment by mingtaiha** [comment]
Since this did work out, I would consider it closed.

**Comment by iparask** [comment]
Have you considered printing an error from the pilot manager if the one node is requested? A least, until the has changed.

**Comment by andre-merzky** [comment]
Not all resources reserve a node for the agent.  The pilot manager is not looking at the agent config - that is done in the pilot launcher.  The pilot launcher could do some magic to raise a warning -- but since that is in a different thread, it will be messy and potentially unreadable output.  Maybe better than nothing -- but the real fix remains to get a proper  reporting channel in place, to communicate errors and warning like this one to the application process...

**Comment by andre-merzky** [comment]
closing per discussion above.
