### ISSUE TITLE
Could not find orte-dvm at Bluewaters

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1041]
Hello guys,

I am getting this error on Bluewaters:

```
2016-06-16 11:49:43,072: agent_0.bootstrap_3 : MainProcess                     : MainThread     : INFO    : Agent(s) running on node(s): ['agent_1']
2016-06-16 11:49:43,072: agent_0.bootstrap_3 : MainProcess                     : MainThread     : INFO    : Remaining work node(s): ['21420', '21421', '21490']
2016-06-16 11:49:43,120: agent_0.bootstrap_3 : MainProcess                     : MainThread     : INFO    : call LRMS config hook for LaunchMethod ORTE: <class 'radical.pilot.agent.lm.orte.ORTE'>
2016-06-16 11:49:43,126: agent_0.bootstrap_3 : MainProcess                     : MainThread     : ERROR   : lrms config hook failed
Traceback (most recent call last):
  File "/mnt/c/scratch/sciteam/paraskev/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 152, in __init__
    rp.agent.LM.lrms_config_hook(lm, self._cfg, self, self._log))
  File "/mnt/c/scratch/sciteam/paraskev/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 157, in lrms_config_hook
    return impl.lrms_config_hook(name, cfg, lrms, logger)
  File "/mnt/c/scratch/sciteam/paraskev/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 46, in lrms_config_hook
    raise Exception("Couldn't find orte-dvm")
Exception: Couldn't find orte-dvm
2016-06-16 11:49:43,137: agent_0.bootstrap_3 : MainProcess                     : MainThread     : ERROR   : Error running agent: agent_0
Traceback (most recent call last):
  File "/mnt/c/scratch/sciteam/paraskev/radical.pilot.sandbox/ve_bw/rp_install/bin/radical-pilot-agent-multicore.py", line 553, in bootstrap_3
    logger = log)
  File "/mnt/c/scratch/sciteam/paraskev/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 222, in create
    return impl(cfg, logger)
  File "/mnt/c/scratch/sciteam/paraskev/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/torque.py", line 19, in __init__
    LRMS.__init__(self, cfg, logger)
  File "/mnt/c/scratch/sciteam/paraskev/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 152, in __init__
    rp.agent.LM.lrms_config_hook(lm, self._cfg, self, self._log))
  File "/mnt/c/scratch/sciteam/paraskev/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 157, in lrms_config_hook
    return impl.lrms_config_hook(name, cfg, lrms, logger)
  File "/mnt/c/scratch/sciteam/paraskev/radical.pilot.sandbox/ve_bw/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 46, in lrms_config_hook
    raise Exception("Couldn't find orte-dvm")
Exception: Couldn't find orte-dvm
```

**Comment by iparask** [comment]
Here is a tarbal
[rp_sandbox.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/319404/rp_sandbox.tar.gz)

**Comment by iparask** [comment]
Devel Branch same error

[rp_sandbox_devel.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/319769/rp_sandbox_devel.tar.gz)

**Comment by marksantcroos** [comment]
Thanks for confirming.

Can you try this on a bw login node:
```shell
$ module use --append /projects/sciteam/gkd/modules
$ module load openmpi
$ orte-dvm --help
```

**Comment by iparask** [comment]
Here is the output:

```
paraskev@h2ologin3:~> module use --append /projects/sciteam/gkd/modules
paraskev@h2ologin3:~> module load openmpi
paraskev@h2ologin3:~> orte-dvm --help
orte-dvm (OpenRTE) 3.0.0a1

Usage: orte-dvm [OPTION]...  [PROGRAM]...
Start the given program using Open RTE

   -allow-run-as-root|--allow-run-as-root 
                         Allow execution as root (STRONGLY DISCOURAGED)
   -am <arg0>            Aggregate MCA parameter set file list
-d|-debug-devel|--debug-devel 
                         Enable debugging of OpenRTE
   -debug-daemons|--debug-daemons 
                         Debug daemons
   -gmca|--gmca <arg0> <arg1>  
                         Pass global MCA parameters that are applicable to
                         all contexts (arg0 is the parameter name; arg1 is
                         the parameter value)
-h|--help                This help message
   -mca|--mca <arg0> <arg1>  
                         Pass context-specific MCA parameters; they are
                         considered global if --gmca is not used and only
                         one context is specified (arg0 is the parameter
                         name; arg1 is the parameter value)
   -prefix|--prefix <arg0>  
                         Prefix to be used to look for ORTE executables
   -report-uri|--report-uri <arg0>  
                         Printout URI on stdout [-], stderr [+], or a file
                         [anything else]
   -tune <arg0>          Application profile options file list
-V|--version             Print version and exit

Report bugs to http://www.open-mpi.org/community/help/
```
This is the expected output, right?

**Comment by marksantcroos** [comment]
> This is the expected output, right?

Yes, indeed, so we can rule that out.

**Comment by marksantcroos** [comment]
You are running `python 00_getting_started.py ncsa.bw`, right?

**Comment by iparask** [comment]
Yes

**Comment by marksantcroos** [comment]
Ok, I can reproduce it under certain circumstances.
This might be the culprit: https://github.com/radical-cybertools/radical.pilot/commit/5d81d331b7cdf5e3668ec7b3a20be9b1cec9465e

Working on a fix now.

@vivek-bala Can you provide me the pilot sandbox for one of your recent (successful) runs on bw? Want to understand why you didn't run into that.

**Comment by marksantcroos** [comment]
The patch below should fix/work-a-round it, but is untested, as I don't get anything done with the terrible fs behavior.

```patch
diff --git a/src/radical/pilot/configs/resource_ncsa.json b/src/radical/pilot/co
nfigs/resource_ncsa.json
index cb03bda..87abd09 100644
--- a/src/radical/pilot/configs/resource_ncsa.json
+++ b/src/radical/pilot/configs/resource_ncsa.json
@@ -47,11 +47,12 @@
             "module switch PrgEnv-cray PrgEnv-gnu",
             "module load bwpy",
             "module use --append /projects/sciteam/gkd/modules",
-            "module load openmpi"
+            "module load openmpi",
+            "export PB2PATH=$PATH"
         ],
         "pre_bootstrap_2"             : [
             "export HOME=$HOME",
-            "export PATH=$PATH",
+            "export PATH=$PB2PATH",
             "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
         ],
         "default_remote_workdir"      : "/scratch/sciteam/$USER",
```

**Comment by vivek-bala** [comment]
Hey Mark,

You can take a look into ```/u/sciteam/balasubr/scratch/radical.pilot.sandbox/rp.session.vivek-Lenovo-IdeaPad-Y480.vivek.016961.0000-pilot.0000```.

**Comment by marksantcroos** [comment]
Thanks Vivek, you are using a RP from before the change, so that explains it luckily!

**Comment by iparask** [comment]
I got the same error.

Here is the path ```/u/sciteam/paraskev/scratch/radical.pilot.sandbox/rp.session.iparask-VirtualBox.iparask.016969.0000-pilot.0000```

**Comment by marksantcroos** [comment]
> Here is the path /u/sciteam/paraskev/scratch/radical.pilot.sandbox/rp.session.iparask-VirtualBox.iparask.016969.0000-pilot.0000

Dont have the permissions to look at that.

**Comment by iparask** [comment]
[pilot.0000.log.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/322735/pilot.0000.log.tar.gz)
There you go. Sorry for the delay

**Comment by marksantcroos** [comment]
Can you enable debugging?

**Comment by iparask** [comment]
As soon as BW comes up again, I will re run with debug. I am not sure how I missed it.

**Comment by iparask** [comment]
I was able to run correctly this morning. Let me take the fix to the spark branch and see if it works there as well.

**Comment by iparask** [comment]
It run also with the Spark branch

**Comment by marksantcroos** [comment]
Good. We have to decide whether we reverse or adapt that change then, or apply the workaround that you tested now.

**Comment by iparask** [comment]
So?

**Comment by andre-merzky** [comment]
closed as outdated.
