### ISSUE TITLE
09_mpi_units.py fails with an MPI error

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1067]
workflow.iu.xsede.org
session: rp.session.workflow.iu.xsede.org.mturilli.016990.0012
target: localhost

All the units fail with the following error:

```
* unit.000000: Fail, exit:   1, MPI ranks: -------------------------------------------------------,Primary job  terminated normally, but 1 process returned,a non-zero exit code.. Per user-direction, the job has been aborted.,-------------------------------------------------------,
```

and slightly different:

```
* unit.000078: Fail, exit:   1, MPI ranks: -------------------------------------------------------,Primary job  terminated normally, but 1 process returned,a non-zero exit code.. Per user-direction, the job has been aborted.,-------------------------------------------------------,--------------------------------------------------------------------------,mpiexec detected that one or more processes exited with non-zero status, thus causing,the job to be terminated. The first process to do so was:,,  Process name: [[4563,1],0],  Exit code:    1,--------------------------------------------------------------------------,
```

Tests from the shell:

```
$ mpiexec -n 2 echo test
test
test
$ echo $?
0
$ mpirun -n 2 echo test
test
test
$ echo $?
0
```

Tarball of pilot sandbox available upon request.

**Comment by andre-merzky** [comment]
Mark, do you have any idea what's up with that?

**Comment by marksantcroos** [comment]
Whats the target for that machine? And related, do we need MPI execution on that machine from a tutorial perspective?

**Comment by mturilli** [comment]
> target: localhost

**Comment by marksantcroos** [comment]
Ok thanks. I'll look into it, but not before tomorrow.

**Comment by marksantcroos** [comment]
```
$ cat STDERR 
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
```

The documentation is out of sync with the code.

Andre, can you install mpi4py?

**Comment by andre-merzky** [comment]
Duh!  Will do.

**Comment by andre-merzky** [comment]
this is done now:

```
[merzky@workflow examples]$ ./helloworld_mpi.py 
1/1/workflow
[merzky@workflow examples]$ mpirun -n 2 !!
mpirun -n 2 ./helloworld_mpi.py 
1/2/workflow
2/2/workflow

```

**Comment by marksantcroos** [comment]
Thanks. Did you change documentation too?

**Comment by andre-merzky** [comment]
Would you suggest to add an mpi4py install item here: http://radicalpilot.readthedocs.io/en/latest/user_guide/09_mpi_units.html
?

**Comment by marksantcroos** [comment]
No, but it describes `/bin/echo`, which was the reason Matteo reported the standalone results of that.

**Comment by andre-merzky** [comment]
Got it, thanks, will do

**Comment by andre-merzky** [comment]
mpi4py dependency is on its way out - this will not be fixed.
