### ISSUE TITLE
New Project-ID for Comet needed due to insufficient allocation

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1079]
I encounter the following error when trying to test on Comet. This is due to an insufficient amount of allocation. I suggest we use the project id TG-CCR140028 instead.

```
2016-07-13 13:06:31,496: radical.saga.cpi    : MainProcess                     : PilotLauncherWorker-1: ERROR   : NoSuccess: Couldn't get job id from submitted job! sbatch output:
sbatch: error: bank_limit plugin: The requested time can not exceed the available balance.
Requested SUs: 19
Allocation limit group SUs: 381958
Allocation limit user SUs: 381958
Allocation used group SUs: 381929
Allocation used user SUs: 15041
Allocation available group SUs: 29
Allocation available user SUs: 366917
Allocation running/queued group SUs: 0
Allocation running/queued user SUs: 0
Allocation completed today group SUs: 12
Allocation completed today user SUs: 0
sbatch: error: Batch job submission failed: Requested time limit is invalid (missing or exceeds some limit)
removed `tmp_lV8ja1.slurm'

2016-07-13 13:06:31,524: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: ERROR   : Using bootstrapper /home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/bootstrapper/bootstrap_1.sh
Copying bootstrapper 'file://localhost/home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/bootstrapper/bootstrap_1.sh' to agent sandbox (<saga.filesystem.directory.Directory object at 0x2e3f150>).
Copying sdist 'file://localhost/home/mingtha/ve/lib/python2.7/site-packages/radical/utils/radical.utils-0.41.1.tar.gz' to sandbox (gsisftp://comet.sdsc.xsede.org/home/mingtha/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.mingtha.016995.0012-pilot.0000/).
Copying sdist 'file://localhost/home/mingtha/ve/lib/python2.7/site-packages/saga/saga-python-0.41.1.tar.gz' to sandbox (gsisftp://comet.sdsc.xsede.org/home/mingtha/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.mingtha.016995.0012-pilot.0000/).
Copying sdist 'file://localhost/home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/controller/..//radical.pilot-v0.40.3-12-gb280097-tutorial-xsede16.tar.gz' to sandbox (gsisftp://comet.sdsc.xsede.org/home/mingtha/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.mingtha.016995.0012-pilot.0000/).
Writing agent configuration to file '/tmp/rp_agent_cfg_dirKpSffX/agent_0.cfg'.
Copying agent configuration file 'file://localhost/tmp/rp_agent_cfg_dirKpSffX/agent_0.cfg' to sandbox (gsisftp://comet.sdsc.xsede.org/home/mingtha/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.mingtha.016995.0012-pilot.0000/).
Submitting SAGA job with description: {'Project': 'TG-MCB090174', 'Executable': '/bin/bash', 'TotalPhysicalMemory': None, 'WorkingDirectory': '/home/mingtha/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.mingtha.016995.0012-pilot.0000/', 'Queue': 'compute', 'Environment': {}, 'WallTimeLimit': 15, 'Arguments': ['-l bootstrap_1.sh', " -d 'radical.utils-0.41.1.tar.gz:saga-python-0.41.1.tar.gz:radical.pilot-v0.40.3-12-gb280097-tutorial-xsede16.tar.gz' -m 'create' -p 'pilot.0000' -r 'local' -s 'rp.session.workflow.iu.xsede.org.mingtha.016995.0012' -v '/home/mingtha/radical.pilot.sandbox/ve_comet' -b 'default' -a 'multicore' -e 'module load python' -w 'export PATH=$PATH' -w 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH'"], 'ProcessesPerHost': 24, 'Error': 'bootstrap_1.err', 'Output': 'bootstrap_1.out', 'CandidateHosts': None, 'TotalCPUCount': 72}
Pilot launching failed! (Couldn't get job id from submitted job! sbatch output:
sbatch: error: bank_limit plugin: The requested time can not exceed the available balance.
Requested SUs: 19
Allocation limit group SUs: 381958
Allocation limit user SUs: 381958
Allocation used group SUs: 381929
Allocation used user SUs: 15041
Allocation available group SUs: 29
Allocation available user SUs: 366917
Allocation running/queued group SUs: 0
Allocation running/queued user SUs: 0
Allocation completed today group SUs: 12
Allocation completed today user SUs: 0
sbatch: error: Batch job submission failed: Requested time limit is invalid (missing or exceeds some limit)
removed `tmp_lV8ja1.slurm'
 (/home/mingtha/ve/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py +626 (_job_run)  :  " sbatch output:\n%s" % out)))
Traceback (most recent call last):
  File "/home/mingtha/ve/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 785, in run
    pilotjob.run()
  File "/home/mingtha/ve/lib/python2.7/site-packages/saga/job/job.py", line 479, in run
    return self._adaptor.run (ttype=ttype)
  File "/home/mingtha/ve/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/mingtha/ve/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 1221, in run
    self._id = self.js._job_run (self.jd)
  File "/home/mingtha/ve/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 626, in _job_run
    " sbatch output:\n%s" % out)
NoSuccess: Couldn't get job id from submitted job! sbatch output:
sbatch: error: bank_limit plugin: The requested time can not exceed the available balance.
Requested SUs: 19
Allocation limit group SUs: 381958
Allocation limit user SUs: 381958
Allocation used group SUs: 381929
Allocation used user SUs: 15041
Allocation available group SUs: 29
Allocation available user SUs: 366917
Allocation running/queued group SUs: 0
Allocation running/queued user SUs: 0
Allocation completed today group SUs: 12
Allocation completed today user SUs: 0
sbatch: error: Batch job submission failed: Requested time limit is invalid (missing or exceeds some limit)
removed `tmp_lV8ja1.slurm'
 (/home/mingtha/ve/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py +626 (_job_run)  :  " sbatch output:\n%s" % out))
```

**Comment by marksantcroos** [comment]
I don't know whether everybody of our group will have access to that, but certainly not the tutorial participants. We will likely update the allocations later with the tutorial ones. For now feel fry to modify your config.json accordingly.

**Comment by marksantcroos** [comment]
(ps. the original allocation has been enlarged already so no need to change anything actually)
