### ISSUE TITLE
09_mpi_units.py fails on Comet: Missing python module mpi4py

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1080]
When executing `09_mpi_units.py`, each unit fails to execute correctly. In the `gather results` section of the output, I get the following for each pilot:

`  * unit.000000: Fail, exit:   1, MPI ranks: `

Upon inspection of the sandbox, I find the following error:
```
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError:     from mpi4py import MPI
ImportErrorNo module named mpi4py: 
No module named mpi4py
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
[comet-23-47.sdsc.edu:mpispawn_0][child_handler] MPI process (rank: 3, pid: 6831) exited with status 1
[comet-23-47.sdsc.edu:mpispawn_0][child_handler] MPI process (rank: 0, pid: 6828) exited with status 1
[comet-23-47.sdsc.edu:mpispawn_0][child_handler] MPI process (rank: 2, pid: 6830) exited with status 1
[comet-23-47.sdsc.edu:mpispawn_0][child_handler] MPI process (rank: 1, pid: 6829) exited with status 1
```

**Comment by marksantcroos** [comment]
Hi Ming, I made some changes, can you pull and retry? Thanks!

**Comment by mingtaiha** [comment]
Just tried it. Looks good!
