### ISSUE TITLE
KeyError 'PILOT_STATE' Error on split_module_2

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1095]
I encountered the following error when submitting a pilot, which executes a CU, to OSG and get the following error on my terminal:
```
Traceback (most recent call last):
  File "aimes_only.py", line 90, in <module>
    aimes.emgr.execute_workload(cfg, run)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/aimes/emgr/emgr.py", line 738, in execute_workload
    session.close(cleanup=False, terminate=True)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/session.py", line 366, in close
    pmgr.close(terminate=terminate)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 166, in close
    self._controller.stop()
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/utils/controller.py", line 230, in stop
    t.stop()
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 787, in stop
    self.join()
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 837, in join
    mp.Process.join(self, timeout)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

I checked all of the log files and only found this error in pmgr.0000.log. 

```
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1044, in _idler
    callback()
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 217, in _state_pull_cb
    self._update_pilot(pilot_dict)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 262, in _update_pilot
    self._pilots[pid]._update(pilot_dict)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 182, in _update
    self._pmgr._call_pilot_callbacks(self, state)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 270, in _call_pilot_callbacks
    for cb_name, cb_val in self._callbacks[rpt.PILOT_STATE].iteritems():
KeyError: 'PILOT_STATE'
```
According to the JSON file, this only occurs after the CU enters the state `Done` and the Pilot enters the state `Cancelled`. The OSG login node does not have any log files, and the saga-condor-job log file does not show anything out of the ordinary. I was unable to SSH into the OSG node on which the CU ran.

Here's the log file.
[pmgr.0000.log.txt](https://github.com/radical-cybertools/radical.pilot/files/400197/pmgr.0000.log.txt)

@andre-merzky, is this another instance of the RP API being updated?

**Comment by mingtaiha** [comment]
Here's all the logs in case you need them.

[rp.session.radical.mingtha.017016.0009.zip](https://github.com/radical-cybertools/radical.pilot/files/400212/rp.session.radical.mingtha.017016.0009.zip)

**Comment by andre-merzky** [comment]
Yeah, I encountered that too.  This is fixed now, will push.

**Comment by andre-merzky** [comment]
pushed to the split branch - please merge from there.  Thanks!

**Comment by mingtaiha** [comment]
Reopening ticket for testing :/

**Comment by mingtaiha** [comment]
Works for me. Re-closing
