### ISSUE TITLE
partition_scheduler: not specifying scheduler hint for CU leads to error

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1098]
```
2016-08-06 06:34:03,430: agent_0.AgentSchedulingComponent.0.child: agent_0.AgentSchedulingComponent.0: MainThread     : ERROR   : unit unit.000000 failed
Traceback (most recent call last):
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 757, in run
    self._workers[state](_unit)
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/base.py", line 327, in work
    if self._try_allocation(cu):
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/base.py", line 178, in _try_allocation
    cu['opaque_slots'] = self._allocate_slot(cu)
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/continuous.py", line 144, in _allocate_slot
    pname = hints.get('partition', 'default')
AttributeError: 'NoneType' object has no attribute 'get'
```

Complete log: https://gist.github.com/vivek-bala/b42824e43e6a0de529fde1ca6b5a2b04

**Comment by andre-merzky** [comment]
thanks Vivek - a fix has been pushed just now, please give it a spin!

**Comment by vivek-bala** [comment]
Tried with the update:

```
2016-08-06 07:17:02,511: agent_0.AgentSchedulingComponent.0.child: agent_0.AgentSchedulingComponent.0: MainThread     : ERROR   : unit unit.000000 failed
Traceback (most recent call last):
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 757, in run
    self._workers[state](_unit)
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/base.py", line 327, in work
    if self._try_allocation(cu):
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/base.py", line 178, in _try_allocation
    cu['opaque_slots'] = self._allocate_slot(cu)
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/continuous.py", line 164, in _allocate_slot
    task_slots = self._find_slots_single_cont(cores, pname)
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/continuous.py", line 252, in _find_slots_single_cont
    slots = self._partitions[pname]['slots']
KeyError: 'default'
```

**Comment by andre-merzky** [comment]
This should work now again.  Thanks!

**Comment by vivek-bala** [comment]
can confirm this works now.
