### ISSUE TITLE
00_getting_started.py fails on comet

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#1099]
```
2016-08-06 18:57:27,101: radical.saga.pty    : MainProcess                     : MainThread     : ERROR   : read from process failed '[Errno 5] Input/output error' : (/usr/bin/env: None: No such file or directory
) (/home/antontre/ve/local/lib/python2.7/site-packages/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
Traceback (most recent call last):
  File "/home/antontre/ve/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 263, in _initialize_pty
    n, match = pty_shell.find (prompt_patterns, delay)
  File "/home/antontre/ve/local/lib/python2.7/site-packages/saga/utils/pty_process.py", line 790, in find
    raise ptye.translate_exception (e, "(%s)" % data)
NoSuccess: read from process failed '[Errno 5] Input/output error' : (/usr/bin/env: None: No such file or directory
) (/home/antontre/ve/local/lib/python2.7/site-packages/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
caught Exception: read from process failed '[Errno 5] Input/output error' : (/usr/bin/env: None: No such file or directory
) (/home/antontre/ve/local/lib/python2.7/site-packages/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.js-156-129.jetstream-cloud.org.antontre.017019.0006 \
close pilot manager2016-08-06 18:57:27,358: radical.pilot       : MainProcess                     : MainThread     : INFO    : Sent 'COMMAND_CANCEL_PILOT' command to pilots [].
                                                            \
wait for 0 pilot(s)                                                           ok
                                                                              ok
session lifetime: 1.4s                                                        ok
Traceback (most recent call last):
  File "00_getting_started.py", line 70, in <module>
    pilot = pmgr.submit_pilots(pdesc)
  File "/home/antontre/ve/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 373, in submit_pilots
    resource_config=resource_cfg)
  File "/home/antontre/ve/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 433, in register_start_pilot_request
    shell = sup.PTYShell(url, self._session)
  File "/home/antontre/ve/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    interactive=self.interactive)
  File "/home/antontre/ve/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 198, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/antontre/ve/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
    raise ptye.translate_exception (e)
saga.exceptions.NoSuccess: read from process failed '[Errno 5] Input/output error' : (/usr/bin/env: None: No such file or directory
) (/home/antontre/ve/local/lib/python2.7/site-packages/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
```

**Comment by marksantcroos** [comment]
Can you re-run it please, this might have just been an intermittent issue.

**Comment by antonst** [comment]
No, I am getting this error consistently

**Comment by marksantcroos** [comment]
Thanks for checking. Then I have to refer to Andre.

**Comment by andre-merzky** [comment]
Thanks indeed!  I'm afraid I can't reproduce the problem though.  Can you please rerun with `RADICAL_PILOT_VERBOSE=DEBUG` and `RADICAL_SAGA_PTY_VERBOSE=DEBUG`, and send the resulting log (client side needed only)?  Thanks!

**Comment by antonst** [comment]
(terminal-output)[https://github.com/antonst/rp-logs/blob/master/rp-2.log]

**Comment by andre-merzky** [comment]
thanks, Antons.  Is `ssh` installed on the client machine?  What does `which ssh` give you, and what is the result of `python -c 'import radical.utils as ru; print ru.which("ssh")'`?  Thanks!

**Comment by antonst** [comment]
```
(ve) antontre@js-156-129:~$ which ssh
/usr/bin/ssh
(ve) antontre@js-156-129:~$ python -c 'import radical.utils as ru; print ru.which("ssh")'
/usr/bin/ssh
(ve) antontre@js-156-129:~$ 
```

I have configured passwordless ssh for Comet and I am using this machine for all of my experiments on Stampede and SuperMIC with both master and devel of RP.

**Comment by andre-merzky** [comment]
I am quite confused by this error.  This all happens on the SAGA layer -- and that layer has not changed recently.  You have been using comet in the past, without any problems of this kind, right?  Any idea what is different in this test sequence?  What machine are you using?

**Comment by marksantcroos** [comment]
FWIW: I also see this one regularly, but I interpreted it as one of the many incarnations of prompt detection failure, as it is always intermittent for me.

**Comment by andre-merzky** [comment]
Interesting.  But no, this is not prompt detection -- this looks like a local problem: the pty log shows the ssh command line as:

```
/usr/bin/env TERM=vt100  "None" -t -o IdentityFile=/home/antontre/.ssh/id_rsa  -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_antontre_%h_%p.ctrl -o TCPKeepAlive=no  -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=10 comet.sdsc.xsede.org'
```

and you will realize that it does not contain any `ssh` command, but has a `None` instead.  That seems to indicate that ssh was not found via `ru.which("ssh")` -- which is surprising, as Antons' reply shows that this actually gives the expected result in isolation.

The SAGA PR https://github.com/radical-cybertools/saga-python/pull/581 will complain about the missing tool earlier, instead of creating that faulty command line.  Antons: can you try that SAGA branch (`fix/which_error`), please, just to confirm I am looking at the right problem?

**Comment by marksantcroos** [comment]
Ok, agreed, mines are not a None error, just a normal prompt detection failure :)
For completeness:
```
Traceback (most recent call last):
  File "/home/marksant/thesis/osg-ve/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 488, in run
    flags=saga.filesystem.CREATE_PARENTS)
  File "/home/marksant/thesis/osg-ve/local/lib/python2.7/site-packages/saga/filesystem/directory.py", line 95, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/home/marksant/thesis/osg-ve/local/lib/python2.7/site-packages/saga/namespace/directory.py", line 95, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/home/marksant/thesis/osg-ve/local/lib/python2.7/site-packages/saga/namespace/entry.py", line 89, in __init__
    url, flags, session, ttype=_ttype)
  File "/home/marksant/thesis/osg-ve/local/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/home/marksant/thesis/osg-ve/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/marksant/thesis/osg-ve/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 297, in init_instance
    self.initialize ()
  File "/home/marksant/thesis/osg-ve/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 347, in initialize
    ret, out, _ = self._command(cmd, location=root, make_location=mkl)
  File "/home/marksant/thesis/osg-ve/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 319, in _command
    return cmd_shell.run_sync ("%s cd %s && %s" % (pre_cmd, location.path, command))
  File "/home/marksant/thesis/osg-ve/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 640, in run_sync
    self.pty_shell.flush ()
  File "/home/marksant/thesis/osg-ve/local/lib/python2.7/site-packages/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/marksant/thesis/osg-ve/local/lib/python2.7/site-packages/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (* * * * * * * * * * * * * * * * * * * * * * * * * *
```

**Comment by andre-merzky** [comment]
Yeah, indeed that looks like the 'normal' mess *sigh*.  Is that frequent enough to warrant its own ticket?

**Comment by marksantcroos** [comment]
```
$ grep 'read from process failed' *.log|wc -l
489
```
Let's hope this goes away once I can use the new branches.

**Comment by andre-merzky** [comment]
the number of ssh interactions will be reduced, but the type of interactions remains the same, so I would not get my hopes up... :/

**Comment by antonst** [comment]
>Antons: can you try that SAGA branch (fix/which_error), please, just to confirm I am looking at the right problem?

Sure, the output is below:

```
2016-08-08 18:34:14,440: radical.pilot       : MainProcess                     : MainThread     : DEBUG   : session rp.session.js-156-129.jetstream-cloud.org.antontre.017021.0008 closed
Traceback (most recent call last):
  File "00_getting_started.py", line 70, in <module>
    pilot = pmgr.submit_pilots(pdesc)
  File "/home/antontre/ve1/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 373, in submit_pilots
    resource_config=resource_cfg)
  File "/home/antontre/ve1/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 433, in register_start_pilot_request
    shell = sup.PTYShell(url, self._session)
  File "/home/antontre/ve1/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    interactive=self.interactive)
  File "/home/antontre/ve1/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 173, in initialize
    posix, interactive)
  File "/home/antontre/ve1/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 519, in _create_master_entry
    info['ssh_exe']    = self._which ("gsissh")
  File "/home/antontre/ve1/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 461, in _which
    raise RuntimeError('cmd %s not found' % cmd)
RuntimeError: cmd gsissh not found
2016-08-08 18:34:14,451: radical.saga.pty    : MainProcess                     : Dummy-3        : DEBUG   : PTYShell del  <saga.utils.pty_shell.PTYShell object at 0x7fd73269bad0>
```

**Comment by marksantcroos** [comment]
> RuntimeError: cmd gsissh not found

Bingo. The default in config.json is still gsissh for comet.

**Comment by antonst** [comment]
Yes, switching to ssh seems to solve the problem.

**Comment by marksantcroos** [comment]
Probably a left-over from running on the workflows machine.

**Comment by andre-merzky** [comment]
Bingo indeed...

Antons, please continue testing with ssh then, I'll fix the config.  Thanks for catching that!

**Comment by andre-merzky** [comment]
Fixed and released.
