### ISSUE TITLE
MPI example fails on Wrangler

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1110]
This is the error I got:
```
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
[c252-135.wrangler.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 0, pid: 35233) exited with status 1
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
[c252-135.wrangler.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 1, pid: 35245) exited with status 1
```
Should I install a package or there is  solution through the configuration?

**Comment by andre-merzky** [comment]
I do not know if an mpi4py module or so exists on wrangler.  RP does not install mpi4py, so, if there is nothing on wrangler, you may need to install it yourself in a toy VE or so :/

**Comment by iparask** [comment]
I does exist with ```python/2.7.9``` that is part of the ```mvapich2/2.1```.  I will add it to the pre_exec and see what is going on.

**Comment by iparask** [comment]
I created a ```VE``` and sourced it. This is how the ```radical_pilot_cu_launch_script.sh```

```
#!/bin/sh


# Change to working directory for unit
cd /work/03170/tg824689/wrangler/radical.pilot.sandbox/rp.session.js-156-70.jetstream-cloud.org.iparask.017045.0002-pilot.0000/unit.000044
# Environment variables
export RP_SESSION_ID=rp.session.js-156-70.jetstream-cloud.org.iparask.017045.0002 RP_PILOT_ID=pilot.0000 RP_AGENT_ID=agent_0 RP_SPAWNER_ID=agent_0.AgentExecutingComponent.0.child RP_UNIT_ID=unit.000044
# Pre-exec commands
source /work/03170/tg824689/wrangler/testing_mpi/bin/activate
# The command to run
mpirun_rsh -np 2 c252-135 c252-135  python "helloworld_mpi.py" 
RETVAL=$?
# Exit the script with the return code from the command
exit $RETVAL
```
The error I am getting is:
```
login1.wrangler(30)$ cat STDERR
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "helloworld_mpi.py", line 8, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
[c252-135.wrangler.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 0, pid: 97667) exited with status 1
[c252-135.wrangler.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 1, pid: 97668) exited with status 1
```

**Comment by iparask** [comment]
Clossing as irrelevant. Mr M ordered it.
