### ISSUE TITLE
experiment/aimes on titan: error: can't start new thread

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1121]
Agent bootstrapping is going through now, but I run into an issue during agent launch.

```
2016-09-30 09:18:24,756: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : DEBUG   : START: agent.staging.input.0.child unregister subscriber agent.staging.input.0.child.subscriber._cancel_monitor_cb
2016-09-30 09:18:24,757: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : DEBUG   : using addr tcp://10.128.0.96:56986 for pubsub control_pubsub
2016-09-30 09:18:24,758: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : ERROR   : TERM : agent.staging.input.0.child run exception (can't start new thread)
2016-09-30 09:18:24,759: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : ERROR   : loop exception
Traceback (most recent call last):
  File "/lustre/atlas1/bip103/scratch/marksant1/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1278, in run
    self._initialize_child()
  File "/lustre/atlas1/bip103/scratch/marksant1/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 470, in _initialize_child
    self.register_subscriber(rpc.CONTROL_PUBSUB, self._cancel_monitor_cb)
  File "/lustre/atlas1/bip103/scratch/marksant1/radical.pilot.sandbox/ve_titan/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1204, in register_subscriber
    t.start()
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
2016-09-30 09:18:24,762: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : ERROR   : TERM : agent.staging.input.0.child run final
2016-09-30 09:18:24,762: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : INFO    : loop stops
2016-09-30 09:18:24,763: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : DEBUG   : TERM : agent.staging.input.0.child _finalize_child
2016-09-30 09:18:24,763: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : DEBUG   : TERM : agent.staging.input.0.child finalize_child (NOOP)
2016-09-30 09:18:24,763: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : DEBUG   : _finalize_common (agent.staging.input.0.child <Default> [agent_1])
```

All configs are committed, using target `ornl.titan_aprun` in this case.

**Comment by andre-merzky** [comment]
Alas: https://bugs.python.org/issue16003

But its likely that we are trying to create too many threads.  Would you mind positing the output of 

```
# cat /proc/sys/kernel/threads-max
# cat /proc/sys/kernel/pid_max
# ulimit
```

Thanks!

**Comment by marksantcroos** [comment]
From the MOM node:
```
marksant1@titan-batch5:~> cat /proc/sys/kernel/threads-max
129067
marksant1@titan-batch5:~> cat /proc/sys/kernel/pid_max
32768
marksant1@titan-batch5:~> ulimit
unlimited
marksant1@titan-batch5:~> ulimit -a
core file size          (blocks, -c) 1
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 64533
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 32768
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 64533
virtual memory          (kbytes, -v) 13227600
file locks                      (-x) unlimited
```

**Comment by marksantcroos** [comment]
Thread limit is 198 on the MOM node.

**Comment by andre-merzky** [comment]
Thanks for checking!  

I don't think we should hit that many, but we do create quite a number indeed, mostly related to the ZMQ channel interactions, but also as process watchers etc.  Hmpf...  That is not a limit I expected us to run into -- its the decade of multicore after all, isn't it?  Let me check if we can control thread creation in the zmq layer.  Also, we don't need all zmq subscriptions really, so we can be more conservative here (right now we simply keep subscriptions somewhat uniform over all components).

**Comment by marksantcroos** [comment]
For completeness, this is the underlying reason:
```
clone(child_stack=0x7f96d9643ff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f96d96449d0, tls=0x7f96d9644700, child_tidptr=0x7f96d96449d0) = -1 ENOSPC (No space left on device)
```

Its a TORQUE enforced limit, as logging in directly to the MOM node doesn't show this limit.

ps. Note that `ENOSPC` is not a documented error of `clone(2)`!

**Comment by andre-merzky** [comment]
Did you did that out via strace or a debugger on some test code?  Thanks!

Yeah, I would not have expected an `ENOSPC` on `clone()` -- specifically not when `CLONE_FILES` is set.  I wonder if it could be a limit on open file descriptors anyway?

**Comment by andre-merzky** [comment]
PS.: could you please try to rerun without profiling?  keeping profiles closed should clarify if the limit is threads or indeed files...

**Comment by marksantcroos** [comment]
I dont have profiles enabled.

**Comment by marksantcroos** [comment]
Thats strace on some test code.

**Comment by andre-merzky** [comment]
*sigh*

**Comment by andre-merzky** [comment]
This has been addressed via agent reconfiguration.
