### ISSUE TITLE
OSX stall in getting_started.py script 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1142]
rp sandbox session: 

[radical.pilot-0.43.1.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/543072/radical.pilot-0.43.1.tar.gz)

**Comment by andre-merzky** [comment]
The relevant error seems to be in bootstrap.out:

```
 Running setup.py install for pyzmq
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/JumanaDakka/radical.pilot.sandbox/rp.session.nbp-78-74.nbp.ruw.rutgers.edu.JumanaDakka.017094.0003-pilot.0000/rp_install/build/pyzmq/setup.py", line 1261, in <module>
        setup(**setup_args)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "build/bdist.linux-i686/egg/setuptools/command/install.py", line 56, in run
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/JumanaDakka/radical.pilot.sandbox/rp.session.nbp-78-74.nbp.ruw.rutgers.edu.JumanaDakka.017094.0003-pilot.0000/rp_install/build/pyzmq/setup.py", line 981, in run
        self.distribution.run_command('configure')
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 971, in run_command
        cmd_obj.ensure_finalized()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/Users/JumanaDakka/radical.pilot.sandbox/rp.session.nbp-78-74.nbp.ruw.rutgers.edu.JumanaDakka.017094.0003-pilot.0000/rp_install/build/pyzmq/setup.py", line 289, in finalize_options
        self.init_settings_from_config()
      File "/Users/JumanaDakka/radical.pilot.sandbox/rp.session.nbp-78-74.nbp.ruw.rutgers.edu.JumanaDakka.017094.0003-pilot.0000/rp_install/build/pyzmq/setup.py", line 320, in init_settings_from_config
        settings = settings_from_prefix(cfg['zmq_prefix'], self.bundle_libzmq_dylib)
      File "/Users/JumanaDakka/radical.pilot.sandbox/rp.session.nbp-78-74.nbp.ruw.rutgers.edu.JumanaDakka.017094.0003-pilot.0000/rp_install/build/pyzmq/setup.py", line 224, in settings_from_prefix
        pkgcfginfo = check_pkgconfig()
      File "/Users/JumanaDakka/radical.pilot.sandbox/rp.session.nbp-78-74.nbp.ruw.rutgers.edu.JumanaDakka.017094.0003-pilot.0000/rp_install/build/pyzmq/setup.py", line 157, in check_pkgconfig
        check_call(['pkg-config', '--exists', 'libzmq'])
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
        retcode = call(*popenargs, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
        return Popen(*popenargs, **kwargs).wait()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
        child_exception = pickle.loads(data)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
        return Unpickler(file).load()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
        dispatch[key](self)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
        raise ValueError, "insecure string pickle"
    ValueError: insecure string pickle
```

whatever that means :/
