### ISSUE TITLE
 Resource temporarily unavailable Error on Comet

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1153]
Hello guys,

I am running some experiments on Comet and I got this error:
```
2016-11-02 15:19:09,358: agent_0.AgentExecutingComponent.0.child: agent_0.AgentExecutingComponent.0: MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/home/iparask/radical.pilot.sandbox/ve_comet/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 181, in work
    self.spawn(launcher=launcher, cu=cu)
  File "/home/iparask/radical.pilot.sandbox/ve_comet/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 313, in spawn
    creationflags      = 0)
  File "/opt/python/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/python/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
  File "/home/iparask/radical.pilot.sandbox/ve_comet/rp_install/lib/python2.7/site-packages/radical/utils/atfork/atfork.py", line 170, in os_fork_wrapper
    pid = _orig_os_fork()
OSError: [Errno 11] Resource temporarily unavailable
```
The setup is about 1500 concurrent CUs.

**Comment by andre-merzky** [comment]
Hmm, seems you run into a system limit here...  what resource config are you using?

**Comment by iparask** [comment]
I am using```xsede.comet```.

**Comment by iparask** [comment]
Hello,

please lower this limit to 1024 CUs. Is there something I can do to overcome it? It is very important to be able to maintain 1024 concurrent CUs.

Thank you,
Ioannis

**Comment by andre-merzky** [comment]
This is expected to be fixed via #1267

**Comment by iparask** [comment]
All right. I will give it a try.

**Comment by andre-merzky** [comment]
@iparask, any news?  Thanks!

**Comment by ibethune** [comment]
@iparask please update!

**Comment by andre-merzky** [comment]
Closed due to inactivity.  This should disappear with ORTE / ORTE_LIB.
