### ISSUE TITLE
test 10_pre_and_post_exec.py fails on titan by aprun

### ISSUE THREAD

**Issue by AA919** [radical-cybertools/radical.pilot#1154]
Hi, 

Test #10 fails on titan by using aprun. Below you can find the error:

#PBS -q debug 
#PBS -A CSC108 
#PBS -l nodes=4
export    PBS_O_WORKDIR=/lustre/atlas/scratch/aleang9/csc108/radical.pilot.sandbox/rp.session.titan-ext4.aleang9.017107.0055-pilot.0000 
mkdir -p  /lustre/atlas/scratch/aleang9/csc108/radical.pilot.sandbox/rp.session.titan-ext4.aleang9.017107.0055-pilot.0000
cd        /lustre/atlas/scratch/aleang9/csc108/radical.pilot.sandbox/rp.session.titan-ext4.aleang9.017107.0055-pilot.0000
export SAGA_PPN=16
/bin/bash -l bootstrap_1.sh  -d 'radical.utils-v0.44-master.tar.gz:saga-python-v0.44.RC1-1-g1a45b69-devel.tar.gz:radical.pilot-v0.44.RC1-12-gcb29106-devel.tar.gz' -m 'create' -p 'pilot.0000' -r 'local' -s 'rp.session.titan-ext4.aleang9.017107.0055' -v '/lustre/atlas/scratch/aleang9/csc108/radical.pilot.sandbox/ve_titan' -b 'default' -a 'multicore' -e 'module swap PrgEnv-pgi PrgEnv-gnu' -e 'module load python' -e 'export LD_PRELOAD=/lib64/librt.so.1' " > $SCRIPTFILE && /usr/bin/qsub $SCRIPTFILE && rm -f $SCRIPTFILE (/ccs/home/aleang9/ve/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py +116 (log_error_and_raise)  :  raise exception(message)))
Traceback (most recent call last):
  File "/ccs/home/aleang9/ve/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 799, in run
    pilotjob.run()
  File "/ccs/home/aleang9/ve/lib/python2.7/site-packages/saga/job/job.py", line 478, in run
    return self._adaptor.run (ttype=ttype)
  File "/ccs/home/aleang9/ve/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/ccs/home/aleang9/ve/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py", line 1170, in run
    self._id = self.js._job_run(self._api())
  File "/ccs/home/aleang9/ve/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py", line 695, in _job_run
    log_error_and_raise(message, saga.NoSuccess, self._logger)
  File "/ccs/home/aleang9/ve/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py", line 116, in log_error_and_raise
    raise exception(message)
NoSuccess: Error running job via 'qsub': 
 Job not submitted 
 
 You currently have a job in the debug queue. Each 
  user is allowed to have only one job at a time in the       
  debug queue.  Please wait until job 3046920 completes  
  before submitting another job to the debug queue.           
 
. Commandline was: SCRIPTFILE=`mktemp -t SAGA-Python-TORQUEJobScript.XXXXXX` &&  echo "
#!/bin/bash 
#PBS -o /lustre/atlas/scratch/aleang9/csc108/radical.pilot.sandbox/rp.session.titan-ext4.aleang9.017107.0055-pilot.0000/bootstrap_1.out 
#PBS -e /lustre/atlas/scratch/aleang9/csc108/radical.pilot.sandbox/rp.session.titan-ext4.aleang9.017107.0055-pilot.0000/bootstrap_1.err 
#PBS -l walltime=0:15:00 
#PBS -q debug 
#PBS -A CSC108 
#PBS -l nodes=4
export    PBS_O_WORKDIR=/lustre/atlas/scratch/aleang9/csc108/radical.pilot.sandbox/rp.session.titan-ext4.aleang9.017107.0055-pilot.0000 
mkdir -p  /lustre/atlas/scratch/aleang9/csc108/radical.pilot.sandbox/rp.session.titan-ext4.aleang9.017107.0055-pilot.0000
cd        /lustre/atlas/scratch/aleang9/csc108/radical.pilot.sandbox/rp.session.titan-ext4.aleang9.017107.0055-pilot.0000
export SAGA_PPN=16
/bin/bash -l bootstrap_1.sh  -d 'radical.utils-v0.44-master.tar.gz:saga-python-v0.44.RC1-1-g1a45b69-devel.tar.gz:radical.pilot-v0.44.RC1-12-gcb29106-devel.tar.gz' -m 'create' -p 'pilot.0000' -r 'local' -s 'rp.session.titan-ext4.aleang9.017107.0055' -v '/lustre/atlas/scratch/aleang9/csc108/radical.pilot.sandbox/ve_titan' -b 'default' -a 'multicore' -e 'module swap PrgEnv-pgi PrgEnv-gnu' -e 'module load python' -e 'export LD_PRELOAD=/lib64/librt.so.1' " > $SCRIPTFILE && /usr/bin/qsub $SCRIPTFILE && rm -f $SCRIPTFILE (/ccs/home/aleang9/ve/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py +116 (log_error_and_raise)  :  raise exception(message))
2016-11-02 18:39:33,966: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : [Callback]: ComputePilot 'pilot.0000' failed -- calling exit
2016-11-02 18:39:33,966: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/ccs/home/aleang9/ve/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 235, in call_callbacks
    cb_func(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/ccs/home/aleang9/ve/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 251, in _default_pilot_error_cb
    sys.exit(1)
SystemExit: 1

**Comment by marksantcroos** [comment]
The answer is in the question:
```
You currently have a job in the debug queue. Each
user is allowed to have only one job at a time in the
debug queue. Please wait until job 3046920 completes
before submitting another job to the debug queue.
```
