### ISSUE TITLE
RP 0.44 bootstrapping fails on Stampede

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#1162]
bootstrap_1.err:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/distutils/__init__.py", line 5, in <module>
    import opcode # opcode is not a virtualenv module, so we can use it to find the stdlib
ImportError: No module named opcode
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/distutils/__init__.py", line 5, in <module>
    import opcode # opcode is not a virtualenv module, so we can use it to find the stdlib
ImportError: No module named opcode
Traceback (most recent call last):
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 698, in <module>
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 701, in Environment
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 96, in get_supported_platform
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 221, in get_build_platform
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/distutils/__init__.py", line 5, in <module>
    import opcode # opcode is not a virtualenv module, so we can use it to find the stdlib
ImportError: No module named opcode
Traceback (most recent call last):
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 698, in <module>
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 701, in Environment
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 96, in get_supported_platform
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 221, in get_build_platform
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/distutils/__init__.py", line 5, in <module>
    import opcode # opcode is not a virtualenv module, so we can use it to find the stdlib
ImportError: No module named opcode
mkdir: cannot create directory `////////radical//': Permission denied
bootstrap_1.sh: line 1030: ////////radical//__init__.py: No such file or directory
bootstrap_1.sh: line 1031: ////////radical//__init__.py: No such file or directory
bootstrap_1.sh: line 1032: ////////radical//__init__.py: No such file or directory
bootstrap_1.sh: line 1033: ////////radical//__init__.py: No such file or directory
Traceback (most recent call last):
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 698, in <module>
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 701, in Environment
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 96, in get_supported_platform
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 221, in get_build_platform
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/distutils/__init__.py", line 5, in <module>
    import opcode # opcode is not a virtualenv module, so we can use it to find the stdlib
ImportError: No module named opcode
Traceback (most recent call last):
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 698, in <module>
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 701, in Environment
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 96, in get_supported_platform
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 221, in get_build_platform
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/distutils/__init__.py", line 5, in <module>
    import opcode # opcode is not a virtualenv module, so we can use it to find the stdlib
ImportError: No module named opcode
Traceback (most recent call last):
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 698, in <module>
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 701, in Environment
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 96, in get_supported_platform
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 221, in get_build_platform
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/distutils/__init__.py", line 5, in <module>
    import opcode # opcode is not a virtualenv module, so we can use it to find the stdlib
ImportError: No module named opcode
Python 2.7.12
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named radical.utils
```

bootstrap_1.out:
```
# -------------------------------------------------------------------
# bootstrap_1 running on host: c405-602.stampede.tacc.utexas.edu.
# bootstrap_1 started as     : 'bootstrap_1.sh -d radical.utils-0.44.tar.gz:saga-python-0.44.tar.gz:radical.pilot-0.44.tar.gz -m create -p pilot.0000 -r local -s rp.session.radical.antons.017117.0000 -v /work/02457/antontre/radical.pilot.sandbox/ve_stampede -b default -a multicore -e module purge -e module load TACC -e module load intel/15.0.2 -e module load python/2.7.12 -e module unload xalt -e source ~train00/ssi_sourceme -e export TACC_DELETE_FILES=TRUE'
# Environment of bootstrap_1 process:
#
#
# -------------------------------------------------------------------
 [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
APPS=/opt/apps
ARCHIVE=/home/02457/antontre
ARCHIVER=ranch.tacc.utexas.edu
ARMCI_OPENIB_DEVICE=mlx4_0
BASH_ENV=/etc/tacc/tacc_functions
BASH_FUNC_ml%%=() {  eval $($LMOD_DIR/ml_cmd "$@")
BASH_FUNC_module%%=() {  eval `$LMOD_CMD bash $*`;
_=/bin/env
CPATH=/opt/apps/intel/15/composer_xe_2015.2.164/mkl/include:/opt/apps/intel/15/composer_xe_2015.2.164/tbb/include
CVS_RSH=ssh
ENVIRONMENT=BATCH
G_BROKEN_FILENAMES=1
GLOBUS_LOCATION=/opt/apps/xsede/gsi-openssh-7.1p2f
HISTSIZE=1000
HOME=/home1/02457/antontre
HOSTNAME=c405-602.stampede.tacc.utexas.edu
ICC_BIN=/opt/apps/intel/15/composer_xe_2015.2.164/bin/intel64
ICC_LIB=/opt/apps/intel/15/composer_xe_2015.2.164/compiler/lib/intel64
IFC_BIN=/opt/apps/intel/15/composer_xe_2015.2.164/bin/intel64
IFC_LIB=/opt/apps/intel/15/composer_xe_2015.2.164/compiler/lib/intel64
I_MPI_DAPL_PROVIDER=ofa-v2-mlx4_0-1u
I_MPI_OFA_ADAPTER_NAME=mlx4_0
INCLUDE=/opt/apps/intel/15/composer_xe_2015.2.164/ipp/include:/opt/apps/intel/15/composer_xe_2015.2.164/mkl/include:/opt/apps/intel/15/composer_xe_2015.2.164/tbb/include
INFOPATH=/opt/apps/intel15/mvapich2/2.1/doc:/opt/apps/intel/15/composer_xe_2015.2.164/debugger/gdb/intel64/share/info
__Init_Default_Modules=1
INPUTRC=/etc/inputrc
INTEL_PYTHONHOME=/opt/apps/intel/15/composer_xe_2015.2.164/debugger/python/intel64
__KNLNAG__=1
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
LD_LIBRARY_PATH=/opt/apps/intel15/mvapich2/2.1/lib:/opt/apps/intel15/mvapich2/2.1/lib/shared:/opt/apps/intel/15/composer_xe_2015.2.164/mpirt/lib/intel64:/opt/apps/intel/15/composer_xe_2015.2.164/ipp/lib/intel64:/opt/apps/intel/15/composer_xe_2015.2.164/mkl/lib/intel64:/opt/apps/intel/15/composer_xe_2015.2.164/tbb/lib/intel64:/opt/apps/intel/15/composer_xe_2015.2.164/tbb/lib/intel64/gcc4.4:/opt/apps/intel/15/composer_xe_2015.2.164/compiler/lib/intel64:/opt/apps/xsede/gsi-openssh-7.1p2f/lib64:/opt/apps/xsede/gsi-openssh-7.1p2f/lib::
LESSOPEN=||/usr/bin/lesspipe.sh %s
LIBRARY_PATH=/opt/apps/intel/15/composer_xe_2015.2.164/ipp/lib/intel64:/opt/apps/intel/15/composer_xe_2015.2.164/mkl/lib/intel64:/opt/apps/intel/15/composer_xe_2015.2.164/tbb/lib/intel64:/opt/apps/intel/15/composer_xe_2015.2.164/compiler/lib/intel64
_LMFILES_=/opt/apps/modulefiles/intel/15.0.2.lua:/opt/apps/intel15/modulefiles/mvapich2/2.1:/opt/apps/modulefiles/xalt/0.6.lua:/opt/modulefiles/TACC.lua
LMOD_CMD=/opt/apps/lmod/lmod/libexec/lmod
LMOD_COLORIZE=yes
LMOD_DEFAULT_MODULEPATH=/opt/apps/xsede/modulefiles:/opt/apps/modulefiles:/opt/modulefiles
LMOD_DIR=/opt/apps/lmod/lmod/libexec
LMOD_FAMILY_COMPILER=intel
LMOD_FAMILY_MPI=mvapich2
LMOD_FULL_SETTARG_SUPPORT=no
LMOD_PKG=/opt/apps/lmod/lmod
LMOD_PREPEND_BLOCK=normal
LMOD_SETTARG_CMD=:
LMOD_SYSTEM_DEFAULT_MODULES=TACC
LMOD_VERSION=6.0.24
LOADEDMODULES=intel/15.0.2:mvapich2/2.1:xalt/0.6:TACC
LOGNAME=antontre
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.tbz=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
MAIL=/var/spool/mail/antontre
MANPATH=/usr/local/man:/usr/share/man:/usr/X11R6/man:/usr/kerberos/man:/usr/man:/opt/apps/intel15/mvapich2/2.1/share/man:/opt/apps/intel/15/composer_xe_2015.2.164/man/en_US
MIC_ENV_PREFIX=MIC
MIC_I_MPI_DAPL_PROVIDER=ofa-v2-mlx4_0-1u
MIC_I_MPI_OFA_ADAPTER_NAME=mlx4_0
MIC_LD_LIBRARY_PATH=/opt/apps/intel/15/composer_xe_2015.2.164/mkl/lib/mic:/opt/apps/intel/15/composer_xe_2015.2.164/tbb/lib/mic:/opt/intel/mic/coi/device-linux-release/lib:/opt/intel/mic/myo/lib:/opt/apps/intel/15/composer_xe_2015.2.164/compiler/lib/mic
MIC_LIBRARY_PATH=/opt/apps/intel/15/composer_xe_2015.2.164/tbb/lib/mic:/opt/apps/intel/15/composer_xe_2015.2.164/mpirt/lib/mic:/opt/apps/intel/15/composer_xe_2015.2.164/compiler/lib/mic
MKLROOT=/opt/apps/intel/15/composer_xe_2015.2.164/mkl
MODULEPATH=/opt/apps/intel15/mvapich2_2_1/modulefiles:/opt/apps/intel15/modulefiles:/opt/apps/xsede/modulefiles:/opt/apps/modulefiles:/opt/modulefiles
MODULESHOME=/opt/apps/lmod/lmod
_ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJhY3RpdmVTaXplIl09NCxiYXNlTXBhdGhBPXsiL29wdC9hcHBzL3hzZWRlL21vZHVsZWZpbGVzIiwiL29wdC9hcHBzL21vZHVsZWZpbGVzIiwiL29wdC9tb2R1bGVmaWxlcyIsfSxbImNfcmVidWlsZFRpbWUiXT1mYWxzZSxbImNfc2hvcnRUaW1lIl09ZmFsc2UsZmFtaWx5PXtbIk1QSSJdPSJtdmFwaWNoMiIsWyJjb21waWxlciJdPSJpbnRlbCIsfSxpbmFjdGl2ZT17fSxtVD17VEFDQz17WyJGTiJdPSIvb3B0L21vZHVsZWZpbGVzL1RBQ0MubHVhIixbImRlZmF1bHQiXT0wLFsiZnVsbE5hbWUiXT0iVEFDQyIsWyJsb2FkT3JkZXIiXT00LHByb3BUPXt9LFsic2hvcnQiXT0iVEFDQyIsWyJzdGF0dXMiXT0iYWN0aXZlIix9LGludGVsPXtbIkZOIl09
_ModuleTable002_=Ii9vcHQvYXBwcy9tb2R1bGVmaWxlcy9pbnRlbC8xNS4wLjIubHVhIixbImRlZmF1bHQiXT0xLFsiZnVsbE5hbWUiXT0iaW50ZWwvMTUuMC4yIixbImxvYWRPcmRlciJdPTEscHJvcFQ9e30sWyJzaG9ydCJdPSJpbnRlbCIsWyJzdGF0dXMiXT0iYWN0aXZlIix9LG12YXBpY2gyPXtbIkZOIl09Ii9vcHQvYXBwcy9pbnRlbDE1L21vZHVsZWZpbGVzL212YXBpY2gyLzIuMSIsWyJkZWZhdWx0Il09MSxbImZ1bGxOYW1lIl09Im12YXBpY2gyLzIuMSIsWyJsb2FkT3JkZXIiXT0yLHByb3BUPXt9LFsic2hvcnQiXT0ibXZhcGljaDIiLFsic3RhdHVzIl09ImFjdGl2ZSIsfSx4YWx0PXtbIkZOIl09Ii9vcHQvYXBwcy9tb2R1bGVmaWxlcy94YWx0LzAuNi5sdWEiLFsiZGVmYXVsdCJdPTEs
_ModuleTable003_=WyJmdWxsTmFtZSJdPSJ4YWx0LzAuNiIsWyJsb2FkT3JkZXIiXT0zLHByb3BUPXt9LFsic2hvcnQiXT0ieGFsdCIsWyJzdGF0dXMiXT0iYWN0aXZlIix9LH0sbXBhdGhBPXsiL29wdC9hcHBzL2ludGVsMTUvbXZhcGljaDJfMl8xL21vZHVsZWZpbGVzIiwiL29wdC9hcHBzL2ludGVsMTUvbW9kdWxlZmlsZXMiLCIvb3B0L2FwcHMveHNlZGUvbW9kdWxlZmlsZXMiLCIvb3B0L2FwcHMvbW9kdWxlZmlsZXMiLCIvb3B0L21vZHVsZWZpbGVzIix9LFsic3lzdGVtQmFzZU1QQVRIIl09Ii9vcHQvYXBwcy94c2VkZS9tb2R1bGVmaWxlczovb3B0L2FwcHMvbW9kdWxlZmlsZXM6L29wdC9tb2R1bGVmaWxlcyIsWyJ2ZXJzaW9uIl09Mix9
_ModuleTable_Sz_=3
MPICH_HOME=/opt/apps/intel15/mvapich2/2.1
MV2_IBA_HCA=mlx4_0
MV2_USE_OLD_BCAST=0
MV2_USE_UD_HYBRID=0
NLSPATH=/opt/apps/intel/15/composer_xe_2015.2.164/compiler/lib/intel64/locale/%l_%t/%N:/opt/apps/intel/15/composer_xe_2015.2.164/mkl/lib/intel64/locale/%l_%t/%N
_OLD_VIRTUAL_PATH=/opt/apps/xalt/0.6/bin:/opt/apps/intel15/mvapich2/2.1/bin:/opt/apps/intel/15/composer_xe_2015.2.164/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/opt/apps/xsede/gsi-openssh-7.1p2f/bin:/usr/X11R6/bin:/opt/ofed/bin:/opt/ofed/sbin:.
_OLD_VIRTUAL_PS1=
_OLD_VIRTUAL_PYTHONHOME=
_OLD_VIRTUAL_PYTHONPATH=
OMP_NUM_THREADS=1
PATH=/opt/apps/xalt/0.6/bin:/opt/apps/intel15/mvapich2/2.1/bin:/opt/apps/intel/15/composer_xe_2015.2.164/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/opt/apps/xsede/gsi-openssh-7.1p2f/bin:/usr/X11R6/bin:/opt/ofed/bin:/opt/ofed/sbin:.
PKG_CONFIG_PATH=/opt/apps/intel15/mvapich2/2.1/lib/pkgconfig
__PROFILE_USER_SOURCED=1
PWD=/work/02457/antontre/radical.pilot.sandbox/rp.session.radical.antons.017117.0000-pilot.0000
QTDIR=/usr/lib64/qt-3.3
QTINC=/usr/lib64/qt-3.3/include
QTLIB=/usr/lib64/qt-3.3/lib
RADICAL_PILOT_PROFILE=TRUE
randint=10
SCRATCH=/scratch/02457/antontre
SHELL=/bin/bash
SHLVL=3
SINK_LD_LIBRARY_PATH=/opt/apps/intel/15/composer_xe_2015.2.164/compiler/lib/mic:/opt/apps/intel/15/composer_xe_2015.2.164/mkl/lib/mic
SLURM_CHECKPOINT_IMAGE_DIR=/var/slurm/checkpoint
SLURM_CLUSTER_NAME=stampede
SLURM_COMMAND=sbatch
SLURM_CPUS_ON_NODE=16
SLURMD_NODENAME=c405-602
SLURM_GTIDS=0
SLURM_JOB_ACCOUNT=TG-MCB090174
SLURM_JOB_CPUS_PER_NODE=16(x2)
SLURM_JOB_ID=7853757
SLURM_JOBID=7853757
SLURM_JOB_NAME=SAGAPythonSLURMJob
SLURM_JOB_NODELIST=c405-602,c407-302
SLURM_JOB_NUM_NODES=2
SLURM_JOB_PARTITION=normal
SLURM_JOB_QOS=normal
SLURM_JOB_UID=817527
SLURM_JOB_USER=antontre
SLURM_LOCALID=0
SLURM_NNODES=2
SLURM_NODE_ALIASES=(null)
SLURM_NODEID=0
SLURM_NODELIST=c405-602,c407-302
SLURM_NPROCS=32
SLURM_NTASKS=32
SLURM_PRIO_PROCESS=0
SLURM_PROCID=0
SLURM_QUEUE=normal
SLURM_SUBMIT_DIR=/home1/02457/antontre
SLURM_SUBMIT_HOST=login1.stampede.tacc.utexas.edu
SLURM_TACC_ACCOUNT=TG-MCB090174
SLURM_TACC_CORES=32
SLURM_TACC_JOBNAME=SAGAPythonSLURMJob
SLURM_TACC_NCORES_SET=1
SLURM_TACC_NNODES_SET=0
SLURM_TACC_NODES=1
SLURM_TACC_RUNLIMIT_MINS=20
SLURM_TASK_PID=65304
SLURM_TASKS_PER_NODE=16(x2)
SLURM_TOPOLOGY_ADDR=c405-602
SLURM_TOPOLOGY_ADDR_PATTERN=node
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
SSH_CLIENT=144.76.72.175 34008 2222
SSH_CONNECTION=144.76.72.175 34008 129.114.62.11 2222
SSH_TTY=/dev/pts/187
STOCKYARD=/work/02457/antontre
TACC_DOMAIN=stampede
TACC_FAMILY_COMPILER=intel
TACC_FAMILY_MPI=mvapich2
TACC_ICC_DIR=/opt/apps/intel/15/composer_xe_2015.2.164
TACC_MKL_DIR=/opt/apps/intel/15/composer_xe_2015.2.164/mkl
TACC_MKL_INC=/opt/apps/intel/15/composer_xe_2015.2.164/mkl/include
TACC_MKL_LIB=/opt/apps/intel/15/composer_xe_2015.2.164/mkl/lib/intel64
TACC_MPI_GETMODE=mvapich2_ssh
TACC_PUBLIC_MACHINE=1
TACC_SYSTEM=stampede
TACC_XALT_BIN=/opt/apps/xalt/0.6/bin
TACC_XALT_DIR=/opt/apps/xalt/0.6/
TBBROOT=/opt/apps/intel/15/composer_xe_2015.2.164/tbb
TERM=vt100
TMPDIR=/tmp
__TRACKER__=1
USER=antontre
WORK=/work/02457/antontre
X509_USER_PROXY=/tmp/x509up_p19446.fileELvbpK.1
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# Running pre_bootstrap_1 command
# cmd: module purge
#
#
# SUCCESS
#
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# Running pre_bootstrap_1 command
# cmd: module load TACC
#
#
# SUCCESS
#
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# Running pre_bootstrap_1 command
# cmd: module load intel/15.0.2
#
#
# SUCCESS
#
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# Running pre_bootstrap_1 command
# cmd: module load python/2.7.12
#
#
# SUCCESS
#
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# Running pre_bootstrap_1 command
# cmd: module unload xalt
#
#
# SUCCESS
#
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# Running pre_bootstrap_1 command
# cmd: source ~train00/ssi_sourceme
#
#
# SUCCESS
#
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# Running pre_bootstrap_1 command
# cmd: export TACC_DELETE_FILES=TRUE
#
#
# SUCCESS
#
# -------------------------------------------------------------------
VIRTENV : /work/02457/antontre/radical.pilot.sandbox/ve_stampede
VIRTENV : /work/02457/antontre/radical.pilot.sandbox/ve_stampede (normalized)
PYTHON: /opt/apps/intel15/python/2.7.12/bin/python
PIP   : /opt/apps/intel15/python/2.7.12/bin/pip
virtenv_create   : TRUE
virtenv_update   : FALSE
rp install sources:  radical.utils-0.44/ saga-python-0.44/ radical.pilot-0.44/
rp install target : VIRTENV
rp install lock   : TRUE
virtenv /work/02457/antontre/radical.pilot.sandbox/ve_stampede exists
PYTHON: /work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/python
PIP   : /work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/pip
PYTHON INTERPRETER: /work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/python
PYTHON_VERSION    : 
VE_MOD_PREFIX     : 
PIP installer     : /work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/pip
PIP version       : 
activated virtenv
VIRTENV      : /work/02457/antontre/radical.pilot.sandbox/ve_stampede
VE_MOD_PREFIX: ///////
RP_MOD_PREFIX: ///////
PYTHONPATH   : ///////:/opt/apps/intel15/mvapich2_2_1/python/2.7.12/lib/python2.7/site-packages
do not update virtenv /work/02457/antontre/radical.pilot.sandbox/ve_stampede
rp lock for rp install (target: VIRTENV)
obtained lock /work/02457/antontre/radical.pilot.sandbox/ve_stampede.lock
Using RADICAL-Pilot install sources ' radical.utils-0.44/ saga-python-0.44/ radical.pilot-0.44/'

# -------------------------------------------------------------------
#
# uninstall radical.pilot
# cmd: /work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/pip uninstall -y radical.pilot
#
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
using virtenv install tree
PYTHONPATH: ///////:///////:/opt/apps/intel15/mvapich2_2_1/python/2.7.12/lib/python2.7/site-packages
rp_install: ///////
radicalmod: ////////radical/
created radical namespace in ////////radical//__init__.py

# -------------------------------------------------------------------
#
# update radical.utils-0.44/ via pip
# cmd: /work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/pip install  --src '/work/02457/antontre/radical.pilot.sandbox/rp.session.radical.antons.017117.0000-pilot.0000/rp_install/src' --build '/work/02457/antontre/radical.pilot.sandbox/rp.session.radical.antons.017117.0000-pilot.0000/rp_install/build' --install-option='--prefix=/work/02457/antontre/radical.pilot.sandbox/ve_stampede/rp_install' radical.utils-0.44/
#
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't install radical.utils-0.44/! Lets see how far we get ...

# -------------------------------------------------------------------
#
# update saga-python-0.44/ via pip
# cmd: /work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/pip install  --src '/work/02457/antontre/radical.pilot.sandbox/rp.session.radical.antons.017117.0000-pilot.0000/rp_install/src' --build '/work/02457/antontre/radical.pilot.sandbox/rp.session.radical.antons.017117.0000-pilot.0000/rp_install/build' --install-option='--prefix=/work/02457/antontre/radical.pilot.sandbox/ve_stampede/rp_install' saga-python-0.44/
#
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't install saga-python-0.44/! Lets see how far we get ...

# -------------------------------------------------------------------
#
# update radical.pilot-0.44/ via pip
# cmd: /work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/pip install  --src '/work/02457/antontre/radical.pilot.sandbox/rp.session.radical.antons.017117.0000-pilot.0000/rp_install/src' --build '/work/02457/antontre/radical.pilot.sandbox/rp.session.radical.antons.017117.0000-pilot.0000/rp_install/build' --install-option='--prefix=/work/02457/antontre/radical.pilot.sandbox/ve_stampede/rp_install' radical.pilot-0.44/
#
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't install radical.pilot-0.44/! Lets see how far we get ...
removed `/work/02457/antontre/radical.pilot.sandbox/ve_stampede.lock'

---------------------------------------------------------------------

 (/work/02457/antontre/radical.pilot.sandbox/ve_stampede/bin/python)
PYTHONPATH: ///////:///////:/opt/apps/intel15/mvapich2_2_1/python/2.7.12/lib/python2.7/site-packages
utils : 
install failed!
```

**Comment by andre-merzky** [comment]
thanks Antons.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/02457/antontre/radical.pilot.sandbox/ve_stampede/lib/python2.7/distutils/__init__.py", line 5, in <module>
    import opcode # opcode is not a virtualenv module, so we can use it to find the stdlib
ImportError: No module named opcode
```

This looks like a broken virtualenv, possibly due to a system level python or library upgrade.  Would you mind removing `/work/02457/antontre/radical.pilot.sandbox/ve_stampede` and try again?  Thanks!

**Comment by antonst** [comment]
Yes, cleaning virtualenv helped. Thanks Andre!
