### ISSUE TITLE
Status of RP on Rhea

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1187]
This is forward looking issue. I believe we have to use Rhea in both the Incite and the earth science projects.

**Comment by marksantcroos** [comment]
SAGA support is there already (https://github.com/radical-cybertools/saga-python/pull/592), no RP.

**Comment by andre-merzky** [comment]
Yeah, its mainly the resource config which is missing.

**Comment by mturilli** [comment]
This is now priority due to supporting the Princeton use case for the HPC-Workflow project.

**Comment by mturilli** [comment]
Apparently, Rhea uses mpirun: do/will we support it 'out of the box' or 'with customization'?

**Comment by andre-merzky** [comment]
mpirun is a supported launch method for RP, so that should work out of the box.  System limits may apply on number of concurrent processes in general, and number of concurrent mpirun instances specifically - but Vivek apparently already inquired about those limits, so lets see what he learns from support.

**Comment by vivek-bala** [comment]
From ORNL:

Rhea does not have a limit for number of mpirun executions. If you
oversubscribe the node, though, you will notice poor performance.

**Comment by vivek-bala** [comment]
Hey Andre.. I took a crack at the config file for Rhea but ran into some errors. Note this is for testing for submitting jobs to Rhea from Rhea (and not Titan).

Error (umgr.0000.log):
```
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rhea/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 521, in ru_initialize_common
    self._log)
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rhea/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 152, in start_bridges
    bridge = rpu_Queue(session, bname, rpu_QUEUE_BRIDGE, bcfg_clone)
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rhea/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 182, in __init__
    self._pqueue = mp.Queue()
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/queues.py", line 69, in __init__
    self._sem = BoundedSemaphore(maxsize)
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/synchronize.py", line 130, in __init__
    SemLock.__init__(self, SEMAPHORE, value, value)
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 28] No space left on device
2017-06-16 02:12:02,140: umgr.0000           : MainProcess                     : MainThread     : ERROR   : initialization error
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rhea/lib/python2.7/site-packages/radical/utils/process.py", line 776, in _ru_initialize
    self.ru_initialize_common()
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rhea/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 521, in ru_initialize_common
    self._log)
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rhea/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 152, in start_bridges
    bridge = rpu_Queue(session, bname, rpu_QUEUE_BRIDGE, bcfg_clone)
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rhea/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 182, in __init__
    self._pqueue = mp.Queue()
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/queues.py", line 69, in __init__
    self._sem = BoundedSemaphore(maxsize)
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/synchronize.py", line 130, in __init__
    SemLock.__init__(self, SEMAPHORE, value, value)
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 28] No space left on device
2017-06-16 02:12:02,141: umgr.0000           : MainProcess                     : MainThread     : ERROR   : initialization failed (initialize: OSError(28, 'No space left on device'))
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rhea/lib/python2.7/site-packages/radical/utils/process.py", line 468, in start
    self._ru_initialize()
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rhea/lib/python2.7/site-packages/radical/utils/process.py", line 793, in _ru_initialize
    raise RuntimeError('initialize: %s' % repr(e))
RuntimeError: initialize: OSError(28, 'No space left on device')
2017-06-16 02:12:02,246: umgr.0000           : MainProcess                     : MainThread     : INFO    : stop umgr.0000 (46350 : None : MainThread) [radical.utils.process.UnitManager.start]
2017-06-16 02:12:02,246: umgr.0000           : MainProcess                     : MainThread     : INFO    : parent stops child
2017-06-16 02:12:02,246: umgr.0000           : MainProcess                     : MainThread     : DEBUG   : ru_finalize_common()
2017-06-16 02:12:02,247: umgr.0000           : MainProcess                     : MainThread     : WARNING : publisher state_pubsub is not registered
2017-06-16 02:12:02,247: umgr.0000           : MainProcess                     : MainThread     : WARNING : publisher control_pubsub is not registered
2017-06-16 02:12:02,247: umgr.0000           : MainProcess                     : MainThread     : DEBUG   : umgr.0000 close prof
```

Quick googling of [os error 28](http://www.linuxquestions.org/questions/linux-newbie-8/linux-error-28-no-space-left-on-device-689726/) indicates that the script is trying to create something in root and does not have space. Do you see anything that might suggest that? The config file is pretty similar to the one being used for Titan. Let me know.

Also, in order to be able to submit to Rhea from Titan we need to add ```#PBS -q rhea``` to the reservation request. I tested it via pbs scripts and it worked fine. Any pointers on how I can specify this in RP/SAGA? Thanks.

**Comment by vivek-bala** [comment]
> Also, in order to be able to submit to Rhea from Titan we need to add #PBS -q rhea (thanks for pointing me to that) to the reservation request. I tested it via pbs scripts and it worked fine. Any pointers on how I can specify this in RP/SAGA? Thanks.

Please ignore this. This is resolved. I simply had to set the queue name as Rhea.

**Comment by vivek-bala** [comment]
I tried to submit a job from Titan on to Rhea using this branch. It seems like one of the packages does not get installed while bootstrapping.

bootstrap1.out: https://gist.github.com/vivek-bala/bf55dc5ec542868976afbb2d682b3bf0

**Comment by andre-merzky** [comment]
This should be addressed by now - could you please give it another try (after emptying the pilot VE)?

**Comment by vivek-bala** [comment]
I tried the rp examples from titan but used the resource label 'ornl.rhea' and queue name 'rhea'. The examples failed. Similar to #1441, the client side logs look the same and there is no VE created in the sandbox.

Stack:
```
> radical-stack

  python               : 2.7.9
  pythonpath           : /sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /autofs/nccs-svm1_home1/vivekb/ves/test-gpu

  radical.pilot        : 0.46-v0.46.RC1-50-gd621ba4@feature-rhea_support
  radical.utils        : 0.47-v0.46-10-gc515db1@devel
  saga                 : 0.46-v0.46.RC1-15-gf2f6aa2@feature-rhea
```

[rp.session.titan-ext7.vivekb.017415.0008.zip](https://github.com/radical-cybertools/radical.pilot/files/1281577/rp.session.titan-ext7.vivekb.017415.0008.zip)


Client side logs are attached.

**Comment by vivek-bala** [comment]
Attaching the client side logs here
[rp.session.titan-ext7.vivekb.017415.0008.zip](https://github.com/radical-cybertools/radical.pilot/files/1282386/rp.session.titan-ext7.vivekb.017415.0008.zip)
. The above logs are from the remote side.

**Comment by mturilli** [comment]
We don't know whether Rhea will be still needed by the Princeton use case. I am going to close this and we will reopen it if the support is needed.
