### ISSUE TITLE
client side updatedb errors with split_module_2

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1189]
10000 cu's (that are all DONE) over 100 nodes on Titan.

```
2017-01-18 11:18:35,440: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000557 [AGENT_EXECUTING] update.0.child
2017-01-18 11:18:35,440: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000557 [AGENT_STAGING_OUTPUT_PENDING] update.0.child
2017-01-18 11:18:35,441: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000557 [AGENT_STAGING_OUTPUT] update.0.child
2017-01-18 11:18:35,442: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000557 [UMGR_STAGING_OUTPUT_PENDING] update.0.child
2017-01-18 11:18:35,443: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000556 [AGENT_EXECUTING] update.0.child
2017-01-18 11:18:35,443: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000556 [AGENT_STAGING_OUTPUT_PENDING] update.0.child
2017-01-18 11:18:35,444: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000556 [AGENT_STAGING_OUTPUT] update.0.child
2017-01-18 11:18:35,444: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000556 [UMGR_STAGING_OUTPUT_PENDING] update.0.child
2017-01-18 11:18:35,445: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000551 [AGENT_EXECUTING] update.0.child
2017-01-18 11:18:35,446: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000551 [AGENT_STAGING_OUTPUT_PENDING] update.0.child
2017-01-18 11:18:35,446: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000551 [AGENT_STAGING_OUTPUT] update.0.child
2017-01-18 11:18:35,447: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000551 [UMGR_STAGING_OUTPUT_PENDING] update.0.child
2017-01-18 11:18:35,448: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000550 [AGENT_EXECUTING] update.0.child
2017-01-18 11:18:35,449: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000550 [AGENT_STAGING_OUTPUT_PENDING] update.0.child
2017-01-18 11:18:35,449: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000550 [AGENT_STAGING_OUTPUT] update.0.child
2017-01-18 11:18:35,450: update.0.child      : update.0                        : update.0.child.subscriber: DEBUG   : bulked unit.000550 [UMGR_STAGING_OUTPUT_PENDING] update.0.child
2017-01-18 11:18:39,583: update.0.child      : update.0                        : update.0.child.subscriber: ERROR   : bulk exec error: {'nModified': 77, 'nUpserted': 0, 'nMatched': 77, 'writeErrors': [{
u'index': 77, u'code': 12501, u'errmsg': u'quota exceeded', u'op': SON([('q', {'type': 'unit', 'uid': 'unit.000555'}), ('u', {'$set': {'state': 'AGENT_STAGING_OUTPUT_PENDING', 'type': 'unit', 'uid': 'un
it.000555'}, '$push': {'states': 'AGENT_STAGING_OUTPUT_PENDING'}}), ('multi', True), ('upsert', False)])}], 'upserted': [], 'writeConcernErrors': [], 'nRemoved': 0, 'nInserted': 0}
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/worker/update.py", line 97, in _timed_bulk_execute
    res = self._bulk.execute()
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/pymongo/bulk.py", line 587, in execute
    return self.__bulk.execute(write_concern)
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/pymongo/bulk.py", line 433, in execute
    return self.execute_command(generator, write_concern)
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/pymongo/bulk.py", line 300, in execute_command
    raise BulkWriteError(full_result)
BulkWriteError: batch op errors occurred
2017-01-18 11:18:39,586: update.0.child      : update.0                        : update.0.child.subscriber: ERROR   : subscriber failed update.0.child.subscriber
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1199, in _subscriber
    callback(topic=topic, msg=m)
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/worker/update.py", line 250, in _state_cb
    self._timed_bulk_execute()
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/worker/update.py", line 97, in _timed_bulk_execute
    res = self._bulk.execute()
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/pymongo/bulk.py", line 587, in execute
    return self.__bulk.execute(write_concern)
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/pymongo/bulk.py", line 433, in execute
    return self.execute_command(generator, write_concern)
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/pymongo/bulk.py", line 300, in execute_command
    raise BulkWriteError(full_result)
BulkWriteError: batch op errors occurred
2017-01-18 11:18:39,587: update.0.child      : update.0                        : update.0.child.idler._idle_cb: ERROR   : mongodb error: Bulk operations can only be executed once.
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/worker/update.py", line 97, in _timed_bulk_execute
    res = self._bulk.execute()
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/pymongo/bulk.py", line 587, in execute
    return self.__bulk.execute(write_concern)
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/pymongo/bulk.py", line 418, in execute
    raise InvalidOperation('Bulk operations can '
InvalidOperation: Bulk operations can only be executed once.
2017-01-18 11:18:39,588: update.0.child      : update.0                        : update.0.child.idler._idle_cb: ERROR   : TERM : update.0.child idler failed update.0.child.idler._idle_cb
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1055, in _idler
    callback()
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/worker/update.py", line 133, in _idle_cb
    return self._timed_bulk_execute()
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/radical/pilot/worker/update.py", line 97, in _timed_bulk_execute
    res = self._bulk.execute()
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/pymongo/bulk.py", line 587, in execute
    return self.__bulk.execute(write_concern)
  File "/autofs/nccs-svm1_home1/marksant1/ve/lib/python2.7/site-packages/pymongo/bulk.py", line 418, in execute
    raise InvalidOperation('Bulk operations can '
InvalidOperation: Bulk operations can only be executed once.
2017-01-18 11:18:39,588: update.0.child      : update.0                        : update.0.child.idler._idle_cb: DEBUG   : TERM : update.0.child idler final update.0.child.idler._idle_cb
2017-01-18 11:18:39,686: update.0.child      : update.0                        : update.0.child.idler._thread_watcher_cb: ERROR   : TERM : update.0.child idler update.0.child.idler._idle_cb died
```

Database is not full.

**Comment by andre-merzky** [comment]
Maybe there is a size limit for the bulk ops or something - I did not see that error before.  Thanks for the Ticket!

**Comment by marksantcroos** [comment]
Same error if I try to submit 50k units, then it fails immediately. Easier to reproduce probably.

**Comment by andre-merzky** [comment]
The bulk size is limited now, and that value is configurable.
