### ISSUE TITLE
version error during bootstrapping

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1196]
bootstrapper_1.err:
```
Python 2.7.12
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/__init__.py", line 18, in <module>
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/session.py", line 23, in <module>
    from .unit_manager    import UnitManager
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 26, in <module>
    from .controller   import UnitManagerController
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/controller/__init__.py", line 10, in <module>
    from pilot_manager_controller import PilotManagerController
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 28, in <module>
    from .pilot_launcher_worker import PilotLauncherWorker
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 28, in <module>
    _, _, _, rp_sdist_name, rp_sdist_path = ru.get_version([root, pwd])
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/utils/get_version.py", line 85, in get_version
    raise RuntimeError ("Cannot determine version from %s" % paths)
RuntimeError: Cannot determine version from ['/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/controller/../', '/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/controller']
```

bootstrapper_1.out: https://gist.github.com/vivek-bala/64b85e92e68ff094a95938d02eaf4e1a
resource: stampede
rp-version: v0.42-159-g578421a-usecase-vivek
ru-version: 0.44
saga-version: 0.44

I've come across this error 2-3 times. I am not exactly sure about the source of the error. But in all these cases I had 2 pilots submitted to the queue where one of the pilots failed after going Active with the error above (the other pilot was successful). Not consistently reproducible.

Let me how I can help debug.

**Comment by andre-merzky** [comment]
Yeah, this is a strange one which I also saw recently. I have no fucking clue what pip does here. I mean, within the scope of a couple of lines is says Successfully installed radical.pilot and cannot use radical.pilot. Pfft.

Can you please try to remove ve_stampede and start from scratch? If that still fails, can you please give me read access to your sandbox on stampede? Thanks!

**Comment by vivek-bala** [comment]
Ok, I'll clean the ve on stampede. If it pops up again, I'll update this ticket.

**Comment by andre-merzky** [comment]
please reopen if needed.
