### ISSUE TITLE
Failed to bootstrap

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/radical.pilot#1207]
So after installing the 0.45.RC1 stack on my Mac, I get an error starting the pilot during the first test:

```
(0.45-test-env) Iains-MacBook-Pro:examples ibethune$ ./00_getting_started.py 

================================================================================
 Getting Started (RP version v0.45.RC1)                                         
================================================================================

new session: [rp.session.Iains-MacBook-Pro.local.ibethune.017210.0000]         \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]                     ok
read config                                                                   ok

--------------------------------------------------------------------------------
submit pilots                                                                   

create pilot manager                                                          ok
create pilot description [local.localhost:2]                                  ok
submit 1 pilot(s) .                                                           ok

--------------------------------------------------------------------------------
submit units                                                                    

create unit manager                                                           ok
add 1 pilot(s)                                                                ok
create 128 unit description(s)
        ........................................................................
        ........................................................              ok
submit 128 unit(s)
        ........................................................................
        ........................................................2017-02-13 17:23:33,061: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: ERROR   : Using bootstrapper /Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/radical/pilot/bootstrapper/bootstrap_1.sh
Copying bootstrapper 'file://localhost/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/radical/pilot/bootstrapper/bootstrap_1.sh' to agent sandbox (<saga.filesystem.directory.Directory object at 0x10a988150>).
Copying sdist 'file://localhost/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/radical/utils/radical.utils-v0.45.RC1-HEAD-detached-at-v0.45.RC1.tar.gz' to sandbox (file://localhost/Users/ibethune/radical.pilot.sandbox/rp.session.Iains-MacBook-Pro.local.ibethune.017210.0000-pilot.0000/).
Copying sdist 'file://localhost/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/saga/saga-python-v0.45.RC1-HEAD-detached-at-v0.45.RC1.tar.gz' to sandbox (file://localhost/Users/ibethune/radical.pilot.sandbox/rp.session.Iains-MacBook-Pro.local.ibethune.017210.0000-pilot.0000/).
Copying sdist 'file://localhost/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/radical/pilot/controller/..//radical.pilot-v0.45.RC1-HEAD-detached-at-v0.45.RC1.tar.gz' to sandbox (file://localhost/Users/ibethune/radical.pilot.sandbox/rp.session.Iains-MacBook-Pro.local.ibethune.017210.0000-pilot.0000/).
Writing agent configuration to file '/var/folders/fk/ljxr9h0x2zx1lcjrtskgv02r0000gn/T/rp_agent_cfg_dirg2Z_uu/agent_0.cfg'.
Copying agent configuration file 'file://localhost/var/folders/fk/ljxr9h0x2zx1lcjrtskgv02r0000gn/T/rp_agent_cfg_dirg2Z_uu/agent_0.cfg' to sandbox (file://localhost/Users/ibethune/radical.pilot.sandbox/rp.session.Iains-MacBook-Pro.local.ibethune.017210.0000-pilot.0000/).
Pilot launching failed! (failed to run bootstrap: (127)(/bin/sh: /Users/ibethune/.saga/adaptors/shell_job//wrapper.sh: No such file or directory
) (/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py +629 (initialize)  :  raise saga.NoSuccess ("failed to run bootstrap: (%s)(%s)" % (ret, out))))
Traceback (most recent call last):
  File "/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 724, in run
    js = saga.job.Service(js_url, session=self._session)
  File "/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line 512, in init_instance
    self.initialize ()
  File "/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line 629, in initialize
    raise saga.NoSuccess ("failed to run bootstrap: (%s)(%s)" % (ret, out))
NoSuccess: failed to run bootstrap: (127)(/bin/sh: /Users/ibethune/.saga/adaptors/shell_job//wrapper.sh: No such file or directory
) (/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py +629 (initialize)  :  raise saga.NoSuccess ("failed to run bootstrap: (%s)(%s)" % (ret, out)))
2017-02-13 17:23:33,417: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : [Callback]: ComputePilot 'pilot.0000' failed -- calling exit
2017-02-13 17:23:33,418: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 235, in call_callbacks
    cb_func(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/Users/ibethune/Desktop/0.45-test-env/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 251, in _default_pilot_error_cb
    sys.exit(1)
SystemExit: 1
exit requested

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.Iains-MacBook-Pro.local.ibethune.017210.0000        \
close pilot manager                                                            \
wait for 1 pilot(s) -                                                         ok
                                                                              ok
close unit manager                                                            ok
session lifetime: 5.7s                                                        ok

--------------------------------------------------------------------------------

```

In case it's not obviously me doing something daft, sandbox to follow.

**Comment by ibethune** [comment]
[sandbox1207.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/771858/sandbox1207.tar.gz)

**Comment by iparask** [comment]
Mac OS is not fully supported, if I not wrong. I do not remember the exact reason.

**Comment by vivek-bala** [comment]
I got the same error on a linux terminal. I deleted ```$HOME/.saga```, it seems to have fixed it.

**Comment by andre-merzky** [comment]
Hi @ibethune: thanks for the sandbox!  That looks virgin, in the sense that it seems that the pilot did not even start to unpack the staged files.  Maybe @vivek-bala is right, and that is a SAGA version problem: could you try to remove `~/.saga`, and run again?  If that still fails, please run

```
export RADICAL_PILOT_VERBOSE=DEBUG
export RADICAL_VERBOSE=DEBUG
export RADICAL_LOG_TGT=/tmp/rp.log
```

then run again and send the resulting log file.  Thanks!

@iparask : that is true for the split_module branches, where we are hitting thread limits in the default MacOS configuration currently.  The devel and release branches should work out of the box though -- but the plethora of ways to deploy Python on MacOS maces life... challenging :/

**Comment by ibethune** [comment]
For reference, subsequent runs all completed OK.  I will try with a fresh VE and see if it re-occurs.

**Comment by ibethune** [comment]
So this didn't reoccur with a fresh install... so must be either something rare, or something bad in my .saga dir from a previous install.
