### ISSUE TITLE
fail to bootstrap on wrangler

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#1209]
```
Traceback (most recent call last):
  File "/work/03662/tg829618/wrangler/radical.pilot.sandbox/ve_wrangler/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 21, in <module>
  File "/usr/lib64/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /work/03662/tg829618/wrangler/radical.pilot.sandbox/ve_wrangler/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS4_EncodeUTF32
Traceback (most recent call last):
  File "/work/03662/tg829618/wrangler/radical.pilot.sandbox/ve_wrangler/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 21, in <module>
  File "/usr/lib64/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /work/03662/tg829618/wrangler/radical.pilot.sandbox/ve_wrangler/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS4_EncodeUTF32
Traceback (most recent call last):
  File "/work/03662/tg829618/wrangler/radical.pilot.sandbox/ve_wrangler/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 21, in <module>
  File "/usr/lib64/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /work/03662/tg829618/wrangler/radical.pilot.sandbox/ve_wrangler/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS4_EncodeUTF32
Traceback (most recent call last):
  File "/work/03662/tg829618/wrangler/radical.pilot.sandbox/ve_wrangler/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 21, in <module>
  File "/usr/lib64/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /work/03662/tg829618/wrangler/radical.pilot.sandbox/ve_wrangler/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS4_EncodeUTF32
Python 2.7.9
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/03662/tg829618/wrangler/radical.pilot.sandbox/rp.session.radical.george.017210.0008-pilot.0000/rp_install/lib/python2.7/site-packages/radical/__init__.py", line 2, in <module>
    import pkg_resources
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 21, in <module>
  File "/usr/lib64/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /work/03662/tg829618/wrangler/radical.pilot.sandbox/ve_wrangler/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS4_EncodeUTF32
```

**Comment by vivek-bala** [comment]
Hey george, just edited your comment. Please use ``` <long verbose output> ``` syntax. It makes it a bit more legible.

**Comment by andre-merzky** [comment]
@vivek-bala: thanks! :D 

@georgeha: it seems that the python version on Wrangler got updated, and the pilot's virtualenv is not compatible with that version anymore.  This relates to #555 -- at the moment we make no attempt to detect system python upgrades of that kind.

Please remove `$HOME/radical.pilot.sandbbox/ve_wrangler` on the target machine, and try again.  That will cause the agent to recreate the VE from scratch, which should then be in sync with the python version.

Note that the wrangler configuration contains this line:

```
module load python/2.7.9
```

Can you please confirm that this module is still available and functional?  Otherwise bootstrap is likely to fail again...

**Comment by georgeha** [comment]
Hi @andre-merzky,

python/2.7.9 is there and works fine.

**Comment by andre-merzky** [comment]
Ok - then please remove the ve_wrangler and retry.  Thanks!

**Comment by georgeha** [comment]
Hi Andre,

I removed the ve and it worked. Also,  I saw these error which I think it worth mentioning

```
2017-02-14 21:08:39,998: radical.saga.cpi    : MainProcess                     : PilotLauncherWorker-1: ERROR   : set name 2: tmp_cAGtae.slurm
```

**Comment by andre-merzky** [comment]
Great - then I would consider this as solved.  But let me address this error message before closing the ticket -- that is a leftover from some debugging session...
