### ISSUE TITLE
orte_cffi could not be installed

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1213]
I see the following error in the bootstrapped's output:
```
# -------------------------------------------------------------------
#
# install orte_cffi
# cmd: /home/iparask/radical.pilot.sandbox/ve_localhost/bin/pip install orte_cffi
#
Collecting orte_cffi
  Downloading orte-cffi-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-91EUqn/orte-cffi/setup.py", line 15, in <module>
        install_requires = ["cffi>=1.5.0"],
      File "/home/iparask/radical.pilot.sandbox/ve_localhost/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/iparask/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/iparask/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/iparask/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/iparask/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1118, in best_match
        return self.obtain(req, installer)
      File "/home/iparask/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1130, in obtain
        return installer(requirement)
      File "/home/iparask/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/iparask/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/iparask/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 700, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/iparask/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/iparask/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/iparask/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1108, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1

    ----------------------------------------
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't install orte_cffi! Lets see how far we get ...
```
The run completes, but I am not sure if this can cause a problem.

I see it when I run localist

**Comment by andre-merzky** [comment]
This is related to #1163.  Right now, the agent will always try to install `orte-cffi`, even if it will actually not use the `ortelib` startup method.  Reason simply is that we don't yet have configuration derived python dependencies, but only a fixed set of dependencies.  For all machines where we use ortelib, we have to manually make sure that `orte-cffi` is installed, installable or otherwise available to the pilot.

The error you see should indeed be ignored by the agent.  It causes some seconds bootstrap delay, but otherwise has no ill side effects.

I don't mind keeping this ticket open to eventually address this, but it has low priority right now, really.  Thanks for reporting it! :-)

**Comment by iparask** [comment]
I see! Thank you!

**Comment by mturilli** [comment]
ORTE has been discontinued, closing.
