### ISSUE TITLE
Pilot does not fail when bootstrap fails on ARCHER

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/radical.pilot#1216]
Possibly two issues here:

1) When I try to run examples towards epsrc.archer, bootstrapping fails with the following in bootstrap_1.out:

```
#
# SUCCESS
#
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# update saga-python-v0.45.RC1-HEAD-detached-at-v0.45.RC1/ via pip
# cmd: /work/e290/shared/shared_pilot_ve_20150924/bin/pip install  --src '/work/z01/z01/ibethune/radical.pil
ot.sandbox/rp.session.mbp-ib.epcc.ed.ac.uk.ibethune.017211.0005-pilot.0000/rp_install/src' --build '/work/z0
1/z01/ibethune/radical.pilot.sandbox/rp.session.mbp-ib.epcc.ed.ac.uk.ibethune.017211.0005-pilot.0000/rp_inst
all/build' --install-option='--prefix=/work/z01/z01/ibethune/radical.pilot.sandbox/rp.session.mbp-ib.epcc.ed
.ac.uk.ibethune.017211.0005-pilot.0000/rp_install' saga-python-v0.45.RC1-HEAD-detached-at-v0.45.RC1/
#
Unpacking ./saga-python-v0.45.RC1-HEAD-detached-at-v0.45.RC1
  Running setup.py egg_info for package from file:///fs3/z01/z01/ibethune/radical.pilot.sandbox/rp.session.m
bp-ib.epcc.ed.ac.uk.ibethune.017211.0005-pilot.0000/saga-python-v0.45.RC1-HEAD-detached-at-v0.45.RC1
    version: v0.45.RC1@HEAD-detached-at-v0.45.RC1 (v0.45.RC1@HEAD-detached-at-v0.45.RC1)
    
Requirement already satisfied (use --upgrade to upgrade): apache-libcloud in /fs4/e290/shared/shared_pilot_v
e_20150924/lib/python2.7/site-packages (from saga-python==v0.45.RC1-HEAD-detached-at-v0.45.RC1)
Downloading/unpacking radical.utils>=0.44 (from saga-python==v0.45.RC1-HEAD-detached-at-v0.45.RC1)
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement radical.utils>=0.44 (from saga-python==v0.45.RC1
-HEAD-detached-at-v0.45.RC1)
No distributions at all found for radical.utils>=0.44 (from saga-python==v0.45.RC1-HEAD-detached-at-v0.45.RC
1)
Storing complete log in /home/z01/z01/ibethune/.pip/pip.log
#
# ERROR
# no fallback command available
```

It's not clear to me if this is just an issue with trying to install in /work/e290/shared (which I can't write to, my user is in group z01), or if there is some other problem indicated by the "Cannot fetch index base" message.  Let me know what output you would like to see to help debug.

Actually, we need to stop using the e290 space as this group space will be removed on 9th April.  A better place is z01 (service staff group) or y07 (software packages), both of which will be around long-term.

2) There is no real indication to the client that the pilot failed.  Everything looks good, except that the  unit statuses are yellow * rather than green +.  In particular, the pilot exit state is "ok", but of course none of the CUs were in fact executed...

```
(0.45-test-env2) Iains-MacBook-Pro:examples ibethune$ ./00_getting_started.py epsrc.archer

================================================================================
 Getting Started (RP version v0.45.RC1)                                         
================================================================================

new session: [rp.session.mbp-ib.epcc.ed.ac.uk.ibethune.017211.0005]            \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]                     ok
read config                                                                   ok

--------------------------------------------------------------------------------
submit pilots                                                                   

create pilot manager                                                          ok
create pilot description [epsrc.archer:48]                                    ok
submit 1 pilot(s) .                                                           ok

--------------------------------------------------------------------------------
submit units                                                                    

create unit manager                                                           ok
add 1 pilot(s)                                                                ok
create 128 unit description(s)
        ........................................................................
        ........................................................              ok
submit 128 unit(s)
        ........................................................................
        ........................................................              ok

--------------------------------------------------------------------------------
gather results                                                                  

wait for 128 unit(s)
        ***********************************************************************|
        *********************************************************             ok

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.mbp-ib.epcc.ed.ac.uk.ibethune.017211.0005           \
close pilot manager                                                            \
wait for 1 pilot(s) +                                                         ok
                                                                              ok
close unit manager                                                            ok
session lifetime: 81.9s                                                       ok

--------------------------------------------------------------------------------
```

**Comment by andre-merzky** [comment]
Indeed, those are two issues.  

I can't remember the setup on archer: are the mom- and compute nodes able to access the public internet?  Since we use a shared virtualenv, this might not have been the case?

For the second one: can you please attach `bootstrap_1.{out,err}` from the pilot sandbox, and also create a log file on the client side and attach it?

```
export RADICAL_PILOT_VERBOSE=DEBUG
export RADICAL_SAGA_PTY_VERBOSE=DEBUG
export RADICAL_VERBOSE=DEBUG
export RADICAL_LOG_TGT=/tmp/rp.log
```

The job should have exited with an error, and the pilot watcher thread should have picked this up.  But, having said that, on some machines its actually hard to get information about the status of a finishing job, specifically if the batch system purges job infos very quickly.  If the pilot did not manage to report any state to the database when it dies (which is what happens on bootstrapping errors), we are left to guess the pilot state - and the SAGA layer in that case guesses `DONE`... :/

**Comment by ibethune** [comment]
Continuing just the discussion of the ve setup here...

Neither the ARCHER mom nodes nor compute nodes have access to the outside internet.  AFAIK all communication goes out via SSH tunnels set up between login nodes and MOM.  It looks like various shared VEs have been set up in the past by you or Mark:

```
ibethune@eslogin005:~> ls -ltr /work/e290/shared/
total 68
dr-xr-sr-x  6 marksant e290 4096 Jun 30  2014 shared_pilot_ve_20140630
dr-xr-sr-x  5 marksant e290 4096 Aug 29  2014 shared_pilot_ve_20140703
drwxr-sr-x  5 merzky   e290 4096 Feb 17  2015 ve
dr-xr-sr-x  6 merzky   e290 4096 Feb 17  2015 shared_pilot_ve_20150217
dr-xr-sr-x  7 merzky   e290 4096 Feb 27  2015 shared_pilot_ve_20150225
drwxr-sr-x  6 merzky   e290 4096 Mar 25  2015 shared_pilot_ve_20150325
drwxr-sr-x  6 merzky   e290 4096 Apr 29  2015 shared_pilot_ve_20150429
drwxr-sr-x  3 marksant e290 4096 Sep  4  2015 shared_pilot_ve_20141216
drwxr-sr-x  6 marksant e290 4096 Sep  4  2015 shared_pilot_ve_20150904
drwxr-sr-x 11 merzky   e290 4096 Sep  9  2015 shared_pilot_ve_20150909
drwxr-sr-x  6 marksant e290 4096 Sep 16  2015 shared_pilot_ve_20150916
drwxr-sr-x  8 pmke290  e290 4096 Oct 11  2015 copernicus
drwxr-sr-x  7 marksant e290 4096 Oct 13  2015 shared_pilot_ve_20150924
drwxrwsr-x  2 merzky   e290 4096 Oct 25  2015 data
lrwxrwxrwx  1 marksant e290    7 Dec 17  2015 privatemodules -> modules
drwxr-sr-x  5 marksant e290 4096 Dec 17  2015 openmpi
drwxr-sr-x  4 marksant e290 4096 Dec 17  2015 modules
drwxr-sr-x  3 marksant e290 4096 Dec 17  2015 gromacs
```

Happy to do whatever needs done, if you can instruct me!

**Comment by andre-merzky** [comment]
The shared VE seems to be fine after all, I don't think there is action needed on that end, thanks!

For the record: we have a small tool in RP (`bin/radicalpilot-create-static-ve`), which, as the name suggests, supports the creation of a shared static VE on that kind of resources.  Testing that tool is not part of the test protocol though, as its rarely needed, and its usually a member of the group who creates and maintains those VEs.


To debug the second part, would need the client side logs :)

**Comment by ibethune** [comment]
Thanks Andre.  I think the 'second part' you refer to here is #1217 and client logs are attached there.  Your comment in that issue re: versioned dependencies belongs in this ticket, right (since here we are concerned with fixing the bootstrapping)?  Can you please move the comment over, if I've not misunderstood entirely...

**Comment by andre-merzky** [comment]
Apologies, I missed the client logs in the gist!  Thanks!

**Comment by andre-merzky** [comment]
This is the relevant part of the log (shortened),  and it indeed indicates a problem:

```
INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[4318431])
DEBUG   : read : [   20] [  174] (    job_state = F\n    ctime = Tue Feb 14 11:13:25 2017\n    exec_host = mom3/145*24+mom3/149*24\n    mtime = Tue Feb 14 11:14:26 2017\n    stime = Tue Feb 14 11:13:31 2017\n    Exit_status = 1\n)
INFO    : Job monitoring thread updating Job [pbspro+ssh://login.archer.ac.uk/]-[4318431] (old state: Running, new state: Done)
```

The qstat output clearly indicates failure, both in state and exit code, but it is either not parsed correctly on the SAGA layer, not interpreted correctly at the SAGA layer, or not evaluated correctly on the RP layer.  This needs fixing before the release.

**Comment by andre-merzky** [comment]
Bugger, I don't think I have an allocation on archer to run tests.  Iain, do you know if/how I can submit short running tests on Archer?

**Comment by ibethune** [comment]
Go to http://www.archer.ac.uk/safe and request an account in group e291.  Should be set up for you within the day.  There is not much budget there but you can run testing jobs. For best turnaround, submit <20m, <8 nodes and use the 'short' queue.

Otherwise I can run stuff for you if needed.

**Comment by ibethune** [comment]
I'm editing the titles on both this ticket and #1217 to make it clear which is which...

**Comment by andre-merzky** [comment]
This should be addressed in branch `fix/issue_1216` - can you give that a try, please?

**Comment by ibethune** [comment]
I might be being dense, but I don't see that branch.  Did you push it?

**Comment by andre-merzky** [comment]
Oh, apologies - the job state handling got fixed on the SAGA layer:  https://github.com/radical-cybertools/saga-python/tree/fix/issue_1216

**Comment by ibethune** [comment]
The client now detects the failure and exits:

```
(0.45-test-env2) mbp-ib:examples ibethune$ ./00_getting_started.py epsrc.archer

<snip>
--------------------------------------------------------------------------------
gather results                                                                  

wait for 128 unit(s)
        /2017-02-17 08:36:14,227: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : [Callback]: ComputePilot 'pilot.0000' failed -- calling exit
2017-02-17 08:36:14,227: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/Users/ibethune/Desktop/0.45-test-env2/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 235, in call_callbacks
    cb_func(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/Users/ibethune/Desktop/0.45-test-env2/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 251, in _default_pilot_error_cb
    sys.exit(1)
SystemExit: 1
exit requested

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.Iains-MacBook-Pro.local.ibethune.017214.0000        \
close pilot manager                                                            \
wait for 1 pilot(s) -                                                         ok
                                                                              ok
close unit manager                                                            ok
session lifetime: 67.8s                                                       ok

--------------------------------------------------------------------------------
```
If that looks like you expected, then please merge that branch.

**Comment by andre-merzky** [comment]
Done

**Comment by ibethune** [comment]
Thanks!
