### ISSUE TITLE
OSG runs fail with 'insufficient system resources'

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1263]
```
$ radical-stack 
python            : 2.7.6
virtualenv        : /home/mturilli/ve/AIMES-EXPERIENCE
radical.utils     : v0.44.RC1-11-ge108e90@experiment-aimes
saga-python       : v0.44-137-g98a692ed@experiment-aimes
radical.pilot     : v0.40.1-243-g52f0a6ce@experiment-aimes
```
Observed the following few times already. Session `rp.session.radical.mturilli.017230.0000`, logs at `/home/mturilli/experiments/AIMES-Experience/OSG/bin/radical.log`, error:

```
Traceback (most recent call last):
File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/radical/utils/threads.py", line 159, in run                                                                                     self._result    = self._call(*self._args, **self._kwargs)                                                                                                                                              File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function                                                                     return sync_function (self, *args, **kwargs)
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py", line 1517, in container_get_states
    bulk_info = self._job_get_info_bulk(cluster_id, job_ids)
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py", line 972, in _job_get_info_bulk
    ret, out, err = self.shell.run_sync(cmd)
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 741, in run_sync
    raise ptye.translate_exception (e)
NoSuccess: Insufficient system resources: Insufficient system resources: read from process failed '[Errno 5] Input/output error' : (lli/radical.pilot.sandbox/rp.session.radical.mturilli.017230.0000/pilot.0062/bootstrap_1.err, /home/mturilli/radical.pilot.sandbox/rp.session.radical.mturilli.017230.0000/pilot.0062/bootstrap_1.out                                                                         Shared connection to xd-login.opensciencegrid.org closed.                                                                                                                                                ) ((62, 0, false, 1488689326, 1488689323, 1488689279, /home/mturilli/radical.pilot.sandbox/rp.session.radical.mturilli.017230.0000/pilot.0062/bootstrap_1.err, /home/mturilli/radical.pilot.sandbox/rp.session.radical.mturilli.017230.0000/pilot.0062/bootstrap_1.out                                                                                                                                            Shared connection to xd-login.opensciencegrid.org closed.                                                                                                                                                )) (/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +64 (translate_exception)  :  e = se.NoSuccess ("Insufficient system resources: %s" % cmsg)) 
```

**Comment by marksantcroos** [comment]
Is there a correlation with a large number of pilots?

**Comment by mturilli** [comment]
I don't think so. This is 'just' with 128 pilots. I had successful runs (not many though) with up to 2048 pilots.

**Comment by andre-merzky** [comment]
Thanks for the pointers to the logs.   Alas, I can't really identify a culprit here - it looks like the ssh channel simply closes.  Now if this happens because the OSG bridge hiccups, or because our end does something wrong, I do now know...

Can you please additionally set `RADICAL_SAGA_PTY_VERBOSE=DEBUG`, and let me know if this pops up again?  Thanks!

**Comment by mturilli** [comment]
Thank you. Done the export, it will be active from the next run. I will post details to this ticket if the error pops up again.

**Comment by ibethune** [comment]
Putting this in scope for next release until we understand in more detail and can decide where/when a fix goes.

**Comment by mturilli** [comment]
This problem shows up every so often so I would not close this ticket only because a couple of runs went through without errors.

**Comment by andre-merzky** [comment]
ok, ack - so lets see if we can learn anything from the PTY logs...

**Comment by mturilli** [comment]
You can find the session and logs mentioned in the first message of this ticket at:
```
one:/home/mturilli/experiments/AIMES-Experience/OSG/sessions/experiment_18/rp.session.radical.mturilli.017230.0000
one:/home/mturilli/experiments/AIMES-Experience/OSG/sessions/experiment_18/radical.log
```
Would this suffice?

**Comment by andre-merzky** [comment]
The logs seem to indicate that all ssh channels fails at approximately the same time, which indicates that either the master channel died, that a network error occurred, or that the remote host capped the connection (reboot, sshd restart, or some runtime policy).  Alas, the logs are not more conclusive really.

You are probably running a series of experiments from the same script, is that right?  Is there any pattern in that respect, like, runs always fail after a day, or always the 10'th run, or something?  Is `session.close()` always called on the runs before the failing one?

**Comment by mturilli** [comment]
No apparent pattern so far. I am going to restart the experiments and see whether I can observe any. Meanwhile, should we catch this type of error and report to the user? When the ssh master channel die, can the session recover of does it have to exit?

**Comment by andre-merzky** [comment]
No, we can't recover at the moment.  Also we do catch it - the error you see is what SAGA reports to the RP layer.  Alas, in the RP layer there is no single point where this can be handled - it can pop up in a number of places... :/

**Comment by mturilli** [comment]
From what I have been observing, once the termination issues will be addressed, most of the current 30% average failure rate will depend on connection issues. Should we open a feature request about making possible to report about it at RP level?

**Comment by andre-merzky** [comment]
Well, we do report on the RP level - that is what the exception is about after all :)  What we miss is better error messages which are meaningful for users, specifically from lower level components - but we have a ticket on that (#1055), and it is in the works (but will still need a while to show results).
