### ISSUE TITLE
segmentation fault on client

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1303]
I am running few experiments with jetstream as the client and supermic as the remote. I have been getting segmentation fault errors several times the last few days. In most of them, there was no error printed at all, but today I got the following:

```
Output transfer failed: Could not run (/usr/bin/env TERM=vt100 X509_USER_PROXY=/tmp/x509up_u1000 /usr/bin/gsissh -t -o IdentityFile=/home/vivek91/.ssh/id_rsa -o Port=2222 -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_vivek91_%h_%p.vivek91.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=10 vivek91@supermic.cct-lsu.xsede.org): [Errno 12] Cannot allocate memory (/home/vivek91/repos/ee_super_4a/myenv/local/lib/python2.7/site-packages/saga/utils/pty_process.py +225 (initialize)  :  % (' '.join (self.command), e)))
```

Stack:
```
$ radical-stack 
python            : 2.7.6
virtualenv        : /home/vivek91/repos/ee_super_4a/myenv
radical.utils     : 0.45
saga-python       : 0.45.1
radical.pilot     : v0.42-159-g578421a@usecase-vivek
```

It occurs at irregular points, so its hard to repeat that. But I guess I can repeat it if I run the experiment long enough (~5-10 hrs).

**Comment by andre-merzky** [comment]
`Cannot allocate memory` is a pretty clear error though.  What does the mem load on your jetstream VM look like while executing this?

**Comment by vivek-bala** [comment]
Currently it seems to be at 94%. I am not sure how much it was when this error occured (it failed overnight). But I am not sure why it is so high either, the only user process is this RP client process:

```
$ ps faux | grep vivek91
root      7427  0.0  0.0 103568  4100 ?        Ss   08:23   0:00  \_ sshd: vivek91 [priv]
vivek91   7507  0.0  0.0 103568  1848 ?        S    08:24   0:00  |   \_ sshd: vivek91@pts/6 
vivek91   7508  0.0  0.0  23488  4428 pts/6    Ss   08:24   0:00  |       \_ -bash
vivek91   7805  0.0  0.0  18840  1352 pts/6    R+   08:39   0:00  |           \_ ps faux
vivek91   7806  0.0  0.0  11980   932 pts/6    S+   08:39   0:00  |           \_ grep --color=auto vivek91
vivek91  19019  0.0  0.0  31232  8060 ?        Ss   Apr01   0:27 tmux new -s ee_super_4c
vivek91  19020  0.0  0.0  28472  8744 pts/0    Ss+  Apr01   0:02  \_ -bash
vivek91  21353  0.2  8.3 2188588 1368212 pts/0 Tl   Apr01   2:26  |   \_ python runme_cont.py --resource xsede.supermic
vivek91  21372  0.0  0.0  90580  2196 pts/2    Ssl+ Apr01   0:23  |       \_ /usr/bin/gsissh -t -o IdentityFile=/home/vivek91/.ssh/id_rsa -o Port=2222 -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_vivek91_%h_%p.vivek91.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=10 vivek91@supermic.cct-lsu.xsede.org
vivek91  21378  0.1  0.0  91016  2736 pts/4    Ssl+ Apr01   1:13  |       \_ /usr/bin/gsissh -t -o IdentityFile=/home/vivek91/.ssh/id_rsa -o Port=2222 -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_vivek91_%h_%p.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=10 supermic.cct-lsu.xsede.org
vivek91  21390  0.0  0.0  53840   644 pts/8    Ss+  Apr01   0:00  |       \_ /usr/bin/gsissh -t -o IdentityFile=/home/vivek91/.ssh/id_rsa -o Port=2222 -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_vivek91_%h_%p.vivek91.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=10 vivek91@supermic.cct-lsu.xsede.org
vivek91  21423  0.0  0.0  53840   644 pts/9    Ss+  Apr01   0:00  |       \_ /usr/bin/gsissh -t -o IdentityFile=/home/vivek91/.ssh/id_rsa -o Port=2222 -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_vivek91_%h_%p.vivek91.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=10 vivek91@supermic.cct-lsu.xsede.org
vivek91  22010  0.0  0.0  53840   644 pts/3    Ss+  Apr01   0:00  |       \_ /usr/bin/gsissh -t -o IdentityFile=/home/vivek91/.ssh/id_rsa -o Port=2222 -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_vivek91_%h_%p.vivek91.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=10 vivek91@supermic.cct-lsu.xsede.org
vivek91  22073  0.0  0.0  14188   256 pts/5    Ss+  Apr01   0:00  |       \_ /usr/bin/gsisftp -o IdentityFile=/home/vivek91/.ssh/id_rsa -o Port=2222 -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_vivek91_%h_%p.vivek91.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=10 vivek91@supermic.cct-lsu.xsede.org
vivek91  22074  0.0  0.0  53840   644 pts/5    S+   Apr01   0:00  |           \_ /usr/bin/gsissh -oForwardX11 no -oForwardAgent no -oPermitLocalCommand no -oClearAllForwardings yes -o IdentityFile=/home/vivek91/.ssh/id_rsa -o Port=2222 -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_vivek91_%h_%p.vivek91.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=10 -l vivek91 -oProtocol 2 -s -- supermic.cct-lsu.xsede.org sftp
vivek91  26512  0.0  0.0  24000  3252 pts/13   Ss+  Apr01   0:00  \_ -bash
```

**Comment by andre-merzky** [comment]
`ps aux --sort -rss` will sort `ps` output by mem usage.  `free -m` will give you some idea bout mem and swap sizes.  

Your `runme_cont.py` seems to clock in at a sizeable 1.3GB if I am reading this right.  Can you please compare to one of the RP examples?  It should not be that high...

**Comment by vivek-bala** [comment]
Thanks. Outputs below:

```
$ ps aux --sort -rss | grep vivek91
vivek91  21353  0.2  8.3 2188588 1368212 pts/0 Tl   Apr01   2:26 python runme_cont.py --resource xsede.supermic
vivek91   7941  7.5  0.2 719984 43112 pts/0    Sl+  08:50   0:02 python 05_unit_input_data.py
vivek91   8721  5.3  0.1 831412 24420 pts/11   Sl   08:50   0:00 radical.pilot agent_0.AgentSchedulingComponent.0.child
<cut-off>
```

Yup, running the 05_* rp example, it does not take much memory. My script will have lots of big CU descriptions. For example, lets say there are 16 tasks and 50 iterations in total. Task number 10 of iteration 20 requires three output from all tasks in the previous+curent iteration:  3 * 16 * 19 (tasks * all previous iterations) + 3 * any tasks that have completed there 20th iteration. So you can see how large my cu.input_staging attribute can get. In my experiment, my total number of iterations is 160 and I get this seg fault from iteration 30-40 itself.

```
$ free -m
             total       used       free     shared    buffers     cached
Mem:         16048       2005      14043          0        113        302
-/+ buffers/cache:       1589      14459
Swap:            0          0          0
```

I was hitting mongodb size limits on the mlab free tier instances and I moved to a DB on our radical.two machine and I didn't see limitations from the mongodb anymore. This was a bit unexpected though. 

Do we keep all the CUs that have finished execution in memory? I ask because the number of CUs executing at any point can only be 16 in my experiment. So I'm not sure why the memory consumption is so high.

**Comment by andre-merzky** [comment]
Vivek, 

can I ask you to run a test to check based on `00_getting_started.py` to check how mem consumption scales with number of units?  Target resource does not matter, can be local.

Thanks!

**Comment by vivek-bala** [comment]
Sure, makes sense.

**Comment by vivek-bala** [comment]
So I tried a scenario close to what it might be in my experiments. I have 16 CUs, each staging in 1500 files. So my CU construction looks like this:

```
        n = 16   # number of units to run

        ip_files = glob.glob('/home/vivek/dump/*.txt')
        ip_files.append('input.dat')

        cuds = list()
        for i in range(0, n):

            # create a new CU description, and fill it.
            # Here we don't use dict initialization.
            cud = rp.ComputeUnitDescription()
            cud.executable     = '/usr/bin/wc'
            cud.arguments      = ['-c', 'input.dat']
            cud.input_staging  = ip_files

            cuds.append(cud)
```

Upon execution, I am getting an error from mongodb (I am using the db on radical.two):

```
Traceback (most recent call last):
  File "05_unit_input_data.py", line 108, in <module>
    units = umgr.submit_units(cuds)
  File "/home/vivek/myenv/local/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 457, in submit_units
    self._worker.publish_compute_units (units=units)
  File "/home/vivek/myenv/local/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 448, in publish_compute_units
    unit_log=[])
  File "/home/vivek/myenv/local/lib/python2.7/site-packages/radical/pilot/db/database.py", line 778, in insert_compute_units
    unit_uids = self._w.insert(unit_docs)
  File "/home/vivek/myenv/local/lib/python2.7/site-packages/pymongo/collection.py", line 410, in insert
    _check_write_command_response(results)
  File "/home/vivek/myenv/local/lib/python2.7/site-packages/pymongo/helpers.py", line 209, in _check_write_command_response
    raise OperationFailure(error.get("errmsg"), error.get("code"), error)
pymongo.errors.OperationFailure: quota exceeded
```

I didn't notice any spikes in the memory yet but I run into pymongo error before a seg fault in this test case. Although, I don't see pymongo errors in my experiment. There might be hard limit on the db instance size? I ask because smaller examples are working.

**Comment by andre-merzky** [comment]
We did not make progress on this one for a while. @vivek-bala, any suggestion on how to proceed?
