### ISSUE TITLE
SPARK lrms config hook fails with devel

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1305]
Hello,

I got this error when I tried to execute a Spark configuration with devel:
```
2017-04-03 12:40:47,447: agent_0             : MainProcess                     : MainThread     : INFO    : Let's print the config
2017-04-03 12:40:47,448: agent_0             : MainProcess                     : MainThread     : ERROR   : lrms config hook failed
Traceback (most recent call last):
  File "/home/iparask/radical.pilot.sandbox/rp.session.js-172-81.jetstream-cloud.org.iparask.017259.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 147, in __init__
    rp.agent.LM.lrms_config_hook(lm, self._cfg, self, self._log))
  File "/home/iparask/radical.pilot.sandbox/rp.session.js-172-81.jetstream-cloud.org.iparask.017259.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 166, in lrms_config_hook
    return impl.lrms_config_hook(name, cfg, lrms, logger)
  File "/home/iparask/radical.pilot.sandbox/rp.session.js-172-81.jetstream-cloud.org.iparask.017259.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/spark.py", line 103, in lrms_config_hook
    logger.info('Config : {0}'.format(cfg['resource_cfg']))
KeyError: 'resource_cfg'
2017-04-03 12:40:47,449: agent_0             : MainProcess                     : MainThread     : ERROR   : lrms construction error
```

It is important and has to be functional with all releases

**Comment by iparask** [comment]
Andre,

we had the resource configuration passed to this hook as an ```cfg``` entry which was a dict. Do you think it can be done quickly again?

**Comment by andre-merzky** [comment]
thanks Iannis!  Couple of questions: how can I reproduce this / what code have you been running?  And, how urgent is this for you guys?  Re urgency: happy to help with merging from devel, as said on the call, but I am trying to prioritize...

**Comment by andre-merzky** [comment]
> Andre,
> 
> we had the resource configuration passed to this hook as an cfg entry which was a dict. Do you think it can be done quickly again?

Ah, I see - yes, that should be easy.  What specific keys from the resource config do you need though?

**Comment by iparask** [comment]
This is the part of the hook that uses it:

```
if master_ip!='localhost':
            for config in cfg['resource_cfg']['pre_bootstrap_1']:
                spark_env_file.write(config + '\n')
```
The name can change, if you want. Also if you tell me where to look I can also do it.

**Comment by iparask** [comment]
I meant v0.46 important, not today important.

**Comment by andre-merzky** [comment]
@iparask: can you please give the branch `fix/issue_1305` a try?

**Comment by iparask** [comment]
Tried it! Worked!
