### ISSUE TITLE
invalid ps arguments and confusing message on ssh timeout

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#1326]
```
  python               : 2.7.13
  pythonpath           : 
  virtualenv           : /Users/mark/Desktop/term_ve

  radical.pilot        : split-85-g7d7c385a@feature-split_termination_4
  radical.utils        : v0.45-43-g781b42d@feature-managed_process
  saga                 : split-14-g43c9ea2d@devel
```

```
2017-04-24 10:37:35,648: radical.saga.pty    : MainProcess                     : MainThread     : DEBUG   : write: [  195] [   29] ( printf 'HELLO_%d_SAGA\n' 12\n)
2017-04-24 10:37:36,663: radical.saga.pty    : MainProcess                     : MainThread     : DEBUG   : write: [  195] [   51] ( export PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2017-04-24 10:41:08,297: radical.saga.pty    : MainProcess                     : MainThread     : INFO    : write: [  195] [   38]
2017-04-24 10:41:08,297: radical.saga.pty    : MainProcess                     : MainThread     : ERROR   : [Errno 5] Input/output error
Traceback (most recent call last):
  File "/Users/mark/Desktop/term_ve/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 302, in _initialize_pty
    pty_shell.write (" export PS1='$' > /dev/null 2>&1 || set prompt='$'\n")
  File "/Users/mark/Desktop/term_ve/lib/python2.7/site-packages/saga/utils/pty_process.py", line 838, in write
    raise ptye.translate_exception (e, "write to process failed (%s)" % e)
OSError: [Errno 5] Input/output error
caught Exception: [Errno 5] Input/output error
ps: illegal option -- -
usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-g grp[,grp...]] [-u [uid,uid...]]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
--------------
RADICAL Utils -- Stacktrace [12369] [MainThread]

Traceback (most recent call last):
File "00_getting_started.py", line 68, in <module>
pilot = pmgr.submit_pilots(pdesc)
File "/Users/mark/Desktop/term_ve/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 416, in submit_pilots
pilot = ComputePilot(pmgr=self, descr=pd)
File "/Users/mark/Desktop/term_ve/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 92, in __init__
self._sandbox       = self._session._get_pilot_sandbox(self.as_dict())
File "/Users/mark/Desktop/term_ve/lib/python2.7/site-packages/radical/pilot/session.py", line 907, in _get_pilot_sandbox
session_sandbox = self._get_session_sandbox(pilot)
File "/Users/mark/Desktop/term_ve/lib/python2.7/site-packages/radical/pilot/session.py", line 883, in _get_session_sandbox
global_sandbox  = self._get_global_sandbox(pilot)
File "/Users/mark/Desktop/term_ve/lib/python2.7/site-packages/radical/pilot/session.py", line 846, in _get_global_sandbox
shell = rsup.PTYShell(js_url, self)
File "/Users/mark/Desktop/term_ve/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
interactive=self.interactive)
File "/Users/mark/Desktop/term_ve/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 198, in initialize
self._initialize_pty (info['pty'], info)
File "/Users/mark/Desktop/term_ve/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
raise ptye.translate_exception (e)
OSError: [Errno 5] Input/output error

--------------
```

**Comment by andre-merzky** [comment]
What is the local and remote OS, please?

**Comment by marksantcroos** [comment]
Local: Mac OS Sierra 10.12.4
Remote: Ubuntu 14.04.5 LTS

**Comment by andre-merzky** [comment]
Thanks.  Can you please give the RU branch `fix/issue_rp_1326` a try?  Thjis is branched off `feature/managed_process`.

**Comment by ibethune** [comment]
I see an RU branch ```fix/issue_rp_1326_b```, but no PR open.  It seems low risk, but if @marksantcroos can't test, then I suggest we leave this one to a future release since it's essentially improving output for an error case.

**Comment by marksantcroos** [comment]
Its a bit difficult to test, as I can't reproduce it on demand. I'll leave it up to your judgement to merge it or not.

**Comment by ibethune** [comment]
Makes sense.  I reviewed the changes, and did a quick manual test.  We can merge and then close this.

**Comment by ibethune** [comment]
The fix is merged in RU, closing the ticket.

**Comment by andre-merzky** [comment]
thanks guys!
