### ISSUE TITLE
CU input staging from remote broken

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1330]
Hello,

I tried to create a input staging directive like:

```
shared = [{'source': 'file://%s/trj_%s_%03i.npz.npy' % (TRJ_LOCATION,ATOM_SEL,k),
                              'target' : 'trj_%s_%03i.npz.npy' % (ATOM_SEL,k),
                              'action' : rp.LINK} for k in range(i,i+WINDOW_SIZE)]
```

where TRJ_LOCATION is  path on SuperMic. My execution failed because my file did not exist. After checking the database I saw:

```
 "input_staging": [
            {
                "uid": "sd.0001",
                "priority": 0,
                "source": "staging:///hausdorff_opt.py",
                "flags": [
                    "CreateParents",
                    "SkipFailed"
                ],
                "action": "Link",
                "target": "hausdorff_opt.py"
            },
            {
                "uid": "sd.0002",
                "priority": 0,
                "source": "file://localhost/vol_b/Hausdorff/SuperMic/Vanilla/file:/work/iparaske/HausdorffTraj/trj_aa_001.npz.npy",
                "flags": [
                    "CreateParents",
                    "SkipFailed"
                ],
                "action": "Link",
                "target": "trj_aa_001.npz.npy"
            },
```

The first part is my localhost path to the pilot script and the second, after the ":" is the path on SuperMic

**Comment by andre-merzky** [comment]
Thanks  Iannis.

Can you please add the output of `radical-stack`, and also a dump of one of the unit descriptions before submission?

**Comment by iparask** [comment]
radical-stack:
```
(ExperimentsEnv) iparask@js-172-81:/vol_b/Hausdorff/SuperMic/Vanilla$ radical-stack
python            : 2.7.13
virtualenv        : None
radical.utils     : v0.45-42-gab119d9@devel
saga-python       : split-15-g41ed411@devel
radical.pilot     : split-60-g2a4ae00@devel
````

**Comment by andre-merzky** [comment]
Sorry Iannis - with 'dump' I meant something like this:

```
import pprint
pprint.pprint(cudesc.as_dict())
```

Thanks!

**Comment by iparask** [comment]
Here it is:

```
{'arguments': ['hausdorff_opt.py',
               '[449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512]',
               '[449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512]',
               'aa',
               'short'],
 'cleanup': False,
 'cores': 1,
 'environment': None,
 'executable': 'python',
 'input_staging': [{'action': 'Link',
                    'source': 'staging:///hausdorff_opt.py',
                    'target': 'hausdorff_opt.py'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_449.npz.npy',
                    'target': 'trj_aa_449.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_450.npz.npy',
                    'target': 'trj_aa_450.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_451.npz.npy',
                    'target': 'trj_aa_451.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_452.npz.npy',
                    'target': 'trj_aa_452.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_453.npz.npy',
                    'target': 'trj_aa_453.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_454.npz.npy',
                    'target': 'trj_aa_454.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_455.npz.npy',
                    'target': 'trj_aa_455.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_456.npz.npy',
                    'target': 'trj_aa_456.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_457.npz.npy',
                    'target': 'trj_aa_457.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_458.npz.npy',
                    'target': 'trj_aa_458.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_459.npz.npy',
                    'target': 'trj_aa_459.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_460.npz.npy',
                    'target': 'trj_aa_460.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_461.npz.npy',
                    'target': 'trj_aa_461.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_462.npz.npy',
                    'target': 'trj_aa_462.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_463.npz.npy',
                    'target': 'trj_aa_463.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_464.npz.npy',
                    'target': 'trj_aa_464.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_465.npz.npy',
                    'target': 'trj_aa_465.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_466.npz.npy',
                    'target': 'trj_aa_466.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_467.npz.npy',
                    'target': 'trj_aa_467.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_468.npz.npy',
                    'target': 'trj_aa_468.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_469.npz.npy',
                    'target': 'trj_aa_469.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_470.npz.npy',
                    'target': 'trj_aa_470.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_471.npz.npy',
                    'target': 'trj_aa_471.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_472.npz.npy',
                    'target': 'trj_aa_472.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_473.npz.npy',
                    'target': 'trj_aa_473.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_474.npz.npy',
                    'target': 'trj_aa_474.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_475.npz.npy',
                    'target': 'trj_aa_475.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_476.npz.npy',
                    'target': 'trj_aa_476.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_477.npz.npy',
                    'target': 'trj_aa_477.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_478.npz.npy',
                    'target': 'trj_aa_478.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_479.npz.npy',
                    'target': 'trj_aa_479.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_480.npz.npy',
                    'target': 'trj_aa_480.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_481.npz.npy',
                    'target': 'trj_aa_481.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_482.npz.npy',
                    'target': 'trj_aa_482.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_483.npz.npy',
                    'target': 'trj_aa_483.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_484.npz.npy',
                    'target': 'trj_aa_484.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_485.npz.npy',
                    'target': 'trj_aa_485.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_486.npz.npy',
                    'target': 'trj_aa_486.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_487.npz.npy',
                    'target': 'trj_aa_487.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_488.npz.npy',
                    'target': 'trj_aa_488.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_489.npz.npy',
                    'target': 'trj_aa_489.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_490.npz.npy',
                    'target': 'trj_aa_490.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_491.npz.npy',
                    'target': 'trj_aa_491.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_492.npz.npy',
                    'target': 'trj_aa_492.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_493.npz.npy',
                    'target': 'trj_aa_493.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_494.npz.npy',
                    'target': 'trj_aa_494.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_495.npz.npy',
                    'target': 'trj_aa_495.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_496.npz.npy',
                    'target': 'trj_aa_496.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_497.npz.npy',
                    'target': 'trj_aa_497.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_498.npz.npy',
                    'target': 'trj_aa_498.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_499.npz.npy',
                    'target': 'trj_aa_499.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_500.npz.npy',
                    'target': 'trj_aa_500.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_501.npz.npy',
                    'target': 'trj_aa_501.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_502.npz.npy',
                    'target': 'trj_aa_502.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_503.npz.npy',
                    'target': 'trj_aa_503.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_504.npz.npy',
                    'target': 'trj_aa_504.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_505.npz.npy',
                    'target': 'trj_aa_505.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_506.npz.npy',
                    'target': 'trj_aa_506.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_507.npz.npy',
                    'target': 'trj_aa_507.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_508.npz.npy',
                    'target': 'trj_aa_508.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_509.npz.npy',
                    'target': 'trj_aa_509.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_510.npz.npy',
                    'target': 'trj_aa_510.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_511.npz.npy',
                    'target': 'trj_aa_511.npz.npy'},
                   {'action': 'Link',
                    'source': 'file:///work/iparaske/HausdorffTraj/trj_aa_512.npz.npy',
                    'target': 'trj_aa_512.npz.npy'}],
 'kernel': None,
 'mpi': False,
 'name': None,
 'output_staging': None,
 'post_exec': None,
 'pre_exec': ['module load python'],
 'restartable': False,
 'stderr': None,
 'stdout': None}
```

The links are correct

**Comment by andre-merzky** [comment]
Hey Iannis, 

can you please try the `fix/issue_1330` branch of RP, and confirm that you get a different error this time?

Thanks!

**Comment by iparask** [comment]
Hello Andre,

It still says localhost in the database, but the rest of the path is being removed:

```
"input_staging": [
            {
                "uid": "sd.0001",
                "priority": 0,
                "source": "file://localhost/hausdorff_opt.py",
                "flags": [
                    "CreateParents",
                    "SkipFailed"
                ],
                "action": "Link",
                "target": "hausdorff_opt.py"
            },
            {
                "uid": "sd.0002",
                "priority": 0,
                "source": "file://localhost/work/iparaske/HausdorffTraj/trj_aa_001.npz.npy",
                "flags": [
                    "CreateParents",
                    "SkipFailed"
                ],
                "action": "Link",
                "target": "trj_aa_001.npz.npy"
            },
```
Unfortunately, linking from the staging area of the pilot also broke

**Comment by ibethune** [comment]
Any update on this one @andre-merzky ? This was also on the 'to be fixed before release' list.

**Comment by andre-merzky** [comment]
Well, yes and no.  looking further into this, it seems that we are really doing the wrong thing wrt. path expansion here. 

Basically, whenever we get a CU with staging directives, we try to expand those directives as soon as the unit is scheduled, which implies that we need to find out if the staging directive is enacted locally (by the client) or remotely (by the agent), and depending on the result expand using local or remote paths.  So far so good, but (a) looking up remote paths is costly, and (b) we don't distinguish correctly what staging directives are enacted where -- and that is actually hard to do without replicating code from the components which actually do the staging, and which make that decision all over again.

So my proposal would be to defer the expansion until the actual staging op is enacted.  This will also simplify things once we want to reschedule units to a different pilot, for example, as in that case we would need the original path specs (or to un-expand which is bad).

Alas, that is also the point where I stopped trying to implement this... :/

Two options: quick fix (some hours of work, will be a problem sooner or later again), or clean up (2 days of work, but less likely to crop up again).  Or both or course: quick fix for release, and redo 'someday' ... :P

**Comment by ibethune** [comment]
For the sake of a few days, I think doing the clean fix is worthwhile.

**Comment by andre-merzky** [comment]
ack

**Comment by ibethune** [comment]
I see some further changes made in ```fix/issue_1330``` - are these ready for testing yet, or more work needed?

**Comment by andre-merzky** [comment]
I'm afraid there is still some work needed.  I am working on that one now.

**Comment by andre-merzky** [comment]
This is now addressed in `fix/issue_1330` - would you mind giving this a try?  Thanks!

**Comment by iparask** [comment]
Alright!

**Comment by iparask** [comment]
I am getting something else:
RADICAL-Stack:
```

  python               : 2.7.6
  pythonpath           :
  virtualenv           : /home/iparask/Virtualenv/RadicalDevel

  radical.pilot        : 0.46-split-94-gdd5dcfe@fix-issue_1330
  radical.utils        : 0.46-v0.45-49-g38f6ee3@devel
  saga                 : 0.46-split-19-g11be22a@devel
```
This is the error:
```

2017-06-09 20:59:07,706: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : INFO    : Launching pilots on xsede.supermic: ['pilot.0000']
2017-06-09 20:59:09,014: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : INFO    : Read agent config file: /home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/../..//configs/agent_default.json
2017-06-09 20:59:09,015: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 328, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 415, in _start_pilot_bulk
    info = self._prepare_pilot(resource, rcfg, pilot)
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 684, in _prepare_pilot
    'resource_sandbox': resource_sandbox}
KeyError: 'global_sandbox'
2017-06-09 20:59:09,015: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
2017-06-09 20:59:09,016: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : DEBUG   : advance bulk: pilot.0000 [1]
2017-06-09 20:59:09,016: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: DEBUG   : launcher got {'cmd': 'add_pilots', 'arg': {'pilots': [{'resource_sandbox': 'gsisftp://supermic.cct-lsu.xsede.org:2222/work/iparaske/radical.pilot.sandbox', 'resource_details': None, 'resource': 'xsede.supermic', 'description': {'queue': None, 'resource': 'xsede.supermic', 'exit_on_error': False, 'candidate_hosts': None, 'project': 'TG-MCB090174', 'sandbox': None, 'cleanup': False, 'access_schema': None, 'memory': None, 'cores': 20, 'runtime': 30}, 'pmgr': 'pmgr.0000', 'stdout': None, 'state': 'PMGR_LAUNCHING', 'sandbox': 'gsisftp://supermic.cct-lsu.xsede.org:2222/work/iparaske/radical.pilot.sandbox/Test1330/pilot.0000/', 'session': 'Test1330', 'log': None, 'stderr': None, 'client_sandbox': '/vol_b/Hausdorff/SuperMic/Vanilla', 'type': 'pilot', 'pilot_sandbox': 'gsisftp://supermic.cct-lsu.xsede.org:2222/work/iparaske/radical.pilot.sandbox/Test1330/pilot.0000/', 'uid': 'pilot.0000'}], 'umgr': 'umgr.0000'}}
2017-06-09 20:59:11,075: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: DEBUG   : launcher got {'cmd': 'cancel_pilots', 'arg': {'uids': ['pilot.0000'], 'pmgr': 'pmgr.0000'}}
2017-06-09 20:59:11,075: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: INFO    : received pilot_cancel command (['pilot.0000'])
2017-06-09 20:59:11,216: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.watch: WARNING : endpoint disappeard
2017-06-09 20:59:11,216: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.watch: ERROR   : watcher failed
Traceback (most recent call last):
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/utils/process.py", line 254, in _ru_watch
    self._ru_watch_socket()
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/utils/process.py", line 305, in _ru_watch_socket
    raise RuntimeError('endpoint disappeard')
RuntimeError: endpoint disappeard
2017-06-09 20:59:11,216: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.watch: INFO    : put message: [pmgr.launching.0.child.watch.thread] work finished
2017-06-09 20:59:11,217: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.watch: DEBUG   : ru_finalize_child (NOOP
```

I am not sure why this is happening

**Comment by iparask** [comment]
PS: found the reason. The resource label did not have the ```_ssh``` suffix. I did add it and got the same error

**Comment by iparask** [comment]
```
2017-06-09 21:04:46,117: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : INFO    : Launching pilots on xsede.supermic_ssh: ['pilot.0000']
2017-06-09 21:04:47,463: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : INFO    : Read agent config file: /home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/../..//configs/agent_default.json
2017-06-09 21:04:47,464: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 328, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 415, in _start_pilot_bulk
    info = self._prepare_pilot(resource, rcfg, pilot)
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 684, in _prepare_pilot
    'resource_sandbox': resource_sandbox}
KeyError: 'global_sandbox'
2017-06-09 21:04:47,464: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
2017-06-09 21:04:47,465: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : DEBUG   : advance bulk: pilot.0000 [1]
2017-06-09 21:04:47,465: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: DEBUG   : launcher got {'cmd': 'add_pilots', 'arg': {'pilots': [{'resource_sandbox': 'gsisftp://supermic.cct-lsu.xsede.org:2222/work/iparaske/radical.pilot.sandbox', 'resource_details': None, 'resource': 'xsede.supermic_ssh', 'description': {'queue': None, 'resource': 'xsede.supermic_ssh', 'exit_on_error': False, 'candidate_hosts': None, 'project': 'TG-MCB090174', 'sandbox': None, 'cleanup': False, 'access_schema': None, 'memory': None, 'cores': 20, 'runtime': 30}, 'pmgr': 'pmgr.0000', 'stdout': None, 'state': 'PMGR_LAUNCHING', 'sandbox': 'gsisftp://supermic.cct-lsu.xsede.org:2222/work/iparaske/radical.pilot.sandbox/Test1330/pilot.0000/', 'session': 'Test1330', 'log': None, 'stderr': None, 'client_sandbox': '/vol_b/Hausdorff/SuperMic/Vanilla', 'type': 'pilot', 'pilot_sandbox': 'gsisftp://supermic.cct-lsu.xsede.org:2222/work/iparaske/radical.pilot.sandbox/Test1330/pilot.0000/', 'uid': 'pilot.0000'}], 'umgr': 'umgr.0000'}}
2017-06-09 21:04:49,558: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: DEBUG   : launcher got {'cmd': 'cancel_pilots', 'arg': {'uids': ['pilot.0000'], 'pmgr': 'pmgr.0000'}}
2017-06-09 21:04:49,558: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.subscriber._pmgr_control_cb: INFO    : received pilot_cancel command (['pilot.0000'])
2017-06-09 21:04:49,668: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.watch: WARNING : endpoint disappeard
2017-06-09 21:04:49,679: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.watch: ERROR   : watcher failed
Traceback (most recent call last):
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/utils/process.py", line 254, in _ru_watch
    self._ru_watch_socket()
  File "/home/iparask/Virtualenv/RadicalDevel/local/lib/python2.7/site-packages/radical/utils/process.py", line 305, in _ru_watch_socket
    raise RuntimeError('endpoint disappeard')
RuntimeError: endpoint disappeard
2017-06-09 21:04:49,680: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.watch: INFO    : put message: [pmgr.launching.0.child.watch.thread] work finished
2017-06-09 21:04:49,680: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.watch: DEBUG   : ru_finalize_child (NOOP)
2017-06-09 21:04:49,680: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.watch: DEBUG   : ru_finalize_common (NOOP)
2017-06-09 21:04:49,680: pmgr.launching.0.child: pmgr.launching.0                : pmgr.launching.0.child.watch: INFO    : put message: [pmgr.launching.0.child.watch.thread] terminating
```

**Comment by andre-merzky** [comment]
Thanks Iannis - looks like a merge conflicted here, will fix.

**Comment by andre-merzky** [comment]
This specific error (`global_sandbox` not defined) should be fixed now.

**Comment by iparask** [comment]
Andre, it does not install now

**Comment by andre-merzky** [comment]
Duh, pushed the fix to the wrong branch :/  Apologies...

**Comment by iparask** [comment]
I made some changes, should I wait?

**Comment by andre-merzky** [comment]
Saw that, I am merging some more from devel and will also test a couple of examples - will push once those pass, ok?  Thanks for your patience! :)

**Comment by andre-merzky** [comment]
PS.: if you have outstanding changes, feel free to push!

**Comment by iparask** [comment]
Yes, thank you!

**Comment by iparask** [comment]
So, I am not sure anymore if I am triggering old bugs or new.... :)

```
(RadicalDevel)iparask@js-172-81:/vol_b/Hausdorff/SuperMic/Vanilla/Test1330$ radical-stack

  python               : 2.7.6
  pythonpath           :
  virtualenv           : /home/iparask/Virtualenv/RadicalDevel

  radical.pilot        : 0.46-split-100-ga509d4c@fix-issue_1330
  radical.utils        : 0.46-v0.45-49-g38f6ee3@devel
  saga                 : 0.46-split-19-g11be22a@devel
```
Agent Side:

```
agent.executing.0.child.log:2017-06-10 15:12:48,040: agent.executing.0.child: agent.executing.0               : agent.executing.0.child.watch: ERROR   : watcher failed
agent.executing.queue.bridge.log:2017-06-10 15:12:49,672: agent.executing.queue.bridge: agent.executing.queue.bridge.child: agent.executing.queue.bridge.child.watch: ERROR   : watcher failed
agent.executing.queue.bridge.log:2017-06-10 15:12:50,628: agent.executing.queue.bridge: agent.executing.queue.bridge.child: MainThread     : ERROR   : abort: RuntimeError('not alive anymore?',)
agent.executing.queue.bridge.log:2017-06-10 15:12:50,629: agent.executing.queue.bridge: agent.executing.queue.bridge.child: MainThread     : ERROR   : abort info not sent: error(9, 'Bad file descriptor')
agent.scheduling.queue.bridge.log:2017-06-10 15:12:50,631: agent.scheduling.queue.bridge: agent.scheduling.queue.bridge.child: agent.scheduling.queue.bridge.child.watch: ERROR   : watcher failed
agent.staging.input.queue.bridge.log:2017-06-10 15:12:49,169: agent.staging.input.queue.bridge: agent.staging.input.queue.bridge.child: agent.staging.input.queue.bridge.child.watch: ERROR   : watcher failed
agent.staging.input.queue.bridge.log:2017-06-10 15:12:49,669: agent.staging.input.queue.bridge: agent.staging.input.queue.bridge.child: MainThread     : ERROR   : abort: RuntimeError('not alive anymore?',)
agent.staging.input.queue.bridge.log:2017-06-10 15:12:49,670: agent.staging.input.queue.bridge: agent.staging.input.queue.bridge.child: MainThread     : ERROR   : abort info not sent: error(9, 'Bad file descriptor')
```

Which one should I check?

**Comment by iparask** [comment]
After correcting some depreciated commands from me script, according to Andre's isntructions, I can say that it works!

**Comment by andre-merzky** [comment]
Puh, great :)  As discussed, I document the staging changes in #1292
