### ISSUE TITLE
Problems running on supermic

### ISSUE THREAD

**Issue by AA919** [radical-cybertools/radical.pilot#1348]
I tried to use Supermic because Stampede does not give me any job. 
RP returns this error:

```bash
2017-05-17 03:59:03,167: radical.pilot       : MainProcess                     : InputFileTransferWorker-1: ERROR   : Error: invalid dir '/work/aangius/radical.pilot.sandbox/rp.session.one.aangius.017303.0004-pilot.0000/unit.000000': mkdir: cannot create directory `/work/aangius': Permission denied
sh: cd: /work/aangius/radical.pilot.sandbox/rp.session.one.aangius.017303.0004-pilot.0000/unit.000000: No such file or directory
 (/home/aangius/src-devel/ve_045/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +352 (initialize)  :  raise saga.BadParameter ("invalid dir '%s': %s" % (self.url.path, out)))
Traceback (most recent call last):
  File "/home/aangius/src-devel/ve_045/local/lib/python2.7/site-packages/radical/pilot/controller/input_file_transfer_worker.py", line 139, in run
    session=self._session)
  File "/home/aangius/src-devel/ve_045/local/lib/python2.7/site-packages/saga/filesystem/directory.py", line 95, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/home/aangius/src-devel/ve_045/local/lib/python2.7/site-packages/saga/namespace/directory.py", line 95, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/home/aangius/src-devel/ve_045/local/lib/python2.7/site-packages/saga/namespace/entry.py", line 89, in __init__
    url, flags, session, ttype=_ttype)
  File "/home/aangius/src-devel/ve_045/local/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/home/aangius/src-devel/ve_045/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/aangius/src-devel/ve_045/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 297, in init_instance
    self.initialize ()
  File "/home/aangius/src-devel/ve_045/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 352, in initialize
    raise saga.BadParameter ("invalid dir '%s': %s" % (self.url.path, out))
BadParameter: invalid dir '/work/aangius/radical.pilot.sandbox/rp.session.one.aangius.017303.0004-pilot.0000/unit.000000': mkdir: cannot create directory `/work/aangius': Permission denied
```
Note that I am using gsissh and I have already verified that everything is ok with the certificate.

**Comment by andre-merzky** [comment]
Does `/work/aangius/` exist?

**Comment by AA919** [comment]
Yes, sorry I forgot to write that:
- The folder exist
- I can write on it without problems.

**Comment by andre-merzky** [comment]
Can you please send the `radical-stack` output?  If that is pre-devel, please do retry with devel.  If it still fails, please rerun with `RADICAL_SAGA_PTY_VERBOSE=DEBUG` and send the resulting logfiles.  Thanks!

**Comment by AA919** [comment]
It works with devel. I do not why but the stack was a mix between v0.45 and devel.

**Comment by andre-merzky** [comment]
Puh! :-)
