### ISSUE TITLE
Bridges - Failing CUs, ssh_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1360]
Some of the CUs fail with the following error when I run my experiments (1024 Cores, 1 CU per core, each CU is a Synapse emulation) on Bridges.

```
ssh_exchange_identification: Connection closed by remote host
```

I get the following errors in the `pmgr.launching.queue.bridge.log`:
```
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.rp_add_res_cfg/local/lib/python2.7/site-packages/radical/utils/process.py", line 549, in _run
    if not self.work_cb():
  File "/home/mingtha/ve/ve.rp_add_res_cfg/local/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 325, in work_cb
    raise RuntimeError('not alive anymore?')
RuntimeError: not alive anymore?
2017-05-31 18:47:18,948: pmgr.launching.queue.bridge: pmgr.launching.queue.bridge.child: MainThread     : INFO    : send message: abort: RuntimeError('not alive anymore?',)
2017-05-31 18:47:18,948: pmgr.launching.queue.bridge: pmgr.launching.queue.bridge.child: MainThread     : ERROR   : abort info not sent: error(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.rp_add_res_cfg/local/lib/python2.7/site-packages/radical/utils/process.py", line 560, in _run
    self._ru_msg_send('abort: %s' % repr(e))
  File "/home/mingtha/ve/ve.rp_add_res_cfg/local/lib/python2.7/site-packages/radical/utils/process.py", line 163, in _ru_msg_send
    self._ru_endpoint.send(msg)
error: [Errno 9] Bad file descriptor
```

The `Bad file descriptor` error also occurs in `agent.staging.input.0.log` and `agent.staging.input.0.log`. Both errors occur in `agent.staging.input.queue.bridge.log`

I get the following error in the `agent_0.log`
```
Traceback (most recent call last):
  File "/home/mha/radical.pilot.sandbox/rp.session.Ubuntu-1604-xenial-64-minimal.mingtha.017317.0019/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/process.py", line 578, in _run
    self._ru_msg_send('terminating')
  File "/home/mha/radical.pilot.sandbox/rp.session.Ubuntu-1604-xenial-64-minimal.mingtha.017317.0019/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/process.py", line 163, in _ru_msg_send
    self._ru_endpoint.send(msg)
error: [Errno 32] Broken pipe
2017-05-31 12:47:18,956: agent_0
```

I get the following error in the `agent_1.log`
```2017-05-31 12:32:28,154: agent_1             : MainProcess                     : MainThread     : DEBUG   : start components: {'AgentExecutingComponent': {'count': 1},
 'AgentSchedulingComponent': {'count': 1},
 'AgentStagingInputComponent': {'count': 1},
 'AgentStagingOutputComponent': {'count': 1}}
2017-05-31 12:32:28,154: agent_1             : MainProcess                     : MainThread     : DEBUG   : start 1 component(s) AgentExecutingComponent
2017-05-31 12:32:28,412: agent_1             : agent.executing.0               : MainThread     : INFO    : Discovered launch command: '/bin/ssh -o StrictHostKeyChecking=no -o ControlMaster=auto'.
2017-05-31 12:32:28,413: agent_1             : agent.executing.0               : MainThread     : ERROR   : LaunchMethod cannot be used: mpirun_rsh could not be found!
Traceback (most recent call last):
  File "/home/mha/radical.pilot.sandbox/rp.session.Ubuntu-1604-xenial-64-minimal.mingtha.017317.0019/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 125, in create
    return impl(cfg, session)
  File "/home/mha/radical.pilot.sandbox/rp.session.Ubuntu-1604-xenial-64-minimal.mingtha.017317.0019/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/mpirun_rsh.py", line 20, in __init__
    LaunchMethod.__init__(self, cfg, session)
  File "/home/mha/radical.pilot.sandbox/rp.session.Ubuntu-1604-xenial-64-minimal.mingtha.017317.0019/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 61, in __init__
    self._configure()
  File "/home/mha/radical.pilot.sandbox/rp.session.Ubuntu-1604-xenial-64-minimal.mingtha.017317.0019/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/mpirun_rsh.py", line 29, in _configure
    raise Exception("mpirun_rsh could not be found")
Exception: mpirun_rsh could not be found
```

**Comment by andre-merzky** [comment]
Well, that is the same problem as on comet an other machines: the number of ssh connections and processes is limited, so we hit that limit with too many CUs.  We would need to deploy and configure ORTE to work around this limit.  I can give this a shot, but will likely not get around to do this before next week :/

The `mpirun_rsh` problem is now fixed with a configuration change in the `feature/bridges` branch.

**Comment by andre-merzky** [comment]
Ming, can you please confirm that the `mpirun_rsh` problem is gone?  Then we should close the ticket, as the limit on ssh connections is a known problem for this configuration, and we can't do anything about it really...
Thanks!

**Comment by mingtaiha** [comment]
This problem has resurfaced in Bridges. This occurred when run a pilot of 1024 cores, 1024 CUs (1 CU per core) where each CU runs `/bin/true`. I checked all of the log files on the local and remote side, but there are no errors except `ssh_exchange_identification: Connection closed by remote host` in the `STDERR` in the unit folder in the remote side.

**Comment by andre-merzky** [comment]
Hi Ming, 

the ticket covers two different errors at this point:

  - `Exception: mpirun_rsh could not be found`: Did this error resurface?

  - `ssh_exchange_identification: Connection closed by remote host`: this is a limit on the number of ssh connections, and cannot be solved in this agent configuration.  The only solution here is to deploy ORTE on Bridges and to create a new agent configuration.  If you need bridges at this scale, please do open a new  ticket, and I'll start the ORTE deployment in a separate branch.

Thanks! :)

**Comment by mingtaiha** [comment]
The `mpirun_rsh` error has not resurfaced. I will open a separate ticket to for ORTE deployment on Bridges

**Comment by andre-merzky** [comment]
Bridges does not support ORTE, yet - Iannis, do you want to take this over?

**Comment by SrinivasMushnoori** [comment]
Going to bring this ticket back from the dead because I see this too. Attached [here](https://github.com/radical-cybertools/radical.pilot/files/2573256/ssh_connection_closed.tar.gz) are my logfiles. 

As far as I can tell the errors that Ming pointed out in that ticket do not occur here (correct me if I am mistaken). 

@andre-merzky @iparask  has there been any resolution on this?

**Comment by andre-merzky** [comment]
Apologies, I also misread the error - it *is* on the pilot side...

On the bridges headnode, does `ssh localhost` work for you?  Thanks.

**Comment by andre-merzky** [comment]
PS.: I should clarify: the ssh command should not prompt for a password.  If it does, please do set up an ssh key and `authorized_keys` so that it does not, and give it another try.

**Comment by iparask** [comment]
@andre-merzky it seems to me like the execution reaches the maximum number of ssh connections. @SrinivasMushnoori how many concurrent units are you having?

**Comment by SrinivasMushnoori** [comment]
@andre-merzky I set up a key but for some reason it still prompts for a password...

**Comment by vivek-bala** [comment]
@SrinivasMushnoori Any updates here?

**Comment by vivek-bala** [comment]
Aymen, is this related/similar to the issue you were facing a few days back?

**Comment by andre-merzky** [comment]
known ssh limitation - outdated
