### ISSUE TITLE
units do not go past AGENT_EXECUTING state on Titan

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1364]
I am trying out the 01_unit_details.py example on Titan with aprun launch mode. The only change I make is I submit only 1 CU (as opposed to the default 128). The unit completes as I can see the output in the sandbox but the CU does not go beyond the AGENT_EXECUTING stage and the pilot times out.

Radical-stack:
```
> radical-stack 

  python               : 2.7.9
  pythonpath           : /sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /autofs/nccs-svm1_home1/vivekb/ves/test_ss_rp

  radical.pilot        : split-74-g10acb0d@devel
  radical.utils        : v0.45-46-g591b33d@devel
  saga                 : split-18-gc074c76@devel
```

Log on client side:
```
================================================================================
 Getting Started (RP version split)                                             
================================================================================

new session: [rp.session.titan-ext3.vivekb.017320.0004]                        \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]                     ok
read config                                                                   ok

--------------------------------------------------------------------------------
submit pilots                                                                   

create pilot manager                                                          ok
create pilot description [ornl.titan_aprun:16]                                ok
submit 1 pilot(s)
        .                                                                     ok

--------------------------------------------------------------------------------
submit units                                                                    

create unit manager                                                           ok
add 1 pilot(s)                                                                ok
create 1 unit description(s)
        .                                                                     ok
submit 1 unit(s)
        .                                                                     ok

--------------------------------------------------------------------------------
gather results                                                                  

wait for 1 unit(s)
        -                                                                     ok

caught Exception: 'NoneType' object has no attribute 'strip'

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.titan-ext3.vivekb.017320.0004                       \
close unit manager                                                            ok
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                              ok
                                                                              ok
session lifetime: 1005.8s                                                     ok
```

CU state lookup in the sandbox:
```
pilot.0000> cat * | grep unit.000000
2017-06-03 18:22:27,473: agent_0             : MainProcess                     : agent_0.idler._check_units_cb: DEBUG   : advance bulk: unit.000000 [1]
2017-06-03 18:22:27,473: agent_0             : MainProcess                     : agent_0.idler._check_units_cb: DEBUG   : bucket: AGENT_STAGING_INPUT_PENDING : [u'unit.000000']
2017-06-03 18:22:27,473: agent_0             : MainProcess                     : agent_0.idler._check_units_cb: DEBUG   : push unit.000000 ---> AGENT_STAGING_INPUT_PENDING
2017-06-03 18:22:29,767: agent.executing.0.child: agent.executing.0               : MainThread     : DEBUG   : got unit (unit.000000)
2017-06-03 18:22:29,767: agent.executing.0.child: agent.executing.0               : MainThread     : DEBUG   : advance bulk: unit.000000 [1]
2017-06-03 18:22:29,769: agent.executing.0.child: agent.executing.0               : MainThread     : DEBUG   : Created launch_script: /lustre/atlas1/bip149/scratch/vivekb/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017320.0004/pilot.0000/unit.000000/radical_pilot_cu_launch_script.sh
2017-06-03 18:22:29,779: agent.executing.0.child: agent.executing.0               : MainThread     : INFO    : Launching unit unit.000000 via /lustre/atlas1/bip149/scratch/vivekb/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017320.0004/pilot.0000/unit.000000/radical_pilot_cu_launch_script.sh in /lustre/atlas1/bip149/scratch/vivekb/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017320.0004/pilot.0000/unit.000000
2017-06-03 18:22:29,764: agent.scheduling.0.child: agent.scheduling.0              : MainThread     : DEBUG   : got unit (unit.000000)
2017-06-03 18:22:29,764: agent.scheduling.0.child: agent.scheduling.0              : MainThread     : DEBUG   : advance bulk: unit.000000 [1]
2017-06-03 18:22:29,765: agent.scheduling.0.child: agent.scheduling.0              : MainThread     : DEBUG   : unit.000000 [1] : {'task_slots': ['3789:0'], 'task_offsets': 0, 'lm_info': {}} [1]
2017-06-03 18:22:29,765: agent.scheduling.0.child: agent.scheduling.0              : MainThread     : DEBUG   : advance bulk: unit.000000 [1]
2017-06-03 18:22:29,766: agent.scheduling.0.child: agent.scheduling.0              : MainThread     : DEBUG   : bucket: AGENT_EXECUTING_PENDING : ['unit.000000']
2017-06-03 18:22:29,766: agent.scheduling.0.child: agent.scheduling.0              : MainThread     : DEBUG   : push unit.000000 ---> AGENT_EXECUTING_PENDING
2017-06-03 18:22:29,761: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : DEBUG   : got unit (unit.000000)
2017-06-03 18:22:29,761: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : DEBUG   : advance bulk: unit.000000 [1]
2017-06-03 18:22:29,762: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : DEBUG   : advance bulk: unit.000000 [1]
2017-06-03 18:22:29,762: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : DEBUG   : bucket: AGENT_SCHEDULING_PENDING : ['unit.000000']
2017-06-03 18:22:29,763: agent.staging.input.0.child: agent.staging.input.0           : MainThread     : DEBUG   : push unit.000000 ---> AGENT_SCHEDULING_PENDING
cat: rp_install: Is a directory
cat: unit.000000: Is a directory
2017-06-03 18:22:29,762: update.0.child      : update.0                        : update.0.child.subscriber._state_cb: DEBUG   : bulked unit.000000 [AGENT_STAGING_INPUT] update.0.child
2017-06-03 18:22:29,784: update.0.child      : update.0                        : update.0.child.subscriber._state_cb: DEBUG   : bulked unit.000000 [AGENT_SCHEDULING_PENDING] update.0.child
2017-06-03 18:22:29,785: update.0.child      : update.0                        : update.0.child.subscriber._state_cb: DEBUG   : bulked unit.000000 [AGENT_SCHEDULING] update.0.child
2017-06-03 18:22:29,785: update.0.child      : update.0                        : update.0.child.subscriber._state_cb: DEBUG   : bulked unit.000000 [AGENT_EXECUTING_PENDING] update.0.child
2017-06-03 18:22:29,785: update.0.child      : update.0                        : update.0.child.subscriber._state_cb: DEBUG   : bulked unit.000000 [AGENT_EXECUTING] update.0.child
```

**Comment by andre-merzky** [comment]
Can you please send the agent side logs?  Thanks!

**Comment by marksantcroos** [comment]
The question is whether aprun is possible at all with the latest RP on Titan. aprun needs to run on the MOM node, and for resource limit reasons we had to move most stuff to the compute node.

**Comment by andre-merzky** [comment]
Ah, indeed - aprun limited to MOM nodes was not on my radar anymore, and the executor in the titan agent config was indeed moved to a compute node.  Vivek, let me try to come up with an agent config which works with aprun.

**Comment by vivek-bala** [comment]
Sure! Let me know when I can test it out.

**Comment by andre-merzky** [comment]
This should be fixed in the branch fix/titan_aprun.  Please let me know if that works for you!

**Comment by vivek-bala** [comment]
I tried the fix/titan_aprun branch and it seems to have solved this issue. Althought I got the following error once (I tried thrice, but can't reproduce this):

```
> python 00_getting_started.py ornl.titan_aprun
new session: [rp.session.titan-ext3.vivekb.017324.0000]                        \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]                     ok
create pilot manager                                                          ok
submit 1 pilot(s)
        .                                                                     ok
create unit manager                                                           ok
add 1 pilot(s)                                                                ok
submit 5 unit(s)
        .....                                                                 ok
wait for 5 unit(s)
        +++++                                                                 ok
closing session rp.session.titan-ext3.vivekb.017324.0000                       \
close unit managerTraceback (most recent call last):
  File "00_getting_started.py", line 121, in <module>
    session.close(cleanup=False)
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rp_aprun/lib/python2.7/site-packages/radical/pilot/session.py", line 433, in close
    umgr.close()
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rp_aprun/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 214, in close
    self.stop()
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rp_aprun/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 658, in stop
    super(Component, self).stop(timeout)
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rp_aprun/lib/python2.7/site-packages/radical/utils/process.py", line 690, in stop
    self._ru_finalize()
  File "/autofs/nccs-svm1_home1/vivekb/ves/test_rp_aprun/lib/python2.7/site-packages/radical/utils/process.py", line 936, in _ru_finalize
    raise RuntimeError('finalize: %s' % repr(e))
RuntimeError: finalize: RuntimeError(['could not join child process 5666'],)
```

**Comment by vivek-bala** [comment]
This issue can be considered resolved. I can't reproduce the above error any more as well.

**Comment by andre-merzky** [comment]
the above error basically tells us that RP caught an unclean termination, and had to shut things down the hard way.  As such it might pop up again, but is indeed signaling that a Python level process error occurred which we then handled.

Thanks for the note, will close.
