### ISSUE TITLE
RP fails on MAC

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1392]
This is the error I get from pmgr.0000.log:

```
2017-07-24 12:50:48,328: pmgr.0000           : MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : [Callback]: pilot 'pilot.0000' failed
2017-07-24 12:50:48,328: pmgr.0000           : MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : abort: RuntimeError('pilot pilot.0000 failed - fatal!',)
Traceback (most recent call last):
  File "/Volumes/Data/Repositories/Cybertools/Testing/ve/lib/python2.7/site-packages/radical/utils/threads.py", line 375, in _run
    if not self.work_cb():
  File "/Volumes/Data/Repositories/Cybertools/Testing/ve/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1097, in work_cb
    ret = self._cb(topic=topic, msg=m)
  File "/Volumes/Data/Repositories/Cybertools/Testing/ve/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 284, in _state_sub_cb
    if not self._update_pilot(thing, publish=False):
  File "/Volumes/Data/Repositories/Cybertools/Testing/ve/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 325, in _update_pilot
    self._pilots[pid]._update(pilot_dict)
  File "/Volumes/Data/Repositories/Cybertools/Testing/ve/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 169, in _update
    else      : cb(self, self.state)
  File "/Volumes/Data/Repositories/Cybertools/Testing/ve/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 129, in _default_state_cb
    raise RuntimeError('pilot %s failed - fatal!' % self.uid)
RuntimeError: pilot pilot.0000 failed - fatal!
2017-07-24 12:50:48,333: pmgr.0000           : MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : put message: [pmgr.0000.subscriber._state_sub_cb.thread] RuntimeError('pilot pilot.0000 failed - fatal!',)
2017-07-24 12:50:48,333: pmgr.0000
```

**Comment by iparask** [comment]
I get the same error on a linux machine as well. In addition, I am using Anaconda Python

**Comment by iparask** [comment]
It run with GCC Python. So I think it is fair to assume that has to do with Anaconda Python

**Comment by iparask** [comment]
:) I was using the wrong label. It works with Anaconda
