### ISSUE TITLE
Examples failing (locally) on multiple machines, with a mongodb error.

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1412]
```
(ve.rc2) ubuntu@ubuntu:~/Gits/src/rp/examples$ python 00_getting_started.py 
new session: [rp.session.ubuntu.ubuntu.017386.0008]                            \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]                    err
Traceback (most recent call last):
  File "00_getting_started.py", line 36, in <module>
    session = rp.Session()
  File "/home/ubuntu/Gits/ve.rc2/local/lib/python2.7/site-packages/radical/pilot/session.py", line 264, in __init__
    % (dburl, ex))  
RuntimeError: Couldn't create new session (database URL 'mongodb://rp:rp@ds015335.mlab.com:15335/rp' incorrect?): command SON([('createIndexes', u'rp.session.ubuntu.ubuntu.017386.0008'), ('indexes', [{'sparse': False, 'unique': True, 'name': u'uid_1', 'key': SON([('uid', 1)])}])]) on namespace rp.$cmd failed: too many namespaces/collections
```

Issue has been replicated on three machines. Examples 00, 01, 03, 04, 06, 07, 09 fail with a "Couldn't create new session" message.

**Comment by andre-merzky** [comment]
Ouch, it seems we did *too much* testing!  Well, not really - but the problem was that the default MongoDB database filled up (`too many namespaces/collections`).  I cleaned it out, and things should work again I hope - please let us know.

**Comment by SrinivasMushnoori** [comment]
Yes this works. However, other possible issues have surfaced. Will be opening tickets soon.

Thanks , Andre!
