### ISSUE TITLE
RP devel on BW fails - several errors

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1416]
I am trying out the devel RP stack on BW with aprun as the task execution method. Each time I try I see different errors:

```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/vivek/ves/test-rp

  radical.pilot        : 0.46-v0.46.RC2@devel
  radical.utils        : 0.46-v0.46.RC1-2-g8f65bf8@devel
  saga                 : 0.46-v0.46.RC1@devel
```

Error in first attempt:

Tail of bootstrap_1.out:
```
Successfully installed setproctitle
Cleaning up...
#
# SUCCESS
#
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# install orte_cffi
# cmd: /mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.46/bin/pip --cert /scratch/sciteam/balasubr/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017398.0002/pilot.0000/../cacert.pem install  orte_cffi
#
Downloading/unpacking orte-cffi
  Downloading orte-cffi-0.4.1.tar.gz
  Running setup.py egg_info for package orte-cffi

    Installed /mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.46/build/orte-cffi/cffi-1.10.0-py2.7-linux-x86_64.egg
    Searching for pycparser
    Reading http://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.18
    Downloading https://pypi.python.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz#md5=72370da54358202a60130e223d488136
    Processing pycparser-2.18.tar.gz
    Running pycparser-2.18/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6oPcgI/pycparser-2.18/egg-dist-tmp-ssXjbl
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    pycparser.ply.yacc: module references __file__
    pycparser.ply.yacc: module MAY be using inspect.getsourcefile
    pycparser.ply.yacc: module MAY be using inspect.stack
    pycparser.ply.ygen: module references __file__
    pycparser.ply.lex: module references __file__
    pycparser.ply.lex: module MAY be using inspect.getsourcefile

    Installed /mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.46/build/orte-cffi/pycparser-2.18-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.46/build/orte-cffi/setup.py", line 15, in <module>
        install_requires = ["cffi>=1.5.0"],
      File "/sw/bw/bwpy/0.3.0/python-single/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.46/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 264, in __init__
      File "/sw/bw/bwpy/0.3.0/python-single/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.46/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 297, in finalize_options
      File "/mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.46/build/orte-cffi/cffi-1.10.0-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 188, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.46/build/orte-cffi/cffi-1.10.0-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.46/build/orte-cffi/cffi-1.10.0-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/orte-cffi/build.py", line 87, in <module>
        pkgconfig_dir = get_pkgconfig_dir()
      File "src/orte-cffi/build.py", line 46, in get_pkgconfig_dir
        libdir = ompi_info_path('libdir')
      File "src/orte-cffi/build.py", line 20, in ompi_info_path
        raise Exception('ompi_info not found, check your path')
    Exception: ompi_info not found, check your path

```

Error in second attempt:

Tail of bootstrap_1.out:
```
Successfully installed radical.pilot
Cleaning up...
#
# SUCCESS
#
# -------------------------------------------------------------------
purge install source at radical.pilot-0.46-v0.46.RC2-devel/
verify python viability: /mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.46/bin/python ... ok
verify module viability: saga            ... ok
verify module viability: radical.utils   ... ok
verify module viability: pymongo         ... ok
verify module viability: hostlist        ... ok
verify module viability: netifaces       ... ok
verify module viability: setproctitle    ... ok
verify module viability: ntplib          ... ok
verify module viability: msgpack         ...Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named msgpack
 failed
python installation cannot load module msgpack - abort
```

Let me know how I can help debug.

**Comment by andre-merzky** [comment]
Hey Vivek, 

that the ompi and cffi install fails is ok as long as you are not using orte/ortelib configurations - so with aprun you should not worry about those.  The bootstrapper should *not* terminate on those errors - or did it?

`msgpack` though should get installed while bootstrapping.  Can you send me the agent logfiles?

**Comment by vivek-bala** [comment]
Please see file attached. I set RADICAL_PILOT_VERBOSE=DEBUG but I didn't any log files in the agent side.

Ok, now it consistently fails and terminates only with the msgpack error.

[rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017400.0002.zip](https://github.com/radical-cybertools/radical.pilot/files/1242837/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017400.0002.zip)

**Comment by andre-merzky** [comment]
Vivek, can you please remove `/mnt/c/scratch/sciteam/balasubr/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.46` and try again?   A different bootstrap error may have left the VE in an inconsistent state...

**Comment by vivek-bala** [comment]
I think this was a consequence of system changes on BW. Closing.
