### ISSUE TITLE
Cannot read OSG agent config

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#1424]
Tried to submit a pilot to `osg.xsede-virt-clust` running CU with executable `/bin/true`. However, I get the following error, which seems the OSG agent config is not read correctly.

```
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 663, in _prepare_pilot
    agent_cfg = ru.read_json(agent_cfg_file)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/utils/read_json.py", line 26, in read_json
    with open (filename) as f:
IOError: [Errno 21] Is a directory: 'osg'
2017-08-30 00:57:11,262: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 329, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 416, in _start_pilot_bulk
    info = self._prepare_pilot(resource, rcfg, pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 663, in _prepare_pilot
    agent_cfg = ru.read_json(agent_cfg_file)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/utils/read_json.py", line 26, in read_json
    with open (filename) as f:
IOError: [Errno 21] Is a directory: 'osg'
```

`radical-stack`
```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/mingtha/ve/ve.exec_model_exp

  radical.analytics    : v0.45.2-2-g476254a@devel
  radical.pilot        : 0.47-v0.46-3-g0f79ca80@devel
  radical.utils        : 0.47-v0.46-10-gc515db1@devel
  saga                 : 0.47-v0.46-2-ga48f5f0c@devel
```

**Comment by andre-merzky** [comment]
Hmm, I have difficulties understanding that message - we do not have any directory named `osg` in our deployment tree, nor in our src tree.  I also don't seem to get that error.  Its also confusing that it complains about `osg` - in that specific place in the code it should read `agent_osg.json`...

Can you please check if that file exists, and/or if you have an `osg` subdir?  If that does not help, please attach `pmgr.launching.0.child.log`.  Thanks!

**Comment by mingtaiha** [comment]
I do have a subdir called `osg`, but it is located in the directory where I run my experiments, and not where the same directory as `read_json.py`. The `osg` subdir should not interfere with the script?

And here's the [`pmgr.launching.0.child.log`](https://gist.github.com/mingtaiha/f62d996a3fd2923609c9881cce7587f4)

**Comment by andre-merzky** [comment]
Duh, found it:  https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/pmgr/launching/default.py#L655

The intent here is that one can point to a user defined agent config - but in your case that name points to a dir (not a config file), and bang.  That exception is not really wrong in this context - but its also clearly not what you expected.

Several options: 

1. we enforce the file naming scheme (`agent_osg.json`), which avoids that confusion
2. we get rid of that mechanism altogether (there are other mechanisms to inject agent configs, and this specific one has not been used, to my knowledge)
3. we raise a better error message.

I would opt for `2`, really - any objection?

**Comment by mingtaiha** [comment]
I am a knight who says **Nay**, keeper of the sacred word

**Comment by andre-merzky** [comment]
Ming, can you please give branch `fix/issue_1424` a try?  Thanks!

**Comment by mingtaiha** [comment]
I gave it a try. On the upside, this fix works and I am able to run `/bin/true` on OSG resources. I have another problem with the number of CUs that I run, but that will go in another ticket.

Can this fix be merged into the `devel` branch?

**Comment by andre-merzky** [comment]
It is merged now - thanks for testing :)  Yes, please open a new ticket for the CU num...
