### ISSUE TITLE
07_shared_unit_data.py fails with RP release

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1426]
See error in pmgr.launching:
```
2017-08-30 14:17:59,781: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/vivek/ves/giannis-test/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 329, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/vivek/ves/giannis-test/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 416, in _start_pilot_bulk
    info = self._prepare_pilot(resource, rcfg, pilot)
  File "/home/vivek/ves/giannis-test/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 819, in _prepare_pilot
    bootstrap_args += " -d '%s'" % ':'.join(sdist_names)
TypeError: sequence item 2: expected string, NoneType found
```

Tested with MacOS/Anaconda, Ubuntu/Anaconda, Ubuntu/GCC (os/python)

**Comment by vivek-bala** [comment]
[rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017408.0000.zip](https://github.com/radical-cybertools/radical.pilot/files/1264655/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017408.0000.zip)

**Comment by andre-merzky** [comment]
Uh, this is somewhat surprising, as this was explicitly part of the test protocol, wasn't it?  So did it work back then?  Also, that code path is the same for all examples - I assume that the other examples also don't work?

You have this file in your launcher log:

```
2017-08-30 14:17:58,668: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : INFO    : ('0.46.1', '0.46.1', None, None, None, '/home/vivek/ves/giannis-test/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/None')
```

This seems do indicate an incomplete / faulty installation of RP, as the sdist is indeed not found.  The output should be something like:

```
2017-08-30 09:54:02,634: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : INFO    : ('0.47', '0.47-v0.46-3-g0f79ca80@devel', '-v0.46', '@devel', 'radical.pilot-0.47-v0.46-3-g0f79ca80-devel.tar.gz', '/home/merzky/radical/radical.pilot.1/ve/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/../..//radical.pilot-0.47-v0.46-3-g0f79ca80-devel.tar.gz')
```

(well, for 0.46, but you get the point).  How was RP installed?  Is there a tarball  in the install tree somewhere?

**Comment by iparask** [comment]
Yes, that is how it is.

From me:
```
2017-08-30 14:12:29,186: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : INFO    : ('0.46.1', '0.46.1', None, None, None, '/home/iparask/Virtualenv/RpPipConda/lib/python2.7/site-packages/radical/pilot/pmgr/launching/None')
````

The tarballs though exist in the VE tree in the correct places actually

**Comment by iparask** [comment]
@andre-merzky , this stops me now to run things. As a result I cannot use the bulk push pull completely

**Comment by vivek-bala** [comment]
I installed it using the usual method. 

New VE > Source VE > ```pip install radical.pilot```

**Comment by andre-merzky** [comment]
I Giannis, let me put some commands together to debug this...

You mentioned that the tarballs exist in the right places - can you send the output of 'ls -l' for all three of them?  Thanks!

**Comment by iparask** [comment]
I think I found the reason command that causes that confusion. Do you want me to past the line here?

**Comment by andre-merzky** [comment]
How about these commands:

```sh
(ve) $ python -c 'import radical.utils as ru; print ru.get_version(["ve/lib/python2.7/site-packages/radical/pilot"])'

('0.47', '0.47-v0.46-3-g0f79ca80@devel', '-v0.46', '@devel', 'radical.pilot-0.47-v0.46-3-g0f79ca80-devel.tar.gz', 've/lib/python2.7/site-packages/radical/pilot/radical.pilot-0.47-v0.46-3-g0f79ca80-devel.tar.gz')


(ve) $ python -c 'import radical.utils as ru; print ru.get_version(["ve/lib/python2.7/site-packages/saga"])'

('0.46', '0.46-v0.46.RC1-9-gc1cb91c4@HEAD-detached-at-c1cb91c4', '-v0.46.RC1', '@HEAD-detached-at-c1cb91c4', 'saga-python-0.46-v0.46.RC1-9-gc1cb91c4-HEAD-detached-at-c1cb91c4.tar.gz', 've/lib/python2.7/site-packages/saga/saga-python-0.46-v0.46.RC1-9-gc1cb91c4-HEAD-detached-at-c1cb91c4.tar.gz')


(ve) $ python -c 'import radical.utils as ru; print ru.get_version(["ve/lib/python2.7/site-packages/radical/utils"])'

('0.47', '0.47-v0.46-10-gc515db1@devel', '-v0.46', '@devel', 'radical.utils-0.47-v0.46-10-gc515db1-devel.tar.gz', 've/lib/python2.7/site-packages/radical/utils/radical.utils-0.47-v0.46-10-gc515db1-devel.tar.gz')

```

You probably have different paths to your ve and python lib dirs - but should see similar results.

**Comment by andre-merzky** [comment]
> I think I found the reason command that causes that confusion. Do you want me to past the line here?

Sure :)

**Comment by iparask** [comment]
(1) 
```
python -c 'import radical.utils as ru; print ru.get_version(["anaconda/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot"])'
('0.46.1', '0.46.1', None, None, 'radical.pilot-0.46.1.tar.gz', 'anaconda/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/radical.pilot-0.46.1.tar.gz')
```
(2)
```
 python -c 'import radical.utils as ru; print ru.get_version(["anaconda/envs/RadicalPilot/lib/python2.7/site-packages/saga"])'
('0.46.1', '0.46.1', None, None, 'saga-python-0.46.1.tar.gz', 'anaconda/envs/RadicalPilot/lib/python2.7/site-packages/saga/saga-python-0.46.1.tar.gz')
```

(3) 
```
python -c 'import radical.utils as ru; print ru.get_version(["anaconda/envs/RadicalPilot/lib/python2.7/site-packages/radical/utils"])'
('0.46.2', '0.46.2', None, None, 'radical.utils-0.46.2.tar.gz', 'anaconda/envs/RadicalPilot/lib/python2.7/site-packages/radical/utils/radical.utils-0.46.2.tar.gz')
```
In the pilot launcher lines 73 and 74 the _mod_dir and _root_dir are setup up. If those are wrong then the ru.get_version will return an empty list and as a result line 87 will not return anything

**Comment by iparask** [comment]
```
(RadicalPilot) Ioannis’s Mac pilot$ pwd
/Users/iparask/anaconda/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot
(RadicalPilot) Ioannis’s Mac pilot$ ls -l radical.pilot-0.46.1.tar.gz
-rw-r--r--  1 iparask  staff  430199 Aug 31 17:54 radical.pilot-0.46.1.tar.gz
```

```
(RadicalPilot) Ioannis’s Mac utils$ pwd
/Users/iparask/anaconda/envs/RadicalPilot/lib/python2.7/site-packages/radical/utils
(RadicalPilot) Ioannis’s Mac utils$ ls -al radical.utils-0.46.2.tar.gz
-rw-r--r--  1 iparask  staff  126515 Aug 31 17:54 radical.utils-0.46.2.tar.gz
```

```
(RadicalPilot) Ioannis’s Mac saga$ pwd
/Users/iparask/anaconda/envs/RadicalPilot/lib/python2.7/site-packages/saga
(RadicalPilot) Ioannis’s Mac saga$ ls -l saga-python-0.46.1.tar.gz
-rw-r--r--  1 iparask  staff  697374 Aug 31 17:54 saga-python-0.46.1.tar.gz
```

**Comment by andre-merzky** [comment]
Duh...  Interpretation of `__file__` is also what caused #1415, so that makes sense...  Can you please, in that deployment, add a print somewhere around there to check what `__file__` is set to?  Thanks!

**Comment by iparask** [comment]
How can I do that without changing master branch?

**Comment by iparask** [comment]
Found how to do it:
```
from os import path, getcwd, chdir

def print_my_path():
    print('cwd:     {}'.format(getcwd()))
    print('__file__:{}'.format(__file__))
    print('abspath: {}'.format(path.abspath(__file__)))

print_my_path()

chdir('..')

print_my_path()
```

result:
```
(RadicalPilot) Ioannis’s Mac ~$ python runme.py
cwd:     /Users/iparask
__file__:runme.py
abspath: /Users/iparask/runme.py
cwd:     /Users
__file__:runme.py
abspath: /Users/runme.py
```

**Comment by andre-merzky** [comment]
like this: ;)

```
vim /Users/iparask/anaconda/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py`

and in line 70 or so, add 'print __file__` :D  That shoud obviously print `/Users/iparask/anaconda/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py`, but lets see...

**Comment by iparask** [comment]
I did:
```
self._mod_dir       = os.path.dirname(os.path.abspath(__file__))
self._log.info("GIANNIS: mod: %s"%self._mod_dir)
```
output:
```
 pmgr.launching.0.child: pmgr.launching.0                : MainThread     : INFO    : GIANNIS: mod: /Users/iparask/anaconda/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/pmgr/launching
```

But:
```
: MainThread     : INFO    : ('0.46.1', '0.46.1', None, None, None, '/Users/iparask/anaconda/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/pmgr/launching/None')
```

**Comment by iparask** [comment]
And:
```
self._log.info("GIANNIS: %s"%__file__)
```
gives
```
GIANNIS: /Users/iparask/anaconda/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py
```

I suppose these are correct?

**Comment by euhruska** [comment]
It seems that hotfix works for me. Thanks

**Comment by andre-merzky** [comment]
This is merged now, and a hotfix release pushed to pypi.  Thanks!
