### ISSUE TITLE
GPU stack fails on Titan

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1441]
I have the following stack installed:
```
> radical-stack

  python               : 2.7.9
  pythonpath           : /sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /autofs/nccs-svm1_home1/vivekb/ves/test-gpu

  radical.pilot        : 0.46-v0.46.RC2-46-ga02c649@feature-gpu
  radical.utils        : 0.47-v0.46-10-gc515db1@devel
  saga                 : 0.46-v0.46.RC1-10-g16fdfc7@feature-gpu
```

I ran the [gpu example](https://github.com/radical-cybertools/radical.pilot/blob/feature/gpu/examples/misc/gpu_pilot.py) under radical.pilot/examples/misc/.

I get the following verbose output:

```
================================================================================
 Getting Started (RP version 0.46)                                              
================================================================================

new session: [rp.session.titan-ext7.vivekb.017415.0007]                        \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]                     ok
read config                                                                   ok

--------------------------------------------------------------------------------
submit pilots                                                                   

create pilot manager                                                          ok
create pilot description[ornl.titan_aprun:64:4]                               ok
submit 1 pilot(s)
        .                                                                     ok

--------------------------------------------------------------------------------
submit units                                                                    

create unit manager                                                           ok
add 1 pilot(s)                                                                ok
create 2 unit description(s)
        ..                                                                    ok
submit 2 unit(s)
        ..                                                                    ok

--------------------------------------------------------------------------------
gather results                                                                  

wait for 2 unit(s)
        --                                                                    ok
  * unit.000000: FAIL, exit: None, out: None
  * unit.000001: FAIL, exit: None, out: None

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.titan-ext7.vivekb.017415.0007                       \
close unit manager                                                            ok
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
session lifetime: 42.5s                                                       ok

-------------------------------------------------------------------------------
```

I have attached the pilot folder but I don't see any VE created inside the sandbox.

```
vivekb@titan-ext2:/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox> ls
rp.session.titan-ext7.vivekb.017414.0002  rp.session.titan-ext7.vivekb.017414.0004  rp.session.titan-ext7.vivekb.017415.0002  rp.session.titan-ext7.vivekb.017415.0005  rp.session.titan-ext7.vivekb.017415.0007
rp.session.titan-ext7.vivekb.017414.0003  rp.session.titan-ext7.vivekb.017414.0005  rp.session.titan-ext7.vivekb.017415.0003  rp.session.titan-ext7.vivekb.017415.0006
```
[rp.session.titan-ext7.vivekb.017415.0007.zip](https://github.com/radical-cybertools/radical.pilot/files/1281542/rp.session.titan-ext7.vivekb.017415.0007.zip)

**Comment by andre-merzky** [comment]
Uh, no, that looks like the pilot did not get submitted correctly.  Would you please attach pmgr.launching.0.child.log from the client side?

**Comment by andre-merzky** [comment]
Darn, PBS changed:

```
NoSuccess: future exception: Error running job via 'qsub': 
 Job not submitted 

 size is no longer the correct way to request cores. 
  Please use the nodes option to request nodes: 
  -l nodes=<nodes>  

. Commandline was: SCRIPTFILE=`mktemp -t SAGA-Python-TORQUEJobScript.XXXXXX` &&  echo "
#!/bin/bash 
#PBS -N pilot.0000 
#PBS -o /lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext7.vivekb.017415.0008/pilot.0000/bootstrap_1.out 
#PBS -e /lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext7.vivekb.017415.0008/pilot.0000/bootstrap_1.err 
#PBS -l walltime=0:15:00 
#PBS -q rhea
#PBS -A BIP149 
#PBS -l size=1024

```

**Comment by vivek-bala** [comment]
I tried the latest commit in feature/gpu of RP. The job gets on the queue but I get an error running the CUs:

```
2017-09-07 11:41:54,759: agent.executing.0.child: agent.executing.0               : MainThread     : DEBUG   : Created launch_script: /lustre/atlas1/bip149/scratch/vivekb/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017416.0000/pilot.0000/unit.000250/radical_pilot_cu_launch_script.sh
2017-09-07 11:41:54,761: agent.executing.0.child: agent.executing.0               : MainThread     : ERROR   : Error in spawner (object of type 'int' has no len())
Traceback (most recent call last):
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017416.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 294, in spawn
    launch_command, hop_cmd = launcher.construct_command(cu, launch_script_name)
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017416.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/aprun.py", line 92, in construct_command
    depth = len(slot)
TypeError: object of type 'int' has no len()
```

I get the above error for each CU. The unit folders are created with the shell script but it seems like they are not executed.

Stack:
```
> radical-stack

  python               : 2.7.9
  pythonpath           : /sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /autofs/nccs-svm1_home1/vivekb/ves/test-gpu

  radical.pilot        : 0.46-v0.46.RC2-47-ga1be69c@feature-gpu
  radical.utils        : 0.47-v0.46-10-gc515db1@devel
  saga                 : 0.47-v0.46-14-g85df2eb@feature-gpu

```

**Comment by vivek-bala** [comment]
Adding agent side logs
[agent_logs.zip](https://github.com/radical-cybertools/radical.pilot/files/1289026/agent_logs.zip)

**Comment by vivek-bala** [comment]
I pulled the latest changes and installed it.  I deleted the VE in sandbox before testing it. 

I got the following error:
```
# -------------------------------------------------------------------
#
# Create virtualenv
# cmd: /autofs/nccs-svm1_home1/vivekb/ves/test-gpu/bin/python virtualenv-1.9/virtualenv.py /autofs/nccs-svm1_home1/vivekb/radical.pilot.sandbox/ve.local.localhost.0.46
#
Using real prefix '/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4'
New python executable in /autofs/nccs-svm1_home1/vivekb/radical.pilot.sandbox/ve.local.localhost.0.46/bin/python
Installing setuptools............done.
Installing pip..............................
  Complete output from command /autofs/nccs-svm1_ho...host.0.46/bin/python -x /autofs/nccs-svm1_ho....46/bin/easy_install /autofs/nccs-svm1_ho...pport/pip-1.3.tar.gz:
  Processing pip-1.3.tar.gz
Running pip-1.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-aYUdeM/pip-1.3/egg-dist-tmp-GMhd6x
warning: no files found matching '*.html' under directory 'docs'
warning: no previously-included files matching '*.txt' found under directory 'docs/_build'
no previously-included directories found matching 'docs/_build/_sources'
Adding pip 1.3 to easy-install.pth file
Installing pip script to /autofs/nccs-svm1_home1/vivekb/radical.pilot.sandbox/ve.local.localhost.0.46/bin
Installing pip-2.7 script to /autofs/nccs-svm1_home1/vivekb/radical.pilot.sandbox/ve.local.localhost.0.46/bin

Installed /autofs/nccs-svm1_home1/vivekb/radical.pilot.sandbox/ve.local.localhost.0.46/lib/python2.7/site-packages/pip-1.3-py2.7.egg
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/vivekb/radical.pilot.sandbox/ve.local.localhost.0.46/bin/easy_install", line 9, in <module>
    load_entry_point('setuptools==0.6rc11', 'console_scripts', 'easy_install')()
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 1712, in main
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 1700, in with_ei_usage
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 1716, in <lambda>
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 211, in run
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 427, in easy_install
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 478, in install_item
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 514, in process_distribution
TypeError: __init__() takes exactly 2 arguments (4 given)
----------------------------------------
...Installing pip...done.
Traceback (most recent call last):
  File "virtualenv-1.9/virtualenv.py", line 2577, in <module>
    main()
  File "virtualenv-1.9/virtualenv.py", line 979, in main
    no_pip=options.no_pip)
  File "virtualenv-1.9/virtualenv.py", line 1094, in create_environment
    install_pip(py_executable, search_dirs=search_dirs, never_download=never_download)
  File "virtualenv-1.9/virtualenv.py", line 667, in install_pip
    filter_stdout=_filter_setup)
  File "virtualenv-1.9/virtualenv.py", line 1057, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /autofs/nccs-svm1_ho...host.0.46/bin/python -x /autofs/nccs-svm1_ho....46/bin/easy_install /autofs/nccs-svm1_ho...pport/pip-1.3.tar.gz failed with error code 1
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
ERROR: Couldn't create virtualenv
Error on virtenv creation -- abort
removed `/autofs/nccs-svm1_home1/vivekb/radical.pilot.sandbox/ve.local.localhost.0.46.lock'
```

**Comment by vivek-bala** [comment]
Getting the following error with the latest changes:

```
2017-09-11 15:49:38,311: agent.executing.0.child: agent.executing.0               : MainThread     : DEBUG   : Created launch_script: /lustre/atlas1/bip149/scratch/vivekb/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017420.0000/pilot.0000/unit.000000/radical_pilot_cu_launch_script.sh
2017-09-11 15:49:38,314: agent.executing.0.child: agent.executing.0               : MainThread     : ERROR   : Error in spawner ('set' object does not support indexing)
Traceback (most recent call last):
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017420.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 294, in spawn
    launch_command, hop_cmd = launcher.construct_command(cu, launch_script_name)
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017420.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/aprun.py", line 122, in construct_command
    assert(1 == depths[0]), 'aprun implies depth==1 for gpu procs'
TypeError: 'set' object does not support indexing
2017-09-11 15:49:38,317: agent.executing.0.child: agent.executing.0               : MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017420.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 201, in _handle_unit
    self.spawn(launcher=launcher, cu=cu)
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017420.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 302, in spawn
    raise RuntimeError(msg)
RuntimeError: Error in spawner ('set' object does not support indexing)
2017-09-11 15:49:38,318: agent.executing.0.child: agent.executing.0               : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
2017-09-11 15:49:38,318: agent.executing.0.child: agent.executing.0               : MainThread     : DEBUG   : got unit (unit.000001)
2017-09-11 15:49:38,318: agent.executing.0.child: agent.executing.0               : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
2017-09-11 15:49:38,319: agent.executing.0.child: agent.executing.0               : MainThread     : DEBUG   : Launching unit with APRun (/sw/xk6/xalt/0.7.5/bin/aprun).
2017-09-11 15:49:38,320: agent.executing.0.child: agent.executing.0               : MainThread     : DEBUG   : Created launch_script: /lustre/atlas1/bip149/scratch/vivekb/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017420.0000/pilot.0000/unit.000001/radical_pilot_cu_launch_script.sh
2017-09-11 15:49:38,323: agent.executing.0.child: agent.executing.0               : MainThread     : ERROR   : Error in spawner (aprun implies uniform process depths)
Traceback (most recent call last):
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017420.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 294, in spawn
    launch_command, hop_cmd = launcher.construct_command(cu, launch_script_name)
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017420.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/aprun.py", line 118, in construct_command
    assert(len(depths) == 1), 'aprun implies uniform process depths'
AssertionError: aprun implies uniform process depths
2017-09-11 15:49:38,324: agent.executing.0.child: agent.executing.0               : MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017420.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 201, in _handle_unit
    self.spawn(launcher=launcher, cu=cu)
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext4.vivekb.017420.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 302, in spawn
    raise RuntimeError(msg)
RuntimeError: Error in spawner (aprun implies uniform process depths)
```

**Comment by andre-merzky** [comment]
This has been fixed in the gpu branch.

**Comment by vivek-bala** [comment]
I used the latest gpu branches in saga and rp. My scripts that were working last week are not executing currently.

I am using the following stack:
```
> radical-stack

  python               : 2.7.9
  pythonpath           : /sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /ccs/home/vivekb/ve-entk-gpu

  radical.pilot        : 0.47-v0.46.2-86-g9382bdc@feature-gpu
  radical.utils        : 0.47-v0.46-10-gc515db1@devel
  saga                 : 0.47-v0.46-23-g21cb4e9@feature-gpu

```

The error seems to be in the agent log file. Attached here: https://gist.github.com/vivek-bala/e9c464eeca09cde30ab9be728121e3e4

For now, I am going to try to find and use the git commit that worked last.

**Comment by andre-merzky** [comment]
Looks like the agent was not able to find `aprun`.  That could also mean an environmental change (PATH, modules loaded, etc).  But lets see what your revert to a previous commit tells us...

**Comment by vivek-bala** [comment]
I think this is an old ticket that wasn't updated. I have, since then, used the GPUs on Titan for our experiments. Closing.
