### ISSUE TITLE
Project reservations do not work

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1444]
I get this error when I add a project reservation in RP.
```
2017-09-07 18:03:22,800: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : DEBUG   : jd: {'Arguments': ['-l /work/03170/tg824689/wrangler/radical.pi
lot.sandbox/test/bootstrap_1.sh',
               " -d 'radical.utils-0.46.2.tar.gz:saga-python-0.46.1.tar.gz:radical.pilot-0.46.2.tar.gz' -p 'pilot.0000' -s 'test' -m 'create' -r 'local' -b 'default' -g 'def
ault' -v '/work/03170/tg824689/wrangler/radical.pilot.sandbox/ve.xsede.wrangler_ssh.0.46.2' -y '120' -e 'module load python' -e 'export TACC_DELETE_FILES=TRUE' -w 'export PA
TH=$PATH' -w 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH'"],
 'CandidateHosts': None,
 'Environment': {'RADICAL_PILOT_PROFILE': 'TRUE'},
 'Error': 'bootstrap_1.err',
 'Executable': '/bin/bash',
 'FileTransfer': [],
 'Name': 'pilot.0000',
 'Output': 'bootstrap_1.out',
 'ProcessesPerHost': 0,
 'Project': 'TG-MCB090174:dssd+TG-MCB090174+2367',
 'Queue': 'normal',
 'SPMDVariation': None,
 'TotalCPUCount': 96,
 'TotalPhysicalMemory': None,
 'WallTimeLimit': 120,
 'WorkingDirectory': '/work/03170/tg824689/wrangler/radical.pilot.sandbox/test/pilot.0000/'}
2017-09-07 18:03:22,964: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 329, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 520, in _start_pilot_bulk
    jc.run()
  File "/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/saga/task.py", line 405, in run
    % (future.exception))
NoSuccess: future exception: need more than 1 value to unpack (/home/iparask/anaconda2/envs/RadicalPilot/lib/python2.7/site-packages/saga/task.py +405 (run)  :  % (future.ex
ception)))
2017-09-07 18:03:22,964: pmgr.launching.0.child: pmgr.launching.0                : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
```

Any ideas? It is a party crasher

**Comment by iparask** [comment]
This is resolved!
