### ISSUE TITLE
any idea where this error come from?

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#1465]
```
Traceback (most recent call last):
  File "submit_bot.py", line 7, in <module>
    import radical.pilot as rp
  File "/home/georgeha/ves/streaming/local/lib/python2.7/site-packages/radical/pilot/__init__.py", line 23, in <module>
    from .session                   import Session
  File "/home/georgeha/ves/streaming/local/lib/python2.7/site-packages/radical/pilot/session.py", line 18, in <module>
    from . import utils         as rpu
  File "/home/georgeha/ves/streaming/local/lib/python2.7/site-packages/radical/pilot/utils/__init__.py", line 8, in <module>
    version, version_detail, version_branch, sdist_name, sdist_path = ru.get_version([_root])
ValueError: too many values to unpack
```

**Comment by andre-merzky** [comment]
Yes - this is most likely a version mixup between RU and RS/RP.  You almost always want to use those three from the same release version or branch, like, all from devel, all from master, all in version 0.42, etc. But please do let me know if the problem persists, and then also send the output of `radical-stack`, please.

**Comment by georgeha** [comment]
```
(streaming)georgeha@js-17-20:~/repos/radical.pilot/src/radical/pilot/agent/lm$ radical-stack

  python               : 2.7.6
  pythonpath           : 
  virtualenv           : /home/georgeha/ves/streaming

  radical.utils        : 0.46.2
  saga                 : 0.46.1
```
This is my radical-stack. I am using the feature/streaming branch

**Comment by iparask** [comment]
A year old issue. Closing due to inactivity
