### ISSUE TITLE
RP failure on Rhea -- possibly bootstrapper failure

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1473]
I am using the following stack:

```
 radical.pilot        : 0.46-v0.46.RC1-51-gb8a3597@feature-rhea_support
 radical.utils        : 0.47-v0.46-10-gc515db1@devel
 saga                 : 0.47-v0.46-23-g21cb4e9@feature-rhea
```

In the sandbox, I noticed that there are no output and error files. Following are the files that exist currently:
```
-bash-4.1$ ls
bootstrap_1.sh  env.orig    pilot.0000.log.tgz   radical.pilot-0.46-v0.46.RC1-51-gb8a3597-feature-rhea-support.tar.gz  rp.session.titan-ext1.vivekb.017450.0005.pmgr.launching.0.child.tgz
cacert.pem      pilot.0000  pilot.0000.prof.tgz  radical.utils-0.47-v0.46-10-gc515db1-devel.tar.gz                     saga-python-0.47-v0.46-23-g21cb4e9-feature-rhea.tar.gz
```

I ran the bootstrapper manually through an interactive session. I got the arguments to the bootstrapper from the pmgr.launching.0.child.log in the client side. My command to launch the bootstrapper was 
```
/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext1.vivekb.017450.0005/bootstrap_1.sh -d 'radical.utils-0.47-v0.46-10-gc515db1-devel.tar.gz:saga-python-0.47-v0.46-23-g21cb4e9-feature-rhea.tar.gz:radical.pilot-0.46-v0.46.RC1-51-gb8a3597-feature-rhea-support.tar.gz' -p 'pilot.0000' -s 'rp.session.titan-ext1.vivekb.017450.0005' -m 'use' -r 'local' -b 'default' -g 'system' -v '/lustre/atlas2/csc230/world-shared/ve.rp.rhea.20017.08.07' -y '15' -f 'rhea-login4g.ccs.ornl.gov' -h '138.201.86.166:27017' -e 'module purge' -e 'module load PE-gnu' -e 'module load python' -e 'module load python_pip' -e 'module load python_virtualenv' -e 'export LD_PRELOAD=/lib64/librt.so.1'
```

The failure happens when the bootstrapper is searching for a TCP port:
```
# Setting up forward tunnel for MongoDB to rhea-login4g.ccs.ornl.gov.

################################################################################
## Searching for available TCP port for tunnel in range 23000..23100.
## No available port found
```

I believe this comes from line https://github.com/radical-cybertools/radical.pilot/blob/feature/rhea_support/src/radical/pilot/agent/bootstrap_1.sh#L1489.

The complete output of the bootstrapper execution is available at https://gist.github.com/vivek-bala/2f04641ddd3d698850b93da4631a4032. This is not from a bootstrap_1.out file but from STDOUT.

Note: Currently, there are no output or error files generated for the bootstrapper execution when the RP example script (00_getting_started.py) is run. I have noticed that in a successful run bootstrap_1.out and bootstrap_1.err are generated inside the pilot.0000 folder. Maybe there are not generated (in the current case) because they are not getting flushed?

Let me know how I can help debug this further.

**Comment by vivek-bala** [comment]
Just to add to my note above: Since there are no output or error files created when running the RP script, the failure might not necessarily be the same as what I observed when running the bootstrapper manually.

**Comment by vivek-bala** [comment]
Update on the testing that I have done so far:

Currently, all the testing has been by running the bootstrapper manually. We still don't get any log, out or error files when running the RP example.  We do get a number of log, out and error files when running manually.

* Added 'module load openssl' to the rhea resource config
* Currently, we fail with the following in agent_0.err:

```
2017-10-11 19:13:43,878: radical.saga        : MainProcess                     : MainThread     : WARNING : cannot initialize context - no session: {'LifeTime' : '-1', 'Type' : 'ssh', 'UserCert' : '/ccs/home/vivekb/.ssh/id_rsa.pub', 'UserKey' : '/ccs/home/vivekb/.ssh/id_rsa'}
Traceback (most recent call last):
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext6.vivekb.017450.0011/pilot.0000/rp_install/bin/radical-pilot-agent", line 26, in <module>
    rp.agent.bootstrap_3(agent_name)
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext6.vivekb.017450.0011/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/bootstrap_3.py", line 42, in bootstrap_3
    agent = Agent_0(agent_name)
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext6.vivekb.017450.0011/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_0.py", line 97, in __init__
    session = rp_Session(cfg=session_cfg)
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext6.vivekb.017450.0011/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/session.py", line 268, in __init__
    self._bridges    = ruc.start_bridges   (self._cfg, self, self._log)
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext6.vivekb.017450.0011/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 152, in start_bridges
    bridge = rpu_Queue(session, bname, rpu_QUEUE_BRIDGE, bcfg_clone)
  File "/lustre/atlas/scratch/vivekb/bip149/radical.pilot.sandbox/rp.session.titan-ext6.vivekb.017450.0011/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 192, in __init__
    self._pqueue = mp.Queue()
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 28] No space left on device
```

The latest commit 21198cbc6a5be0f98baf8762380d17371ea120de does not fix the issue. No out, err or log files generated.

**Comment by andre-merzky** [comment]
You know, the whole time I was tracking down python stack issues, since we have seen that error in that context so often - but the error actually is what it says:

```
merzky1@rhea-login7g:~ $ qsub -I -lnodes=2,walltime=00:30:00 -A BIP149 -q batch_rhea
qsub: waiting for job 302005.rhea-moab.ccs.ornl.gov to start
qsub: job 302005.rhea-moab.ccs.ornl.gov ready

merzky1@rhea87:~ $ module list
Currently Loaded Modulefiles:
  1) intel/14.0.4            3) PE-intel/14.0.4-1.8.4   5) xalt/0.5.3              7) bbcp/15.02.03.00.1
  2) openmpi/1.8.4           4) lustredu/1.4            6) hsi/5.0.2.p1            8) DefApps

merzky1@rhea87:~ $ module load python
merzky1@rhea87:~ $ python
Python 2.7.9 (default, May 22 2015, 13:43:43) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocessing as mp
>>> queues = list()
>>> for i in range(10):
...   print i
...   queues.append(mp.Queue())
... 
0
1
2
3
4
5
6
7
8
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/queues.py", line 68, in __init__
    self._wlock = Lock()
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 28] No space left on device
```

I'll open an ORNL ticket.

**Comment by andre-merzky** [comment]
This is an ORNL ticket now, they'll look into it.  Seems indeed an issue with limits on shmem, but no solution so far.

**Comment by andre-merzky** [comment]
According to ORNL support, this is waiting for a RHEA reboot to get fixed on system level.  We may want to ask for that reboot to be triggered.

**Comment by andre-merzky** [comment]
@mturilli : Matteo, do we want to ask for that trigger?

**Comment by vivek-bala** [comment]
This issue is still critical. I believe Princeton is working on the analysis but testing it on Titan. For production they need to use Rhea.

**Comment by andre-merzky** [comment]
yes :-)  Finally!

**Comment by vivek-bala** [comment]
Testing RP on Rhea again. Tried to create a new static VE (old one seems to be purged), I get
the following error:
```
vivekb@titan-ext4:/lustre/atlas2/csc190/world-shared> ./radical-pilot-create-static-ve ve.rp.rhea.2018.06.06

script : ./radical-pilot-create-static-ve
prefix : ve.rp.rhea.2018.06.06
arg    : 

create rct ve [/lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.06]
create  virtualenv ...
update  setuptools .........
update  pip ..........
install pymongo==2.8 .openstacksdk 0.12.0 requires PyYAML>=3.12, which is not installed.
os-client-config 1.29.0 requires PyYAML>=3.10, which is not installed.
cliff 2.11.0 requires PyYAML>=3.10, which is not installed.
..
install python-hostlist .openstacksdk 0.12.0 requires PyYAML>=3.12, which is not installed.
os-client-config 1.29.0 requires PyYAML>=3.10, which is not installed.
cliff 2.11.0 requires PyYAML>=3.10, which is not installed.
..
install netifaces==0.10.4 .openstacksdk 0.12.0 requires PyYAML>=3.12, which is not installed.
os-client-config 1.29.0 requires PyYAML>=3.10, which is not installed.
cliff 2.11.0 requires PyYAML>=3.10, which is not installed.
.....
install setproctitle .openstacksdk 0.12.0 requires PyYAML>=3.12, which is not installed.
os-client-config 1.29.0 requires PyYAML>=3.10, which is not installed.
cliff 2.11.0 requires PyYAML>=3.10, which is not installed.
..
install ntplib .openstacksdk 0.12.0 requires PyYAML>=3.12, which is not installed.
os-client-config 1.29.0 requires PyYAML>=3.10, which is not installed.
cliff 2.11.0 requires PyYAML>=3.10, which is not installed.
..
install pyzmq .openstacksdk 0.12.0 requires PyYAML>=3.12, which is not installed.
os-client-config 1.29.0 requires PyYAML>=3.10, which is not installed.
cliff 2.11.0 requires PyYAML>=3.10, which is not installed.

install apache-libcloud .......openstacksdk 0.12.0 requires PyYAML>=3.12, which is not installed.
os-client-config 1.29.0 requires PyYAML>=3.10, which is not installed.
cliff 2.11.0 requires PyYAML>=3.10, which is not installed.
..
install colorama ..openstacksdk 0.12.0 requires PyYAML>=3.12, which is not installed.
os-client-config 1.29.0 requires PyYAML>=3.10, which is not installed.
cliff 2.11.0 requires PyYAML>=3.10, which is not installed.
..
install backports.ssl-match-hostname ..openstacksdk 0.12.0 requires PyYAML>=3.12, which is not installed.
os-client-config 1.29.0 requires PyYAML>=3.10, which is not installed.
cliff 2.11.0 requires PyYAML>=3.10, which is not installed.
....
```

Any idea?

**Comment by andre-merzky** [comment]
No, I don't really know what that's all about - but you could probably try to manually install `PyYAML`, as that seems to be what the process is having trouble with?

**Comment by vivek-bala** [comment]
Fixed the yaml issues. The bootstrapper fails with the following error:

```
# SUCCESS
#
# -------------------------------------------------------------------
# -------------------------------------------------------------------
# Touching output tarballs
# -------------------------------------------------------------------
create gtod
build gtod with cc... success
0.0049,bootstrap_1,pilot.0000,PMGR_ACTIVE_PENDING,bootstrap_1_start,
VIRTENV : /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20
VIRTENV : /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20 (normalized)
PYTHON: /sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/bin/python
PIP   : /sw/rhea/python_pip/8.1.2/rhel6.6_python2.7.9/bin/pip --cert /lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/../cacert.pem
0.1002,bootstrap_1,pilot.0000,PMGR_ACTIVE_PENDING,ve_setup_start,
virtenv_create   : FALSE
virtenv_update   : FALSE
rp install sources:  radical.utils-0.47.4-merge-pre-gpu-22-ga942c4b-devel/ saga-python-0.47.4-v0.47.4-32-g71a97659-devel/ radical.pilot-0.46-v0.46.RC1-54-g6fd820a4-feature-rhea-support/
rp install target : SANDBOX
rp install lock   : FALSE
do not create virtenv /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20
1.1793,bootstrap_1,pilot.0000,PMGR_ACTIVE_PENDING,ve_activate_start,
PYTHON: /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin/python
PIP   : /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin/pip --cert /lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/../cacert.pem
PYTHON INTERPRETER: /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin/python
PYTHON_VERSION    : 2.7
VE_MOD_PREFIX     : /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/lib/python2.7/site-packages
PIP installer     : /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin/pip --cert /lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/../cacert.pem
Traceback (most recent call last):
  File "/lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named _internal
PIP version       :
activated virtenv
VIRTENV      : /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20
VE_MOD_PREFIX: /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/lib/python2.7/site-packages
RP_MOD_PREFIX: /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/rp_install/lib/python2.7/site-packages
PYTHONPATH   : /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/lib/python2.7/site-packages:/sw/rhea/python_virtualenv/13.0.1/python2.7.9_gnu4.8.2/lib64/python2.7/site-packages:/sw/rhea/python_virtualenv/13.0.1/python2.7.9_gnu4.8.2/lib/python2.7/site-packages:/sw/rhea/python_pip/8.1.2/rhel6.6_python2.7.9/lib64/python2.7/site-packages:/sw/rhea/python_pip/8.1.2/rhel6.6_python2.7.9/lib/python2.7/site-packages:/sw/rhea/python_setuptools/23.0.0/python2.7.9/lib64/python2.7/site-packages:/sw/rhea/python_setuptools/23.0.0/python2.7.9/lib/python2.7/site-packages:/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/site-packages
13.5560,bootstrap_1,pilot.0000,PMGR_ACTIVE_PENDING,ve_activate_stop,
do not update virtenv /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20
13.5693,bootstrap_1,pilot.0000,PMGR_ACTIVE_PENDING,rp_install_start,
Using RADICAL-Pilot install sources ' radical.utils-0.47.4-merge-pre-gpu-22-ga942c4b-devel/ saga-python-0.47.4-v0.47.4-32-g71a97659-devel/ radical.pilot-0.46-v0.46.RC1-54-g6fd820a4-feature-rhea-support/'
VE_MOD_PREFIX: /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/lib/python2.7/site-packages
VIRTENV      : /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20
SANDBOX      : /lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000
VE_LOC_PREFIX:
using local install tree
PYTHONPATH: /lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install/lib/python2.7/site-packages::/sw/rhea/python_virtualenv/13.0.1/python2.7.9_gnu4.8.2/lib64/python2.7/site-packages:/sw/rhea/python_virtualenv/13.0.1/python2.7.9_gnu4.8.2/lib/python2.7/site-packages:/sw/rhea/python_pip/8.1.2/rhel6.6_python2.7.9/lib64/python2.7/site-packages:/sw/rhea/python_pip/8.1.2/rhel6.6_python2.7.9/lib/python2.7/site-packages:/sw/rhea/python_setuptools/23.0.0/python2.7.9/lib64/python2.7/site-packages:/sw/rhea/python_setuptools/23.0.0/python2.7.9/lib/python2.7/site-packages:/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/lib/python2.7/site-packages
rp_install: /lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install/lib/python2.7/site-packages
radicalmod: /lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/
created radical namespace in /lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical//__init__.py

# -------------------------------------------------------------------
#
# update radical.utils-0.47.4-merge-pre-gpu-22-ga942c4b-devel/ via pip
# cmd: /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin/pip --cert /lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/../cacert.pem install  --src '/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install/src' --build '/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install/build' --install-option='--prefix=/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install' --no-deps radical.utils-0.47.4-merge-pre-gpu-22-ga942c4b-devel/
#
Traceback (most recent call last):
  File "/lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named _internal
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't install radical.utils-0.47.4-merge-pre-gpu-22-ga942c4b-devel/! Lets see how far we get ...
purge install source at radical.utils-0.47.4-merge-pre-gpu-22-ga942c4b-devel/

# -------------------------------------------------------------------
#
# update saga-python-0.47.4-v0.47.4-32-g71a97659-devel/ via pip
# cmd: /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin/pip --cert /lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/../cacert.pem install  --src '/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install/src' --build '/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install/build' --install-option='--prefix=/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install' --no-deps saga-python-0.47.4-v0.47.4-32-g71a97659-devel/
#
Traceback (most recent call last):
  File "/lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named _internal
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't install saga-python-0.47.4-v0.47.4-32-g71a97659-devel/! Lets see how far we get ...
purge install source at saga-python-0.47.4-v0.47.4-32-g71a97659-devel/

# -------------------------------------------------------------------
#
# update radical.pilot-0.46-v0.46.RC1-54-g6fd820a4-feature-rhea-support/ via pip
# cmd: /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin/pip --cert /lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/../cacert.pem install  --src '/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install/src' --build '/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install/build' --install-option='--prefix=/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install' --no-deps radical.pilot-0.46-v0.46.RC1-54-g6fd820a4-feature-rhea-support/
#
Traceback (most recent call last):
  File "/lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named _internal
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't install radical.pilot-0.46-v0.46.RC1-54-g6fd820a4-feature-rhea-support/! Lets see how far we get ...
purge install source at radical.pilot-0.46-v0.46.RC1-54-g6fd820a4-feature-rhea-support/
18.7030,bootstrap_1,pilot.0000,PMGR_ACTIVE_PENDING,rp_install_stop,
18.7144,bootstrap_1,pilot.0000,PMGR_ACTIVE_PENDING,ve_setup_stop,
18.7254,bootstrap_1,pilot.0000,PMGR_ACTIVE_PENDING,ve_activate_start,
which: no radical-pilot-agent in (/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017702.0000/pilot.0000/rp_install/bin:/lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin:/sw/rhea/python_virtualenv/13.0.1/python2.7.9_gnu4.8.2/bin:/sw/rhea/python_pip/8.1.2/rhel6.6_python2.7.9/bin:/sw/rhea/python_setuptools/23.0.0/python2.7.9/bin:/sw/rhea/python/2.7.9/rhel6.6_gnu4.4.7/bin:/sw/rhea/openmpi/1.8.4/rhel6.6_gcc4.8.2/bin:/ccs/compilers/gcc/rhel6-x86_64/4.8.2/bin:/usr/bin:/usr/sbin:/opt/moab/bin:/usr/bin:/usr/sbin:/usr/lib64/qt-3.3/bin:/opt/moab/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin)
verify python viability: /lustre/atlas2/csc190/world-shared/ve.rp.rhea.2018.06.20/bin/python ... ok
verify module viability: saga            ...Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named saga
 failed
python installation cannot load module saga - abort
```

Can you take a look into why the bootstrapping fails? The VE is in world shared and should be accessible by everyone in the group.

**Comment by vivek-bala** [comment]
Hey Andre, can you recreate the static VE on rhea please. I don't have permissions to do that. I think since the Rhea restart, the example worked. But I wanted to verify before closing this ticket. Will need the static VE for that. Thanks.

**Comment by vivek-bala** [comment]
Bump. Hey Andre, can you create a static VE that can be used by other members as well? I don't have permissions to create it in the project space. Thanks!

**Comment by vivek-bala** [comment]
Tagging to bump the issue @andre-merzky @mturilli

**Comment by andre-merzky** [comment]
@vivek-bala : ack.

**Comment by vivek-bala** [comment]
I don't think we have an active use case on Rhea any more. I can confirm once when the post-doc at Princeton is back on the project. @mturilli would you agree?

**Comment by mturilli** [comment]
Agreed. I would close this ticket and open a new on if we will have a use case for Rhea.
