### ISSUE TITLE
Socket is not connected

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.pilot#1523]
for https://github.com/radical-collaboration/extasy-grlsd with radical.entk 0.6.0 getting:
```2017-12-19 18:59:03,095: pmgr.0000.launching.0: MainProcess                     : pmgr.0000.launching.0.watch: ERROR   : abort: error(57, 'Socket is not connected')
Traceback (most recent call last):
  File "/Users/eh/myenv/lib/python2.7/site-packages/radical/utils/threads.py", line 375, in _run
    if not self.work_cb():
  File "/Users/eh/myenv/lib/python2.7/site-packages/radical/utils/process.py", line 300, in _ru_watch
    self._ru_endpoint.shutdown(socket.SHUT_RDWR)
error: [Errno 57] Socket is not connected
```
whole output: https://www.dropbox.com/sh/41pj44tjjt89ba6/AACC9jfY5pRHORqoT1ZcCrLIa?dl=0

**Comment by andre-merzky** [comment]
This run tries to connect to BlueWaters via an gsissh configuration, and meets this error:

```
2017-12-19 18:59:02,650: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/Users/eh/myenv/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 487, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/Users/eh/myenv/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 625, in _start_pilot_bulk
    fs.copy(tar_url, tar_rem, flags=rsfs.CREATE_PARENTS)
  File "/Users/eh/myenv/lib/python2.7/site-packages/saga/namespace/directory.py", line 353, in copy
    if url_2  :  return self._adaptor.copy (url_1, url_2, flags, ttype=ttype)
  File "/Users/eh/myenv/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/Users/eh/myenv/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 557, in copy
    files_copied = copy_shell.stage_to_remote (src.path, tgt.path, rec_flag)
  File "/Users/eh/myenv/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 899, in stage_to_remote
    raise ptye.translate_exception (e)
NoSuccess: unexpected EOF (exec: /usr/bin/gsissh: No such file or directory
Connection closed
) (/Users/eh/myenv/lib/python2.7/site-packages/saga/utils/pty_process.py +606 (read)  :  raise se.NoSuccess ("unexpected EOF (%s)" % self.tail))
```

Can you please check what's up with `/usr/bin/gsissh`?

In general, its most likely the first ERROR in the log files which is significant - later `ERROR` level log messages are likely triggered due to the previous execeptions.

**Comment by vivek-bala** [comment]
Thanks Andre! 

@euhruska : Can you run the following and try again?
```
export GLOBUS_LOCATION=`which gsissh`
```

**Comment by euhruska** [comment]
my gsissh was at /Library/Globus/bin/gsissh, but after adding "export GLOBUS_LOCATION=`which gsiss`" it still gave an error:
```
Traceback (most recent call last):
  File "/Users/eh/myenv/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 487, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/Users/eh/myenv/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 625, in _start_pilot_bulk
    fs.copy(tar_url, tar_rem, flags=rsfs.CREATE_PARENTS)
  File "/Users/eh/myenv/lib/python2.7/site-packages/saga/namespace/directory.py", line 353, in copy
    if url_2  :  return self._adaptor.copy (url_1, url_2, flags, ttype=ttype)
  File "/Users/eh/myenv/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/Users/eh/myenv/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 557, in copy
    files_copied = copy_shell.stage_to_remote (src.path, tgt.path, rec_flag)
  File "/Users/eh/myenv/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 899, in stage_to_remote
    raise ptye.translate_exception (e)
NoSuccess: unexpected EOF (/Library/Globus/bin/gsissh/etc/ssh not found.
exec: /Library/Globus/bin/gsissh/bin/gsissh: Not a directory
Connection closed
```
Full: https://www.dropbox.com/sh/t0fo9m03j7otmte/AABPjbAQdkVs8r_IRXoegqcPa?dl=0

**Comment by vivek-bala** [comment]
Oops, my bad.  Can you set the env variable to the Globus folder and try again.

```
export GLOBUS_LOCATION=/Library/Globus
```

**Comment by euhruska** [comment]
Alright, connected and running
