### ISSUE TITLE
Job submission error when using 16 nodes on Wrangler

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1554]
When I submit a 16 node job on Wrangler we get the following error at `umgr.0000.staging.input.0.child.log`:

```
2018-02-04 20:33:17,572: umgr.0000.staging.input.0.child: umgr.0000.staging.input.0       : MainThread     : DEBUG   :  === sbox: gsisftp://wrangler.tacc.utexas.edu:2222/work/03170/tg824689/wrangler/radical.pilot.sandbox/Test384cores [<class 'saga.url.Url'>]
2018-02-04 20:33:17,572: umgr.0000.staging.input.0.child: umgr.0000.staging.input.0       : MainThread     : DEBUG   :  === copy: file://localhost//tmp/rp_agent_tar_dirJO8k6Y/Test384cores.umgr.0000.staging.input.0.child.tgz -> gsisftp://wrangler.tacc.utexas.edu:2222/work/03170/tg824689/wrangler/radical.pilot.sandbox/Test384cores/Test384cores.umgr.0000.staging.input.0.child.tgz
2018-02-04 20:33:21,385: umgr.0000.staging.input.0.child: umgr.0000.staging.input.0       : MainThread     : DEBUG   :  === js  : slurm+gsissh://wrangler.tacc.utexas.edu:2222/
2018-02-04 20:33:29,817: umgr.0000.staging.input.0.child: umgr.0000.staging.input.0       : MainThread     : ERROR   : worker <bound method Default.work of <Default(umgr.0000.staging.input.0, started)>> failed
Traceback (most recent call last):
  File "/home/iparask/miniconda2/envs/rp0.47/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1265, in work_cb
    self._workers[state](things)
  File "/home/iparask/miniconda2/envs/rp0.47/lib/python2.7/site-packages/radical/pilot/umgr/staging_input/default.py", line 272, in work
    j   = js_tmp.run_job(cmd)
  File "/home/iparask/miniconda2/envs/rp0.47/lib/python2.7/site-packages/saga/job/service.py", line 344, in run_job
    job.run()
  File "/home/iparask/miniconda2/envs/rp0.47/lib/python2.7/site-packages/saga/job/job.py", line 478, in run
    return self._adaptor.run (ttype=ttype)
  File "/home/iparask/miniconda2/envs/rp0.47/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/iparask/miniconda2/envs/rp0.47/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 1216, in run
    self._id      = self.js._job_run(self.jd)
  File "/home/iparask/miniconda2/envs/rp0.47/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 540, in _job_run
    " sbatch output:\n%s" % out)
NoSuccess: Couldn't get job id from submitted job! sbatch output:
-----------------------------------------------------------------
          Welcome to Wrangler at TACC
-----------------------------------------------------------------

--> Submission error: all jobs must have a queue name specified with "-p"

removed ‘tmp_MNLIAp.slurm’
 (/home/iparask/miniconda2/envs/rp0.47/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py +540 (_job_run)  :  " sbatch output:\n%s" % out))
2018-02-04 20:33:29,817: umgr.0000.staging.input.0.child: umgr.0000.staging.input.0       : MainThread     : DEBUG   : advance bulk size: 384 [False, True]
```

**Comment by andre-merzky** [comment]
Do you see that *not* happening with a different number of nodes?

**Comment by andre-merzky** [comment]
There is no ORTE config defined for wrangler - what config are you using exactly?

**Comment by iparask** [comment]
I do not see it up to 4 nodes for sure. I am using one I have created. It can be found: `/home/iparask/miniconda2/envs/rp0.47/lib/python2.7/site-packages/radical/pilot/configs` on radical two.

Also I have a reservation on Wrangler up to 32 nodes. The config file in the `WeakScalingUpTo32Nodes` can provide the project number with the reservation, if you want to give it a try.

**Comment by andre-merzky** [comment]
what is the number of CUs you use for the 4-node and 16-node runs?  

Either way though: please try `fix/issue_1554` and let me know if that helps.

**Comment by iparask** [comment]
It is equal to the number of cores I acquire. Each Wrangler node has 24 cores. Will do and get back at you.

**Comment by iparask** [comment]
It does work! If I introduce the same changes to my ve in the same files it should be okay right?

**Comment by andre-merzky** [comment]
Depends what you mean with 'ok'...  It needs  fixing in devel to get into the release eventually.

**Comment by iparask** [comment]
It worked like a charm!
