### ISSUE TITLE
Agent1 attempts to access $HOME on Titan and fails 

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1566]
I am running the RP getting started example on Titan using the following stack:
```
> radical-stack

  python               : 2.7.9
  pythonpath           : /sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /autofs/nccs-svm1_home1/vivekb/ves/test-htbac

  radical.entk         : 0.6.0
  radical.pilot        : 0.47.1
  radical.utils        : 0.47.1
  saga                 : 0.47
```

Error in agent_1:
```
2018-02-23 10:39:43,082: radical.saga        : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.9 (default, May 6 2016, 10:34:30) [GCC 4.9.0 20140422 (Cray Inc.)]
2018-02-23 10:39:43,084: radical.saga        : MainProcess                     : MainThread     : INFO    :                      pid: 20561
2018-02-23 10:39:43,084: radical.saga        : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2018-02-23 10:39:43,084: radical.saga        : MainProcess                     : MainThread     : INFO    : radical.saga         version: 0.47
2018-02-23 10:39:43,327: radical.pilot       : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.9 (default, May 6 2016, 10:34:30) [GCC 4.9.0 20140422 (Cray Inc.)]
2018-02-23 10:39:43,327: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      pid: 20561
2018-02-23 10:39:43,327: radical.pilot       : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
Traceback (most recent call last):
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/bin/radical-pilot-agent", line 26, in <module>
    rp.agent.bootstrap_3(agent_name)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/bootstrap_3.py", line 44, in bootstrap_3
    agent = Agent_n(agent_name)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_n.py", line 60, in __init__
    session = rp_Session(cfg=session_cfg, _connect=False)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/session.py", line 148, in __init__
    rs.Session.__init__(self)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/saga/session.py", line 176, in __init__
    simple_base.__init__ ()
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/saga/base.py", line 37, in __init__
    self._id     = ru.generate_id (self._get_apitype (), mode=ru.ID_SIMPLE)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/ids.py", line 181, in generate_id
    return _generate_id(template, prefix, namespace)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/ids.py", line 198, in _generate_id
    os.makedirs(state_dir)
  File "/lustre/atlas2/csc230/world-shared/ve.rp.titan.20017.10.06/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/lustre/atlas2/csc230/world-shared/ve.rp.titan.20017.10.06/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/lustre/atlas2/csc230/world-shared/ve.rp.titan.20017.10.06/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: '/ccs/home/vivekb'
```

Then the client simply waits for the submitted units to finish and they never do.

Logfiles attached.
[rp.session.titan-ext2.vivekb.017585.0005.zip](https://github.com/radical-cybertools/radical.pilot/files/1752254/rp.session.titan-ext2.vivekb.017585.0005.zip)

**Comment by itomaldonado** [comment]
I think this is a similar issue that we saw in AdaptiveMD. Where saga tries to create an id for the Agent_1 and it fails because it has no access to the ${HOME}.

Here is the line in `agent_1.err` that makes me think that:

```
Traceback (most recent call last):
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/bin/radical-pilot-agent", line 26, in <module>
    rp.agent.bootstrap_3(agent_name)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/bootstrap_3.py", line 44, in bootstrap_3
    agent = Agent_n(agent_name)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_n.py", line 60, in __init__
    session = rp_Session(cfg=session_cfg, _connect=False)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/session.py", line 148, in __init__
    rs.Session.__init__(self)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/saga/session.py", line 176, in __init__
    simple_base.__init__ ()
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/saga/base.py", line 37, in __init__
    self._id     = ru.generate_id (self._get_apitype (), mode=ru.ID_SIMPLE)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/ids.py", line 181, in generate_id
    return _generate_id(template, prefix, namespace)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext2.vivekb.017585.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/ids.py", line 198, in _generate_id
    os.makedirs(state_dir)
  File "/lustre/atlas2/csc230/world-shared/ve.rp.titan.20017.10.06/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/lustre/atlas2/csc230/world-shared/ve.rp.titan.20017.10.06/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/lustre/atlas2/csc230/world-shared/ve.rp.titan.20017.10.06/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: '/ccs/home/vivekb'
```

**Comment by andre-merzky** [comment]
And its likely the same fix, which lives in this pull request: radical-cybertools/radical.utils/pull/131

**Comment by andre-merzky** [comment]
Thanks Manuel - that PR is now merged in RU devel.

**Comment by vivek-bala** [comment]
I followed up on RU devel merge. I ran the RP getting started example with 64 units. I get a different error now. Some of the units fails with:
```
touch: missing file operand
Try `touch --help' for more information.

GThread-ERROR **: file gthread-posix.c: line 367 (g_thread_create_posix_impl): error 'No space left on device' during 'pthread_create'
aborting...
/autofs/nccs-svm1_sw/xk6/xalt/0.7.5/bin/xalt_helper_functions.sh: line 175: 17604 Aborted                 $MY_CMD "$@"
```

I see the following in the executor log:

```
2018-02-23 16:50:39,896: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : INFO    : Launching unit unit.000028 via /lustre/atlas2/csc190/scratch/vivekb/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017585.0012/pilot.0000/unit.000028/unit.000028.sh in /lustre/atlas2/csc190/scratch/vivekb/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017585.0012/pilot.0000/unit.000028
2018-02-23 16:50:39,899: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017585.0012/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 193, in _handle_unit
    self.spawn(launcher=launcher, cu=cu)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017585.0012/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 351, in spawn
    creationflags      = 0)
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017585.0012/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/atfork/atfork.py", line 182, in os_fork_wrapper
    pid = _orig_os_fork()
OSError: [Errno 28] No space left on device
```

Logfiles attached.
[rp.session.titan-ext3.vivekb.017585.0012.zip](https://github.com/radical-cybertools/radical.pilot/files/1753292/rp.session.titan-ext3.vivekb.017585.0012.zip)

**Comment by vivek-bala** [comment]
@andre-merzky let me know if I should open a new ticket since the original issue seems to be fixed

**Comment by andre-merzky** [comment]
I assume you are runninng with aprun, and are hitting process limits.  is the aprun?  And how many units do you run over what pilot size?
yeah, new issue makes sense - but we probably have a related one open somewhere...

**Comment by vivek-bala** [comment]
Okay, I'll make a new one for now. The original issue is fixed.

**Comment by vivek-bala** [comment]
new ticket for the second issue: https://github.com/radical-cybertools/radical.pilot/issues/1567
