### ISSUE TITLE
Units fail with aprun error on Titan

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1567]
I am using the getting started example with 64 single core units and a pilot of 64 cores. I get the following error:
```
touch: missing file operand
Try `touch --help' for more information.

GThread-ERROR **: file gthread-posix.c: line 367 (g_thread_create_posix_impl): error 'No space left on device' during 'pthread_create'
aborting...
/autofs/nccs-svm1_sw/xk6/xalt/0.7.5/bin/xalt_helper_functions.sh: line 175: 17604 Aborted                 $MY_CMD "$@"
```

with the following in the executor log:
```
2018-02-23 16:50:39,896: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : INFO    : Launching unit unit.000028 via /lustre/atlas2/csc190/scratch/vivekb/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017585.0012/pilot.0000/unit.000028/unit.000028.sh in /lustre/atlas2/csc190/scratch/vivekb/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017585.0012/pilot.0000/unit.000028
2018-02-23 16:50:39,899: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017585.0012/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 193, in _handle_unit
    self.spawn(launcher=launcher, cu=cu)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017585.0012/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 351, in spawn
    creationflags      = 0)
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017585.0012/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/atfork/atfork.py", line 182, in os_fork_wrapper
    pid = _orig_os_fork()
OSError: [Errno 28] No space left on device
```

Stack used:
```
> radical-stack

  python               : 2.7.9
  pythonpath           : /sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
  virtualenv           : /lustre/atlas1/bip149/scratch/vivekb/test-htbac/ve-htbac

  radical.pilot        : 0.47.1
  radical.utils        : 0.47.1-v0.47.1-4-g7f65216@devel
  saga                 : 0.47
```

Logfiles attached
[rp.session.titan-ext3.vivekb.017585.0012.zip](https://github.com/radical-cybertools/radical.pilot/files/1753438/rp.session.titan-ext3.vivekb.017585.0012.zip)

**Comment by vivek-bala** [comment]
I run 64 single core units and only 14 succeed.

**Comment by andre-merzky** [comment]
```
pid = _orig_os_fork()
OSError: [Errno 28] No space left on device
```

you are using aprun and are running out of processes.  Can you switch to ORTE?

**Comment by shantenujha** [comment]
64 units on 64 cores and running out of processes. @andre-merzky  surely, that is not expected behaviour?

@vivek-bala to reduce can you also reduce the scale of your runs  to avoid running out of processes?

**Comment by vivek-bala** [comment]
@andre-merzky Yes, I was suspecting the same. I was under the impression that the aprun limit was ~80. Maybe that changed? I will test with 16 units for now.

@andre-merzky @shantenujha I was testing in the context of HT-BAC where there are 32-65 concurrent tasks (per protocol) at any given point. With the previously known aprun limit, this issue shouldn't have come up. Andre, you are right though, since they have to build against ORTE if they want to scale the number of protocols.

**Comment by vivek-bala** [comment]
Tried the same example with 16 units. Similar issue where 3 units fail:
```
> cat /lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext3.vivekb.017588.0011/pilot.0000/unit.0000*/STDERR                                          
touch: missing file operand
Try `touch --help' for more information.
touch: missing file operand
Try `touch --help' for more information.
touch: missing file operand
Try `touch --help' for more information.
touch: missing file operand
Try `touch --help' for more information.
touch: missing file operand
Try `touch --help' for more information.
touch: missing file operand
Try `touch --help' for more information.
touch: missing file operand
Try `touch --help' for more information.
touch: missing file operand
Try `touch --help' for more information.
touch: missing file operand
Try `touch --help' for more information.
XALT_EXCEPTION(xalt_run_submission.py):  [Errno 28] No space left on device
touch: missing file operand
Try `touch --help' for more information.
touch: missing file operand
Try `touch --help' for more information.
touch: missing file operand
Try `touch --help' for more information.
sh: fork: No space left on device
XALT_EXCEPTION(xalt_run_submission.py):  [Errno 28] No space left on device
touch: missing file operand
Try `touch --help' for more information.
touch: missing file operand
Try `touch --help' for more information.

GThread-ERROR **: file gthread-posix.c: line 367 (g_thread_create_posix_impl): error 'No space left on device' during 'pthread_create'
aborting...
/autofs/nccs-svm1_sw/xk6/xalt/0.7.5/bin/xalt_helper_functions.sh: line 175: 21471 Aborted                 $MY_CMD "$@"
touch: missing file operand
Try `touch --help' for more information.
/autofs/nccs-svm1_sw/xk6/xalt/0.7.5/bin/xalt_helper_functions.sh: fork: No space left on device
touch: missing file operand
Try `touch --help' for more information.
/autofs/nccs-svm1_sw/xk6/xalt/0.7.5/bin/xalt_helper_functions.sh: fork: No space left on device
```

It seems like the the number of concurrent aprun limits might have been reduced to 13. @andre-merzky would you be able to verify this with ORNL?

**Comment by andre-merzky** [comment]
Yeah, I'll open a ticket to check.

The `touch` errors are unrelated though - they result from an invalid shell command when `RADICAL_PROFILE` is not set, but it should not influence process startup.  This is fixed in some branch already.

**Comment by andre-merzky** [comment]
Ticket is open.

**Comment by andre-merzky** [comment]
Support replied that the aprun limit on titan is 50 right now.  While we fail on a number lower than that, we'll leave this limit alone for now, as we have more pressing issues, unfortunately ...
