### ISSUE TITLE
Pilot fails on BW with "Insufficient system resources"

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1569]
My `radical-stack` is:

```
  python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/scm177/VirtualEnvs/EnTK0.6_env

  radical.analytics    : v0.45.2-101-g8358b08@devel
  radical.entk         : 0.6.0-entk-0.5-284-g114574c@master
  radical.pilot        : 0.47.1
  radical.utils        : 0.47.1
  saga                 : 0.47-v0.46-36-g307daeb7@devel

```

The error is as follows:

```
2018-02-25 23:03:36,542: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot p[30/1873] state: FAILED
2018-02-25 23:03:36,542: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
2018-02-25 23:03:36,617: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-02-25 23:03:36,617: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 242, in run
    self._resource_manager._submit_resource_request()
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 319, in _submit_resource_reque
st
    raise Exception
Exception

2018-02-25 23:03:36,617: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2018-02-25 23:03:36,617: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : ERROR   : Could not terminate wfprocessor process
Traceback (most recent call last):
  File "run.py", line 68, in <module>
    appman.run() # Run the Application Manager
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 433, in run
    self._wfp.end_processor()
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 645, in end_processor
    self._logger.debug('Attempting to end WFprocessor... event: %s' % self._wfp_terminate.is_set())
AttributeError: 'WFprocessor' object has no attribute '_wfp_terminate'
(EnTK0.6_env) scm177@two:~/RepEx3.0/src/radical/repex$ 2018-02-25 23:03:48,836: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : WARN
ING : monitoring channel noise: Shared connection to bw.ncsa.illinois.edu closed.
2018-02-25 23:03:48,837: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : ERROR   : Exception in job monitoring thread: Insufficient
system resources: Insufficient system resources: read from process failed '[Errno 5] Input/output error' : (RUNNING:
25924.0:DONE:0
27446.0:RUNNING:
27446.0:DONE:0
2033.0:RUNNING:
2033.0:DONE:0
58520.0:RUNNING:
58520.0:DONE:0
11882.0:RUNNING:
11882.0:DONE:0
48647.0:RUNNING:
48647.0:DONE:0
Shared connection to bw.ncsa.illinois.edu closed.
) (()) (/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +64 (translate_exception)  :  e = se.NoSuccess ("
Insufficient system resources: %s" % cmsg))
2018-02-25 23:03:48,837: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : ERROR   : Cancel job monitoring for gsissh://bw.ncsa.illino
is.edu

```

Logfiles are attached here: 
[session_logfiles.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/1756775/session_logfiles.tar.gz)

**Comment by SrinivasMushnoori** [comment]
I see, my apologies. Should I close, and reopen on EnTK?

**Comment by andre-merzky** [comment]
No need to apologize.  Lets wait for Vivek to chime in before we move the ticket, he might have a different opinion.

**Comment by vivek-bala** [comment]
I think the error is coming from the saga layer? See below:
```
2018-02-25 23:03:48,837: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : ERROR   : Exception in job monitoring thread: Insufficient
system resources: Insufficient system resources: read from process failed '[Errno 5] Input/output error' : (RUNNING:
```
@SrinivasMushnoori Can you check if there are any stray RP process on BW? (ps faux | grep <username> | grep rp)
I have faced a similar error in that scenario. Otherwise I am not too sure what the source of the error is.

Agreed that the error reporting is not too informative.

**Comment by SrinivasMushnoori** [comment]
BW is down for maintenance today, I believe. It should be up tomorrow, I'll check and report back here.

**Comment by andre-merzky** [comment]
@vivek-bala : well, maybe SAGA - but that's popping up like 10 seconds later, during termination, isn't it?  But yeah, maybe we are generally running into system limits here, not sure.

**Comment by SrinivasMushnoori** [comment]
```ps faux | grep | grep rp```

gives me 

```
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
```

Trying ```ps faux | grep rp```

does seem to have some processes. But they're all controlled by root and I cannot kill them.

**Comment by SrinivasMushnoori** [comment]
Jobs on BW now fail with
```
2018-03-14 18:17:43,966: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : INFO    : Job monitoring thread updating Job [torque+gsissh://bw.ncsa.illinois.edu]-[8311178] (old state: Pending, new state: Failed)
2018-03-14 18:17:49,904: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: FAILED
2018-03-14 18:17:49,905: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
2018-03-14 18:17:49,913: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-03-14 18:17:49,913: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 240, in run
    self._resource_manager._submit_resource_request()
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 319, in _submit_resource_request
    raise Exception
Exception

2018-03-14 18:17:49,913: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2018-03-14 18:17:49,913: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : ERROR   : Could not terminate wfprocessor process
Traceback (most recent call last):
  File "run.py", line 75, in <module>
    appman.run() # Run the Application Manager 
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 425, in run
    self._wfp.end_processor()
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 641, in end_processor
    self._logger.debug('Attempting to end WFprocessor... event: %s' % self._wfp_terminate.is_set())
AttributeError: 'WFprocessor' object has no attribute '_wfp_terminate'
(EnTK0.6_env) scm177@two:~/RepEx3.0/src/radical/repex$ 2018-03-14 18:18:02,066: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : WARNING : monitoring channel noise: Shared connection to bw.ncsa.illinois.edu closed.
```
After remaining in "Pending" state for some time. 

Session logfiles are [here](https://github.com/radical-cybertools/radical.pilot/files/1812286/session.tar.gz)

**Comment by andre-merzky** [comment]
Hmm, I don't think that is the same issue.  Am I missing something?  This seems to fall squarely into the EnTK court.  @vivek-bala: any opinion?

**Comment by vivek-bala** [comment]
I think we will need the logs from the agent side as well. Possibly not the same issue. The msg in the pmgr launcher reads:
```
2018-03-14 18:17:39,890: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : pmgr.0000.launching.0.child.idler._pilot_watcher_cb: DEBUG   : saga job state: pilot.0000 Pending
2018-03-14 18:17:49,903: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : pmgr.0000.launching.0.child.idler._pilot_watcher_cb: DEBUG   : bulk states: ['Failed']
```

**Comment by SrinivasMushnoori** [comment]
I believe agent side logs are already in the uploaded tarball. I did a `radicalpilot-fetch-logfiles` , as far as I understand, that pulls the agent side logs. Please confirm. If required, I can reproduce this issue and upload the files again.

**Comment by vivek-bala** [comment]
Well, maybe there are no agent side files on the remote. Can you check if you have any bootstrap files on remote though? I am not sure if they are fetched by that command.

I do see the following error in the pmgr launcher, but I think it might be related to termination and not the pilot failure:
```
pmgr.0000.launching.0.child.log:2018-03-14 18:18:03,266: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : finalization error
pmgr.0000.launching.0.child.log:2018-03-14 18:18:03,266: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : finalization error
pmgr.0000.launching.0.child.log:2018-03-14 18:18:03,266: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : finalization error: RuntimeError('finalize: RuntimeError(\'finalize: read from process failed \\\'[Errno 5] Input/output error\\\' : (4372e312e7461722e677a0a7261646963616c2e7574696c732d302e34372e312e7461722e677a0a736167612d707974686f6e2d302e34372d76302e34362d33362d6733303764616562372d646576656c2e7461722e677a0a\\nPROMPT-0->\\n\\nOK\\n\\nPROMPT-0->\\n\\nShared connection to bw.ncsa.illinois.edu closed.\\n)
```

**Comment by SrinivasMushnoori** [comment]
Okay. Let me try to reproduce it, and upload the complete pilot sandbox + agent/client logs.

**Comment by SrinivasMushnoori** [comment]
It's back to failing with this:
```
2018-03-15 15:21:15,251: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: FAILED
2018-03-15 15:21:15,251: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
2018-03-15 15:21:15,261: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-03-15 15:21:15,261: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 240, in run
    self._resource_manager._submit_resource_request()
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 319, in _submit_resource_request
    raise Exception
Exception

2018-03-15 15:21:15,261: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2018-03-15 15:21:15,261: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : ERROR   : Could not terminate wfprocessor process
Traceback (most recent call last):
  File "run.py", line 75, in <module>
    appman.run() # Run the Application Manager 
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 425, in run
    self._wfp.end_processor()
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 641, in end_processor
    self._logger.debug('Attempting to end WFprocessor... event: %s' % self._wfp_terminate.is_set())
AttributeError: 'WFprocessor' object has no attribute '_wfp_terminate'
(EnTK0.6_env) scm177@two:~/RepEx3.0/src/radical/repex$ 2018-03-15 15:21:27,515: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : WARNING : monitori
ng channel noise: Shared connection to bw.ncsa.illinois.edu closed.
2018-03-15 15:21:27,516: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : ERROR   : Exception in job monitoring thread: Insufficient system resourc
es: Insufficient system resources: read from process failed '[Errno 5] Input/output error' : (RUNNING: 
11882.0:DONE:0   
48647.0:RUNNING: 
48647.0:DONE:0   
56068.0:RUNNING: 
56068.0:DONE:0   
4584.0:RUNNING: 
4584.0:DONE:0   
34008.0:RUNNING: 
34008.0:DONE:0   
52194.0:RUNNING: 
52194.0:DONE:0   
Shared connection to bw.ncsa.illinois.edu closed.
) (()) (/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +64 (translate_exception)  :  e = se.NoSuccess ("Insufficient s
ystem resources: %s" % cmsg))
2018-03-15 15:21:27,516: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : ERROR   : Cancel job monitoring for gsissh://bw.ncsa.illinois.edu
```


Logfiles are [here](https://github.com/radical-cybertools/radical.pilot/files/1816003/BW_session_logfiles.tar.gz)
Session sandbox is [here](https://github.com/radical-cybertools/radical.pilot/files/1816004/BW_session_sandbox.tar.gz)

**Comment by SrinivasMushnoori** [comment]
Hi, gentle ping @vivek-bala @andre-merzky

**Comment by andre-merzky** [comment]
Hey Srinivas - thanks for the ping.  This problem is caused by an invalid pilot virtualenv on BW.  Please do the following:

```
$ cd /mnt/c/scratch/sciteam/mushnoor/radical.pilot.sandbox/
$ rm -rf ve.ncsa.bw_aprun.0.47.1
$ wget https://raw.githubusercontent.com/radical-cybertools/radical.pilot/feature/create_ve/bin/radicalpilot-create-static-ve
$ /bin/sh radicalpilot-create-static-ve ve.ncsa.bw_aprun.0.47.1 bw
```

and run again.

**Comment by SrinivasMushnoori** [comment]
Thanks, I just tested this and it has resolved the issue.
