### ISSUE TITLE
ZMQ error on Titan

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1570]
I've created a venv on Titan. Python points the following path

```
(rp_venv_processes)jdakka@titan-ext1:/lustre/atlas2/chm126/scratch/jdakka/radical.pilot> echo $PYTHONPATH
/lustre/atlas2/chm126/scratch/jdakka/rp_venv_processes/lib/python2.7/site-packages:/sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_virtualenv/12.0.7/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_pip/8.1.2/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib64/python2.7/site-packages:/sw/xk6/python_setuptools/21.0/python2.7.9/lib/python2.7/site-packages:/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/lustre/atlas/sw/xk7/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages:/sw/xk6/xalt/0.7.5/site:/sw/xk6/xalt/0.7.5/libexec
```

After I installed the stack using `pip install . --upgrade` it still doesn't show `RP`

```
virtualenv           : /lustre/atlas2/chm126/scratch/jdakka/rp_venv_processes
radical.utils        : 0.47.1-v0.47.1@master
saga                 : 0.47-v0.46-34-g0f186f66@master
```
When I tried to import `rp` I get:

```
>>> import radical.pilot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustre/atlas2/chm126/scratch/jdakka/rp_venv_processes/lib/python2.7/site-packages/radical/pilot/__init__.py", line 23, in <module>
    from .session                   import Session
  File "/lustre/atlas2/chm126/scratch/jdakka/rp_venv_processes/lib/python2.7/site-packages/radical/pilot/session.py", line 29, in <module>
    from . import utils         as rpu
  File "/lustre/atlas2/chm126/scratch/jdakka/rp_venv_processes/lib/python2.7/site-packages/radical/pilot/utils/__init__.py", line 24, in <module>
    from .queue        import *
  File "/lustre/atlas2/chm126/scratch/jdakka/rp_venv_processes/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 4, in <module>
    import zmq
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /sw/xk6/python/2.7.9/sles11.3_gnu4.3.4/lib/python2.7/site-packages/zmq/backend/cython/error.so: undefined symbol: zmq_strerror
```

I did `pip install pyzmq --upgrade` without any luck. 

I have the following modules loaded:

```
python/2.7.9
python_setuptools/21.0
python_pip/8.1.2
python_virtualenv/12.0.7
```

**Comment by jdakka** [comment]
Solved:
Needed to use the `devel` stack of `radical.utils`

**Comment by itomaldonado** [comment]
For future reference, this was also needed in the `~/.bashrc`

```
export LD_PRELOAD=/lib64/librt.so.1
module unload PrgEnv-pgi
module load   PrgEnv-gnu
module load   tmux
module load   python
module load   python_pip
module load   python_virtualenv
```
