### ISSUE TITLE
VE creation fails on BW

### ISSUE THREAD

**Issue by kristofarkas** [radical-cybertools/radical.pilot#1606]
This error might be due to continuous changes in the python installation on BW, but the current master stack or radical gives an error when submitting a job remotely.

This is in `bootstrap_1.out`:

```
# -------------------------------------------------------------------
#
# Create virtualenv
# cmd: /sw/bw/bwpy/mnt/bin/python virtualenv-1.9/virtualenv.py /mnt/c/scratch/sciteam/farkaspa/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.47.10
#
Failed to import the site module
Traceback (most recent call last):
  File "/mnt/c/scratch/sciteam/farkaspa/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.47.10/lib/python3.5/site.py", line 67, in <module>
    import os
  File "/mnt/c/scratch/sciteam/farkaspa/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.47.10/lib/python3.5/os.py", line 708, in <module>
    from _collections_abc import MutableMapping
ImportError: No module named '_collections_abc'
Using base prefix '/mnt/bwpy/single/usr/lib/python-exec/python3.5/../../..'
New python executable in /mnt/c/scratch/sciteam/farkaspa/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.47.10/bin/python
ERROR: The executable /mnt/c/scratch/sciteam/farkaspa/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.47.10/bin/python is not functioning
ERROR: It thinks sys.prefix is '/mnt/c/scratch/sciteam/farkaspa/radical.pilot.sandbox/rp.session.julian.chem.ucl.ac.uk.kristof.farkas-pall.017640.0019/pilot.0000' (should be '/mnt/c/scr
atch/sciteam/farkaspa/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.47.10')
ERROR: virtualenv is not compatible with this system or executable
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
ERROR: Couldn't create virtualenv
Error on virtenv creation -- abort
```

Could it be because the default `bwpy` is python3 now?

Stack:
```
  radical.entk         : 0.6.1-entk-0.5-309-gc2bb40b@master
  radical.pilot        : 0.47.10-v0.47.10@master
  radical.utils        : 0.47.4-merge-pre_gpu@master
  saga                 : 0.47.3-merge-pre_gpu@master
```

**Comment by kristofarkas** [comment]
Okay, I'll close this as there a number of other open tickets with this same underlying issue. Current fix is to install own VE.
