### ISSUE TITLE
Devel branch fails on SuperMIC

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1613]
The error I see is here:
```
2018-05-08 16:19:48,441: radical.saga.cpi    : pmgr.0000.launching.0           : MainThread     : INFO    : ssh copy  mode set to 'sftp'
2018-05-08 16:19:48,441: radical.saga.cpi    : pmgr.0000.launching.0           : MainThread     : INFO    : ssh share mode set to 'auto'
2018-05-08 16:19:48,442: radical.saga.cpi    : pmgr.0000.launching.0           : MainThread     : INFO    : ssh timeout    set to '2000.0'
2018-05-08 16:19:49,419: radical.saga.cpi    : pmgr.0000.launching.0           : MainThread     : INFO    : PTY prompt pattern: [\$#%>\]]\s*$
2018-05-08 16:19:49,420: radical.saga.cpi    : pmgr.0000.launching.0           : MainThread     : INFO    : ssh copy  mode set to 'sftp'
2018-05-08 16:19:49,421: radical.saga.cpi    : pmgr.0000.launching.0           : MainThread     : INFO    : ssh share mode set to 'auto'
2018-05-08 16:19:49,421: radical.saga.cpi    : pmgr.0000.launching.0           : MainThread     : INFO    : ssh timeout    set to '2000.0'
2018-05-08 16:19:53,719: radical.saga.cpi    : pmgr.0000.launching.0           : MainThread     : INFO    : Found PBS version: version: 3.0.6
2018-05-08 16:19:53,957: radical.saga.cpi    : pmgr.0000.launching.0           : MainThread     : INFO    : Found PBS qdel: /usr/local/bin/qdel
2018-05-08 16:19:54,197: radical.saga.cpi    : pmgr.0000.launching.0           : MainThread     : INFO    : Found PBS qsub: /usr/local/bin/qsub
2018-05-08 16:19:54,435: radical.saga.cpi    : pmgr.0000.launching.0           : MainThread     : INFO    : Found PBS pbsnodes: /usr/local/bin/pbsnodes
2018-05-08 16:19:54,673: radical.saga.cpi    : pmgr.0000.launching.0           : MainThread     : INFO    : Found PBS qstat: /usr/local/bin/qstat
2018-05-08 16:19:55,307: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: FAILED
2018-05-08 16:19:55,308: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
2018-05-08 16:19:55,314: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-05-08 16:19:55,315: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 252, in run
    self._resource_manager._submit_resource_request()
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 319, in _submit_resource_request
    raise Exception
Exception

2018-05-08 16:19:55,315: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2018-05-08 16:19:55,315: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : ERROR   : Could not terminate wfprocessor process
Traceback (most recent call last):
  File "run.py", line 87, in <module>
    appman.run() # Run the Application Manager 
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 443, in run
    self._wfp.end_processor()
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 601, in end_processor
    self._logger.debug('Attempting to end WFprocessor... event: %s' % self._wfp_terminate.is_set())
AttributeError: 'WFprocessor' object has no attribute '_wfp_terminate'
(EnTK0.6_env) scm177@two:~/RepEx3.0/src/radical/repex$ 2018-05-08 16:20:07,519: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-1       : WARNING : monitoring channel noise: Shared connection to supermic.cct-lsu.xsede.org closed.
```

My `radical-stack` is:

```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/EnTK0.6_env

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.6.2-0.6.2-1-g81da461@master
  radical.pilot        : 0.47.10-v0.47.10-164-g9dd427ce@devel
  radical.utils        : 0.47.4-merge-pre_gpu-14-ga2181d6@devel
  saga                 : 0.47.3-merge-pre_gpu@master

```

Logfiles are [here](https://github.com/radical-cybertools/radical.pilot/files/1984302/devel_fail.tar.gz)

**Comment by andre-merzky** [comment]
I will let @vivek-bala have the first look on this one.

**Comment by vivek-bala** [comment]
See the error in the pmgr launcher:
```
2018-05-08 16:19:55,306: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 489, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 688, in _start_pilot_bulk
    jc.add(js.create_job(jd))
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/saga/job/service.py", line 281, in create_job
    default = jd_default.get_attribute (key)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/saga/attributes.py", line 2353, in get_attribute
    return   self._attributes_i_get        (us_key, _flow)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/saga/attributes.py", line 1144, in _attributes_i_get
    d = self._attributes_t_init (key)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/saga/attributes.py", line 406, in _attributes_t_init
    raise se.DoesNotExist ("attribute key is invalid: %s"  %  (key))
DoesNotExist: attribute key is invalid: total_gpu_count (/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/saga/attributes.py +406 (_attributes_t_init)  :  raise se.DoesNotExist ("attribute key is invalid: %s"  %  (key)))

```

I think you are using the GPU branch of RP. You might want to use master of RP.

**Comment by SrinivasMushnoori** [comment]
@vivek-bala I believe the point of this experiment was in response to @andre-merzky 's email the other day about running some tests using devel and reporting any failures...

**Comment by vivek-bala** [comment]
Ah okay, you will probably have to use the gpu branch of saga as well in that case.

**Comment by SrinivasMushnoori** [comment]
I see. My apologies for the gaffe. I'll repeat the experiment and upload logs if it fails.

**Comment by iparask** [comment]
This is resolved. SAGA accepts now a `total_gpu_count` key in the job description.
