### ISSUE TITLE
RP devel fails locally with error in launch method

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1637]
I am using the devel stack and running the RP getting_started example. I get the following error in the agent_0.log:

```
2018-06-18 16:52:56,811: agent_0             : agent_0.executing.0             : MainThread     : ERROR   : LaunchMethod cannot be used: [Errno 2] No such file or directory!
Traceback (most recent call last):
  File "/home/vivek/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017700.0015/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 133, in create
    return impl(cfg, session)
  File "/home/vivek/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017700.0015/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/mpirun.py", line 19, in __init__
    LaunchMethod.__init__(self, cfg, session)
  File "/home/vivek/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017700.0015/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 68, in __init__
    self._configure()
  File "/home/vivek/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017700.0015/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/mpirun.py", line 33, in _configure
    self.mpi_version, self.mpi_flavor = self._get_mpi_info(self.launch_command)
  File "/home/vivek/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017700.0015/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 325, in _get_mpi_info
    out, err, ret = ru.sh_callout('%s -v' % exe)
  File "/home/vivek/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017700.0015/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/misc.py", line 592, in sh_callout
    p = sp.Popen(cmd, stdout=sp.PIPE, stderr=sp.PIPE, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

All the unit folders are created, but are empty. Let me know how I can help debug.

**Comment by andre-merzky** [comment]
Is this actually a fatal error?  The agent seems to be configured to use `mpirun` for MPI units - but on system check, it can't find an `mpirun` executable, thus the error log.  The agent *should*, however, continue to run non-MPI units?

**Comment by andre-merzky** [comment]
PS.: when submitting more than 256 units in a bulk, the unit folders get created as a bulk, even before the units are actually hitting the agent.  I assume this is what you wrt. to those unit folders...

**Comment by vivek-bala** [comment]
Ah you are right. That might not have been fatal. I also have the following in the executing component:
```
2018-06-18 16:52:58,725: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/home/vivek/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017700.0015/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 193, in _handle_unit
    raise RuntimeError("no launcher (process type = %s)" % cpt)
RuntimeError: no launcher (process type = MPI)
2018-06-18 16:52:58,735: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/home/vivek/radical.pilot.sandbox/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017700.0015/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 193, in _handle_unit
    raise RuntimeError("no launcher (process type = %s)" % cpt)
RuntimeError: no launcher (process type = MPI)

..
.. (several more lines of the same error)
```

**Comment by vivek-bala** [comment]
PFA all the logfiles.

[rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017700.0015.zip](https://github.com/radical-cybertools/radical.pilot/files/2113214/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017700.0015.zip)

**Comment by vivek-bala** [comment]
Bump

**Comment by iparask** [comment]
@vivek-bala is trying to run example 00. In [line 92](https://github.com/radical-cybertools/radical.pilot/blob/devel/examples/00_getting_started.py#L92) it setups the units as MPI. If `mpirun` is not installed locally it will fail

**Comment by iparask** [comment]
We should probably include in the documentation that if `MPIRUN` is not present in a local resource example 09 will fail.
