### ISSUE TITLE
RP release on local execution issues

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1638]
I am trying to replicate some of the issues @AymenFJA is facing with RP's release. 

All examples are run locally with GCC python and Anaconda Python. All installations are done by using `pip`.

My release stacks are:
 1. GCC:
```
  python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/iparask/rpRelease

  radical.pilot        : 0.47.14
  radical.utils        : 0.47.5
  saga                 : 0.47.6
```

2. Conda:
```
  python               : 2.7.15
  pythonpath           :
  virtualenv           : RpRelease

  radical.pilot        : 0.47.14
  radical.utils        : 0.47.5
  saga                 : 0.47.6

```
With my GCC python I am getting the following error during the VE creation:
```
purge install source at radical.pilot-0.47.14/
verify python viability: /home/iparask/radical.pilot.sandbox/ve.local.localhost.0.47.14/bin/python ... ok
verify module viability: saga            ... ok
verify module viability: radical.utils   ... ok
verify module viability: pymongo         ... ok
verify module viability: hostlist        ... ok
verify module viability: netifaces       ... ok
verify module viability: setproctitle    ... ok
verify module viability: ntplib          ... ok
verify module viability: msgpack         ...Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named msgpack
 failed
python installation cannot load module msgpack - abort
```

The conda env case runs. In both cases the reporter does not work.

**Comment by andre-merzky** [comment]
For the reporter to work, please set `RADICAL_REPORT=True`

Fir msgpack - can you please enable pip logging to see what's up with that?   Where is the above log from - the bootstrapper output?

**Comment by iparask** [comment]
Yes, I will. This is `bootstrap_1.out`

**Comment by andre-merzky** [comment]
The please try to manually activate the agent VE, and attempt a verbose `pip install ` for the msgpack module.  Can you please send the full bootstrapper out and err files?  `locally` means your laptop? 
 Thanks!

**Comment by AymenFJA** [comment]
Hi, I have tried one of RP examples on local.localhost using (anaconda env) with RADICAL_REPORT=True and it is working

**Comment by iparask** [comment]
Locally, I mean on a JestreamVM running `Ubuntu 16.0.4`. Installing `msgpack` manually succeeded. I also removed the VE and run the example again. This time everything was installed successfully, but I got:
```
2018-06-21 13:03:21,346: update.0.child      : update.0                        : update.0.child.subscriber._state_cb: ERROR   : bulk exec error: {'nModified': 98, 'nUpserted': 0, 'nMatched': 98, 'writeErrors': [{u'index': 98, u'code': 12501, u'errmsg': u'quota exceeded', u'op': SON([('q', {'type': 'unit', 'uid': 'unit.000097'}), ('u', {'$set': {'state': 'UMGR_SCHEDULING_PENDING', 'type': 'unit', 'uid': 'unit.000097'}, '$push': {'states': 'UMGR_SCHEDULING_PENDING'}}), ('multi', True), ('upsert', False)])}], 'upserted': [], 'writeConcernErrors': [], 'nRemoved': 0, 'nInserted': 0}
Traceback (most recent call last):
  File "/home/iparask/rpRelease/local/lib/python2.7/site-packages/radical/pilot/worker/update.py", line 111, in _timed_bulk_execute
    res = self._bulk.execute()
  File "/home/iparask/rpRelease/local/lib/python2.7/site-packages/pymongo/bulk.py", line 587, in execute
    return self.__bulk.execute(write_concern)
  File "/home/iparask/rpRelease/local/lib/python2.7/site-packages/pymongo/bulk.py", line 433, in execute
    return self.execute_command(generator, write_concern)
  File "/home/iparask/rpRelease/local/lib/python2.7/site-packages/pymongo/bulk.py", line 300, in execute_command
    raise BulkWriteError(full_result)
BulkWriteError: batch op errors occurred
2018-06-21 13:03:21,347: update.0.child      : update.0                        : update.0.child.subscriber._state_cb: ERROR   : abort: BulkWriteError('batch op errors occurred',)
Traceback (most recent call last):
  File "/home/iparask/rpRelease/local/lib/python2.7/site-packages/radical/utils/threads.py", line 375, in _run
    if not self.work_cb():
  File "/home/iparask/rpRelease/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1125, in work_cb
    ret = self._cb(topic=topic, msg=m)
  File "/home/iparask/rpRelease/local/lib/python2.7/site-packages/radical/pilot/worker/update.py", line 251, in _state_cb
    self._timed_bulk_execute()
  File "/home/iparask/rpRelease/local/lib/python2.7/site-packages/radical/pilot/worker/update.py", line 111, in _timed_bulk_execute
    res = self._bulk.execute()
  File "/home/iparask/rpRelease/local/lib/python2.7/site-packages/pymongo/bulk.py", line 587, in execute
    return self.__bulk.execute(write_concern)
  File "/home/iparask/rpRelease/local/lib/python2.7/site-packages/pymongo/bulk.py", line 433, in execute
    return self.execute_command(generator, write_concern)
  File "/home/iparask/rpRelease/local/lib/python2.7/site-packages/pymongo/bulk.py", line 300, in execute_command
    raise BulkWriteError(full_result)
BulkWriteError: batch op errors occurred
```

My db is not full.

**Comment by andre-merzky** [comment]
urgh, I have no idea :(  The error can have many causes: out of file descriptors, out of memory, too many collections, etc.  We would need to look into the MongoDB logfiles it seems to check this out.  what DBURL are you using?

**Comment by iparask** [comment]
One I have on Jetstream. Let me see if it is something that I can find why it is happening. Thank you Andre.

**Comment by iparask** [comment]
This has been resolved.
