### ISSUE TITLE
DA_Algorithm branch issues with localhost execution of examples

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1642]
I'm facing issues on localhost execution. Unsure if this should be its own thread, but I find that the pilot sandboxes are empty while running the examples. 

Terminal output:

```
================================================================================                                                                                   [20/637]
 Getting Started (RP version 0.47.14)                                           
================================================================================

new session: [rp.session.two.scm177.017710.0004]                               \
database   : [mongodb://smush:key1209@ds117848.mlab.com:17868/db_repex_1]     ok
read config                                                                   ok

--------------------------------------------------------------------------------
submit pilots                                                                   

create pilot manager                                                          ok
submit 1 pilot(s)
        [local.localhost:1]
                                                                              ok

--------------------------------------------------------------------------------
submit units                                                                    

create unit manager                                                           ok
add 1 pilot(s)                                                                ok
create 8 unit description(s)
        ........                                                              ok
submit 8 unit(s)
        ........                                                              ok

--------------------------------------------------------------------------------
gather results                                                                  

wait for 8 unit(s)
        --------                                                              ok

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.two.scm177.017710.0004                              \
close unit manager                                                            ok
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
+ rp.session.two.scm177.017710.0004 (json)
- pilot.0000 (profiles)
- pilot.0000 (logfiles)
session lifetime: 19.1s                                                       ok

--------------------------------------------------------------------------------

```

`radical-stack` is as follows:

```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/RP_Devel

  radical.pilot        : 0.47.14-v0.47.14-268-g56216caf@project-DA-scheduler_algo
  radical.utils        : 0.47.5
  saga                 : 0.47.6

```

Unable to fetch profiles or logfiles, `radical-pilot-fetch` commands yield the following:

```
(RP_Devel) scm177@two:~/radical.pilot/examples$ radical-pilot-fetch-logfiles rp.session.two.scm177.017710.0004
- pilot.0000 (logfiles)
```
```
(RP_Devel) scm177@two:~/radical.pilot/examples$ radical-pilot-fetch-profiles rp.session.two.scm177.017710.0004                                                             
- pilot.0000 (profiles)
2018-06-28 21:09:55,275: radical.pilot.utils : MainProcess                     : MainThread     : ERROR   : failed to fet profile for pilot.0000
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/RP_Devel/local/lib/python2.7/site-packages/radical/pilot/utils/session.py", line 168, in fetch_profiles
    profiles = sandbox.list('*.prof')
  File "/home/scm177/VirtualEnvs/RP_Devel/local/lib/python2.7/site-packages/saga/namespace/directory.py", line 243, in list
    return self._adaptor.list (pattern, flags, ttype=ttype)
  File "/home/scm177/VirtualEnvs/RP_Devel/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/scm177/VirtualEnvs/RP_Devel/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 473, in list
    % (ret, out))
NoSuccess: failed to list(): (2)(/bin/ls: cannot access '*.prof': No such file or directory
) (/home/scm177/VirtualEnvs/RP_Devel/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +473 (list)  :  % (ret, out)))
```

Sandbox is [here](https://github.com/radical-cybertools/radical.pilot/files/2146649/sandbox.tar.gz)

**Comment by andre-merzky** [comment]
@SrinivasMushnoori , you will have to use the `devel` branches from RU and RS.

**Comment by SrinivasMushnoori** [comment]
I am using `devel` now. Here is my stack:
```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/RP_Master

  radical.pilot        : 0.47.4-merge-pre_gpu-190-gb67c43db@project-DA-scheduler_algo
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
  saga                 : 0.47.6-v0.47.6-35-gf578245a@devel
```

However, I get the following error: 
```
Traceback (most recent call last):
  File "00_getting_started.py", line 37, in <module>
    session = rp.Session()
  File "/home/scm177/VirtualEnvs/RP_Master/local/lib/python2.7/site-packages/radical/pilot/session.py", line 224, in __init__
    self._log.report.info ('<<new session: ')
  File "/home/scm177/VirtualEnvs/RP_Master/local/lib/python2.7/site-packages/radical/utils/logger.py", line 352, in __getattr__
    return getattr(self._logger, attr)
AttributeError: 'Logger' object has no attribute 'report'
```

**Comment by iparask** [comment]
@SrinivasMushnoori , what happened with this issue? Are you still having issues?

**Comment by SrinivasMushnoori** [comment]
This issue has resolved itself with the latest devel branches of saga and utils.
