### ISSUE TITLE
RP Tests Examples Fails

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#1652]
Hello i was trying to run one of the RP examples "01_unit_detailes.py"  on xsede.comet and it keep failing 
```
2018-07-03 11:23:53,621: pmgr.0000           : MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : [Callback]: pilot 'pilot.0000' failed (exit on error)
2018-07-03 11:23:53,635: pmgr.0000           : MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : abort: RuntimeError('pilot pilot.0000 failed - fatal!',)
Traceback (most recent call last):
  File "/home/aymen/miniconda2/envs/conda_env3/lib/python2.7/site-packages/radical/utils/threads.py", line 375, in _run
    if not self.work_cb():
  File "/home/aymen/miniconda2/envs/conda_env3/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1125, in work_cb
    ret = self._cb(topic=topic, msg=m)
  File "/home/aymen/miniconda2/envs/conda_env3/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 296, in _state_sub_cb
    if not self._update_pilot(thing, publish=False):
  File "/home/aymen/miniconda2/envs/conda_env3/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 337, in _update_pilot
    self._pilots[pid]._update(pilot_dict)
  File "/home/aymen/miniconda2/envs/conda_env3/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 184, in _update
    else      : cb(self, self.state)
  File "/home/aymen/miniconda2/envs/conda_env3/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 133, in _default_state_cb
    raise RuntimeError('pilot %s failed - fatal!' % self.uid)
RuntimeError: pilot pilot.0000 failed - fatal!
```

My radical Stack is :
```
python               : 2.7.15
  pythonpath           :
  virtualenv           : conda_env3

  radical.entk         : 0.6.3-0.6.3@master
  radical.pilot        : 0.47.14-v0.47.14@master
  radical.utils        : 0.47.5-v0.47.5@master
  saga                 : 0.47.6-v0.47.6-35-gf5b05e5@fix-issue_676
```

**Comment by andre-merzky** [comment]
Unfortunately, this can have any number of reasons.  I would like to ask you to turn on logging with

```
export RADICAL_PILOT_VERBOSE=DEBUG
export RADICAL_VERBOSE=DEBUG
```

and try again.  You should find a new subdirectory with the name of your session - please create a tarball from it and attach it here.  Assuming you run the example on localhost, you should also find a similar named subdir under `~/radical.pilot.sandbox/`, and within there a `pilot.0000/` subdir - please pack this one up, too, and attach it.

**Comment by AymenFJA** [comment]
Hello @andre-merzky  sorry for the late answer, i have attached both the session tarball and pilot.0000/ subdir 
[pilot.0000.zip](https://github.com/radical-cybertools/radical.pilot/files/2167232/pilot.0000.zip)

[session_logfile.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/2167238/session_logfile.tar.gz)

**Comment by AymenFJA** [comment]
Hello @andre-merzky any updates ?

**Comment by AymenFJA** [comment]
@iparask , same thing :
```
curl -k -L -O 'https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.tar.gz'
```
```
curl: (35) SSL connect error
```
BUT if i execute :
```
curl -1 -k -L -O 'https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.tar.gz'  the ssl connection error problem dissapers 
```
```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1957k  100 1957k    0     0  2403k      0 --:--:-- --:--:-- --:--:-- 2403k
```

**Comment by andre-merzky** [comment]
Hey @AymenFJA - this is surprising, as `-1` should be the default anyway, as it leave the ttls version ujp to negotiation.  Either way, I changed that in branch `fix/issue_1652` now, but before merging, please give that a try, if possible also on some other machines than the one you are using here, and report back on this ticket.  Thank you!

**Comment by AymenFJA** [comment]
The problem was with my anaconda env. we have tried it on @iparask computer before and everything went well, So i had to create new anaconda environment.
using the same radical-stack 

```
python               : 2.7.15
  pythonpath           :
  virtualenv           : conda_env1

  radical.entk         : 0.6.3-0.6.3@master
  radical.pilot        : 0.47.14-v0.47.14@master
  radical.utils        : 0.47.5-v0.47.5@master
  saga                 : 0.47.6-v0.47.6-35-gf5b05e5@fix-issue_676
```


now am using radical-stack 

```
 python               : 2.7.15
  pythonpath           :
  virtualenv           : conda_env1

  radical.entk         : 0.7.3
  radical.pilot        : 0.50.4-v0.50.4-1-gc70a3a55@fix-issue_1679
  radical.utils        : 0.50.1
  saga                 : 0.50.0

```
i am not facing this problem anymore .thanks for the answer @andre-merzky

**Comment by andre-merzky** [comment]
Great, thanks for the ping-back!  I'll be removing that branch then.
