### ISSUE TITLE
RP DA scheduler fails during pilot launch

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1659]
RP DA scheduler fails during pilot launch with following error.
pmgr.0000.launching.0.child.log:
```
2018-07-09 19:05:40,300: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/vivek/Research/ves/test-da-entk/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 485, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/vivek/Research/ves/test-da-entk/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 572, in _start_pilot_bulk
    info = self._prepare_pilot(resource, rcfg, pilot)
  File "/home/vivek/Research/ves/test-da-entk/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 759, in _prepare_pilot
    rcfg[k]  = rcfg[k] % expand
ValueError: unsupported format character ''' (0x27) at index 47
2018-07-09 19:05:43,054: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : abort: KeyboardInterrupt()
Traceback (most recent call last):
  File "/home/vivek/Research/ves/test-da-entk/local/lib/python2.7/site-packages/radical/utils/process.py", line 625, in _run
    if not self.work_cb():
  File "/home/vivek/Research/ves/test-da-entk/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1218, in work_cb
    things = input.get_nowait(1000) # timeout in microseconds
  File "/home/vivek/Research/ves/test-da-entk/local/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 435, in get_nowait
    if _uninterruptible(self._q.poll, flags=zmq.POLLIN, timeout=timeout):
  File "/home/vivek/Research/ves/test-da-entk/local/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 50, in _uninterruptible
    return f(*args, **kwargs)
  File "/home/vivek/Research/ves/test-da-entk/local/lib/python2.7/site-packages/zmq/sugar/socket.py", line 695, in poll
    evts = dict(p.poll(timeout))
  File "/home/vivek/Research/ves/test-da-entk/local/lib/python2.7/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
    PyErr_CheckSignals()
KeyboardInterrupt
```

Stack:
```
$ radical-stack

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/vivek/Research/ves/test-da-entk

  radical.entk         : 0.7.1-0.7.1@feature-tagging
  radical.pilot        : 0.50.1-v0.47.14-319-g01970d8@project-DA-scheduler_algo
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
  saga                 : 0.47.6-v0.47.6-35-gf578245@devel
```

Log files attached.
[rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017721.0242.zip](https://github.com/radical-cybertools/radical.pilot/files/2178366/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017721.0242.zip)

**Comment by iparask** [comment]
Can you provide the session json file or the pilot description you used?

Thank you!

**Comment by vivek-bala** [comment]
Attached zipfile with logfiles and json file from a new run on comet. Same stack used.
[rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017722.0005.zip](https://github.com/radical-cybertools/radical.pilot/files/2180767/rp.session.vivek-HP-Pavilion-m6-Notebook-PC.vivek.017722.0005.zip)

**Comment by iparask** [comment]
So, the reason for this error is that [line 759](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/pmgr/launching/default.py#L759). As it tries to expand the resource configuration it creates an error at the [description of Comet](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_xsede.json#L572) and specifically the single quote that exists there. 

At this point I do not know what is the solution. @andre-merzky can you pick this up? Apparently it stops a part of our development track for the DA scheduler.

**Comment by andre-merzky** [comment]
Yes, I think I need to revert the key expansion from the config files for the time being.  That patch was supposed to address a problem on titan: the default sandbox location points to a path which is *project* dependent, and thus depends on the `project` value of the pilot description.  That conflicts with hardcoding it in the resource config, at least for users with multiple  projects (like @jdakka )...

I'll revert for now, and will have to think of a different approach.

**Comment by andre-merzky** [comment]
The hotfix has been pushed and released.

**Comment by iparask** [comment]
I believe if it does not take into account the `description` of the resource that exists there, it should be okay.  Thank you for the quick fix!!!!
