### ISSUE TITLE
RP 0.50.3 fails on Titan with ORTE launch method

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1663]
I am running a simple hello world task with 1 cpu process and 1 thread per process. I think the possible
values for ```cpu_process_type``` were ```MPI/None``` and for ```cpu_thread_type``` were ```OpenMP/None```. I see that doing a lower() on a Nonetype leads to the following error. Have the possibly values for ```cpu_process_type``` and ```cpu_thread_type``` changed?

```
2018-07-11 12:05:56,689: agent_1.executing.0.child: agent_1.executing.0             : MainThread     : DEBUG   : Launching unit with ORTE (/lustre/atlas2/csc230/world-shared/openmpi/installed/2018_01_16_539f71d/bin/orterun).
2018-07-11 12:05:56,690: agent_1.executing.0.child: agent_1.executing.0             : MainThread     : DEBUG   : Created launch_script: /lustre/atlas2/csc190/scratch/vivekb/radical.pilot.sandbox/rp.session.titan-ext5.vivekb.017723.0005/pilot.0000/unit.000000/unit.000000.sh
2018-07-11 12:05:56,692: agent_1.executing.0.child: agent_1.executing.0             : MainThread     : ERROR   : Error in spawner ('NoneType' object has no attribute 'lower')
Traceback (most recent call last):
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext5.vivekb.017723.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 310, in spawn
    launch_command, hop_cmd = launcher.construct_command(cu, launch_script_name)
  File "/lustre/atlas/scratch/vivekb/csc190/radical.pilot.sandbox/rp.session.titan-ext5.vivekb.017723.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 216, in construct_command
    task_mpi     = bool('mpi' in cud.get('cpu_process_type', '').lower())
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by andre-merzky** [comment]
Hi Vivek,  as a workaround, can you please set `cpu_process_type` to an empty string in the CU description?  Thanks!

**Comment by andre-merzky** [comment]
The CU description defaults are now empty strings instead of `None`, avoiding this problem.
