### ISSUE TITLE
RP 0.50.3 fails on Titan (looking for attribute that doesn't exist) 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1664]
I'm testing a `/bin/hostname` workload in EnTK, [here](https://github.com/radical-cybertools/htbac/blob/fifo_queue/null/entk_2_pipelines_titan.py)

This is the `cpu_req` in `EnTK`:
```
t.cpu_reqs = { 
                            'processes': 1,
                            'process_type': 'MPI',
                            'threads_per_process': 15,
                            'thread_type': None
                        }
```

I set `threads_per_process` to `15` based on discussion [here](https://github.com/radical-cybertools/radical.pilot/issues/1661)

Stack: 

```
 radical.entk         : 0.7.3-0.7.3@master
 radical.pilot        : 0.50.3-v0.50.3@master
 radical.utils        : 0.50.1-v0.50.1-1-gce60836@master
 saga                 : 0.47.6-v0.47.6@master
```
I get the following error from the client:

```
2018-07-11 14:16:37,948: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/jdakka/ve_entk_7_rp_master/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 485, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/autofs/nccs-svm1_home1/jdakka/ve_entk_7_rp_master/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 683, in _start_pilot_bulk
    jc.add(js.create_job(jd))
  File "/autofs/nccs-svm1_home1/jdakka/ve_entk_7_rp_master/lib/python2.7/site-packages/saga/job/service.py", line 281, in create_job
    default = jd_default.get_attribute (key)
  File "/autofs/nccs-svm1_home1/jdakka/ve_entk_7_rp_master/lib/python2.7/site-packages/saga/attributes.py", line 2353, in get_attribute
    return   self._attributes_i_get        (us_key, _flow)
  File "/autofs/nccs-svm1_home1/jdakka/ve_entk_7_rp_master/lib/python2.7/site-packages/saga/attributes.py", line 1144, in _attributes_i_get
    d = self._attributes_t_init (key)
  File "/autofs/nccs-svm1_home1/jdakka/ve_entk_7_rp_master/lib/python2.7/site-packages/saga/attributes.py", line 406, in _attributes_t_init
    raise se.DoesNotExist ("attribute key is invalid: %s"  %  (key))
DoesNotExist: attribute key is invalid: total_gpu_count (/autofs/nccs-svm1_home1/jdakka/ve_entk_7_rp_master/lib/python2.7/site-packages/saga/attributes.py +406 (_attributes_t_init)  :  raise se.DoesNotExist ("attribute key is invalid: %s"  %  (key)))
```

Note I did not set anything for `gpu_reqs` in `EnTK`, not sure if that has any bearing on the variable `total_gpu_count`. 

[rp.session.titan-ext4.jdakka.017723.0005.zip](https://github.com/radical-cybertools/radical.pilot/files/2185854/rp.session.titan-ext4.jdakka.017723.0005.zip)
[rp.session.titan-ext4.jdakka.017723.0005_agent.zip](https://github.com/radical-cybertools/radical.pilot/files/2185855/rp.session.titan-ext4.jdakka.017723.0005_agent.zip)

**Comment by andre-merzky** [comment]
Looks like you need yo update your SAGA installation - that should be on 0.50.0 or later to have GPU support enabled.

**Comment by jdakka** [comment]
Mah bad,

Closing this one but the new can of worms is found [here](https://github.com/radical-cybertools/radical.pilot/issues/1665)
