### ISSUE TITLE
`radical-pilot-fetch-logfiles` fails with "Authentication failed"

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1666]
The terminal output I see is as follows:
```
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/bin/radical-pilot-fetch-logfiles", line 88, in <module>
    rpu.fetch_logfiles(sid=sid, dburl=dburl, src=src, tgt=tgt, access=access, skip_existing=skip)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/radical/pilot/utils/session.py", line 252, in fetch_logfiles
    _, db, _, _, _ = ru.mongodb_connect (dburl)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/radical/utils/misc.py", line 105, in mongodb_connect
    db.authenticate(user, pwd)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/pymongo/database.py", line 978, in authenticate
    self.connection._cache_credentials(self.name, credentials)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 467, in _cache_credentials
    auth.authenticate(credentials, sock_info, self.__simple_command)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/pymongo/auth.py", line 475, in authenticate
    auth_func(credentials[1:], sock_info, cmd_func)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/pymongo/auth.py", line 450, in _authenticate_default
    return _authenticate_scram_sha1(credentials, sock_info, cmd_func)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/pymongo/auth.py", line 238, in _authenticate_scram_sha1
    sasl_start, sasl_continue)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/pymongo/auth.py", line 185, in _scram_sha1_conversation
    res, _ = cmd_func(sock_info, source, sasl_start)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 703, in __simple_command
    helpers._check_command_response(response, None, msg)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/pymongo/helpers.py", line 182, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: command SON([('saslStart', 1), ('mechanism', 'SCRAM-SHA-1'), ('autoAuthorize', 1), ('payload', Binary('n,,n=smush,r=NjQ3ODEyMzUxMTk2', 0))]) on namespace repex_db_2.$cmd failed: Authentication failed.
```

However, I am able to execute locally. So the mongodb access should be fine. Unsure why this is occurring.  `radical-stack` is:

```
python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/RepEx_RP_Devel

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.7.0-0.7.0@master
  radical.pilot        : 0.50.2-v0.50.2-6-g3af53b66@devel
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
  saga                 : 0.47.6-v0.47.6-35-gf578245a@devel

```

EDIT: Oops, this should probably have been in `radical.utils`
Sorry!

**Comment by andre-merzky** [comment]
What is the mongodb URL you are using?

FWIW, your SAGA needs updating to 0.50.0 or newer, otherwise RP may run into troubles - but that should be unrelated to the MongoDB problem.

**Comment by SrinivasMushnoori** [comment]
@andre-merzky I updated saga to 0.50. 
My mongodb URL is 
`mongodb://smush:key1209@ds233551.mlab.com:33551/db_repex_2`

**Comment by andre-merzky** [comment]
I am really sorry, Srinivas, but I can't reproduce the problem with this URL.  I am running:

```
export RADICAL_PILOT_DBURL=mongodb://smush:key1209@ds233551.mlab.com:33551/db_repex_2
./examples/00_getting_started.py
# remove local session dir
rm -rf rp.session.rivendell.merzky.017725.0000
# fetch agent logs
radical-pilot-fetch-logfiles rp.session.rivendell.merzky.017725.0000
# check logs
du -a rp.session.rivendell.merzky.017725.0000/
```

and get the expected output  (the `rm` step is only to make sure the files are not yet there).  Any idea what's different for you?  Note that its also easier to call `session.close(download=True)` to get all log and profiles fetched on termination.

**Comment by SrinivasMushnoori** [comment]
I see.
Let me try to make a completely fresh mongodb and test again.

**Comment by SrinivasMushnoori** [comment]
So I created a fresh mongodb, reset all environment variables and tried again. Seems to work now. Strange that it wouldn't work before. Closing thread now.
