### ISSUE TITLE
Error in RP : Channel allocation requires an open connection

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#1672]
Hi , i was trying to execute my pipelines on ```comet``` , my resource dict is :
```
res_dict = {
                  'resource': 'xsede.comet_orte',
                  'walltime': 10,
                  'cores'   : args.cores,
                  'project' : '',
                  'queue'   : 'compute',
                  'schema'  :'gsissh',
               }
```
any number of pipelines above 5 will raise the error  for each pipeline ``` Error in RP callback thread: Channel allocation requires an open connection: <SelectConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=32769 virtual_host=/ ssl=False>>``` .

my radical-stack

```
 python               : 2.7.14
  pythonpath           :
  virtualenv           : conda_env4
  radical.entk         : 0.6.3-0.6.3@master
  radical.pilot        : 0.47.14-v0.47.14-2-g92a9abfa@master
  radical.utils        : 0.47.5-v0.47.5@master
  saga                 : 0.47.6-v0.47.6-35-gf5b05e5@fix-issue_676
```
The error 
```
2018-07-20 10:29:28,931: radical.entk.task_manager.0000: task-manager                    : umgr.0000.subscriber._state_sub_cb: ERROR   : Error in RP callback thread: Channel allocation requires an open connection: <SelectConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=32769 virtual_host=/ ssl=False>>
Traceback (most recent call last):
  File "/home/aymen/miniconda2/envs/conda_env4/lib/python2.7/site-packages/radical/entk/execman/task_manager.py", line 213, in unit_state_cb
    mq_channel = self._mq_connection.channel()
  File "/home/aymen/miniconda2/envs/conda_env4/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 791, in channel
    channel_number=channel_number)
  File "/home/aymen/miniconda2/envs/conda_env4/lib/python2.7/site-packages/pika/connection.py", line 1217, in channel
    'Channel allocation requires an open connection: %s' % self)
ConnectionClosed: Channel allocation requires an open connection: <SelectConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=32769 virtual_host=/ ssl=False>>
```
```
2018-07-20 10:53:35,600: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Message queues not deleted, error: (-1, "error(32, 'Broken pipe')")
Traceback (most recent call last):
  File "/home/aymen/miniconda2/envs/conda_env4/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 550, in _cleanup_mqs
    self._mq_channel.queue_delete(queue='%s-tmgr-to-sync' % self._sid)
  File "/home/aymen/miniconda2/envs/conda_env4/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2492, in queue_delete
    self._flush_output(delete_ok_result.is_ready)
  File "/home/aymen/miniconda2/envs/conda_env4/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/home/aymen/miniconda2/envs/conda_env4/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 477, in _flush_output
    result.reason_text)
ConnectionClosed: (-1, "error(32, 'Broken pipe')")
```

any help would be appreciated

thanks .

**Comment by iparask** [comment]
Are there any errors in the RP logs? This seems to me as an EnTK error

**Comment by vivek-bala** [comment]
Yup, this is a Pika issue in EnTK. This issue has been resolved in the latest releases. You can try again with 0.7.3, you shouldn't be facing broken pipe/channel closed issues.

**Comment by AymenFJA** [comment]
@iparask  @vivek-bala Yes, the error vanished after updating  ```radical.pilot :0.50```  and  ```radical.entk : 0.7.3 ```

so i will close the issue
