### ISSUE TITLE
CU creation fails with "error: attribute key is invalid: tag "

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1674]
Below is the error output. 

```
2018-07-22 06:47:53,312: radical.saga        : MainProcess                     : MainThread     : WARNING : ru.get_logger() is deprecated, use ru.Logger()
2018-07-22 06:47:53,316: radical.saga        : MainProcess                     : MainThread     : WARNING : cannot initialize context - no session: {'LifeTime' : '-1', 'Type' : 'X509', 'UserProxy' : '/tmp/x509up_u1011'}
2018-07-22 06:47:53,320: radical.saga        : MainProcess                     : MainThread     : WARNING : cannot initialize context - no session: {'LifeTime' : '-1', 'Type' : 'ssh', 'UserCert' : '/home/scm177/.ssh/id_rsa.pub', 'UserKe\
y' : '/home/scm177/.ssh/id_rsa'}
2018-07-22 06:47:55,317: radical.entk.task_processor: task-manager                    : MainThread     : ERROR   : CU creation failed, error: attribute key is invalid: tag (/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/sit\
e-packages/saga/attributes.py +406 (_attributes_t_init)  :  raise se.DoesNotExist ("attribute key is invalid: %s"  %  (key)))
2018-07-22 06:47:55,317: radical.entk.task_manager.0000: task-manager                    : MainThread     : ERROR   : Error in task execution: attribute key is invalid: tag (/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/si\
te-packages/saga/attributes.py +406 (_attributes_t_init)  :  raise se.DoesNotExist ("attribute key is invalid: %s"  %  (key)))
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/radical/entk/execman/rp/task_manager.py", line 209, in _tmgr
    bulk_cuds.append(create_cud_from_task(t, placeholder_dict, local_prof))
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/radical/entk/execman/rp/task_processor.py", line 281, in create_cud_from_task
    print 'T-proc: Cud tag %s for Task %s with tag %s' %(cud.tag, task.uid, task.tag)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/saga/attributes.py", line 2630, in __getattr__
    return self._attributes_i_get      (key, flow=self._DOWN)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/saga/attributes.py", line 1144, in _attributes_i_get
    d = self._attributes_t_init (key)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/saga/attributes.py", line 406, in _attributes_t_init
    raise se.DoesNotExist ("attribute key is invalid: %s"  %  (key))
DoesNotExist: attribute key is invalid: tag (/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/saga/attributes.py +406 (_attributes_t_init)  :  raise se.DoesNotExist ("attribute key is invalid: %s"  %  (key)))

```
The above error then seems to cause some sort of a loop where the SAGA layer appears to communicate with the resource infinitely. I've attached a [debug.log](https://github.com/radical-cybertools/radical.pilot/files/2216734/debug1.log) to demonstrate this.

Clientside logs are [here](https://github.com/radical-cybertools/radical.pilot/files/2216735/clientside_logs.tar.gz)

Fetching agent logs fails, because there is no rp directory in the `radical.pilot.sandbox` directory on the resource. 

`radical-stack` is
```
  python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/scm177/VirtualEnvs/RepEx_RP_Devel

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.7.4-0.7.3-10-gaffd55e5@devel
  radical.pilot        : 0.50.4-v0.50.4-1-g6670e662@devel
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
  saga                 : 0.50.0-v0.50.0@devel
```

**Comment by vivek-bala** [comment]
The tagging feature only exists in the "project/DA-scheduler" branch, you are using devel.
```
radical.pilot        : 0.50.4-v0.50.4-1-g6670e662@devel
```

**Comment by SrinivasMushnoori** [comment]
I tried devel as well as `project/DA-scheduler` but the loop persists. 
```
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 504, in _wfp
    self._enqueue_thread.join()
AttributeError: 'NoneType' object has no attribute 'join'
```
[debug.log](https://github.com/radical-cybertools/radical.pilot/files/2219839/debug.log) (terminal output) and [logfiles](https://github.com/radical-cybertools/radical.pilot/files/2219855/logs.tar.gz)
are attached.

**Comment by SrinivasMushnoori** [comment]
Closing this ticket as the issue in the topis is resolved, and the issue being face currently is a different one.
