### ISSUE TITLE
Pilot pilot.0000 failed - fatal!

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#1675]
Radical Pilot failed to create units  :
```
Traceback (most recent call last):
  File "01_unit_details.py", line 113, in <module>
    unit.exit_code, unit.stderr[:35]))
TypeError: 'NoneType' object has no attribute '__getitem__'
```

all logs are included from both sides .

My Radical-Stack
```
python               : 2.7.15
  pythonpath           :
  virtualenv           : conda_env2

  radical.entk         : 0.7.3-0.7.3@master
  radical.pilot        : 0.50.4
  radical.utils        : 0.50.1
  saga                 : 0.50.0
```

pmgr.0000.log

```
2018-07-23 12:38:45,634: pmgr.0000           : MainProcess                     : pmgr.0000.idler._state_pull_cb: INFO    : [Callback]: pilot pilot.0000 state: FAILED.
2018-07-23 12:38:45,634: pmgr.0000           : MainProcess                     : pmgr.0000.idler._state_pull_cb: ERROR   : [Callback]: pilot 'pilot.0000' failed (exit on error)
2018-07-23 12:38:45,634: pmgr.0000           : MainProcess                     : pmgr.0000.idler._state_pull_cb: ERROR   : abort: RuntimeError('pilot pilot.0000 failed - fatal!',) 

```

```Traceback (most recent call last):
  File "/home/aymen/miniconda2/envs/conda_env2/lib/python2.7/site-packages/radical/utils/threads.py", line 375, in _run
    if not self.work_cb():
  File "/home/aymen/miniconda2/envs/conda_env2/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 954, in work_cb
    ret = self._cb()
  File "/home/aymen/miniconda2/envs/conda_env2/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 264, in _state_pull_cb
    if not self._update_pilot(pilot_dict, publish=True):
  File "/home/aymen/miniconda2/envs/conda_env2/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 337, in _update_pilot
    self._pilots[pid]._update(pilot_dict)
  File "/home/aymen/miniconda2/envs/conda_env2/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 185, in _update
    else      : cb(self, self.state)
  File "/home/aymen/miniconda2/envs/conda_env2/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 133, in _default_state_cb
    raise RuntimeError('pilot %s failed - fatal!' % self.uid)
RuntimeError: pilot pilot.0000 failed - fatal!
```

bootstrap_0.out

```
reset final state to FAILED
# -------------------------------------------------------------------
# push final pilot state: rp.session.js-168-10.jetstream-cloud.org.aymen.017735.0005


 pilot.0000 FAILED
session : rp.session.js-168-10.jetstream-cloud.org.aymen.017735.0005
dburl   : mongodb://rp:rp@dsxxxxx.mlab.com:xxxx/rp
pilot   : pilot.0000
state   : pilot.0000
update  : {u'nModified': 1, u'opTime': {u'ts': Timestamp(1532363921, 2), u't': 7L}, u'n': 1, 'updatedExisting': True, u'electionId': ObjectId('7fffffff0000000000000007'), u'$clusterTime': {u'clusterTime': Timestamp(1532363921, 2), u'signature': {u'keyId': 6580759486615519233L, u'hash': Binary('\xf5\xe9o:\xd8\xd5\xd840\x93\x8b\x0b\xde\xaaI\x97\x827\x95\xfc', 0)}}, u'ok': 1.0, u'operationTime': Timestamp(1532363921, 2)}
```

[comet_session_017735.0005.zip](https://github.com/radical-cybertools/radical.pilot/files/2220627/comet_session_017735.0005.zip)
[session_017735.0005.zip](https://github.com/radical-cybertools/radical.pilot/files/2220628/session_017735.0005.zip)

**Comment by vivek-bala** [comment]
The scheduler is failing at https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/agent/scheduler/continuous.py#L90-L92.

The agent cfg has 'gpus_per_node': 0,' which is why the above exception is raised. Not sure why the if condition on line 90-92 exists though, as it does not let any system with no gpus to be used.

**Comment by iparask** [comment]
This is because there is no `gpu_per_node` entry in the resource configurations. We can either solve it by adding the entry in all configurations or via setting the value by default to 0 at LRMS.

@andre-merzky what do you believe?

**Comment by vivek-bala** [comment]
The gpu_per_node key and value is their in the resource config. But the value is 0 which raises the exception in line 90-92 in the continuous scheduler. I think the if-condition needs to be changed to check if it is None specifically.

**Comment by vivek-bala** [comment]
where did you add it? Can you link the specific line and file.

**Comment by AymenFJA** [comment]
@vivek-bala  i just added the ``` 'gpu_per_node' : 1``` under the ``` xsede.comet```  in this file : ```conda_env1/lib/python2.7/site-packages/radical/pilot/config/resource_xsde.json``` line ``` 587```

**Comment by vivek-bala** [comment]
Try ```'gpus_per_node': 1```

**Comment by AymenFJA** [comment]
WORKED ! , thanks @vivek-bala , i will close the issue now .
