### ISSUE TITLE
Error running CU COMET ORTE

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#1679]
Trying to run RADICAL PILOT  example ``` 01_unit_details.py```   but keep failing on both COMET ``` xsede.comet```and ```xsede.comet_orte```:

terminal error :

``` 
 * unit.000000: FAIL, exit: None, out:
Pilot cannot start compute unit:
E
  * unit.000001: FAIL, exit: None, out:
Pilot cannot start compute unit:
E
unit workdir : gsisftp://comet.sdsc.xsede.org/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0005/pilot.0000//unit.000000/
pilot id     : pilot.0000
exit code    : None
exit stdout  :
unit workdir : gsisftp://comet.sdsc.xsede.org/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0005/pilot.0000//unit.000001/
pilot id     : pilot.0000
exit code    : None
exit stdout  :
```

Msg from ```agent_0.executing.0.child.log ``` :

``` Traceback (most recent call last):
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 310, in spawn
    launch_command, hop_cmd = launcher.construct_command(cu, launch_script_name)
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 216, in construct_command
    task_mpi     = bool('mpi' in cud.get('cpu_process_type', '').lower())
AttributeError: 'NoneType' object has no attribute 'lower'
2018-07-27 14:59:26,319: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 202, in _handle_unit
    self.spawn(launcher=launcher, cu=cu)
  File "/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 318, in spawn
    raise RuntimeError(msg) ```

```
```
RuntimeError: Error in spawner ('NoneType' object has no attribute 'lower')
2018-07-27 14:59:26,320: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
2018-07-27 14:59:29,670: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : got unit (unit.000009)
2018-07-27 14:59:29,670: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
2018-07-27 14:59:29,670: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : Launching unit with ORTE (/home/amerzky/ompi//installed/2017_02_17_6da4dbb/bin/orterun).
2018-07-27 14:59:29,671: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : Created launch_script: /home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0005/pilot.0000/unit.000009/unit.000009.sh
2018-07-27 14:59:29,672: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : Error in spawner ('NoneType' object has no attribute 'lower
```
ERROR from  ``` bootstrap_0.out : ```
```
# push final pilot state: rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0005 pilot.0000 CANCELED
session : rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0005
dburl   : mongodb://aymenfja:*******@ds127490.mlab.com:27490/radicallab
pilot   : pilot.0000
state   : pilot.0000
update  : {u'nModified': 1, u'opTime': {u'ts': Timestamp(1532728803, 1), u't': 2L}, u'n': 1, 'updatedExisting': True, u'electionId': ObjectId('7fffffff0000000000000002'), u'$clusterTime': {u'clusterTime': Timestamp(1532728803, 1), u'signature': {u'keyId': 6580673565794762753L, u'hash': Binary('\x8f\x06\x9f`\xd4\xa6\xce9\xb8Q\x11v\x00\xfc\x0c\xc3\xb8\xdd\xf7\\', 0)}}, u'ok': 1.0, u'operationTime': Timestamp(1532728803, 1)}
```
[rp.comet.zip](https://github.com/radical-cybertools/radical.pilot/files/2239060/rp.comet.zip)

**Comment by andre-merzky** [comment]
Thanks for the detailed issue description!  This should be fix in branch `fix/issue_1679` - could you please give that a try?  Thanks!

**Comment by AymenFJA** [comment]
Hi @andre-merzky I did upgrade the RP to ``` fix/issue_1679 ```  i faced this error :

My radica-stack:
```
 python               : 2.7.15
  pythonpath           :
  virtualenv           : conda_env1

  radical.entk         : 0.7.3
  radical.pilot        : 0.50.4-v0.50.4-1-gc70a3a55@fix-issue_1679
  radical.utils        : 0.50.1
  saga                 : 0.50.0 
```

Terminal output :
```
* unit.000000: FAIL, exit: 132, out: -----------------------------------
  * unit.000001: DONE, exit:   0, out:
unit workdir : gsisftp://comet.sdsc.xsede.org/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0015/pilot.0000//unit.000000/
pilot id     : pilot.0000
exit code    : 132
exit stdout  :
unit workdir : gsisftp://comet.sdsc.xsede.org/home/aymen/radical.pilot.sandbox/rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0015/pilot.0000//unit.000001/
pilot id     : pilot.0000
exit code    : 0
exit stdout  :
[ORTE] Task: 0 is launched! (Job ID: [51979,2])
[ORTE] Task: 0 returned: 0 (Job ID: [51979,2])
```
``` unit00000 STDERR output```
```
orterun was unable to launch the specified application as it could not access
or execute an executable:

Executable: /usr/bin/mongo
Node: comet-22-17

while attempting to start process rank 0.
```
```bootstrap_0.out```
```
# push final pilot state: rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0015 pilot.0000 CANCELED
session : rp.session.js-168-10.jetstream-cloud.org.aymen.017741.0015
dburl   : mongodb://rp:rp@ds015335.mlab.com:15335/rp
pilot   : pilot.0000
state   : pilot.0000
update  : {u'nModified': 1, u'opTime': {u'ts': Timestamp(1532906415, 1), u't': 7L}, u'n': 1, 'updatedExisting': True, u'electionId': ObjectId('7fffffff0000000000000007'), u'$clusterTime': {u'clusterTime': Timestamp(1532906415, 1), u'signature': {u'keyId': 6580759486615519233L, u'hash': Binary('\xc4\xacc\x1f\x98g\xff$\x18\xa3\x9a\x9a\xea\x89\xca\xbe\xabZ\xdf\xbf', 0)}}, u'ok': 1.0, u'operationTime': Timestamp(1532906415, 1)}
```
Session log file is here 
[rp_comet_session0015.zip](https://github.com/radical-cybertools/radical.pilot/files/2239298/rp_comet_session0015.zip)

**Comment by andre-merzky** [comment]
This seems like an workload error to me: the first unit tries to run `/usr/bin/mongo "mongodb://$RP_APP_TUNNEL/" "--eval" "db.stats()"` -- but the executable `/usr/bin/mongo` does not exist on the target system, which is the `STDERR` message you get for that unit.  There is not much RP can do  at that point other than reporting that error.

Or am I missing anything?

**Comment by SrinivasMushnoori** [comment]
Has the fix for this been merged into DA branch? This issue is springing up in the following `radical-stack` 

```

  python               : 2.7.14
  pythonpath           :
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.7.4-0.7.3-10-gaffd55e@devel
  radical.pilot        : 0.50.7-v0.50.7-99-g4193371@project-DA-scheduler_algo
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
  saga                 : 0.50.0-v0.50.0@devel

```

The error in `agent_0.executing.0.child.log` is:

```
2018-08-03 10:27:54,698: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : Error in spawner ('NoneType' object has no attribute 'lower')
Traceback (most recent call last):
  File "/home/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017746.0007/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 310, in spawn
    launch_command, hop_cmd = launcher.construct_command(cu, launch_script_name)
  File "/home/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017746.0007/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 216, in construct_command
    task_mpi     = bool('mpi' in cud.get('cpu_process_type', '').lower())
AttributeError: 'NoneType' object has no attribute 'lower'
2018-08-03 10:27:54,700: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/home/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017746.0007/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 202, in _handle_unit
    self.spawn(launcher=launcher, cu=cu)
  File "/home/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017746.0007/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 318, in spawn
    raise RuntimeError(msg)
RuntimeError: Error in spawner ('NoneType' object has no attribute 'lower')
2018-08-03 10:27:59,379: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : Error in spawner ('NoneType' object has no attribute 'lower')
Traceback (most recent call last):
  File "/home/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017746.0007/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 310, in spawn
    launch_command, hop_cmd = launcher.construct_command(cu, launch_script_name)
  File "/home/mushnoor/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017746.0007/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 216, in construct_command
    task_mpi     = bool('mpi' in cud.get('cpu_process_type', '').lower())
AttributeError: 'NoneType' object has no attribute 'lower'
```

Logs are [here](https://github.com/radical-cybertools/radical.pilot/files/2258280/error_in_spawner.tar.gz)

**Comment by jdakka** [comment]
I followed this ticket and it worked for the same stack you showed. 

https://github.com/radical-cybertools/radical.pilot/issues/1663

**Comment by andre-merzky** [comment]
Yes, this should be merged and release.  As a quick workaround, please set `MPI` in the unit description to an empty string.

**Comment by iparask** [comment]
Closing as resolved
