### ISSUE TITLE
"Error running CU, Error in spawner (list indices must be integers, not str)" on DA Algo branch

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.pilot#1682]
This is on SuperMIC. None of the units execute. There is no STDERR or STDOUT file, and digging into the logs on the agent side reveals the following:
```
2018-07-30 12:46:28,041: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : Error in spawner (list indices must be integers, not str)
Traceback (most recent call last):
  File "/work/smushnoo/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017742.0017/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 310, in spawn
    launch_command, hop_cmd = launcher.construct_command(cu, launch_script_name)
  File "/work/smushnoo/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017742.0017/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/ssh.py", line 77, in construct_command
    host = slots['nodes']['name'][0]
TypeError: list indices must be integers, not str
2018-07-30 12:46:28,044: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/work/smushnoo/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017742.0017/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 202, in _handle_unit
    self.spawn(launcher=launcher, cu=cu)
  File "/work/smushnoo/radical.pilot.sandbox/rp.session.mcewan.engr.rutgers.edu.scm177.017742.0017/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 318, in spawn
    raise RuntimeError(msg)
RuntimeError: Error in spawner (list indices must be integers, not str)
```

`radical-stack` is 

```
  python               : 2.7.14
  pythonpath           :
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.7.4-0.7.3-10-gaffd55e@devel
  radical.pilot        : 0.50.5-v0.50.5-96-g5c40479@project-DA-scheduler_algo
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
  saga                 : 0.50.0-v0.50.0@devel
```

Complete logs are [here](https://github.com/radical-cybertools/radical.pilot/files/2242314/error_running_cu.tar.gz)

I've reproduced this with not only my use case but also with RP examples.

**Comment by SrinivasMushnoori** [comment]
This seems to be a duplicate of issue #1679

**Comment by andre-merzky** [comment]
No, I think #1679 is fixed by now, and unrelated.  Alas, your new error is likely due to the changes in the scheduler output with in the DA scheduler algo branch, and as such I'd rather leave to the RCT class to fix it.  In case this sees no activity before the RCT call tomorrow, we'll discuss a possible solution at that point, ok?

**Comment by andre-merzky** [comment]
This should be fixed now in the  DA branch - subagent and unit startup were out of sync.

**Comment by iparask** [comment]
Closing as fixed
