### ISSUE TITLE
radical-pilot-fetch-json results in TypeError [non-fatal]

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1725]
See the traceback when I ran radical-pilot-fetch-json on one of my sessions:
```
> radical-pilot-fetch-json re.session.titan-ext4.vivekb.017801.0008
saving json to re.session.titan-ext4.vivekb.017801.0008.json
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/vivekb/ves/ve-bms/bin/radical-pilot-fetch-json", line 25, in <module>
    mongo.disconnect()
  File "/autofs/nccs-svm1_home1/vivekb/ves/ve-bms/lib/python2.7/site-packages/pymongo/database.py", line 1348, in __call__
    self.__name, self.__client.__class__.__name__))
```

Note that the session file did get generated but the above error also popped up.

**Comment by andre-merzky** [comment]
Not sure why that would happen - but it probably makes sense to wrap the `disconnect()` into a `try/catch`...

**Comment by lee212** [comment]
Waiting for the PR #1841 pass Travis and to be merged.
