### ISSUE TITLE
pubsub bridges fails

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1728]
I am trying to run a simple example to verify a conda intsallation and I am: 
```
new session: [rp.session.js-169-78.jetstream-cloud.org.iparask.017802.0001]    \
database   : [mongodb://giannis:giannis1@ds125872.mlab.com:25872/re_rp_devel]Traceback (most recent call last):
  File "00_getting_started.py", line 37, in <module>
    session = rp.Session()
  File "/home/iparask/anaconda2/envs/rp_conda/lib/python2.7/site-packages/radical/pilot/session.py", line 271, in __init__
    self._bridges    = ruc.start_bridges   (self._cfg, self, self._log)
  File "/home/iparask/anaconda2/envs/rp_conda/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 155, in start_bridges
    bridge = rpu_Pubsub(session, bname, rpu_PUBSUB_BRIDGE, bcfg_clone)
  File "/home/iparask/anaconda2/envs/rp_conda/lib/python2.7/site-packages/radical/pilot/utils/pubsub.py", line 139, in __init__
    self.start()
  File "/home/iparask/anaconda2/envs/rp_conda/lib/python2.7/site-packages/radical/utils/process.py", line 504, in start
    (self._ru_childname, msg))
RuntimeError: child control.pubsub.bridge.0000.child failed to come up [s]
```
```
2018-09-28 10:45:36,079: control.pubsub.bridge.0000: MainProcess                     : MainThread     : ERROR   : initialization failed (child control.pubsub.bridge.0000.child failed to come up [s])
Traceback (most recent call last):
  File "/home/iparask/anaconda2/envs/rp_conda/lib/python2.7/site-packages/radical/utils/process.py", line 504, in start
    (self._ru_childname, msg))
RuntimeError: child control.pubsub.bridge.0000.child failed to come up [s]
control.pubsub.bridge.0000.log (END)
```
There is nothing in the sandbox folder.

Any ideas how to debug this?

**Comment by iparask** [comment]
Yes, it is that one. I hope not. 
```
(radical.pilot) iparask@js-169-78:~/Git/radical.pilot/examples$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 64059
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 64059
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

[radical.log](https://github.com/radical-cybertools/radical.pilot/files/2429232/radical.log)

**Comment by andre-merzky** [comment]
I don't see anything suspicious... :/  Lets discuss this when we talk later today...

**Comment by lee212** [comment]
@iparask, I am following up this. Any changes to share?

**Comment by iparask** [comment]
This hasn't happened from that day. I'm closing until I see it again.
