### ISSUE TITLE
hombre scheduler requiring gpu

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1730]
I am running an `entk` script on `supermic` using the hombre scheduler. I fixed my `cpu` reqs to following:

```
self.cpu_reqs = {'processes': 1, 'thread_type': None, 'threads_per_process': 20, 'process_type': None}
  
```
I get the following stack trace in `agent_0.scheduling.0.child.log`:

```
Traceback (most recent call last):
  File "/work/jdakka/radical.pilot.sandbox/re.session.two.jdakka.017807.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1267, in work_cb
    self._workers[state](things)
  File "/work/jdakka/radical.pilot.sandbox/re.session.two.jdakka.017807.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/base.py", line 437, in _schedule_units
    if self._try_allocation(unit):
  File "/work/jdakka/radical.pilot.sandbox/re.session.two.jdakka.017807.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/base.py", line 461, in _try_allocation
    unit['slots'] = self._allocate_slot(unit['description'])
  File "/work/jdakka/radical.pilot.sandbox/re.session.two.jdakka.017807.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/hombre.py", line 295, in _allocate_slot
    self._delayed_configure(cud)
  File "/work/jdakka/radical.pilot.sandbox/re.session.two.jdakka.017807.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/hombre.py", line 150, in _delayed_configure
    self.gpn / gpus_needed )
ZeroDivisionError: integer division or modulo by zero
```
[re.session.two.jdakka.017807.0000.zip](https://github.com/radical-cybertools/radical.pilot/files/2440328/re.session.two.jdakka.017807.0000.zip)

`radical-stack`

```
radical.entk         : 0.7.6-0.7.6@master
radical.pilot        : 0.50.8-v0.50.8-1-g8228b9f5@fix-issue_1705
radical.utils        : 0.50.2-v0.50.2@master
saga                 : 0.50.0-v0.50.0@master
```

**Comment by mturilli** [comment]
@vivek-bala do you need to use hombre (does this have a new name?!) scheduler?

**Comment by vivek-bala** [comment]
No, I don't need to use the HOMBRE scheduler. I believe the name is still HOMBRE. 

The error seems like there is no guard in the scheduler to check if tasks don't require gpus though.

**Comment by mturilli** [comment]
@vivek-bala thank you. @andre-merzky I am confused :/ Is HOMBRE still actual or was it replaced by your latest iteration of the 'tagged' scheduler?

**Comment by andre-merzky** [comment]
The `Ordered` scheduler replaces the `Fifo` scheduler - `HOMBRE` is different really, as it expects a unifor BoT.  The `Ordered` and `Fifo` schedulers made no assumption about the unit shape.

**Comment by andre-merzky** [comment]
Maybe we should rename `HOMBRE` to `UniBoT` ;-)

**Comment by lee212** [comment]
It seems PR #1714 fixed this issue and merged. It can be closed now.
