### ISSUE TITLE
Summit LRMS does not parse nodelist correctly

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1741]
While running full stack example the following error was produced from LRMS
```
2018-10-16 12:27:17,074: radical.utils       : MainProcess                     : MainThread     : DEBUG   : lm new manager
2018-10-16 12:27:17,077: radical.saga.api    : MainProcess                     : MainThread     : INFO    : ignore ssh key at /ccs/home/iparask2/.ssh/known_hosts (no public key: /ccs/home/iparask2/.ssh/known_hosts.pub)
Traceback (most recent call last):
  File "/ccs/home/iparask2/radical.pilot.sandbox/rp.session.summitdev-login1.iparask2.017820.0004/pilot.0000/rp_install/bin/radical-pilot-agent", line 71, in <module>
    bootstrap_3(sys.argv[1])
  File "/ccs/home/iparask2/radical.pilot.sandbox/rp.session.summitdev-login1.iparask2.017820.0004/pilot.0000/rp_install/bin/radical-pilot-agent", line 42, in bootstrap_3
    if agent_name == 'agent_0': agent = rpa.Agent_0(agent_name)
  File "/ccs/home/iparask2/radical.pilot.sandbox/rp.session.summitdev-login1.iparask2.017820.0004/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_0.py", line 118, in __init__
    session=self._session)
  File "/ccs/home/iparask2/radical.pilot.sandbox/rp.session.summitdev-login1.iparask2.017820.0004/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 232, in create
    return impl(cfg, session)
  File "/ccs/home/iparask2/radical.pilot.sandbox/rp.session.summitdev-login1.iparask2.017820.0004/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/lsf_summit.py", line 26, in __init__
    LRMS.__init__(self, cfg, session)
  File "/ccs/home/iparask2/radical.pilot.sandbox/rp.session.summitdev-login1.iparask2.017820.0004/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 118, in __init__
    (self.node_list, self.cores_per_node))
RuntimeError: LRMS configuration invalid ([['summitdev-r0c0n15', 'summitdev-r0c0n15'], ['summitdev-login1', 'summitdev-login1']])(None)
```

**Comment by vivek-bala** [comment]
We might want to consider not calling the base class constructor https://github.com/radical-cybertools/radical.pilot/blob/feature/summit/src/radical/pilot/agent/rm/lsf_summit.py#L26. Quick idea. I'll revaluate on Wednesday.

**Comment by iparask** [comment]
Closing. It is fixed in `feature/summit`
