### ISSUE TITLE
lrms config hook failure

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.pilot#1768]
I'm running `titan.orte` and experience an lrms hook failure with the `ORTE` launch method. Has the `ORTE` version changed?

```
2018-11-19 08:17:38,080: agent_0             : MainProcess                     : MainThread     : INFO    : call LRMS config hook for LaunchMethod ORTE: <class 'radical.pilot.agent.lm.orte.ORTE'>
2018-11-19 08:17:38,097: agent_0             : MainProcess                     : MainThread     : ERROR   : lrms config hook failed
Traceback (most recent call last):
  File "/lustre/atlas/scratch/jdakka/chm126/radical.pilot.sandbox/re.session.titan-ext4.jdakka.017854.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 155, in __init__
    self._log, self._prof))
  File "/lustre/atlas/scratch/jdakka/chm126/radical.pilot.sandbox/re.session.titan-ext4.jdakka.017854.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/base.py", line 177, in lrms_config_hook
    return impl.lrms_config_hook(name, cfg, lrms, logger, profiler)
  File "/lustre/atlas/scratch/jdakka/chm126/radical.pilot.sandbox/re.session.titan-ext4.jdakka.017854.0005/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/orte.py", line 65, in lrms_config_hook
    assert(orte_info.get('version'))
AssertionError
```

using stack:

```
radical.entk         : 0.7.8-0.7.8@master
radical.pilot        : 0.50.18-v0.50.18@master
radical.utils        : 0.50.2-v0.50.2@master
saga                 : 0.50.3-v0.50.3@master
```

Agent logs can be found in this path `/lustre/atlas2/chm126/scratch/jdakka/radical.pilot.sandbox/rp.session.titan-ext4.jdakka.017854.0005`

**Comment by mturilli** [comment]
Escalated to high as RP paper depends on this

**Comment by andre-merzky** [comment]
Ack

**Comment by jdakka** [comment]
@andre-merzky any progress with this?

**Comment by andre-merzky** [comment]
Jumana, the fix has been released - can you please give release or master a try?  Thanks
