### ISSUE TITLE
RP/SAGA fails on Comet

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1777]
RP/SAGA failed on Comet with the following error for a user:

```
saga-python-0.50.3.tar.gz
,
2018-12-12 13:31:36,691: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/sun95/env/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 488, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/sun95/env/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 677, in _start_pilot_bulk
    js = rs.job.Service(js_ep, session=self._session)
  File "/home/sun95/env/local/lib/python2.7/site-packages/saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "/home/sun95/env/local/lib/python2.7/site-packages/saga/base.py", line 104, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/home/sun95/env/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/sun95/env/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 295, in init_instance
    self._open()
  File "/home/sun95/env/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 377, in _open
    self._version = StrictVesrion(out.split()[1].strip())
NameError: global name 'StrictVesrion' is not defined
```

Attaching client logs, there were no logs in the agent side.
[re.session.js-17-147.jetstream-cloud.org.sun95.017877.0005.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/2673790/re.session.js-17-147.jetstream-cloud.org.sun95.017877.0005.tar.gz)

**Comment by vivek-bala** [comment]
From @iparask : try the devel stack. 

@Freddie: You can do this by checking out the devel branch in RP, radical.saga and radical.utils.

@iparask @andre-merzky if this is a small fix, maybe we can/should patch it immediately and not wait for a major/minor release.

**Comment by andre-merzky** [comment]
This looks like a typo: `StrictVesrion` vs `StrictVersion`.  Seems like someone did not run pylint ;-)  I'll fix and release now.

**Comment by andre-merzky** [comment]
A fix was pushed to pipy as v0.50.4.

**Comment by FreddieSun** [comment]
Never mind, I got that. Now my current radical-stack is
```
  python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/sun95/env

  radical.entk         : 0.7.10
  radical.pilot        : 0.50.19-v0.50.19-4-g70c584a@devel
  radical.utils        : 0.50.2
  saga                 : 0.50.0-v0.50.0-5-g7073412@devel
```

Now after
```shell
export RADICAL_PILOT_VERBOSE=DEBUG
export RADICAL_PILOT_PROFILE=TRUE
export RADICAL_ENTK_VERBOSE=INFO
export RADICAL_PILOT_DBURL=mongodb://freddiesun:sunweijia95jiang@ds143603.mlab.com:43603/entk
```

 I run the get_start.py I get the information like this(didn't get the information about created a session):

```
2018-12-12 21:40:26,551: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
2018-12-12 21:40:26,551: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    :                      pid/tid: 20346/MainThread
2018-12-12 21:40:26,552: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Application Manager initialized
2018-12-12 21:40:26,761: radical.entk.task_processor: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
2018-12-12 21:40:26,761: radical.entk.task_processor: MainProcess                     : MainThread     : INFO    :                      pid/tid: 20346/MainThread
2018-12-12 21:40:26,762: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
2018-12-12 21:40:26,762: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    :                      pid/tid: 20346/MainThread
2018-12-12 21:40:26,762: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Created resource manager object: resource_manager.0000
2018-12-12 21:40:26,763: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Resource description validated
2018-12-12 21:40:26,763: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Workflow assigned to Application Manager
2018-12-12 21:40:26,809: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
2018-12-12 21:40:26,810: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : INFO    :                      pid/tid: 20346/MainThread
2018-12-12 21:40:26,810: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : INFO    : Created WFProcessor object: wfprocessor.0000
2018-12-12 21:40:26,811: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Starting resource request submission
2018-12-12 21:40:39,992: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Pilot pilot.0000 state: PMGR_LAUNCHING_PENDING
2018-12-12 21:40:39,993: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Resource request submission successful.. waiting for pilot to go Active
2018-12-12 21:40:39,996: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: PMGR_LAUNCHING
2018-12-12 21:40:50,710: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: PMGR_ACTIVE_PENDING
2018-12-12 21:41:17,683: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.idler._state_pull_cb: INFO    : Pilot pilot.0000 state: PMGR_ACTIVE
2018-12-12 21:41:17,771: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Pilot is now active
2018-12-12 21:41:17,771: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Starting synchronizer thread
2018-12-12 21:41:17,772: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : synchronizer thread started
2018-12-12 21:41:17,774: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Starting WFProcessor process from AppManager
2018-12-12 21:41:17,777: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : INFO    : Starting WFprocessor process
2018-12-12 21:41:17,789: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
2018-12-12 21:41:17,790: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : WFprocessor started
2018-12-12 21:41:17,791: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    :                      pid/tid: 20346/MainThread
2018-12-12 21:41:17,792: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : Starting dequeue-thread
2018-12-12 21:41:17,793: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : INFO    : Dequeue thread started
2018-12-12 21:41:17,793: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : Starting enqueue-thread
2018-12-12 21:41:17,796: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : enqueue-thread started
2018-12-12 21:41:17,821: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received pipeline.0000 with state SCHEDULING
2018-12-12 21:41:17,823: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Found pipeline pipeline.0000, state SCHEDULING, completed False
2018-12-12 21:41:17,825: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Transition of pipeline.0000 to new state SCHEDULING successful
2018-12-12 21:41:17,828: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received stage.0000 with state SCHEDULING
2018-12-12 21:41:17,829: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Found parent pipeline: pipeline.0000
2018-12-12 21:41:17,832: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Transition of stage.0000 to new state SCHEDULING successful
2018-12-12 21:41:17,837: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Created task manager object: task_manager.0000
2018-12-12 21:41:17,837: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.0000 with state SCHEDULING
2018-12-12 21:41:17,839: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Starting task manager process from AppManager
2018-12-12 21:41:17,840: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Transition of task.0000 to new state SCHEDULING successful
2018-12-12 21:41:17,841: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Starting task manager process
2018-12-12 21:41:17,849: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Starting heartbeat thread
2018-12-12 21:41:17,853: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.0000 with state SCHEDULED
2018-12-12 21:41:17,853: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Task Manager process started
2018-12-12 21:41:17,857: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Transition of task.0000 to new state SCHEDULED successful
2018-12-12 21:41:17,862: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received stage.0000 with state SCHEDULED
2018-12-12 21:41:17,862: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Found parent pipeline: pipeline.0000
2018-12-12 21:41:17,864: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Transition of stage.0000 to new state SCHEDULED successful
2018-12-12 21:41:17,874: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
/home/sun95/env/local/lib/python2.7/site-packages/pymongo/topology.py:149: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
  "MongoClient opened before fork. Create MongoClient only "
2018-12-12 21:41:26,726: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.0000 with state SUBMITTING
2018-12-12 21:41:26,727: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Transition of task.0000 to new state SUBMITTING successful
2018-12-12 21:41:26,729: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Received heartbeat request
2018-12-12 21:41:26,729: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Sent heartbeat response
2018-12-12 21:41:26,780: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.0000 with state SUBMITTED
2018-12-12 21:41:26,782: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Transition of task.0000 to new state SUBMITTED successful
2018-12-12 21:41:26,782: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Task task.0000 submitted to RTS
2018-12-12 21:41:31,991: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.0000 with state EXECUTED
2018-12-12 21:41:31,993: radical.entk.task_manager.0000: task-manager                    : umgr.0000.subscriber._state_sub_cb: INFO    : Transition of task.0000 to new state EXECUTED successful
2018-12-12 21:41:31,994: radical.entk.task_manager.0000: task-manager                    : umgr.0000.subscriber._state_sub_cb: INFO    : Pushed task task.0000 with state EXECUTED to completed queue re.session.js-17-147.jetstream-cloud.org.sun95.017878.0005-completedq-1
2018-12-12 21:41:31,995: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : INFO    : Got finished task task.0000 from queue
2018-12-12 21:41:31,996: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.0000 with state DEQUEUEING
2018-12-12 21:41:31,997: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : INFO    : Transition of task.0000 to new state DEQUEUEING successful
2018-12-12 21:41:31,999: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.0000 with state DEQUEUED
2018-12-12 21:41:32,000: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : INFO    : Transition of task.0000 to new state DEQUEUED successful
2018-12-12 21:41:32,001: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.0000 with state DONE
2018-12-12 21:41:32,003: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : INFO    : Transition of task.0000 to new state DONE successful
2018-12-12 21:41:32,004: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received stage.0000 with state DONE
2018-12-12 21:41:32,004: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Found parent pipeline: pipeline.0000
2018-12-12 21:41:32,006: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : INFO    : Transition of stage.0000 to new state DONE successful
2018-12-12 21:41:32,007: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received pipeline.0000 with state DONE
2018-12-12 21:41:32,007: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Found pipeline pipeline.0000, state DONE, completed False
2018-12-12 21:41:32,008: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2018-12-12 21:41:32,009: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : INFO    : Transition of pipeline.0000 to new state DONE successful
2018-12-12 21:41:32,009: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : Terminating enqueue-thread
2018-12-12 21:41:32,010: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Enqueue thread terminated
2018-12-12 21:41:32,016: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : Terminating dequeue-thread
2018-12-12 21:41:32,017: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : INFO    : Terminated dequeue thread
2018-12-12 21:41:32,025: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating synchronizer thread
2018-12-12 21:41:32,028: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Synchronizer thread terminated
2018-12-12 21:41:32,028: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating task manager process
2018-12-12 21:41:47,877: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2018-12-12 21:41:47,878: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2018-12-12 21:41:48,041: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Task manager process closed
2018-12-12 21:42:17,884: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Hearbeat thread terminated
2018-12-12 21:42:28,224: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.idler._state_pull_cb: INFO    : Pilot pilot.0000 state: CANCELED
```

and I didn't find the STDOUT file inside the session file. Here is my session's file
[re.session.js-17-147.jetstream-cloud.org.sun95.017878.0003.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/2674440/re.session.js-17-147.jetstream-cloud.org.sun95.017878.0003.tar.gz)

Any idea? Thanks

**Comment by FreddieSun** [comment]
@vivek-bala  Hey Vivek, do you have any idea? Thanks

**Comment by FreddieSun** [comment]
Yeah, I saw that! Thanks for your patient help! appreciate that.

**Comment by vivek-bala** [comment]
Awesome! Glad to help. Does this mean you were able to example end-to-end with no issues? Let us know if it is resolved.

**Comment by FreddieSun** [comment]
Yep, it works fluently right now. I think I can close the issue in the EnTK repo.

**Comment by vivek-bala** [comment]
Sounds good. Thanks for confirming. I'll close this one.
