### ISSUE TITLE
CU launching fails with memory intensive workloads

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#1782]
I am trying to launch a use case which is data-intensive, in the sense that it will use all the memory of the nodes, and I am getting this error:
```
2018-12-24 12:04:09,208: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : Launching unit with SSH (/bin/ssh -o StrictHostKeyChecking=no -o ControlMaster=auto).
2018-12-24 12:04:09,208: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : Created launch_script: /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/RealDeal1/pilot.0000/unit.000047/unit.000047.sh
2018-12-24 12:04:09,212: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : INFO    : Launching unit unit.000047 via /bin/ssh -o StrictHostKeyChecking=no -o ControlMaster=auto gpu024 LD_LIBRARY_PATH=/opt/packages/python/2_7_11_gcc/lib:/usr/mpi/gcc/openmpi-2.1.2-hfi/lib64:/opt/packages/gcc/5.3.0/lib64:/opt/packages/gcc/5.3.0/lib PATH=/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/ve.xsede.bridges.0.50.19/bin:/opt/packages/python/2_7_11_gcc/bin:/opt/packages/slurm/default/bin:/usr/mpi/gcc/openmpi-2.1.2-hfi/bin:/opt/packages/gcc/5.3.0/bin:/home/paraskev/miniconda2/bin:/home/paraskev/miniconda2/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/puppet/bin:/bin:/sbin:/opt/puppetlabs/bin:/home/paraskev/.local/bin:/home/paraskev/bin:/opt/puppetlabs/puppet/bin:/bin:/sbin:/home/paraskev/.local/bin:/home/paraskev/bin PYTHONPATH=/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/RealDeal1/pilot.0000/rp_install/lib/python2.7/site-packages::NODE_LFS_PATH=/local/4672635 /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/RealDeal1/pilot.0000/unit.000047/unit.000047.sh in /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/RealDeal1/pilot.0000/unit.000047
2018-12-24 12:04:09,213: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : ERROR   : error running CU
Traceback (most recent call last):
  File "/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/RealDeal1/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 202, in _handle_unit
    self.spawn(launcher=launcher, cu=cu)
  File "/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/RealDeal1/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/executing/popen.py", line 366, in spawn
    cwd        = sandbox)
  File "/opt/packages/python/2_7_11_gcc/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/packages/python/2_7_11_gcc/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
  File "/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/RealDeal1/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/atfork/atfork.py", line 182, in os_fork_wrapper
    pid = _orig_os_fork()
OSError: [Errno 12] Cannot allocate memory
2018-12-24 12:04:09,247: agent_0.executing.0.child: agent_0.executing.0             : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
```

This is on Bridges where each node has 128GB of RAM and 32 cores. I am launching 16 concurrent CUs per nodes and use totally 4 nodes. 

I believe this is because the first node cannot handle running units and launching everything. Furthermore, I cannot utilize `ORTE` for two reasons. First, it is not installed on Bridges. Second, the total number of units will exceed 4096.

We need to take into consideration the above fact in the Mem aware scheduler (PR #1781)

**Comment by iparask** [comment]
I do not think that losing a whole compute node is the correct way of doing this. Do we have a profile of the memory consumption of the agent? By knowing how much memory we need to launch each process, I can try and see whether there is a way to be a bit more clever with how the unit submission is happening, such that the memory does not fill, given the information I have from my use case.

**Comment by mturilli** [comment]
Here a summary from yesterday meeting with @iparask:

- In some configurations, it is not viable to assign a full work node to the agent (e.g., ICEBERG use case with 4 work nodes on Bridges)
- We do not know the agent's memory footprint. Thus, when the agent runs on a node that is also used to execute CUs we cannot asses whether/how the agent affects CU memory requirements.
- It is likely that the agent's memory footprint depends on the agent's configuration, pilot size and number of (concurrent?) CU executed. It is also likely this footprint changes over runtime.
- Profiling agent's memory consumption would be useful for use cases that require estimating the amount of memory available to the CU at runtime (e.g., ICEBERG, QArchive).
- We should know the order of magnitude of the agent memory footprint, with lower and upper boundary for a given configuration and workload. If this proves to be relevant, we may want to profile the footprint in more detail.
- We should start with the configuration and workload of the seal use case of ICEBERG.

**Comment by lee212** [comment]
According to PR (#1781), this has been resolved. It can be closed now.
