### ISSUE TITLE
Questions on MPI tutorial

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#1799]
1) when setting up the "ComputeUnit", the "cud.executable" should be on the local file system or on the remote hpc file system? 
2) (I assumed the latter) if this is the case, we need to log in the remote hpc system and compile the source code at least once, right?
3) I wrote a simple MPI code to simulate ER random graph and output the fraction of the largest connected component.

    I compiled the code on the stampede2. 
    I wrote the CU description as follows: (attached in the tar.gz, "b.py")
```
for i in range(0, n):
        # create a new CU description, and fill it.
        # Here we don't use dict initialization.
        cud = rp.ComputeUnitDescription()
        cud.executable       = '/home1/06078/tg853774/er_graph/er'
        cud.arguments        = [1000, 100, 0.05]
        cud.gpu_processes    = 0
        cud.cpu_processes    = 3
        cud.cpu_process_type = 'mpi'
        cuds.append(cud)
        report.progress()
```
The program takes three arguments. 
Are there any problems with this CU description? 
(This works for non-mpi simple tasks like /bin/date following the tutorial.)

4) the `agent_0.err` shows: 
   
```
2019-02-01 10:01:46,829: radical.saga        : MainProcess                     : MainThread     : WARNING : cannot initialize context - no session: {'LifeTime' : '-1', 'Type' : 'ssh', 'UserCert' : '/home1/06078/tg853774/.ssh/id_rsa.pub', 'UserKey' : '/home1/06078/tg853774/.ssh/id_rsa'}
Traceback (most recent call last):
  File "/work/06078/tg853774/stampede2/radical.pilot.sandbox/rp.session.js-169-25.jetstream-cloud.org.yren.017928.0000/pilot.0000/rp_install/bin/radical-pilot-agent", line 71, in <module>
    bootstrap_3(sys.argv[1])
  File "/work/06078/tg853774/stampede2/radical.pilot.sandbox/rp.session.js-169-25.jetstream-cloud.org.yren.017928.0000/pilot.0000/rp_install/bin/radical-pilot-agent", line 42, in bootstrap_3
    if agent_name == 'agent_0': agent = rpa.Agent_0(agent_name)
  File "/work/06078/tg853774/stampede2/radical.pilot.sandbox/rp.session.js-169-25.jetstream-cloud.org.yren.017928.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_0.py", line 118, in __init__
    session=self._session)
  File "/work/06078/tg853774/stampede2/radical.pilot.sandbox/rp.session.js-169-25.jetstream-cloud.org.yren.017928.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 229, in create
    return impl(cfg, session)
  File "/work/06078/tg853774/stampede2/radical.pilot.sandbox/rp.session.js-169-25.jetstream-cloud.org.yren.017928.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/slurm.py", line 20, in __init__
    LRMS.__init__(self, cfg, session)
  File "/work/06078/tg853774/stampede2/radical.pilot.sandbox/rp.session.js-169-25.jetstream-cloud.org.yren.017928.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/base.py", line 110, in __init__
    self._configure()
  File "/work/06078/tg853774/stampede2/radical.pilot.sandbox/rp.session.js-169-25.jetstream-cloud.org.yren.017928.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/rm/slurm.py", line 80, in _configure
    lfs_path = os.path.expandvars(lfs_path)
  File "/work/06078/tg853774/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.0.50.21/lib/python2.7/posixpath.py", line 287, in expandvars
    if '$' not in path:
TypeError: argument of type 'NoneType' is not iterable
```
(Note that, the "bash" script in tutorial_09_mpi shows the same error message.)
I have attached the tar ball for your inspection. 

5) Q. Is there a workflow such that we can stage the source code and compile remotely as well? 
6) here is the radical-stack: 

```
(rad) js-169-25$ radical-stack

  python               : 2.7.15
  pythonpath           : 
  virtualenv           : rad

  radical.pilot        : 0.50.21
  radical.utils        : 0.50.3
  saga                 : 0.50.5
```

**Comment by andre-merzky** [comment]
> 1. when setting up the "ComputeUnit", the "cud.executable" should be on the local file system or on the remote hpc file system?

On the remote filesystem.  It is possible to stage executable - but given the peculiarities of HPC machines and their compilers, I would advise against that, at least initially.

**Comment by andre-merzky** [comment]
> 2,  (I assumed the latter) if this is the case, we need to log in the remote hpc system and compile the source code at least once, right?
> 

Yes, indeed - or you ask the admins of the target resource to deploy your application for you.  Depending on the use case, size of user groups, policies etc. they might be willing to do so.

**Comment by andre-merzky** [comment]
> 3\. I wrote a simple MPI code to simulate ER random graph and output the fraction of the largest connected component.
>     I compiled the code on the stampede2.
>     I wrote the CU description as follows: (attached in the tar.gz, "b.py")
> 
> ```
> for i in range(0, n):
>         # create a new CU description, and fill it.
>         # Here we don't use dict initialization.
>         cud = rp.ComputeUnitDescription()
>         cud.executable       = '/home1/06078/tg853774/er_graph/er'
>         cud.arguments        = [1000, 100, 0.05]
>         cud.gpu_processes    = 0
>         cud.cpu_processes    = 3
>         cud.cpu_process_type = 'mpi'
>         cuds.append(cud)
>         report.progress()
> ```
> The program takes three arguments.
> Are there any problems with this CU description?
> (This works for non-mpi simple tasks like /bin/date following the tutorial.)

The only potential problem I see is that `/home` might not be available on the compute nodes.  But that very much depends on system configuration and policies.  Otherwise that description looks good to me.

**Comment by andre-merzky** [comment]
Yes, indeed.  In order to keep the compute unit descriptions uniform and independent from the target resource, you could put the executable path into your `$PATH` in `~/.bashrc`, or use some other env variable to point to that executable.

**Comment by andre-merzky** [comment]
closed as answered / outdated
