### ISSUE TITLE
RP fails on localhost during pilot launch

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#1831]
Snippet from pmgr.launching.child.log:
```
2019-03-14 14:43:21,825: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : pmgr.0000.launching.0.child.idler._pilot_watcher_cb: ERROR   : abort: read from process failed '[Errno 5] Input/output error' : (-0->PROMPT-0->PROMPT-0->PID: 27812
PROMPT-0->

RUNNING
OK
27905.0
PROMPT-0->
OK
BULK COMPLETED
PROMPT-0->

OK
STATE : RUNNING

START  : 1552588996

START_STDERR

END_STDERR

START_STDOUT

END_STDOUT

PROMPT-0->

trapped EXIT
cmd_quit called (1)PROMPT-1->
) (/home/vivek/Research/ves/ve-entk-susp-res/local/lib/python2.7/site-packages/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/vivek/Research/ves/ve-entk-susp-res/local/lib/python2.7/site-packages/radical/utils/futures.py", line 98, in run
    self._result = self._call(*self._args, **self._kwargs)
  File "/home/vivek/Research/ves/ve-entk-susp-res/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/vivek/Research/ves/ve-entk-susp-res/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line 1255, in container_get_states
    self.shell.run_async (bulk)
  File "/home/vivek/Research/ves/ve-entk-susp-res/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 762, in run_async
    self.pty_shell.flush ()
  File "/home/vivek/Research/ves/ve-entk-susp-res/local/lib/python2.7/site-packages/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/vivek/Research/ves/ve-entk-susp-res/local/lib/python2.7/site-packages/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
  File "/home/vivek/Research/ves/ve-entk-susp-res/local/lib/python2.7/site-packages/saga/exceptions.py", line 441, in __init__
    SagaException.__init__ (self, msg, parent, api_object, from_log)
Traceback (most recent call last):
  File "/home/vivek/Research/ves/ve-entk-susp-res/local/lib/python2.7/site-packages/radical/utils/threads.py", line 375, in _run
    if not self.work_cb():
  File "/home/vivek/Research/ves/ve-entk-susp-res/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 954, in work_cb
    ret = self._cb()
  File "/home/vivek/Research/ves/ve-entk-susp-res/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 270, in _pilot_watcher_cb
    states = tc.get_states()
  File "/home/vivek/Research/ves/ve-entk-susp-res/local/lib/python2.7/site-packages/saga/task.py", line 630, in get_states
    raise future.exception
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->PROMPT-0->PROMPT-0->PID: 27812
```

All logs attached:
[re.session.vivek-ThinkPad-X1-Carbon-6th.vivek.017969.0011.zip](https://github.com/radical-cybertools/radical.pilot/files/2968018/re.session.vivek-ThinkPad-X1-Carbon-6th.vivek.017969.0011.zip)

**Comment by vivek-bala** [comment]
This is required for testing the pipeline suspend/resume functionality in EnTK.

**Comment by andre-merzky** [comment]
Hmm, this is surprising.  This is a new `localhost` - the X1 is nice :-D , right?  What is the RCT stack you are using?

**Comment by vivek-bala** [comment]
Lol where does it say X1 :)

radical-stack:
```
$ radical-stack

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/vivek/Research/ves/ve-entk-susp-res

  radical.entk         : 0.7.13-0.7.11-63-gd411a37@feature-suspend_resume
  radical.pilot        : 0.50.22
  radical.utils        : 0.50.3
  saga                 : 0.50.5
```
Ubuntu: 16.04

**Comment by andre-merzky** [comment]
`re.session.vivek-ThinkPad-X1-Carbon-6th` ;-)   But 16.04 is not new anyway...  Hmm, did RP work on that machine before>  what changed?  Do plain RP examples work?

The stack looks ok.  If that persists, can you please run with `RADICAL_SAGA_PTY_VERBOSE=DEBUG`?   What you see is a timeout on the pty level - I don't see an immediate reason on why that would happen suddenly...

**Comment by vivek-bala** [comment]
Yea it did. Last time I had an issue running locally, I had to remove $HOME/.saga and it worked. 
I set the pty verbose level and ran the RP getting started example. Got the same issue.
See logs attached.

[rp.session.vivek-ThinkPad-X1-Carbon-6th.vivek.017969.30812.zip](https://github.com/radical-cybertools/radical.pilot/files/2968260/rp.session.vivek-ThinkPad-X1-Carbon-6th.vivek.017969.30812.zip)

**Comment by andre-merzky** [comment]
thanks  Vivek - but the interesting output (`pmgr.0000.launching.0.child.err`) is truncated :(  Can you please rerun, and after things fail, make sure that all python processes are killed, and the run `sync`, and then pack up again?  Thanks, sorry for the troubles...

**Comment by vivek-bala** [comment]
Sure yea. What do you mean by "and the run sync" though?

**Comment by andre-merzky** [comment]
I mean running the shell command `sync` to flush disk caches.

**Comment by vivek-bala** [comment]
Okay ran it again and followed it up with ```sync```. Logs attached. 
[rp.session.vivek-ThinkPad-X1-Carbon-6th.vivek.017970.0000.zip](https://github.com/radical-cybertools/radical.pilot/files/2970127/rp.session.vivek-ThinkPad-X1-Carbon-6th.vivek.017970.0000.zip)

**Comment by andre-merzky** [comment]
Does the error happen on every run?

I can't yet see whats up,  I am sorry - the launcher process seems to hang on something until the pty layer times out, but the logs don't let me see on what exactly.  The pty logs are still incomplete, I am not sure why the Python log layer is not flushing to disk (every entry *should* be atomic).  Your disk does not happen to be full (just grabbing at straws...)?

Vivek, if that delays the suspend/resume debug, can you move to the radical server?  If the problem persists there, I can attach to the process and debug where it hangs (it has a 5 min timeout AFAICS).

**Comment by vivek-bala** [comment]
Yes, it happens on every run. Disk is not full no. Also, the entire failed run takes about 2 minutes (not 5), in case that gives you a hint.

Yes, let me try it on radical.two.

**Comment by andre-merzky** [comment]
@vivek-bala : I  am not really sure how to resolve this one.  Can I get access to that machine by any chance?

**Comment by andre-merzky** [comment]
Closed for lack of activity
