### ISSUE TITLE
worker bound method Continuous._schedule_units failed

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#1918]
Hello all i was trying to request 8 GPUs to run 20 CUs on Bridges, each CU is taking only 1 gpu, i am stuck in this error below :

``` 
2019-07-14 03:52:08,399: agent_0.scheduling.0.child: agent_0.scheduling.0            : MainThread     : ERROR   : worker <bound method Continuous._schedule_units of <Continuous(agent_0.scheduling.0, started)>> failed
Traceback (most recent call last):
  File "/pylon5/mc3bggp/aymen/radical.pilot.sandbox/rp.session.js-17-21.jetstream-cloud.org.aymen.018089.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1267, in work_cb
    self._workers[state](things)
  File "/pylon5/mc3bggp/aymen/radical.pilot.sandbox/rp.session.js-17-21.jetstream-cloud.org.aymen.018089.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/base.py", line 479, in _schedule_units
    if self._try_allocation(unit):
  File "/pylon5/mc3bggp/aymen/radical.pilot.sandbox/rp.session.js-17-21.jetstream-cloud.org.aymen.018089.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/continuous.py", line 191, in _try_allocation
    unit['slots'] = self._allocate_slot(unit['description'])
  File "/pylon5/mc3bggp/aymen/radical.pilot.sandbox/rp.session.js-17-21.jetstream-cloud.org.aymen.018089.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/continuous.py", line 237, in _allocate_slot
    slots = self._alloc_nompi(cud)
  File "/pylon5/mc3bggp/aymen/radical.pilot.sandbox/rp.session.js-17-21.jetstream-cloud.org.aymen.018089.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/continuous.py", line 469, in _alloc_nompi
    mem_chunk=mem_chunk)
  File "/pylon5/mc3bggp/aymen/radical.pilot.sandbox/rp.session.js-17-21.jetstream-cloud.org.aymen.018089.0002/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/scheduler/continuous.py", line 332, in _find_resources
    if requested_gpus : nprocs.append(min(requested_gpus,  free_gpus)  / gpu_chunk)
ZeroDivisionError: integer division or modulo by zero
```
`Python Version: Python 2.7.16:: Anaconda custom (64-bit)`

P.S : if i don't assign the ` cud.gpu_processes    = 1` or any number of gpus the error will not be existed but i will have another error wihch is no enough CUDA memory 
```


 Radical stack : python  : 2.7.16
 virtualenv           : penguins2
 radical.pilot        : 0.62.0
 radical.saga         : 0.62.0
 radical.utils        : 0.62.0
```
`Resource used ` : `xsede.bridges`

`Pilot`
```
pd_init = {
                   'resource'      : 'xsede.bridges',
                   'runtime'       : args.runtime,  # pilot runtime (min)
                   'exit_on_error' : True,
                   'project'       : args.project,
                   'queue'         : args.queue,
                   'access_schema' : 'gsissh',
                   'cores'         : args.cpus,
                   'gpus'          : '8'
                  }
```
`CU`
```
cud = rp.ComputeUnitDescription()
            cud.pre_exec         =  ['export CUDA_VISIBLE_DEVICES=%d' % gpu_id]
            cud.executable       =   'python'
            cud.arguments        = [ ******] 
            cud.gpu_processes    = 1
            cud.cpu_processes    = 1
            cud.cpu_threads      = 1
            cud.cpu_process_type = rp.POSIX
            cud.cpu_thread_type  = rp.POSIX

            cuds.append(cud)
```
[xsede_bridges_session.zip](https://github.com/radical-cybertools/radical.pilot/files/3390218/xsede_bridges_session.zip)

[jetstream_session.zip](https://github.com/radical-cybertools/radical.pilot/files/3390216/jetstream_session.zip)

**Comment by andre-merzky** [comment]
This was fixed in the last release, via this line: https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/scheduler/continuous.py#L470.  Pleas try to update and let us know how it goes!

**Comment by AymenFJA** [comment]
Using the current `radical-stack` :
```
  radical.pilot        : 0.70.0
  radical.saga         : 0.70.0
  radical.utils        : 0.70.0
```
solved the issue, this ticket will be closed now .
