### ISSUE TITLE
Frontera agent error

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1970]
```
  python               : 2.7.16
  pythonpath           : /opt/apps/intel19/impi19_0/python2/2.7.16/lib/python2.7/site-packages
  virtualenv           : /home1/02855/mturilli/ve/test

  radical.pilot        : 0.73.0
  radical.saga         : 0.72.1
  radical.utils        : 0.72.0
```

```
$ cat agent_0.err 
Traceback (most recent call last):
  File "/scratch1/02855/mturilli/radical.pilot.sandbox/rp.session.login4.frontera.tacc.utexas.edu.mturilli.018176.0000/pilot.0000/rp_install/bin/radical-pilot-agent", line 71, in <module>
    bootstrap_3(sys.argv[1])
  File "/scratch1/02855/mturilli/radical.pilot.sandbox/rp.session.login4.frontera.tacc.utexas.edu.mturilli.018176.0000/pilot.0000/rp_install/bin/radical-pilot-agent", line 46, in bootstrap_3
    agent.start(spawn=False)
  File "/scratch1/02855/mturilli/radical.pilot.sandbox/rp.session.login4.frontera.tacc.utexas.edu.mturilli.018176.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/process.py", line 573, in start
    self._ru_initialize()
  File "/scratch1/02855/mturilli/radical.pilot.sandbox/rp.session.login4.frontera.tacc.utexas.edu.mturilli.018176.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/process.py", line 895, in _ru_initialize
    self.ru_initialize_parent()
  File "/scratch1/02855/mturilli/radical.pilot.sandbox/rp.session.login4.frontera.tacc.utexas.edu.mturilli.018176.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 593, in ru_initialize_parent
    self.initialize_parent()
  File "/scratch1/02855/mturilli/radical.pilot.sandbox/rp.session.login4.frontera.tacc.utexas.edu.mturilli.018176.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_0.py", line 160, in initialize_parent
    self._start_sub_agents()
  File "/scratch1/02855/mturilli/radical.pilot.sandbox/rp.session.login4.frontera.tacc.utexas.edu.mturilli.018176.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/agent_0.py", line 388, in _start_sub_agents
    launch_script_hop='/usr/bin/env RP_SPAWNER_HOP=TRUE "%s"' % ls_name)
  File "/scratch1/02855/mturilli/radical.pilot.sandbox/rp.session.login4.frontera.tacc.utexas.edu.mturilli.018176.0000/pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/agent/lm/srun.py", line 65, in construct_command
    sbox         = cu['unit_sandbox_path']
KeyError: 'unit_sandbox_path'
```

**Comment by andre-merzky** [comment]
This specific error is resolved by now.
