### ISSUE TITLE
pty error with Stampede2 and p3

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#1979]
Please provide all error messaages and the output of the following commands:

```
$ python -V
Python 3.5.2
$ radical-stack

  python               : 3.5.2
  pythonpath           : 
  virtualenv           : /home/mturilli/Virtualenvs/stampede2-p3

  radical.pilot        : 0.90.1-v0.90.1-44-gbcf9a01f@devel
  radical.saga         : 0.90.0
  radical.utils        : 0.90.3
```
Attempting to running `./heterogeneous.py` on `stampede2`, `ssh` method. Consistently get the following trace:
```
Traceback (most recent call last):
  File "./heterogeneous.py", line 25, in <module>
    pilot = pmgr.submit_pilots(pdesc)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/pilot/pilot_manager.py", line 502, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/pilot/compute_pilot.py", line 102, in __init__
    self._resource_sandbox = self._session._get_resource_sandbox(pilot)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/pilot/session.py", line 1003, in _get_resource_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/saga/utils/pty_shell.py", line 244, in __init__
    interactive=self.interactive)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/saga/utils/pty_shell_factory.py", line 199, in initialize
    self._initialize_pty(info['pty'], info)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/saga/utils/pty_shell_factory.py", line 420, in _initialize_pty
    raise ptye.translate_exception (e)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/saga/utils/pty_shell_factory.py", line 292, in _initialize_pty
    if time.time() - time_start > timeout:
TypeError: unorderable types: float() > str()
```

**Comment by andre-merzky** [comment]
fixed by casting in RU config parsing
