### ISSUE TITLE
RP fails with '>' not supported between instances of 'float' and 'str' on Comet

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#1994]
```
  python               : 3.7.0
  pythonpath           :
  virtualenv           : /home/aymen/rp_py3_test

  radical.pilot        : 0.90.1-v0.90.1-59-gf726cb2@devel
  radical.saga         : 0.90.0
  radical.utils        : 0.90.3

```
```
Traceback (most recent call last):
  File "00_getting_started.py", line 68, in <module>
    pilot = pmgr.submit_pilots(pdesc)
  File "/home/aymen/rp_py3_test/lib/python3.7/site-packages/radical/pilot/pilot_manager.py", line 537, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/home/aymen/rp_py3_test/lib/python3.7/site-packages/radical/pilot/compute_pilot.py", line 102, in __init__
    self._resource_sandbox = self._session._get_resource_sandbox(pilot)
  File "/home/aymen/rp_py3_test/lib/python3.7/site-packages/radical/pilot/session.py", line 1003, in _get_resource_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/aymen/rp_py3_test/lib/python3.7/site-packages/radical/saga/utils/pty_shell.py", line 244, in __init__
    interactive=self.interactive)
  File "/home/aymen/rp_py3_test/lib/python3.7/site-packages/radical/saga/utils/pty_shell_factory.py", line 199, in initialize
    self._initialize_pty(info['pty'], info)
  File "/home/aymen/rp_py3_test/lib/python3.7/site-packages/radical/saga/utils/pty_shell_factory.py", line 420, in _initialize_pty
    raise ptye.translate_exception (e)
  File "/home/aymen/rp_py3_test/lib/python3.7/site-packages/radical/saga/utils/pty_shell_factory.py", line 292, in _initialize_pty
    if time.time() - time_start > timeout:
TypeError: '>' not supported between instances of 'float' and 'str'
```

This is fixable, should I provide a PR for this issue?  @andre-merzky

**Comment by andre-merzky** [comment]
Oh, I thought this was fixed - can you please try the RU `devel` branch, please?

**Comment by AymenFJA** [comment]
Thanks. It did work. I will keep testing it on `Comet`
