### ISSUE TITLE
Restless Heartbeat on slow filesystem? Summit

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#2004]
rp fails on summit if heartbeat is set 1 second (which is default):
```
$ python 00_getting_started.py.bak ornl.summit

================================================================================
 Getting Started (RP version 0.90.6)
================================================================================

new session: [rp.session.login2.hrlee.018241.0002]                             \
database   : [mongodb://rct:rct_test@two.radical-project.org:27017/rct_test]============= session
Traceback (most recent call last):
  File "00_getting_started.py.bak", line 37, in <module>
    session = rp.Session()
  File "/ccs/home/hrlee/venv3/entk.copy2/lib/python3.7/site-packages/radical/pilot/session.py", line 146, in __init__
    self._initialize_primary(dburl)
  File "/ccs/home/hrlee/venv3/entk.copy2/lib/python3.7/site-packages/radical/pilot/session.py", line 191, in _initialize_primary
    self._cmgr.start_components()
  File "/ccs/home/hrlee/venv3/entk.copy2/lib/python3.7/site-packages/radical/pilot/utils/component.py", line 232, in start_components
    raise RuntimeError('could not start all components %s' % failed)
RuntimeError: could not start all components ['update.0000']
```
and the radical.log indicates the expiration of the timeout:
```
1576022723.358 : control_pubsub       : 86545 : 140735435698608 : WARNING  : hb control_pubsub[cmgr.0000]: 1576022723.4 - 1576022722.4 > 1: timeout
1576022723.358 : control_pubsub       : 86545 : 140735435698608 : WARNING  : hb fail cmgr.0000: fatal (86545)
```

Increasing the timeout e.g. 30 sec easily solves the problem.

https://github.com/radical-cybertools/radical.pilot/blob/4f05a4fd768842b02ad3d11644d0e6e8543e28cc/src/radical/pilot/configs/session_default.json#L15

**Comment by mturilli** [comment]
@andre-merzky is the heartbeat timeout configuration exposed in a config file? If not, should we expose it, maybe for the moment in the resource configuration file, so that we could set different timeouts for each resource?

**Comment by andre-merzky** [comment]
It is exposed, in the config files for the session  (client side) and agent (agent side).  I'll increase the default values to a minute, ok?
