### ISSUE TITLE
RuntimeError could not start all bridges

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#2014]
```
hrlee@two:~/radical.pilot.sandbox/re.session.two.hrlee.018247.0006/pilot.0000$ more agent.0.out
bootstrap agent agent.0
new session: [re.session.two.hrlee.018247.0006]                               ok
failed agent.0
--------------
RADICAL Utils -- Stacktrace [4383] [MainThread]

hrlee     4383  3371  1 03:18 pts/72   00:00:00          \_ rp.agent.0
Traceback (most recent call last):
File "/home/hrlee/radical.pilot.sandbox/re.session.two.hrlee.018247.0006/pilot.0000/rp_install/bin/radical-pilot-agent", line 50, in bootstrap_3
if aid == 'agent.0': agent = rp.Agent_0(cfg, session)
File "/home/hrlee/radical.pilot.sandbox/re.session.two.hrlee.018247.0006/pilot.0000/rp_install/lib/python3.5/site-packages/radical/pilot/agent/agent_0.py", l
ine 76, in __init__
self._cmgr.start_bridges()
File "/home/hrlee/radical.pilot.sandbox/re.session.two.hrlee.018247.0006/pilot.0000/rp_install/lib/python3.5/site-packages/radical/pilot/utils/component.py",
 line 173, in start_bridges
raise RuntimeError('could not start all bridges %s' % failed)
RuntimeError: could not start all bridges ['control_pubsub', 'agent_scheduling_queue', 'funcs_res_queue', 'agent_unschedule_pubsub', 'log_pubsub', 'agent_sch
edule_pubsub', 'agent_staging_output_queue', 'agent_executing_queue', 'funcs_wrk_queue', 'agent_staging_input_queue', 'state_pubsub']
```

```
(entk) hrlee@two:~/git/radical.entk/examples/user_guide$ radical-stack

  python               : 3.5.2
  pythonpath           :
  virtualenv           : /home/hrlee/venv3/entk

  radical.entk         : 0.90.6-v0.72.0-84-g5357e08a@fix-issue_393
  radical.pilot        : 0.90.8-v0.90.1-172-g627b65db@devel
  radical.saga         : 0.90.6-bv0.72.1-67-g5deb253b@devel
  radical.utils        : 0.90.8-v0.90.3-179-g05efb5b@fix-ru_stack
```
```
(entk) hrlee@two:~/git/radical.entk/examples/user_guide$ python get_started.py
EnTK session: re.session.two.hrlee.018247.0006
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
new session: [re.session.two.hrlee.018247.0006]                                \
database   : [mongodb://rct:rct_test@two.radical-project.org/rct_test]        ok
create pilot manager                                                          ok
submit 1 pilot(s)
        [local.localhost:1]
                                                                              ok

wait for 1 pilot(s)
                                                                              ok
closing session re.session.two.hrlee.018247.0006                               \
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
session lifetime: 110.1s                                                      ok
All components terminated
Traceback (most recent call last):
  File "get_started.py", line 61, in <module>
    appman.run()
  File "/home/hrlee/venv3/entk/lib/python3.5/site-packages/radical/entk/appman/appmanager.py", line 385, in run
    'ended in state %s' % res_alloc_state)
radical.entk.exceptions.EnTKError: Cannot proceed. Resource ended in state FAILED

```

**Comment by andre-merzky** [comment]
See #2018 for related work - but the problem itself needs to be fixed by a system python update.
