### ISSUE TITLE
radical-pilot-bridge missing

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.pilot#2022]
Running python3 on summit fails to find radical-pilot-bridge
```
radical-pilot-bridge                                         
error: invalid arguments                                                                              
usage: /ccs/home/eh22/.conda/envs/vamp5/bin/radical-pilot-bridge                            
Traceback (most recent call last):                                                                    
  File "/ccs/home/eh22/.conda/envs/vamp5/bin/radical-pilot-bridge", line 155, in              
    raise RuntimeError('invalid arguments: %s' % sys.argv)                                            
RuntimeError: invalid arguments: ['/ccs/home/eh22/.conda/envs/vamp5/bin/radical-pilot-bridge']        
```
python -V
```
Python 3.7.3
```
radical-stack
```
python               : 3.7.3                                                                        
  pythonpath           : /sw/summit/xalt/1.1.4/site:/sw/summit/xalt/1.1.4/libexec                     
  virtualenv           : vamp5                                                                        
  radical.entk         : 0.90.6-v0.72.0-89-g6c8cf2c@devel                                             
  radical.pilot        : 0.90.8-v0.90.1-223-g2917c34@devel                                            
  radical.saga         : 0.90.6-bv0.72.1-67-g5deb253@devel                                            
  radical.utils        : 0.90.8-v0.90.3-183-g3c12c19@devel    
```

**Comment by euhruska** [comment]
the session contains the radical-pilot-bridge, but it still fails
[re.session.login5.eh22.018249.0034.zip](https://github.com/radical-cybertools/radical.pilot/files/3984554/re.session.login5.eh22.018249.0034.zip)

**Comment by lee212** [comment]
I confirm this is related to`conda` which I can replicate by:
```
module load python/3.6.6-anaconda3-5.3.0
conda create -n entk.conda.py3 python=3.7
conda activate entk.conda.py3
```

with the conda init lines at `.bashrc` or `.bash_profile`:
```
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/sw/summit/python/3.6/anaconda3/5.3.0/bin/conda' 'shell.bash'
'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/sw/summit/python/3.6/anaconda3/5.3.0/etc/profile.d/conda.sh" ]; th
en
        . "/sw/summit/python/3.6/anaconda3/5.3.0/etc/profile.d/conda.sh"
    else
        export PATH="/sw/summit/python/3.6/anaconda3/5.3.0/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

**Comment by andre-merzky** [comment]
@lee212 : I tried your conda VE setup, but that seems to work as expected.  I create a VE with your commands, install the RP devel branch with `pip install .`, and get:

```sh
$ which radical-pilot-bridge
~/.conda/envs/entk.conda.py3/bin/radical-pilot-bridge
```

Is that different for you?

As for the problem @euhruska encounters: I think I can see how the installation done by the bootstrapper can confuse `$PATH`.  I don't fully understand how that is different from virutualenv, but let me work on a fix attempt.

Thanks both, Andre.

**Comment by lee212** [comment]
@andre-merzky , you're correct. I also have the command in my `$PATH`. 
```
(entk.py3.conda) [hrlee@login2.summit pilot.0000]$ which radical-pilot-bridge
~/.conda/envs/entk.py3.conda/bin/radical-pilot-bridge
```
The `FileNotFound` problem was on the remote, not the client. For example, my `get_started.py` fails with:
```
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
session lifetime: 73.3s                                                       ok
All components terminated
Traceback (most recent call last):
  File "get_started.py", line 38, in <module>
    appman.run()
  File "/ccs/home/hrlee/.conda/envs/entk.py3.conda/lib/python3.7/site-packages/radical/entk/appman/appmanager.py", line 385, in run
    'ended in state %s' % res_alloc_state)
radical.entk.exceptions.EnTKError: Cannot proceed. Resource ended in state FAILED
```
and `agent.0.out` on sandbox shows: 
```
(entk.py3.conda) [hrlee@login2.summit pilot.0000]$ more agent.0.out
bootstrap agent agent.0
failed agent.0
--------------
RADICAL Utils -- Stacktrace [75512] [MainThread]

hrlee     75512  74634 15 11:44 ?        00:00:00                  \_ rp.agent.0
Traceback (most recent call last):
File "/gpfs/alpine/scratch/hrlee/bip191/radical.pilot.sandbox/re.session.login2.hrlee.018250.0000/pilot.0000/rp_install/bin/radical-pilot-agent", line 50, in bootstrap_3
if aid == 'agent.0': agent = rp.Agent_0(cfg, session)
File "/gpfs/alpine/scratch/hrlee/bip191/radical.pilot.sandbox/re.session.login2.hrlee.018250.0000/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/agent_0.py", line 76, in __init__
self._cmgr.start_bridges()
File "/gpfs/alpine/scratch/hrlee/bip191/radical.pilot.sandbox/re.session.login2.hrlee.018250.0000/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/utils/component.py", line 162, in start_bridges
out, err, ret = ru.sh_callout('radical-pilot-bridge %s' % fname)
File "/gpfs/alpine/scratch/hrlee/bip191/radical.pilot.sandbox/re.session.login2.hrlee.018250.0000/pilot.0000/rp_install/lib/python3.7/site-packages/radical/utils/shell.py", line 30, in sh_callout
p = sp.Popen(cmd, stdout=stdout, stderr=stderr, shell=shell)
File "/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/subprocess.py", line 756, in __init__
restore_signals, start_new_session)
File "/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/lib/python3.7/subprocess.py", line 1499, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'radical-pilot-bridge': 'radical-pilot-bridge'

--------------
finalize agent.0
```

**Comment by andre-merzky** [comment]
Thanks @lee212 , that makes sense then.  I'll assume the bootstrapper is (in some cases) incorrectly setting the  `PATH`.  I'm on it.

**Comment by andre-merzky** [comment]
@lee212 , @euhruska : could you please  give the RP branch `fix/issue_2022` a try?  Thanks!

**Comment by euhruska** [comment]
confirmed, the conda installation finds now radical-pilot-bridge. The run looks ok too
