### ISSUE TITLE
Bootstrap still tries to install orte_cffi

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2056]
```
$ radical-stack 

  python               : 3.7.6
  pythonpath           : 
  virtualenv           : /home/mturilli/Virtualenvs/rp-testing

  radical.pilot        : 1.0.0-v1.0.0-72-g47132d5@devel
  radical.saga         : 1.0.1-v1.0.1-7-g265601d@devel
  radical.utils        : 1.0.0-v1.0.0-31-ga6ecd7a@devel
```
From `bootstrap_0.out` in the sandbox on Stampede2:
```
#
# install orte_cffi
# cmd: /work/02855/mturilli/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.1.0.0/bin/pip --no-cache-dir install --no-build-isolation orte_cffi
#
Collecting orte_cffi
  Downloading orte-cffi-0.4.1.tar.gz (2.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /work/02855/mturilli/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.1.0.0/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mneiqqjr/orte-cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mneiqqjr/orte-cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-mneiqqjr/orte-cffi/pip-egg-info
         cwd: /tmp/pip-install-mneiqqjr/orte-cffi/
    Complete output (40 lines):
    Traceback (most recent call last):
      File "src/orte-cffi/build.py", line 18, in ompi_info_path
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/opt/apps/intel18/python3/3.7.0/lib/python3.7/subprocess.py", line 756, in __init__
        restore_signals, start_new_session)
      File "/opt/apps/intel18/python3/3.7.0/lib/python3.7/subprocess.py", line 1499, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'ompi_info': 'ompi_info'
[...]
```
This error is nonfatal but we should probably avoid to try to install it anyway as it does not exist anymore.

**Comment by mtitov** [comment]
module `orte_cffi` was removed from the [bootstrap script](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/bootstrap_0.sh#L112)
