### ISSUE TITLE
unusable lm MPIRUN

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#2063]
I verbally discussed this issue with Kartik but couldn't find a ticket created under RP here.

localhost run hangs (including 00_getting_started.py example), and found out the error message:

```
1581099154.988 : test.0011            : 87678 : 123145353703424 : DEBUG    : create LaunchMethod: <class 'radical.pilot.agent.launch_method.fork.Fork'>
1581099154.989 : test.0011            : 87678 : 123145353703424 : DEBUG    : create LaunchMethod: <class 'radical.pilot.agent.launch_method.mpirun.MPIRun'>
1581099154.989 : test.0011            : 87678 : 123145353703424 : ERROR    : unusable lm MPIRUN
Traceback (most recent call last):
  File "/Users/hrlee/radical.pilot.sandbox/test.0011/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/base.py", line 168, in create
    return impl(name, cfg, session)
  File "/Users/hrlee/radical.pilot.sandbox/test.0011/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/mpirun.py", line 20, in __init__
    LaunchMethod.__init__(self, name, cfg, session)
  File "/Users/hrlee/radical.pilot.sandbox/test.0011/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/base.py", line 91, in __init__
    self._configure()
  File "/Users/hrlee/radical.pilot.sandbox/test.0011/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/mpirun.py", line 72, in _configure
    self._get_mpi_info(self.launch_command)
  File "/Users/hrlee/radical.pilot.sandbox/test.0011/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/base.py", line 375, in _get_mpi_info
    raise ValueError('no executable found')
ValueError: no executable found
...
```

This error was captured during the EnTK unit test: test_rmgr_rp_get_resource_allocation_state but it is failing because of missing mpirun executable.

```
(entk.copy.2) (base) nbp-25-108-51:radical.entk hrlee$ radical-stack

  python               : 3.7.4
  pythonpath           :
  virtualenv           : /Users/hrlee/venv3/entk.copy.2

  radical.entk         : 1.0.0
  radical.pilot        : 1.0.0-v1.0.0-102-gf58b0122@devel
  radical.saga         : 1.0.1
  radical.utils        : 1.0.0-v1.0.0-31-ga6ecd7a@devel
```

**Comment by lee212** [comment]
I find PR #2041 fixes this and it's already merged to `devel` branch. Close this
