### ISSUE TITLE
Exception in 00_getting_started.py script from devel branch

### ISSUE THREAD

**Issue by Abdullah-Ghani** [radical-cybertools/radical.pilot#2071]
Cloned and checked out the devel branch. I was getting timeout error when waiting for pilots in master branch but now am getting both an exception and timeout

```
(ve) abdullahg@js-156-107:~/radical.pilot/examples$ git branch 
* devel
(ve) abdullahg@js-156-107:~/radical.pilot/examples$ radical-stack

  python               : 3.7.6
  pythonpath           : 
  virtualenv           : /home/abdullahg/ve

  radical.pilot        : 1.0.0
  radical.saga         : 1.0.1
  radical.utils        : 1.0.0

(ve) abdullahg@js-156-107:~/radical.pilot/examples$ python 00_getting_started.py 

================================================================================
 Getting Started (RP version 1.0.0)                                             
================================================================================

new session: [rp.session.js-156-107.jetstream-cloud.org.abdullahg.018305.0001] \
database   : [mongodb://rct:rct_test@two.radical-project.org/rct_test]        ok
create pilot manager                                                          ok
create unit manager                                                           ok

--------------------------------------------------------------------------------
submit pilots                                                                   

submit 1 pilot(s)
        [local.localhost:1]
                                                                              ok

--------------------------------------------------------------------------------
submit 1024 units                                                               

add 1 pilot(s)                                                                ok
caught Exception: progress_tgt() got an unexpected keyword argument 'label'
--------------
RADICAL Utils -- Stacktrace [26001] [MainThread]

abdulla+ 26001 22711  4 12:14 pts/7    00:00:00              \_ python 00_getting_started.py
abdulla+ 26380 26001  4 12:14 pts/17   00:00:00                  \_ /bin/bash -i
abdulla+ 26393 26001  5 12:14 pts/18   00:00:00                  \_ /bin/sh -i
Traceback (most recent call last):
File "00_getting_started.py", line 75, in <module>
report.progress_tgt(n, label='create')
TypeError: progress_tgt() got an unexpected keyword argument 'label'

--------------

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.js-156-107.jetstream-cloud.org.abdullahg.018305.0001\
close unit manager                                                            ok
close pilot manager                                                            \
wait for 1 pilot(s)
              0                                                          timeout
                                                                              ok
+ rp.session.js-156-107.jetstream-cloud.org.abdullahg.018305.0001 (json)
+ pilot.0000 (profiles)
- pilot.0000 (logfiles)
session lifetime: 18.3s                                                       ok
Traceback (most recent call last):
  File "00_getting_started.py", line 75, in <module>
    report.progress_tgt(n, label='create')
TypeError: progress_tgt() got an unexpected keyword argument 'label'
```

**Comment by andre-merzky** [comment]
Hi @Abdullah-Ghani : I should have mentioned that, apologies: when using a devel branch in RP, its usually the case that you will also need a devel branch in RU, as some of the supporting code often goes to the utility layer.

Having said that: all those branches are released now, and you should be able to install the default stack from pypi.

FWIW: the timeout message you got was an erroneous message, but the execution was not affected by the message.

**Comment by Abdullah-Ghani** [comment]
fixed with the version update. Thank you.
