### ISSUE TITLE
Issue with allocating more than one core on Stampede 

### ISSUE THREAD

**Issue by Abdullah-Ghani** [radical-cybertools/radical.pilot#2081]
Issue still persists after version update.

 ```
pd_init = {'resource'      : 'xsede.stampede2_ssh',
                   'queue'         : 'normal',
                   'project'       : 'TG-MCB090174',
                   'queue'         : 'development',
                   'access_schema' : 'gsissh',
                   'runtime'       : 60,
                   'exit_on_error' : True,
                   'cores'         : 60
                  }

        pdesc = rp.ComputePilotDescription(pd_init)
```

```
$ radical-stack

  python               : 3.7.6
  pythonpath           : 
  virtualenv           : /home/abdullahg/ve

  radical.pilot        : 1.1.0
  radical.saga         : 1.1.0
  radical.utils        : 1.1.1

```
The error:

```
$ grep ERROR *.*
grep: pilot.0000: Is a directory
pmgr.0000.log:1582052148.468 : pmgr.0000            : 11485 : 140688893142784 : ERROR    : [Callback]: pilot 'pilot.0000' failed - exit
pmgr.0000.log:1582052148.468 : pmgr.0000            : 11485 : 140688893142784 : ERROR    : listener died
pmgr_launching.0000.log:1582052148.464 : pmgr_launching.0000  : 11619 : 140494607775488 : ERROR    : bulk launch failed
radical.saga.cpi.log:1582052148.463 : radical.saga.cpi     : 11619 : 140493547632384 : ERROR    : NoSuccess: Couldn't get job id from submitted job! sbatch output:
rp.session.js-156-107.jetstream-cloud.org.abdullahg.018310.0001.log:1582052158.033 : rp.session.js-156-107.jetstream-cloud.org.abdullahg.018310.0001 : 11485 : 140690915473152 : ERROR    : failed to fet profile for pilot.0000

```

**Comment by andre-merzky** [comment]
Hi @Abdullah-Ghani : you saw the `ERROR` log entries in `pmgr_launching.0000.log`: can you have a look into that logfile, and check what causes this?  You will likely find an stack trace or a trace of the slurm error message close to the ERROR log entry.

**Comment by Abdullah-Ghani** [comment]
Thank you @andre-merzky .

This is the output for both files.
```
abdullahg@js-156-107:~/ve/share/radical.pilot/examples/rp.session.js-156-107.jetstream-cloud.org.abdullahg.018312.0001$ cat radical.saga.cpi.log
1582214601.490 : radical.saga.cpi     : 13376 : 140430154901248 : ERROR    : NoSuccess: Couldn't get job id from submitted job! sbatch output:

-----------------------------------------------------------------
          Welcome to the Stampede2 Supercomputer                 
-----------------------------------------------------------------

--> Submission error: please define total core count with the "-n" option
rm -f tmp_izrxdux1.slurm


```

```
cat pmgr_launching.0000.log 
1582214601.492 : pmgr_launching.0000  : 13376 : 140430811850496 : ERROR    : bulk launch failed
Traceback (most recent call last):
  File "/home/abdullahg/ve/local/lib/python3.7/site-packages/radical/pilot/pmgr/launching/default.py", line 553, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/abdullahg/ve/local/lib/python3.7/site-packages/radical/pilot/pmgr/launching/default.py", line 814, in _start_pilot_bulk
    jc.run()
  File "/home/abdullahg/ve/local/lib/python3.7/site-packages/radical/saga/task.py", line 411, in run
    raise se.NoSuccess ("future exception: %s" % (future.exception))
radical.saga.exceptions.NoSuccess: future exception: Couldn't get job id from submitted job! sbatch output:

-----------------------------------------------------------------
          Welcome to the Stampede2 Supercomputer                 
-----------------------------------------------------------------
```

**Comment by andre-merzky** [comment]
> `please define total core count with the "-n" option`

This should actually be fixed already, so my suspicion is that your RCT stack needs updating.  Can you please post the output of the command `radical-stack`?  Thanks.

**Comment by Abdullah-Ghani** [comment]
```
$ radical-stack 

  python               : 3.7.6
  pythonpath           : 
  virtualenv           : /home/abdullahg/ve

  radical.pilot        : 1.1.1
  radical.saga         : 1.1.0
  radical.utils        : 1.1.1

```

**Comment by andre-merzky** [comment]
Duh, it appears that the recent fix for Stampede2 did not make it into the release.  I pushed out a hotfix - if you could please upgrade RS, you should get that to version 1.1.1 also, and the problem should be fixed.  Thanks!

**Comment by Abdullah-Ghani** [comment]
thank you.
