### ISSUE TITLE
AttributeError: module 'radical.utils' has no attribute 'to_byte'

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2087]
After upgrading to latest devel  to reduce log size, every run fails with:
```
1582732236.579 : umgr_staging_input.0000 : 113101 : 47791327127296 : ERROR    : work <bound method Default.work of <radical.pilot.umgr.staging_input.default.Default object at 0x2b7748da42b0>> failed
Traceback (most recent call last):
  File "/home1/02855/mturilli/ve/lib/python3.7/site-packages/radical/pilot/utils/component.py", line 1028, in work_cb
    self._workers[state](things)
  File "/home1/02855/mturilli/ve/lib/python3.7/site-packages/radical/pilot/umgr/staging_input/default.py", line 237, in work
    rpu.create_tar(tar_tgt, rels)
  File "/home1/02855/mturilli/ve/lib/python3.7/site-packages/radical/pilot/utils/misc.py", line 95, in create_tar
    write_dir(dname)
  File "/home1/02855/mturilli/ve/lib/python3.7/site-packages/radical/pilot/utils/misc.py", line 92, in write_dir
    fout.write(ru.to_byte(data))
AttributeError: module 'radical.utils' has no attribute 'to_byte'
```
Stack:
```
$ radical-stack 

  python               : 3.7.0
  pythonpath           : /opt/apps/intel19/impi19_0/python3/3.7.0/lib/python3.7/site-packages
  virtualenv           : /home1/02855/mturilli/ve

  radical.pilot        : 1.1.1
  radical.saga         : 1.1.2
  radical.utils        : 1.1.1
```
Note that `radical-stack` does not tell on what branch I am. `hotfix/frontera`. Do we need to merge `devel` back into `hotfix/frontera`?

**Comment by andre-merzky** [comment]
`to_byte` needs to be `as_bytes`, and that is correct in devel already.  I would like not to sync the `hotfix/frontera` branch with `devel` right now, as there are too many changes, but we can do that fix directly.  One sec :-)

**Comment by andre-merzky** [comment]
pushed to `hotfix/frontera` - can you give it a try, please?

**Comment by mturilli** [comment]
```
Traceback (most recent call last):
  File "random_eth.py", line 26, in <module>
    pilot = pmgr.submit_pilots(pdesc)
  File "/home1/02855/mturilli/ve/lib/python3.7/site-packages/radical/pilot/pilot_manager.py", line 551, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/home1/02855/mturilli/ve/lib/python3.7/site-packages/radical/pilot/compute_pilot.py", line 99, in __init__
    = self._session._get_jsurl           (pilot)
  File "/home1/02855/mturilli/ve/lib/python3.7/site-packages/radical/pilot/session.py", line 927, in _get_jsurl
    rcfg    = self.get_resource_config(resrc, schema)
  File "/home1/02855/mturilli/ve/lib/python3.7/site-packages/radical/pilot/session.py", line 648, in get_resource_config
    raise RuntimeError("Resource domain '%s' is unknown." % domain)
RuntimeError: Resource domain 'xsede' is unknown.
```

**Comment by mturilli** [comment]
This is now solved.
