### ISSUE TITLE
PRTE failed on Summit: Exception: VMURI not found!

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.pilot#2158]
My prte run is failed and the error message is `Exception: VMURI not found!` from `agent.0.out` and the full messages are:

```
$ more agent.0.out
bootstrap agent agent.0
failed agent.0
--------------
RADICAL Utils -- Stacktrace [40038] [MainThread]

hrlee     40038  38969  0 01:25 ?        00:00:00                  \_ rp.agent.0
hrlee     40409  40038  0 01:25 ?        00:00:00                  |   \_ [prte] <defunct>
Traceback (most recent call last):
File "/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/rp.session.login1.hrlee.018411.0002/pilot.0000/rp_install/bin/radical-pilot-agent", line 51, in bootstrap_3
if aid == 'agent.0': agent = rp.Agent_0(cfg, session)
File "/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/rp.session.login1.hrlee.018411.0002/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/agent_0.py", line 67, in __init__
self._configure_rm()
File "/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/rp.session.login1.hrlee.018411.0002/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/agent_0.py", line 147, in _configure_rm
cfg=self._cfg, session=self._session)
File "/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/rp.session.login1.hrlee.018411.0002/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/resource_manager/base.py", line 247, in create
return impl(cfg, session)
File "/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/rp.session.login1.hrlee.018411.0002/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/resource_manager/lsf_summit.py", line 138, in __init__
self, self._log, self._prof))
File "/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/rp.session.login1.hrlee.018411.0002/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/base.py", line 226, in rm_config_hook
return impl.rm_config_hook(name, cfg, rm, log, profiler)
File "/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/rp.session.login1.hrlee.018411.0002/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/launch_method/prte.py", line 182, in rm_config_hook
raise Exception("VMURI not found!")
Exception: VMURI not found!

--------------
finalize agent.0

```

There is `prrte.hosts` but no `prrte.uri` to generate `dvm_uri`. 
```
$ more prrte.hosts
h50n14 slots=168
```

My stack info:

```
$ radical-stack

  python               : 3.7.0
  pythonpath           : /sw/summit/xalt/1.2.0/site:/sw/summit/xalt/1.2.0/libexec
  virtualenv           : /ccs/home/hrlee/venv3/entk.copy3

  radical.entk         : 1.4.0
  radical.pilot        : 1.4.0
  radical.saga         : 1.4.0
  radical.utils        : 1.4.0
```

**Comment by andre-merzky** [comment]
Can you please attach the pilot sandbox?  Thanks!

**Comment by lee212** [comment]
[rp.session.login1.hrlee.018411.0004.tar.gz](https://github.com/radical-cybertools/radical.pilot/files/4702177/rp.session.login1.hrlee.018411.0004.tar.gz)

**Comment by lee212** [comment]
thanks!

**Comment by lee212** [comment]
Any update?
