### ISSUE TITLE
Pilot fails to bootstrap on ornl.summit

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2216]
Stack:
```
$ radical-stack

  python               : 3.7.0
  pythonpath           : /autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/py-setuptools-40.4.3-xynpmbuwujfkcw52tegkndot6jj5bye5/lib/python3.7/site-packages:/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/py-virtualenv-16.0.0-ohsvxc5mf4aornhyrfp4ecea5bzcowon/lib/python2.7/site-packages:/sw/summit/xalt/1.2.0/site:/sw/summit/xalt/1.2.0/libexec
  virtualenv           : /autofs/nccs-svm1_home1/mturilli1/gb20/integration-level-0/ve/gb20-integration-0

  radical.entk         : 1.5.0
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.2
  radical.saga         : 1.5.2
  radical.utils        : 1.5.3
```
Error in bootstrap.0.out:
```
# Create virtualenv
# cmd: /autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/bin/python virtualenv-16.7.5/virtualenv.py -p python3 /gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2
#
Already using interpreter /autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/bin/python3
Using base prefix '/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn'
New python executable in /gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/bin/python3
Also creating executable in /gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/bin/python3
#
# SUCCESS
#
# -------------------------------------------------------------------
9.0000,ve_activate_start,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
VIRTENV activated : /gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2
RP_PATH           : /gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/bin
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/py-setuptools-40.4.3-xynpmbuwujfkcw52tegkndot6jj5bye5/lib/python3.7/site-packages/setuptools/__init__.py", line 6, in <module>
    import distutils.core
  File "/gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools._distutils'
PYTHON            : /gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/bin/python
PYTHON_VERSION    :
PIP               : /gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/bin/python -m pip --cert /gpfs/alpine/scratch/mturilli1/csc343/radical.pilot.sandbox/rp.session.login2.mturilli1.018505.0003/pilot.0000/../cacert.pem
PIP version       : pip 10.0.1 from /autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/py-pip-10.0.1-ppmoqmblkncxkfwytkqpu4afmqylywbj/lib/python3.7/site-packages/pip (python 3.7)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/py-setuptools-40.4.3-xynpmbuwujfkcw52tegkndot6jj5bye5/lib/python3.7/site-packages/setuptools/__init__.py", line 6, in <module>
    import distutils.core
  File "/gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools._distutils'
VE_MOD_PREFIX init:
VE_MOD_PREFIX     : ///////
RP_MOD_PREFIX     : ///////
VE_PYTHONPATH     : /autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/py-setuptools-40.4.3-xynpmbuwujfkcw52tegkndot6jj5bye5/lib/python3.7/site-packages:/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/py-virtualenv-16.0.0-ohsvxc5mf4aornhyrfp4ecea5bzcowon/lib/python2.7/site-packages:/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/py-pip-10.0.1-ppmoqmblkncxkfwytkqpu4afmqylywbj/lib/python3.7/site-packages
11.0000,ve_activate_stop,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/py-setuptools-40.4.3-xynpmbuwujfkcw52tegkndot6jj5bye5/lib/python3.7/site-packages/setuptools/__init__.py", line 6, in <module>
    import distutils.core
  File "/gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools._distutils'
PYTHON            : /gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/bin/python
PYTHON_VERSION    :
PIP               : /gpfs/alpine/csc343/scratch/mturilli1/radical.pilot.sandbox/ve.ornl.summit.1.5.2/bin/python -m pip --cert /gpfs/alpine/scratch/mturilli1/csc343/radical.pilot.sandbox/rp.session.login2.mturilli1.018505.0003/pilot.0000/../cacert.pem
PIP version       : pip 10.0.1 from /autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/py-pip-10.0.1-ppmoqmblkncxkfwytkqpu4afmqylywbj/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by benjha** [comment]
I am having a similar error with EnTK with the current stack:

```
$ radical-stack 

  python               : 3.7.0
  pythonpath           : /sw/summit/xalt/1.2.0/site:/sw/summit/xalt/1.2.0/libexec
  virtualenv           : /gpfs/alpine/world-shared/bip115/radical_tools_python/entk_1.5.1

  radical.entk         : 1.5.1
  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.2
  radical.saga         : 1.5.2
  radical.utils        : 1.5.3
```

the last lines of my bootstrap.0.out  looks like: 

```
Processing ./radical.pilot-1.5.2
Installing collected packages: radical.pilot
  Running setup.py install for radical.pilot: started
    Running setup.py install for radical.pilot: finished with status 'done'
Successfully installed radical.pilot-1.5.2
You are using pip version 10.0.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
#
# SUCCESS
#
# -------------------------------------------------------------------
purge install source at radical.pilot-1.5.2/
16.0000,rp_install_stop,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
16.0000,ve_setup_stop,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
verify python viability: /gpfs/alpine/stf011/scratch/benjha/radical.pilot.sandbox/ve.ornl.summit.1.5.2/bin/python ... ok
verify module viability: radical.pilot   ...Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/gpfs/alpine/scratch/benjha/stf011/radical.pilot.sandbox/re.session.login5.benjha.018514.0020/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/__init__.py", line 9, in <module>
    import radical.utils as _ru
  File "/gpfs/alpine/scratch/benjha/stf011/radical.pilot.sandbox/re.session.login5.benjha.018514.0020/pilot.0000/rp_install/lib/python3.7/site-packages/radical/utils/__init__.py", line 14, in <module>
    from .plugin_manager import PluginManager
  File "/gpfs/alpine/scratch/benjha/stf011/radical.pilot.sandbox/re.session.login5.benjha.018514.0020/pilot.0000/rp_install/lib/python3.7/site-packages/radical/utils/plugin_manager.py", line 15, in <module>
    from .logger    import Logger
  File "/gpfs/alpine/scratch/benjha/stf011/radical.pilot.sandbox/re.session.login5.benjha.018514.0020/pilot.0000/rp_install/lib/python3.7/site-packages/radical/utils/logger.py", line 44, in <module>
    from   .misc      import get_env_ns       as ru_get_env_ns
  File "/gpfs/alpine/scratch/benjha/stf011/radical.pilot.sandbox/re.session.login5.benjha.018514.0020/pilot.0000/rp_install/lib/python3.7/site-packages/radical/utils/misc.py", line 17, in <module>
    from .ru_regex import ReString
  File "/gpfs/alpine/scratch/benjha/stf011/radical.pilot.sandbox/re.session.login5.benjha.018514.0020/pilot.0000/rp_install/lib/python3.7/site-packages/radical/utils/ru_regex.py", line 7, in <module>
    import regex
ModuleNotFoundError: No module named 'regex'
 failed
python installation cannot load module radical.pilot - abort

------------------------------------------------------------
Sender: LSF System <lsfadmin@batch1>
Subject: Job 331772: <pilot.0000> in cluster <summit> Exited
```

As a workaround @lee212 suggested to manually install the missing packages...

FYI @daipayans

**Comment by andre-merzky** [comment]
outdated
