### ISSUE TITLE
Error when running the first example  00_getting_started.py 

### ISSUE THREAD

**Issue by Achraf-Nagihi** [radical-cybertools/radical.pilot#2232]
When i try to run the first example by the command
```sh
python 00_getting_started.py
``` 
and after specifying the environment variable :(cluster created on Mongodb Atlas, and i added my ip adresse)
```sh
export RADICAL_PILOT_DBURL="mongodb://kodai:***@cluster0.lukzc.mongodb.net:27017/test1"
```
i get the following error
```sh
================================================================================
 Getting Started (RP version 1.5.2)                                             
================================================================================

new session: [rp.session.kodai.kodai.018537.0018]                              \
database   : [mongodb://kodai:****@cluster0.lukzc.mongodb.net:27017/test1]   err
Traceback (most recent call last):
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/radical/pilot/session.py", line 177, in _initialize_primary
    self._dbs = DBSession(sid=self.uid, dburl=dburl,
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/radical/pilot/db/database.py", line 50, in __init__
    self._mongo, self._db, _, _, _ = ru.mongodb_connect(str(dburl))
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/radical/utils/misc.py", line 120, in mongodb_connect
    db.authenticate(user, pwd)
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/pymongo/database.py", line 1492, in authenticate
    self.client._cache_credentials(
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/pymongo/mongo_client.py", line 775, in _cache_credentials
    server = self._get_topology().select_server(
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/pymongo/topology.py", line 241, in select_server
    return random.choice(self.select_servers(selector,
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/pymongo/topology.py", line 199, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/pymongo/topology.py", line 215, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: cluster0.lukzc.mongodb.net:27017: [Errno -5] No address associated with hostname, Timeout: 30s, Topology Description: <TopologyDescription id: 5f775a9383b7011625e5a5b1, topology_type: Single, servers: [<ServerDescription ('cluster0.lukzc.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.lukzc.mongodb.net:27017: [Errno -5] No address associated with hostname')>]>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "00_getting_started.py", line 34, in <module>
    session = rp.Session()
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/radical/pilot/session.py", line 148, in __init__
    self._initialize_primary(dburl)
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/radical/pilot/session.py", line 192, in _initialize_primary
    raise RuntimeError ('session create failed [%s]' %
RuntimeError: session create failed [mongodb://kodai:****@cluster0.lukzc.mongodb.net:27017/test1]
-----------------------------------------------------------------------------------------------------------
```

but it works fine when i use export RADICAL_PILOT_DBURL=mongodb://localhost:27017/test1

```
$ python -V
Python 3.8.2

$ radical-stack
  python               : 3.8.2
  pythonpath           : 
  virtualenv           : /home/kodai/RADICALPilot

  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.2
  radical.saga         : 1.5.2
  radical.utils        : 1.5.3
```

[r.log](https://github.com/radical-cybertools/radical.pilot/files/5319338/r.log)
[rp.session.kodai.kodai.018537.0019.log](https://github.com/radical-cybertools/radical.pilot/files/5319339/rp.session.kodai.kodai.018537.0019.log)

**Comment by andre-merzky** [comment]
Hi @Achraf-Nagihi - I am afraid we don't support the clustered MongoDB deployment as provided by Atlas.  We know that this is quite a limitation, but it is unlikely to get fixed, as we plan to remove the MongoDB requirement altogether in the near future.  I can only recommend to use a simple stand-alone MongoDB deployment (similar to what you run on your localhost) and host it on a VM somewhere.

**Comment by Achraf-Nagihi** [comment]
Thank you @andre-merzky i have been trying all week to fix it .

**Comment by andre-merzky** [comment]
Oh, I'm sorry to hear that ...  Don't hesitate to open an issue earlier when you are stuck!  We can't always figure out what's wrong - but often enough :-)

**Comment by Achraf-Nagihi** [comment]
Okey i will, Thank u :)
