### ISSUE TITLE
submit: caught Exception: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by Achraf-Nagihi** [radical-cybertools/radical.pilot#2234]
Hello, when i try to run my script i get this error 

```
Traceback (most recent call last):
  File "test.py", line 148, in <module>
    units = umgr.submit_units(cuds)
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/radical/pilot/unit_manager.py", line 825, in submit_units
    unit = ComputeUnit(umgr=self, descr=ud)
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/radical/pilot/compute_unit.py", line 61, in __init__
    descr.verify()
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/radical/utils/munch.py", line 292, in verify
    self._data[k] = self._verify_kvt(k, v, self._schema[k])
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/radical/utils/munch.py", line 273, in _verify_kvt
    if isinstance(t, dict)    : return cls._verify_dict(k, v, t)
  File "/home/kodai/RADICALPilot/lib/python3.8/site-packages/radical/utils/munch.py", line 256, in _verify_dict
    for _k, _v in v.items()}
AttributeError: 'list' object has no attribute 'items'
```
the part of my code containing cud:
```
        cud = rp.ComputeUnitDescription()
        cud.environment    = ['PATH='+config['pathtoLIGGHTS']+':$PATH']
        cud.pre_exec         = ['mkdir CSVs','mkdir post','mkdir restart']
        cud.executable       = 'lmp_micstam'
        cud.arguments       = ['-in','in.*' ]
        cud.cores          = config['DEMcores']
        cud.mpi            = True
        report.progress()
        report.ok('>>ok\n')
        cuds = []
        cuds.append(cud)
        # Submit the previously created ComputeUnit descriptions to the
        # PilotManager. This will trigger the selected scheduler to start
        # assigning ComputeUnits to the ComputePilots.
        units = umgr.submit_units(cuds)
        

        # Wait for all compute units to reach a final state (DONE, CANCELED or FAILED).
        umgr.wait_units()
```

```
$ python -V
Python 3.8.5
$ radical-stack
 
  python               : 3.8.5
  pythonpath           : 
  virtualenv           : /home/kodai/RADIC


ALPilot

  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.2
  radical.saga         : 1.5.2
  radical.utils        : 1.5.3
```
```
[pmgr.0000.log](https://github.com/radical-cybertools/radical.pilot/files/5356516/pmgr.0000.log)
[r.log](https://github.com/radical-cybertools/radical.pilot/files/5356517/r.log)
[rp.session.kodai.kodai.018544.0020.log](https://github.com/radical-cybertools/radical.pilot/files/5356518/rp.session.kodai.kodai.018544.0020.log)
[umgr.0000.log](https://github.com/radical-cybertools/radical.pilot/files/5356519/umgr.0000.log)


```

**Comment by andre-merzky** [comment]
The `environment` value in your description is expected to be a dictionary, of the form
```py
{ 
   "PATH" : "/bin/:$PATH"
}
```
We actually don't guarantee that the `$PATH` part in the value can be expanded in all cases (although it should work on most machines).  In case it does not, I would suggest to use a `pre_exec` command like this:
```py
cud.pre_exec = ['export PATH="/bin:$PATH"']
```
pre_exec commands are guaranteed to be executed in an actual shell environment.

**Comment by andre-merzky** [comment]
btw, you seem to be using an outdated format for the description.  the `cud.mpi` key is deprecated by now.  I would suggest you use:
```py
        cud = rp.ComputeUnitDescription()
        cud.environment      = {'PATH' : config['pathtoLIGGHTS'] + ':$PATH'}
        cud.pre_exec         = ['mkdir CSVs post restart']
        cud.executable       = 'lmp_micstam'
        cud.arguments        = ['-in', 'in.*' ]
        cud.cpu_processes    = config['DEMcores']
        cud.cpu_process_type = rp.MPI

        umgr.submit_units([cud])
        umgr.wait_units()
```

**Comment by Achraf-Nagihi** [comment]
Thank you so much @andre-merzky  :)
