### ISSUE TITLE
RADICAL-Pilot functions executor "worker thread initialization failed"

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2247]
While trying to run `unit_funcs` example [here](https://github.com/radical-cybertools/radical.pilot/blob/master/examples/12_unit_function.py), I got the following error:

Note that I am running the example on `localhost` with resource `local.localhost_funcs`.

```1604364721.468 : agent_executing.0000 : 25705 : 139821778953984 : ERROR    : worker thread initialization failed
Traceback (most recent call last):
  File "/home/aymen/radical.pilot.sandbox/parsl.radical_executor.session.js-17-185.jetstream-cloud.org.aymen.018569.0005/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/utils/component.py", line 472, in _worker_thread
    self._initialize()
  File "/home/aymen/radical.pilot.sandbox/parsl.radical_executor.session.js-17-185.jetstream-cloud.org.aymen.018569.0005/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/utils/component.py", line 609, in _initialize
    self.initialize()
  File "/home/aymen/radical.pilot.sandbox/parsl.radical_executor.session.js-17-185.jetstream-cloud.org.aymen.018569.0005/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/agent/executing/funcs.py", line 53, in initialize
    addr_wrk = self._cfg['bridges']['funcs_req_queue']
  File "/home/aymen/radical.pilot.sandbox/parsl.radical_executor.session.js-17-185.jetstream-cloud.org.aymen.018569.0005/pilot.0000/rp_install/lib/python3.7/site-packages/radical/utils/munch.py", line 113, in __getitem__
    return self._data[k]
KeyError: 'bridges'
```

`Radical-stack:`
```
  python               : 3.7.6
  pythonpath           :
  virtualenv           : 

  radical.gtod         : 1.5.0
  radical.pilot        : 1.5.7
  radical.saga         : 1.5.4
  radical.utils        : 1.5.4
```

I will look into this problem this week.

**Comment by andre-merzky** [comment]
Sorry @AymenFJA , this took longer than I expected, the code deteriorated a lot...  Please do give the `fix/funcs` branch a try (also see PR #2262), and let me know how it goes.

**Comment by AymenFJA** [comment]
@andre-merzky  Great :). I did try it, so far I don't see the thread initialization failure. But, RP is stuck on `wait` due to `SSH` permission denied (public key) in `func_exec.0000` `stderr`. From the output of the `unit`, it seems like `RP` is trying to `SSH` to my `VM` but is failing to get access due to the SSH password that I have. BTW, I am using the `local` schema and pretty that other examples like `00_getting_started` are working correctly on `local.localhost`

**Comment by andre-merzky** [comment]
Hmm, I am not sure how ssh comes into the picture.  Can you please provide the client and pilot session dirs?  Thanks!

**Comment by andre-merzky** [comment]
Ah, and the script you try to run.

**Comment by AymenFJA** [comment]
> Ah, and the script you try to run.

I have attached the requested files below:

[client_dir.zip](https://github.com/radical-cybertools/radical.pilot/files/5591763/client_dir.zip)
[pilot_dir.zip](https://github.com/radical-cybertools/radical.pilot/files/5591764/pilot_dir.zip)

```
import os
import sys

import radical.pilot as rp
import radical.utils as ru

dh = ru.DebugHelper()

os.environ['RADICAL_PILOT_DBURL'] = "mongodb://aymen:*******@129.114.17.185:27017/radical3"
if __name__ == '__main__':

    # we use a reporter class for nicer output
    report = ru.Reporter(name='radical.pilot')
    report.title('Getting Started (RP version %s)' % rp.version)

    session = rp.Session(uid=ru.generate_id('google.colab.rct.session',
                         mode=ru.ID_PRIVATE))

    try:

        # read the config used for resource details
        report.info('read config')
        config = ru.read_json('config.json')
        report.ok('>>ok\n')

        report.header('submit pilots')

        # Add a Pilot Manager. Pilot managers manage one or more ComputePilots.
        pmgr = rp.PilotManager(session=session)

        pd_init = {'resource'      : 'local.localhost_funcs',
                   'runtime'       : 60,
                   'exit_on_error' : True,
                   'project'       : None,
                   'queue'         : None,
                   'access_schema' : None,
                   'cores'         : 8,
                   'gpus'          : 0,
                  }
        pdesc = rp.ComputePilotDescription(pd_init)

        # Launch the pilot.
        pilot = pmgr.submit_pilots(pdesc)

        report.header('submit units')

        # Register the ComputePilot in a UnitManager object.
        umgr = rp.UnitManager(session=session)
        umgr.add_pilots(pilot)

        n = 2
        report.progress_tgt(n, label='create')

        cuds = list()
        for i in range(0, n):

            cud = rp.ComputeUnitDescription()
            cud.executable       = 'time.time'
            cud.arguments        = []
            cud.pre_exec         = ['import time']
            cud.gpu_processes    = 0
            cud.cpu_processes    = 1
            cud.cpu_threads      = 1
            cud.cpu_process_type = rp.FUNC
            cuds.append(cud)
            report.progress()

        report.progress_done()

        units = umgr.submit_units(cuds)

        report.header('gather results')
        umgr.wait_units()

        for unit in (units[:10] + units[-10:]):
            if unit.state == rp.DONE:
                print('\t+ %s: %-10s: %10s: %s'
                     % (unit.uid, unit.state, unit.pilot, unit.stdout))
            else:
                print('\t- %s: %-10s: %10s: %s'
                     % (unit.uid, unit.state, unit.pilot, unit.stderr))


    except Exception as e:
        # Something unexpected happened in the pilot code above
        report.error('caught Exception: %s\n' % e)
        ru.print_exception_trace()
        raise

    except (KeyboardInterrupt, SystemExit):

        ru.print_exception_trace()
        report.warn('exit requested\n')

    finally:

        report.header('finalize')
        session.close(download=True)

    report.header()

```

**Comment by AymenFJA** [comment]
Please ignore the session name `google.colab` as it is running on my `js.vm` from the command line :)

**Comment by andre-merzky** [comment]
Ah, I misunderstood the problem - you can launch the pilot all right.  The problem is the `agent_launch_method` - you may want to switch that from `SSH` to `FORK` in the resource config.

**Comment by AymenFJA** [comment]
@andre-merzky Thank you the example did work and finish. I have one question since I am submitting 4 tasks I just noticed that the report shows the following:
```
gather results

wait  : ########################################################################
        DONE      :     2
                                                                              ok
        + unit.000000: DONE      : pilot.0000: 1606321036.2054734
        + unit.000001: DONE      : pilot.0000: 1606321036.2993317
        + unit.000000: DONE      : pilot.0000: 1606321036.2054734
        + unit.000001: DONE      : pilot.0000: 1606321036.2993317

```

but the sandbox is showing only one unit under the name `func_exec.0000`. Am I missing something?

**Comment by AymenFJA** [comment]
Regarding executing the `RP_func` on `comet` it is reporting done but with the following:
Under the `sandbox/pilot.0000/func_exec.0000/func_exec.0000.err/` I see `killed by signal 15`. 

I am submitting 2 units using the following pilot description:
```
pd_init = {'resource'      : 'xsede.comet_ssh_funcs',
                   'runtime'       : 30,
                   'exit_on_error' : True,
                   'project'       : 'XXXX', # I did specify the project here!
                   'queue'         : 'debug',
                   'access_schema' : 'gsissh',
                   'cores'         : 24,
                   'gpus'          : 0,
```

Unit description:
```
cud = rp.ComputeUnitDescription()
            cud.executable       = 'time.time'
            cud.arguments        = []
            cud.pre_exec         = ['import time']
            cud.gpu_processes    = 0
            cud.cpu_processes    = 3
            cud.cpu_threads      = 8
            cud.cpu_process_type = rp.FUNC
            cuds.append(cud)
            report.progress()
```

**Comment by AymenFJA** [comment]
@andre-merzky, update: this is working only with `time.time`. I have tried something similar :

```
cud.executable       = 'math.exp(2)'
cud.arguments        = []
cud.pre_exec         = ['import math']
```
And I keep getting an error from the function:

```
gather results

wait  : ########################################################################
        FAILED    :     2
                                                                              ok
        - unit.000000: FAILED    : pilot.0000: name 'math' is not defined
        - unit.000001: FAILED    : pilot.0000: name 'math' is not defined
        - unit.000000: FAILED    : pilot.0000: name 'math' is not defined
        - unit.000001: FAILED    : pilot.0000: name 'math' is not defined
```

Please let me know if I am doing something wrong!

**Comment by andre-merzky** [comment]
I added some simple support for import-like pre-execs, and changed the example 12 to show the use of it  - can you give it a try?

**Comment by AymenFJA** [comment]
@andre-merzky, Both `local` and `remote` went successfully. 


```
gather results

wait  : ########################################################################
        DONE      :     8
                                                                              ok
        + unit.000000: DONE      : pilot.0000: 1.0
        + unit.000001: DONE      : pilot.0000: 2.718281828459045
        + unit.000002: DONE      : pilot.0000: 7.38905609893065
        + unit.000003: DONE      : pilot.0000: 20.085536923187668
        + unit.000004: DONE      : pilot.0000: 54.598150033144236
        + unit.000005: DONE      : pilot.0000: 148.4131591025766
        + unit.000006: DONE      : pilot.0000: 403.4287934927351
        + unit.000007: DONE      : pilot.0000: 1096.6331584284585
        + unit.000000: DONE      : pilot.0000: 1.0
        + unit.000001: DONE      : pilot.0000: 2.718281828459045
        + unit.000002: DONE      : pilot.0000: 7.38905609893065
        + unit.000003: DONE      : pilot.0000: 20.085536923187668
        + unit.000004: DONE      : pilot.0000: 54.598150033144236
        + unit.000005: DONE      : pilot.0000: 148.4131591025766
        + unit.000006: DONE      : pilot.0000: 403.4287934927351
        + unit.000007: DONE      : pilot.0000: 1096.6331584284585

```

I will close this ticket now. And reopen it if something fails again.
