### ISSUE TITLE
Local examples fail on systems with less than 8 cores

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#2295]
I tried to run RP's examples locally in a VM that had 4 cores instead of 8. As a result, I got an error from the resource manager that reported insufficient resources:
```
bootstrap agent agent.0
failed agent.0
--------------
RADICAL Utils -- Stacktrace [60958] [MainThread]

iparask    60958   59828 38 13:25 pts/14   00:00:00          \_ rp.agent.0
Traceback (most recent call last):
File "/home/iparask/radical.pilot.sandbox/rp.session.ubuntu-20-04-devel-and-docker.iparask.018632.0001/pilot.0000/rp_install/bin/radical-pilot-agent", line 51, in bootstrap_3
if aid == 'agent.0': agent = rp.Agent_0(cfg, session)
File "/home/iparask/radical.pilot.sandbox/rp.session.ubuntu-20-04-devel-and-docker.iparask.018632.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/agent_0.py", line 67, in __init__
self._configure_rm()
File "/home/iparask/radical.pilot.sandbox/rp.session.ubuntu-20-04-devel-and-docker.iparask.018632.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/agent_0.py", line 150, in _configure_rm
self._rm = ResourceManager.create(name=self._cfg.resource_manager,
File "/home/iparask/radical.pilot.sandbox/rp.session.ubuntu-20-04-devel-and-docker.iparask.018632.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/resource_manager/base.py", line 254, in create
return impl(cfg, session)
File "/home/iparask/radical.pilot.sandbox/rp.session.ubuntu-20-04-devel-and-docker.iparask.018632.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/resource_manager/fork.py", line 21, in __init__
ResourceManager.__init__(self, cfg, session)
File "/home/iparask/radical.pilot.sandbox/rp.session.ubuntu-20-04-devel-and-docker.iparask.018632.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/resource_manager/base.py", line 114, in __init__
self._configure()
File "/home/iparask/radical.pilot.sandbox/rp.session.ubuntu-20-04-devel-and-docker.iparask.018632.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/resource_manager/fork.py", line 40, in _configure
raise RuntimeError('insufficient cores found (%d < %d'
RuntimeError: insufficient cores found (4 < 8
```

After a quick check, I found that local resource configs assume 8 cores per node. Would it make sense to reduce it to 1 so that all examples run locally independent of the system used?

**Comment by andre-merzky** [comment]
We discussed and agreed to reduce to 4 cores

**Comment by andre-merzky** [comment]
@mtitov : check if still valid.

**Comment by mtitov** [comment]
tests were checked (performed as expected), resource config `local.localhost` has parameter set `"fake_resources"              : true`, thus number of cores per node could be any number
