### ISSUE TITLE
Agent staging input fails

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#2318]
Running an EnTK script that links data between tasks produced this error:
```
1612283541.718 : agent_staging_input.0000 : 19640 : 139867611555584 : DEBUG    :    expand with file://localhost:2222/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018660.0001/pilot.0000/
1612283541.718 : agent_staging_input.0000 : 19640 : 139867611555584 : ERROR    : work <bound method AgentStagingInputComponent.work of <radical.pilot.agent.staging_input.default.Default object at 0x7f35774f1d60>> failed
Traceback (most recent call last):
  File "/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018660.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/utils/component.py", line 1106, in work_cb
    self._workers[state](things)
  File "/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018660.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/staging_input/base.py", line 82, in work
    self._work(tasks)
  File "/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018660.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/staging_input/default.py",
 line 85, in _work
    self._handle_task(task, actionables)
  File "/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/re.session.js-17-185.jetstream-cloud.org.iparask.018660.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/pilot/agent/staging_input/default.py",
 line 172, in _handle_task
    assert(tgt.schema == 'file'), 'staging tgt must be file://'
AssertionError: staging tgt must be file://
```

I'm using the `user/repex` branch, which I synced to devel today, and the agent staging input last change is the one on devel as well.

**Comment by iparask** [comment]
this is the description:
```
{'uid': '',
'name': 'task.0000,rep.0000.0000.0000.md,stage.0000,None,pipeline.0000,p_rep.0000',
'executable': 'gmx_mpi',
'kernel': '',
'sandbox': 'rep.0000.0000.md',
'arguments': ['grompp', '-f', 'mdin.mdp', '-c', 'inpcrd.gro', '-o', 'sys.tpr', '-p', 'sys.top'],
'environment': {},
'named_env': '',
'pre_exec': ['module purge', 'module load intel/18.4', 'module load gromacs/2018_cpu'],
'post_exec': [],
'stdout': '',
'stderr': '',
'input_staging': [{'uid': 'sd.0000',
                   'source': 'pilot:///inputs//mdin.mdp.rep.0000',
                   'target': 'unit:////mdin.mdp',
                   'action': 'Link',
                   'flags': 64,
                   'priority': 0},
                  {'uid': 'sd.0001',
                   'source': 'pilot:///inputs//sys.top',
                   'target': 'unit:////sys.top',
                   'action': 'Link',
                   'flags': 64,
                   'priority': 0},
                  {'uid': 'sd.0002',
                   'source': 'pilot:///inputs//sys.itp',
                   'target': 'unit:////sys.itp',
                   'action': 'Link',
                   'flags': 64,
                   'priority': 0},
                  {'uid': 'sd.0003',
                   'source': 'pilot:///inputs//inp.ener',
                   'target': 'unit:////inp.ener',
                   'action': 'Link',
                   'flags': 64,
                   'priority': 0},
                  {'uid': 'sd.0004',
                   'source': 'pilot:///inputs//martini_v2.2.itp',
                   'target': 'unit:////martini_v2.2.itp',
                   'action': 'Link',
                   'flags': 64,
                   'priority': 0},
                  {'uid': 'sd.0005',
                   'source': 'pilot:///inputs//inpcrd.gro.rep.0000',
                   'target': 'unit:////inpcrd.gro',
                   'action': 'Link',
                   'flags': 64,
                   'priority': 0}],
'output_staging': [],
'cpu_processes': 1,
'cpu_process_type': 'MPI',
'cpu_threads': 1,
'cpu_thread_type': 'None',
'gpu_processes': 0,
'gpu_process_type': 'None',
'gpu_threads': 0,
'gpu_thread_type': 'None',
'lfs_per_process': 0,
'mem_per_process': 0,
'restartable': False,
'tags': {},
'tag': None,
'metadata': None,
'cleanup': False,
'pilot': ''}
```

EnTK, which is used to create the input staging directives, does not use the schema that RP recognizes ([here](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/execman/rp/task_processor.py#L183)). So I think it has to do with what RP considers as defaults?

**Comment by andre-merzky** [comment]
Ah, right - so the sandbox expansion is broken...  Got it...

**Comment by mtitov** [comment]
basic RP run also affected with this issue (tested with multi-DVM test run)

**Comment by andre-merzky** [comment]
@iparask , @mtitov : my understanding that this can be closed?
