### ISSUE TITLE
IBRUN unusable on stampede2

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#2547]
```
 11 1647286593.498 : agent.0              : 49759 : 47800393171904 : ERROR    : unusable lm IBRUN
 12 Traceback (most recent call last):                                               
 13   File "/work2/07698/tg869979/stampede2/radical.pilot.sandbox/re.session.abanerjee-OptiPlex-990.abanerjee.019065.0003/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/      agent/launch_method/base.py", line 143, in create
 14     return impl[name](name, lm_cfg, rm_info, log, prof)                          
 15   File "/work2/07698/tg869979/stampede2/radical.pilot.sandbox/re.session.abanerjee-OptiPlex-990.abanerjee.019065.0003/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/      agent/launch_method/ibrun.py", line 22, in __init__
 16     self._node_list: list = self._rm_info.node_list or []                        
 17 AttributeError: 'IBRun' object has no attribute '_rm_info'                       
 18 1647286593.506 : agent.0              : 49759 : 47800393171904 : ERROR    : skip LM IBRUN
 19 Traceback (most recent call last):                                               
 20   File "/work2/07698/tg869979/stampede2/radical.pilot.sandbox/re.session.abanerjee-OptiPlex-990.abanerjee.019065.0003/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/      agent/resource_manager/base.py", line 351, in _prepare_launch_methods
 21     name, lm_cfg, rm_info, self._log, self._prof)                                
 22   File "/work2/07698/tg869979/stampede2/radical.pilot.sandbox/re.session.abanerjee-OptiPlex-990.abanerjee.019065.0003/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/      agent/launch_method/base.py", line 143, in create
 23     return impl[name](name, lm_cfg, rm_info, log, prof)                          
 24   File "/work2/07698/tg869979/stampede2/radical.pilot.sandbox/re.session.abanerjee-OptiPlex-990.abanerjee.019065.0003/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/      agent/launch_method/ibrun.py", line 22, in __init__
 25     self._node_list: list = self._rm_info.node_list or []                        
 26 AttributeError: 'IBRun' object has no attribute '_rm_info'                       
```

**Comment by andre-merzky** [comment]
@andre-merzky : open PR
