### ISSUE TITLE
setting environment variable fails in RAPTOR worker_mpi

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2602]
```python
Traceback (most recent call last):
  File "/home/aymen/radical.pilot.sandbox/parsl.radical.session.radical.3.aymen.019117.0007/pilot.0000/master.000000/./raptor_worker.py", line 96, in run
    out, err, ret, val, exc = self._dispatch(task)
  File "/home/aymen/ve/raptor/lib/python3.9/site-packages/radical/pilot/raptor/worker_mpi.py", line 533, in _dispatch
    return self._dispatch_non_mpi(task)
  File "/home/aymen/ve/raptor/lib/python3.9/site-packages/radical/pilot/raptor/worker_mpi.py", line 593, in _dispatch_non_mpi
    return dispatcher(task)
  File "/home/aymen/ve/raptor/lib/python3.9/site-packages/radical/pilot/raptor/worker_mpi.py", line 675, in _dispatch_function
    os.environ[k] = v
  File "/home/aymen/ve/raptor/lib/python3.9/os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "/home/aymen/ve/raptor/lib/python3.9/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not int
```
```
                 'environment': {'RP_GTOD': '/home/aymen/radical.pilot.sandbox/parsl.radical.session.radical.3.aymen.019117.0007//pilot.0000//gtod',
                                 'RP_PILOT_ID': 'pilot.0000',
                                 'RP_PILOT_SANDBOX': '/home/aymen/radical.pilot.sandbox/parsl.radical.session.radical.3.aymen.019117.0007//pilot.0000/',
                                 'RP_PROF': '/home/aymen/radical.pilot.sandbox/parsl.radical.session.radical.3.aymen.019117.0007//pilot.0000//prof',
                                 'RP_PROF_TGT': '/home/aymen/radical.pilot.sandbox/parsl.radical.session.radical.3.aymen.019117.0007//pilot.0000//master.000000/master.000000.worker.0000.prof',
                                 'RP_RANK': 0,
                                 'RP_RANKS': 1,
                                 'RP_RESOURCE': 'local.localhost',
                                 'RP_RESOURCE_SANDBOX': '/home/aymen/radical.pilot.sandbox',
                                 'RP_SESSION_ID': 'parsl.radical.session.radical.3.aymen.019117.0007',
                                 'RP_SESSION_SANDBOX': '/home/aymen/radical.pilot.sandbox/parsl.radical.session.radical.3.aymen.019117.0007/',
                                 'RP_TASK_ID': '1',
                                 'RP_TASK_NAME': 'colmena',
                                 'RP_TASK_SANDBOX': '/home/aymen/radical.pilot.sandbox/parsl.radical.session.radical.3.aymen.019117.0007//pilot.0000//master.000000'},
```

In here RP_RANK/RANKS will fail to be set https://github.com/radical-cybertools/radical.pilot/blob/60bb2a8e45e2c01987b03c55465562f28288d7a6/src/radical/pilot/raptor/worker_mpi.py#L674

 because it was defined as `int` and assumed to be overwritten by `_dispatch_non_mpi` https://github.com/radical-cybertools/radical.pilot/blob/60bb2a8e45e2c01987b03c55465562f28288d7a6/src/radical/pilot/raptor/worker_mpi.py#L523

**Comment by andre-merzky** [comment]
Fixed by #2603
