### ISSUE TITLE
prepare_env fails to register a user-provided (existing) venv for use with *named_env*

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2621]
@andre-merzky says that I should be able to use an existing Python virtual environment with the *named_env* feature of an RP Task as long as it is registered with `prepare_env`. When I try this, though, I get an error that looks like #2589.

I.e.
```
Pilot cannot start task:
Traceback (most recent call last):
  File "/home/rp/radical.pilot.sandbox/rp.session.8acf1360-da9b-11ec-801c-0242ac120004/pilot.0000/rp_install/lib/python3.9/site-packages/radical/pilot/agent/executing/popen.py", line 122, in work
    self._handle_task(task)
  File "/home/rp/radical.pilot.sandbox/rp.session.8acf1360-da9b-11ec-801c-0242ac120004/pilot.0000/rp_install/lib/python3.9/site-packages/radical/pilot/agent/executing/popen.py", line 327, in _handle_task
    tmp += self._get_task_env(task, launcher)
  File "/home/rp/radical.pilot.sandbox/rp.session.8acf1360-da9b-11ec-801c-0242ac120004/pilot.0000/rp_install/lib/python3.9/site-packages/radical/pilot/agent/executing/popen.py", line 680, in _get_task_env
    ret += '. %s\n' % launcher.get_task_named_env(td['named_env'])
  File "/home/rp/radical.pilot.sandbox/rp.session.8acf1360-da9b-11ec-801c-0242ac120004/pilot.0000/rp_install/lib/python3.9/site-packages/radical/pilot/agent/launch_method/base.py", line 201, in get_task_named_env
    ru.env_prep(environment=ru.env_read(src),
  File "/home/rp/radical.pilot.sandbox/rp.session.8acf1360-da9b-11ec-801c-0242ac120004/pilot.0000/rp_install/lib/python3.9/site-packages/radical/utils/env.py", line 52, in env_read
    with ru_open(fname, 'r') as fin:
  File "/home/rp/radical.pilot.sandbox/rp.session.8acf1360-da9b-11ec-801c-0242ac120004/pilot.0000/rp_install/lib/python3.9/site-packages/radical/utils/misc.py", line 946, in ru_open
    return open(*args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/home/rp/radical.pilot.sandbox/rp.session.8acf1360-da9b-11ec-801c-0242ac120004/pilot.0000/env/rp_named_env.test-env.env'
```

A minimal reproduction is provided at https://github.com/eirrgang/scale-ms/commit/e9e99bd74baea6877e7aebedd9026b607b3fbad9

**Comment by andre-merzky** [comment]
Hi @eirrgang :  I had to change the env spec to this:
```py
        version = platform.python_version()
        version = '.'.join(version.split('.')[0:2])
        pilot.prepare_env(
            env_name=env_name,
            env_spec={
                'type': 'virtualenv',
                'path': env_path,
                'version': version,
                'setup': []
            }
        )
```

since the prep_env version check complained about a mismatch between `3.6` and `3.6.9`.  There now exists a PR to catch that (#2682).
