### ISSUE TITLE
Nested lists in Task.stdout undocumented and problematic.

### ISSUE THREAD

**Issue by eirrgang** [radical-cybertools/radical.pilot#2727]
This may constitute multiple issues. Please advise if/how I should break up and resubmit as multiple issues.

https://radicalpilot.readthedocs.io/en/stable/apidoc.html#radical.pilot.Task.stdout describes the task stdout as a string.

When tasks are submitted with a request for more than one `ranks` <s>(I don't think this field is documented)</s>, the stdout field is a list of strings. *update: Note that this is a new field since the RP 1.17 online documentation was last built.*

When a raptor Worker calls `self.get_master().run_task()`, the nested task appears to trigger additional call(s) to `Master._result_cb()` with muddled output. The nested tasks appear to reuse the Task UID, but there may either be some additional unintended recursion, or Task UIDs may be getting reused in a wider scope than intended.

To reproduce, run the `raptor.py` script in `examples/misc`.

## Log excerpt
From `master.000000.log`

```
...
1665492070.337 : master.000000        : 2292  : 140480360724224 : INFO     : === out: ['hello 1/2: task.extra_mpi.c.000000\n', 'hello 0/2: task.extra_mpi.c.000000\n']
1665492070.337 : master.000000        : 2292  : 140480360724224 : INFO     : result_cb  task.extra_mpi.c.000000: AGENT_EXECUTING [['hello 0/2: task.extra_mpi.c.000000\n', 'hello 1/2: task.extra_mpi.c.000000\n']] [[None, None]]
1665492070.338 : master.000000        : 2292  : 140480360724224 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_OUTPUT_PENDING]
1665492070.339 : master.000000        : 2292  : 140480360724224 : DEBUG    : put bulk AGENT_STAGING_OUTPUT_PENDING: 1
1665492071.350 : master.000000        : 2292  : 140480117466880 : DEBUG    : advance bulk: 1 [False, False, NEW]
1665492071.350 : master.000000        : 2292  : 140480117466880 : DEBUG    : insert master.000000.subtask.0000
1665492071.350 : master.000000        : 2292  : 140480117466880 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_INPUT_PENDING]
1665492071.351 : master.000000        : 2292  : 140480117466880 : DEBUG    : put bulk AGENT_STAGING_INPUT_PENDING: 1
1665492072.681 : master.000000        : 2292  : 140481283487488 : DEBUG    : unlock 2 master.000000.subtask.0000
1665492072.694 : master.000000        : 2292  : 140480360724224 : INFO     : === out: ['hello task.call.w.000000\nhello task.call.w.000000\n\n']
1665492072.694 : master.000000        : 2292  : 140480360724224 : INFO     : result_cb  task.call.c.3.000000: AGENT_EXECUTING [['hello task.call.w.000000\nhello task.call.w.000000\n\n']] [[None]]
1665492072.694 : master.000000        : 2292  : 140480360724224 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_OUTPUT_PENDING]
1665492072.694 : master.000000        : 2292  : 140480360724224 : DEBUG    : put bulk AGENT_STAGING_OUTPUT_PENDING: 1
1665492075.217 : master.000000        : 2292  : 140480360724224 : INFO     : === out: ['hello 1/2: task.extra.c.3.000000\n', 'hello 0/2: task.extra.c.3.000000\n']
1665492075.217 : master.000000        : 2292  : 140480360724224 : INFO     : result_cb  task.extra.c.3.000000: AGENT_EXECUTING [['hello 0/2: task.extra.c.3.000000\n', 'hello 1/2: task.extra.c.3.000000\n']] [[None, None]]
1665492075.218 : master.000000        : 2292  : 140480360724224 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_OUTPUT_PENDING]
1665492075.218 : master.000000        : 2292  : 140480360724224 : DEBUG    : put bulk AGENT_STAGING_OUTPUT_PENDING: 1
1665492076.721 : master.000000        : 2292  : 140480092288768 : DEBUG    : still alive
1665492077.729 : master.000000        : 2292  : 140480360724224 : INFO     : === out: ['hello 1/2: task.mpi_ser_func.c.000000\n', 'hello 0/2: task.mpi_ser_func.c.000000\n']
1665492077.729 : master.000000        : 2292  : 140480360724224 : INFO     : result_cb  task.mpi_ser_func.c.000000: AGENT_EXECUTING [['hello 0/2: task.mpi_ser_func.c.000000\n', 'hello 1/2: task.mpi_ser_func.c.000000\n']] [[None, None]]
1665492077.729 : master.000000        : 2292  : 140480360724224 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_OUTPUT_PENDING]
1665492077.729 : master.000000        : 2292  : 140480360724224 : DEBUG    : put bulk AGENT_STAGING_OUTPUT_PENDING: 1
1665492080.275 : master.000000        : 2292  : 140480360724224 : INFO     : === out: ['hello 1/2: task.mpi_ser_func.c.000000\n', ['hello 1/2: task.mpi_ser_func.c.000000\n', 'hello 0/2: task.mpi_ser_func.c.000000\n'], 'hello 0/2: task.call.c.000000\n']
1665492080.276 : master.000000        : 2292  : 140480360724224 : ERROR    : result callback failed
Traceback (most recent call last):
  File "/home/rp/radical.pilot.sandbox/rp.session.bd9afe9c-4960-11ed-9fbc-0242ac120002/pilot.0000/env/rp_named_env.ve_raptor/lib/python3.9/site-packages/radical/pilot/raptor/master.py", line 609, in _result_cb
    self.result_cb(tasks)
  File "/home/rp/radical.pilot.sandbox/rp.session.bd9afe9c-4960-11ed-9fbc-0242ac120002/pilot.0000/master.000000/./raptor_master.py", line 251, in result_cb
    sorted(task['stdout']),
TypeError: '<' not supported between instances of 'list' and 'str'
1665492080.278 : master.000000        : 2292  : 140480360724224 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_OUTPUT_PENDING]
1665492080.278 : master.000000        : 2292  : 140480360724224 : DEBUG    : put bulk AGENT_STAGING_OUTPUT_PENDING: 1
1665492080.282 : master.000000        : 2292  : 140480360724224 : INFO     : === out: ['hello 1/2: task.mpi_ser_func.c.000000\n', ['hello 1/2: task.mpi_ser_func.c.000000\n', 'hello 0/2: task.mpi_ser_func.c.000000\n'], ['hello 1/2: task.mpi_ser_func.c.000000\n', ['hello 1/2: task.mpi_ser_func.c.000000\n', 'hello 0/2: task.mpi_ser_func.c.000000\n'], 'hello 0/2: task.call.c.000000\n'], 'hello 1/2: task.call.c.000000\n']
1665492080.282 : master.000000        : 2292  : 140480360724224 : ERROR    : result callback failed
Traceback (most recent call last):
  File "/home/rp/radical.pilot.sandbox/rp.session.bd9afe9c-4960-11ed-9fbc-0242ac120002/pilot.0000/env/rp_named_env.ve_raptor/lib/python3.9/site-packages/radical/pilot/raptor/master.py", line 609, in _result_cb
    self.result_cb(tasks)
  File "/home/rp/radical.pilot.sandbox/rp.session.bd9afe9c-4960-11ed-9fbc-0242ac120002/pilot.0000/master.000000/./raptor_master.py", line 251, in result_cb
    sorted(task['stdout']),
TypeError: '<' not supported between instances of 'list' and 'str'
1665492080.283 : master.000000        : 2292  : 140480360724224 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_OUTPUT_PENDING]
1665492080.283 : master.000000        : 2292  : 140480360724224 : DEBUG    : put bulk AGENT_STAGING_OUTPUT_PENDING: 1
1665492082.835 : master.000000        : 2292  : 140480360724224 : INFO     : === out: ['hello 0/2: task.ser_func.c.000000\n', 'hello 1/2: task.ser_func.c.000000\n']
1665492082.835 : master.000000        : 2292  : 140480360724224 : INFO     : result_cb  task.ser_func.c.000000: AGENT_EXECUTING [['hello 0/2: task.ser_func.c.000000\n', 'hello 1/2: task.ser_func.c.000000\n']] [[None, None]]
1665492082.835 : master.000000        : 2292  : 140480360724224 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_OUTPUT_PENDING]
1665492082.836 : master.000000        : 2292  : 140480360724224 : DEBUG    : put bulk AGENT_STAGING_OUTPUT_PENDING: 1
1665492085.365 : master.000000        : 2292  : 140480360724224 : INFO     : === out: ['hello 0/2: task.ser_func.c.000000\n', ['hello 0/2: task.ser_func.c.000000\n', 'hello 1/2: task.ser_func.c.000000\n'], 'func_non_mpi\n']
1665492085.365 : master.000000        : 2292  : 140480360724224 : ERROR    : result callback failed
Traceback (most recent call last):
  File "/home/rp/radical.pilot.sandbox/rp.session.bd9afe9c-4960-11ed-9fbc-0242ac120002/pilot.0000/env/rp_named_env.ve_raptor/lib/python3.9/site-packages/radical/pilot/raptor/master.py", line 609, in _result_cb
    self.result_cb(tasks)
  File "/home/rp/radical.pilot.sandbox/rp.session.bd9afe9c-4960-11ed-9fbc-0242ac120002/pilot.0000/master.000000/./raptor_master.py", line 251, in result_cb
    sorted(task['stdout']),
TypeError: '<' not supported between instances of 'list' and 'str'
1665492085.366 : master.000000        : 2292  : 140480360724224 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_OUTPUT_PENDING]
1665492085.366 : master.000000        : 2292  : 140480360724224 : DEBUG    : put bulk AGENT_STAGING_OUTPUT_PENDING: 1
1665492087.861 : master.000000        : 2292  : 140480360724224 : INFO     : === out: ['hello 1/2: task.exec.c.000000\n', 'hello 0/2: task.exec.c.000000\n']
1665492087.861 : master.000000        : 2292  : 140480360724224 : INFO     : result_cb  task.exec.c.000000: AGENT_EXECUTING [['hello 0/2: task.exec.c.000000\n', 'hello 1/2: task.exec.c.000000\n']] [[None, None]]
1665492087.862 : master.000000        : 2292  : 140480360724224 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_OUTPUT_PENDING]
1665492087.862 : master.000000        : 2292  : 140480360724224 : DEBUG    : put bulk AGENT_STAGING_OUTPUT_PENDING: 1
1665492090.407 : master.000000        : 2292  : 140480360724224 : INFO     : === out: ['hello 0/2: task.eval.c.000000 [None]\n', 'hello 1/2: task.eval.c.000000 [None]\n']
1665492090.407 : master.000000        : 2292  : 140480360724224 : INFO     : result_cb  task.eval.c.000000: AGENT_EXECUTING [['hello 0/2: task.eval.c.000000 [None]\n', 'hello 1/2: task.eval.c.000000 [None]\n']] [[None, None]]
1665492090.407 : master.000000        : 2292  : 140480360724224 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_OUTPUT_PENDING]
1665492090.412 : master.000000        : 2292  : 140480360724224 : DEBUG    : put bulk AGENT_STAGING_OUTPUT_PENDING: 1
1665492095.449 : master.000000        : 2292  : 140480360724224 : INFO     : === out: ['hello 1/2: task.proc.c.000000\n', 'hello 0/2: task.proc.c.000000\n']
1665492095.449 : master.000000        : 2292  : 140480360724224 : INFO     : result_cb  task.proc.c.000000: AGENT_EXECUTING [['hello 0/2: task.proc.c.000000\n', 'hello 1/2: task.proc.c.000000\n']] [[None, None]]
1665492095.449 : master.000000        : 2292  : 140480360724224 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_OUTPUT_PENDING]
1665492095.450 : master.000000        : 2292  : 140480360724224 : DEBUG    : put bulk AGENT_STAGING_OUTPUT_PENDING: 1
1665492100.435 : master.000000        : 2292  : 140480360724224 : INFO     : === out: ['hello 1/2: task.shell.c.000000\n', 'hello 0/2: task.shell.c.000000\n']
1665492100.435 : master.000000        : 2292  : 140480360724224 : INFO     : result_cb  task.shell.c.000000: AGENT_EXECUTING [['hello 0/2: task.shell.c.000000\n', 'hello 1/2: task.shell.c.000000\n']] [[None, None]]
1665492100.436 : master.000000        : 2292  : 140480360724224 : DEBUG    : advance bulk: 1 [True, True, AGENT_STAGING_OUTPUT_PENDING]
1665492100.436 : master.000000        : 2292  : 140480360724224 : DEBUG    : put bulk AGENT_STAGING_OUTPUT_PENDING: 1

```
##   Requests

- [ ] Update documentation for `Task.stdout` (#2730 )
- [x] Document `TaskDescription.ranks`
- [ ] Update `raptor.py` example script to resolve errors. https://github.com/radical-cybertools/radical.pilot/pull/2729
- [ ] Document the intended / expected behavior for `raptor.Worker.get_master().run_task()` with notes on how to handle results. (partially treated with #2729, though the nested lists of output and possibly duplicated/reentrant/recursive calls don't yet make sense to me. Hopefully addressed with #2730 )

**Comment by andre-merzky** [comment]
[ ] Update documentation for Task.stdout
 Agree, that needs to be done. 
 [x] Document TaskDescription.ranks
 This is (documented](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/task_description.py#L202)
 [ ] Update raptor.py example script to resolve errors
 Oh, indeed - the `sorted` should have been removed.  I'll take care of this.
 [ ] Document the intended / expected behavior for raptor.Worker.get_master().run_task() with notes on how to handle results.
 Ack.
