### ISSUE TITLE
RAPTOR: master fails

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2792]
Related to: [RP-Parsl_Draft_PR](https://github.com/radical-cybertools/radical.pilot/issues/2782)

```
Traceback (most recent call last):
  File "raptor_master.py", line 141, in <module>
    master.submit_workers(descr=descr, count=n_workers)
  File "/home/aymen/radical.pilot.sandbox/rpex.session.surfacebook.aymen.019334.0003/pilot.0000/env/rp_named_env.ve_raptor/lib/python3.8/site-packages/radical/pilot/raptor/master.py", line 306, in submit_workers
    td['ranks']          = descr['ranks']
  File "/home/aymen/radical.pilot.sandbox/rpex.session.surfacebook.aymen.019334.0003/pilot.0000/env/rp_named_env.ve_raptor/lib/python3.8/site-packages/radical/utils/typeddict.py", line 194, in __getitem__
    return self._data[k]
KeyError: 'ranks'
```
I assumed that the cpu_processes is supported as our code is backward compatible, or am I missing something? Also, the example in the devel branch shows that.

RP-Stack: 

```
 version              : 3.8.10
  virtualenv           : /home/aymen/ve/repex

  radical.gtod         : 1.16.0
  radical.pilot        : 1.18.1-v1.18.1-240-gc337c9a67@devel
  radical.saga         : 1.18.0
  radical.utils        : 1.18.1
```

**Comment by andre-merzky** [comment]
Thanks for opening this!  The backward compatibility is handled in the `TaskDescription` class - but the worker description dict is never rendered as a `TaskDescription` and only ever handled as a dict, thus the mechanism does not kick in...

I assume this is not a showstopper though for now, right?
