### ISSUE TITLE
RAPTOR: fails, related to #2792

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2794]
This is related to #2792. If specify `ranks` instead of `cpu_processes`, RAPTOR fails with: 
1- `agent_executing.0000.log`
```
Traceback (most recent call last):
  File "/home/aymen/ve/rpex/lib/python3.8/site-packages/radical/pilot/agent/executing/popen.py", line 104, in work
    self._handle_task(task)
  File "/home/aymen/ve/rpex/lib/python3.8/site-packages/radical/pilot/agent/executing/popen.py", line 238, in _handle_task
    launcher = self._rm.find_launcher(task)
  File "/home/aymen/ve/rpex/lib/python3.8/site-packages/radical/pilot/agent/resource_manager/base.py", line 423, in find_launcher
    lm_can_launch, err_message = launcher.can_launch(task)
  File "/home/aymen/ve/rpex/lib/python3.8/site-packages/radical/pilot/agent/launch_method/fork.py", line 56, in can_launch
    node = task['slots']['ranks'][0]['node_name']
IndexError: list index out of range
```

2- `master.000000/master.000000.log`
```

raceback (most recent call last):
  File "/home/aymen/radical.pilot.sandbox/rpex.session.surfacebook.aymen.019334.0004/pilot.0000/env/rp_named_env.ve_raptor/lib/python3.8/site-packages/radical/pilot/raptor/master.py", line 582, in _request_cb
    filtered = self.request_cb(tasks)
  File "raptor_master.py", line 70, in request_cb
    self._submitted[mode] += 1
KeyError: 'function'
```

**Comment by mturilli** [comment]
@andre-merzky this is breaking Parsl/RP integration and, in turn, it is breaking ExaWorks tutorial(s). Apart from escalating this in today Sprint, we should trace back what produced the break. I can see this might be a consequence of the changes we made to task description. Were those changes mandated by a use case/project?

**Comment by mtitov** [comment]
@AymenFJA regarding p.2: please ensure that `mode` for such tasks is `rp.TASK_FUNCTION` and not `rp.FUNCTION`

**Comment by AymenFJA** [comment]
@mtitov I am using the `rp.Task_FUNCTION` as follow:
```
  task. Mode       = rp.TASK_FUNCTION
  task.scheduler  = 'master.%06d' % (tid % self.n_masters)
  task.function   = PythonTask(func, *args, **kwargs)
```

**Comment by AymenFJA** [comment]
Inconsistent stack problem was fixed, thanks @mtitov .
