### ISSUE TITLE
RAPTOR: DeafultWorker (non-MPI) fails 

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.pilot#2814]
Using `rp.raptor.DeafultWorker` instead of `rp.raptor.MPI_Worker` in the raptor_worker.py in here https://github.com/radical-cybertools/radical.pilot/blob/ae0fa49e7aa6ed18232974fadc046805cb07b0b1/examples/misc/raptor_worker.py#L10: 

the examples (`raptor.py`) fails with (from `master.000000/master.000000.worker.0000.err`):
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aymen/radical.pilot.sandbox/rp.session.surfacebook.aymen.019368.0005/pilot.0000/env/rp_named_env.ve_raptor/lib/python3.8/site-packages/radical/pilot/raptor/worker.py", line 91, in run
    worker = wclass(cfg)
  File "/home/aymen/radical.pilot.sandbox/rp.session.surfacebook.aymen.019368.0005/pilot.0000/master.000000/./raptor_worker.py", line 21, in __init__
    rp.raptor.DefaultWorker.__init__(self, cfg)
  File "/home/aymen/radical.pilot.sandbox/rp.session.surfacebook.aymen.019368.0005/pilot.0000/env/rp_named_env.ve_raptor/lib/python3.8/site-packages/radical/pilot/raptor/worker_default.py", line 63, in __init__
    self._resources = {'cores' : [0] * self._n_cores,
TypeError: can't multiply sequence by non-int of type 'NoneType'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aymen/radical.pilot.sandbox/rp.session.surfacebook.aymen.019368.0005/pilot.0000/env/rp_named_env.ve_raptor/lib/python3.8/site-packages/radical/pilot/raptor/worker.py", line 91, in run
    worker = wclass(cfg)
  File "/home/aymen/radical.pilot.sandbox/rp.session.surfacebook.aymen.019368.0005/pilot.0000/master.000000/./raptor_worker.py", line 21, in __init__
    rp.raptor.DefaultWorker.__init__(self, cfg)
  File "/home/aymen/radical.pilot.sandbox/rp.session.surfacebook.aymen.019368.0005/pilot.0000/env/rp_named_env.ve_raptor/lib/python3.8/site-packages/radical/pilot/raptor/worker_default.py", line 63, in __init__
    self._resources = {'cores' : [0] * self._n_cores,
TypeError: can't multiply sequence by non-int of type 'NoneType'
```

**Comment by mturilli** [comment]
Related PR merged. Closing.
