### ISSUE TITLE
Tasks Stuck on tmgr.wait_tasks - 

### ISSUE THREAD

**Issue by kartikmodi** [radical-cybertools/radical.pilot#2840]
The documentation was building on locally because there seems to be a bug that tasks are getting stuck. 
 Maybe I was using an older RP release when I was writing and working on jupyter notebook. 
 
 However, I may have upgraded the environment and now documentation isn't building. 
 
I confirmed the issue by running the basic examples - 
Command ran - 
```
dotenv run /home/workstation/.virtualenvs/radical-pilot-env/bin/python /home/workstation/workspace/PycharmProjects/radical.pilot/examples/03_multiple_pilots.py local.localhost local.localhost

```
```
create task manager                                                           ok
create 128 task description(s)
        ........................................................................
        ........................................................              ok
submit: ########################################################################

--------------------------------------------------------------------------------
gather results                                                                  

wait  : 
```

Then I did a `pip install .` and the above command started working. 
But the documentation build is not working. 
Upon checking i see the log in bootstrap.out - 

```
Installing collected packages: radical.pilot
Successfully installed radical.pilot-1.20.1
#
# SUCCESS
#
# -------------------------------------------------------------------
purge install source at radical.pilot-1.20.1/
/home/workstation/.local/bin/radical-utils-env.sh
verify python viability: /home/workstation/radical.pilot.sandbox/ve.local.localhost.1.20.1/bin/python3 ... ok
verify module viability: radical.pilot   ...Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/workstation/radical.pilot.sandbox/rp.session.debian-x.workstation.019419.0008/pilot.0000/rp_install/lib/python3.9/site-packages/radical/pilot/__init__.py", line 9, in <module>
    import radical.utils as _ru
ModuleNotFoundError: No module named 'radical.utils'
 failed
python installation cannot load module radical.pilot - abort
```

**Comment by kartikmodi** [comment]
@andre-merzky @mturilli This issue is now always re-creatable in jupyter notebooks in recent releases. I don't know and lost track that on which release it working on my system, but I am sure 1.20, 1.21. 1.22 all have this problem.
