### ISSUE TITLE
Stock RP fails to boostrap on localhost

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#2845]
Clean Ubuntu server LTS installation; default stack installed via pip:

```
$ radical-stack

  python               : /home/mturilli/ve/docs/bin/python3
  pythonpath           :
  version              : 3.10.6
  virtualenv           : /home/mturilli/ve/docs

  radical.analytics    : 1.20.1
  radical.entk         : 1.30.0
  radical.gtod         : 1.20.1
  radical.pilot        : 1.21.0
  radical.saga         : 1.21.0
  radical.utils        : 1.21.0
```

Script starts execution on localhost and hangs forever:

```
$ python het.py
new session: [rp.session.mosto.mturilli.019426.0002]                           \
database   : [mongodb://rct-tutorial:****@95.217.193.116:27017/rct-tutorial]  ok
create pilot manager                                                          ok
submit 1 pilot(s)
        pilot.0000   local.localhost         128 cores      16 gpus           ok
create task manager                                                           ok
submit: ########################################################################
wait  :
```

Only visible error is in `bootstrap_0.out`:

```
# -------------------------------------------------------------------
#
# Create virtualenv
# cmd: /usr/bin/python3 virtualenv-16.7.5/virtualenv.py -p python3 /home/mturilli/radical.pilot.sandbox/ve.local.localhost.1.21.0
#
/home/mturilli/radical.pilot.sandbox/rp.session.mosto.mturilli.019426.0002/pilot.0000/virtualenv-16.7.5/virtualenv.py:24: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
/home/mturilli/radical.pilot.sandbox/rp.session.mosto.mturilli.019426.0002/pilot.0000/virtualenv-16.7.5/virtualenv.py:25: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  import distutils.sysconfig
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/mturilli/radical.pilot.sandbox/ve.local.localhost.1.21.0/bin/python3
Also creating executable in /home/mturilli/radical.pilot.sandbox/ve.local.localhost.1.21.0/bin/python
Traceback (most recent call last):
  File "/home/mturilli/radical.pilot.sandbox/rp.session.mosto.mturilli.019426.0002/pilot.0000/virtualenv-16.7.5/virtualenv.py", line 2632, in <module>
    main()
  File "/home/mturilli/radical.pilot.sandbox/rp.session.mosto.mturilli.019426.0002/pilot.0000/virtualenv-16.7.5/virtualenv.py", line 860, in main
    create_environment(
  File "/home/mturilli/radical.pilot.sandbox/rp.session.mosto.mturilli.019426.0002/pilot.0000/virtualenv-16.7.5/virtualenv.py", line 1156, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/home/mturilli/radical.pilot.sandbox/rp.session.mosto.mturilli.019426.0002/pilot.0000/virtualenv-16.7.5/virtualenv.py", line 1719, in install_python
    fix_local_scheme(home_dir, symlink)
  File "/home/mturilli/radical.pilot.sandbox/rp.session.mosto.mturilli.019426.0002/pilot.0000/virtualenv-16.7.5/virtualenv.py", line 1805, in fix_local_scheme
    if sysconfig._get_default_scheme() == "posix_local":
AttributeError: module 'sysconfig' has no attribute '_get_default_scheme'. Did you mean: 'get_default_scheme'?
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
ERROR: couldn't create virtualenv
ERROR: couldn't create virtenv - abort
```

**Comment by mturilli** [comment]
Follow up. Running the script a second time, leads to a race condition in the bootstrapper. Always from `bootstrap_0.out`:
```
virtenv /home/mturilli/radical.pilot.sandbox/ve.local.localhost.1.21.0 exists
/home/mturilli/radical.pilot.sandbox/rp.session.mosto.mturilli.019427.0000/pilot.0000//bootstrap_0.sh: line 908: /home/mturilli/radical.pilot.sandbox/ve.local.loca
lhost.1.21.0/bin/activate: No such file or directory
Loading of virtual env failed!
```

**Comment by andre-merzky** [comment]
Dammit, that `sysconfig` call changed scope between 3.9 and 3.10 - will fix.  

The second point you raise, that the bootstrapper leaves the VE in an unusable state, is difficult to solve in general: we could force-remove the VE, but then again, the VE might point to something specifically prepared by the user, so blindly purging it might be a bad idea.  The clean approach would be to set the `virtenv_mode` flag in the resource config to `recreate` (instead of the default `create`).  In that case, an existing VE gets purged before creation.  That though is cumbersome and opaque to the user...

**Comment by andre-merzky** [comment]
Oh, wait - I just realized that the `sysconfig` call does not happen in our code, but in `virtualenv.py`!  Uhm, I have no idea what to do about that, really - we have no power over that code, nor what module versions are installed in that fresh Ubuntu LTS... :-/  Any idea how we should handle this?

**Comment by mtitov** [comment]
Resolved, and now it is tracked (e.g., https://github.com/radical-cybertools/radical.pilot/actions/runs/4407168204)
