### ISSUE TITLE
pilot staging error

### ISSUE THREAD

**Issue by AlexReedy** [radical-cybertools/radical.pilot#2923]
```
/Traceback (most recent call last):                                                                                 
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/entk/execman/rp/resource_manager.py", line 196, in submit_resource_request
    self._pilot.stage_in(shared_data)
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/pilot/pilot.py", line 701, in stage_in
    self._pmgr._pilot_staging_input(sds)
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/pilot/pilot_manager.py", line 453, in _pilot_staging_input
    raise RuntimeError('pilot staging failed: %s' % errs)
RuntimeError: pilot staging failed: ['NoSuccess("failed at mkdir \'/home/dev/radical.pilot.sandbox/re.session.neuromancer.dev.019480.0000/pilot.0000/\': (1) (mkdir: cannot create directory ‘/home/dev/radical.pilot.sandbox’: File exists\\n)")']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/entk/appman/appmanager.py", line 418, in run
    self._rmgr.submit_resource_request()
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/entk/execman/rp/resource_manager.py", line 220, in submit_resource_request
    raise EnTKError(ex) from ex
radical.entk.exceptions.EnTKError: pilot staging failed: ['NoSuccess("failed at mkdir \'/home/dev/radical.pilot.sandbox/re.session.neuromancer.dev.019480.0000/pilot.0000/\': (1) (mkdir: cannot create directory ‘/home/dev/radical.pilot.sandbox’: File exists\\n)")']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/entk/execman/rp/resource_manager.py", line 251, in _terminate_resource_request
    self._session.close(cleanup=cleanup,
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/pilot/session.py", line 281, in close
    pmgr.close(terminate=options.terminate)
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/pilot/pilot_manager.py", line 229, in close
    self.cancel_pilots(_timeout=20)
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/pilot/pilot_manager.py", line 841, in cancel_pilots
    self.wait_pilots(uids=uids, timeout=_timeout)
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/pilot/pilot_manager.py", line 772, in wait_pilots
    time.sleep (0.1)
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/runFACTS.py", line 207, in <module>
    run_experiment(args.edir, args.debug, resourcedir=args.resourcedir, makeshellscript = args.shellscript)
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/runFACTS.py", line 101, in run_experiment
    amgr.run()
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/entk/appman/appmanager.py", line 449, in run
    self.terminate()
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/entk/appman/appmanager.py", line 486, in terminate
    self._rmgr._terminate_resource_request()
  File "/home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/lib/python3.10/site-packages/radical/entk/execman/rp/resource_manager.py", line 264, in _terminate_resource_request
    raise KeyboardInterrupt from ex
KeyboardInterrupt
```

**Comment by AlexReedy** [comment]
python               : /home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3/bin/python3
  pythonpath           : 
  version              : 3.10.9
  virtualenv           : /home/dev/factsv1.0.0/branches/emulandice.setup.fix/facts/scripts/ve3

  radical.entk         : 1.34.0-v1.33.0-1-gceedb212@projects-facts
  radical.gtod         : 1.20.1
  radical.pilot        : 1.33.0
  radical.saga         : 1.33.0
  radical.utils        : 1.33.0

**Comment by mturilli** [comment]
@AlexReedy as discussed, could you provide a session so that @andre-merzky can reproduce this and fix it?

**Comment by AlexReedy** [comment]
Hey Matteo, I sent the session over yesterday. Let me know if you need me to resendSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Matteo Turilli ***@***.***> Date: 5/5/23  2:53 PM  (GMT-05:00) To: "radical-cybertools/radical.pilot" ***@***.***> Cc: AHReedy ***@***.***>, Mention ***@***.***> Subject: Re: [radical-cybertools/radical.pilot] pilot staging error (Issue #2923) 
@AlexReedy as discussed, could you provide a session so that @andre-merzky can reproduce this and fix it?

**Comment by andre-merzky** [comment]
Pasting update from slack:

```
You may want to have a look into bootstrap_0.out of the first session ([re.session.neuromancer.dev](http://re.session.neuromancer.dev/).019481.0003).  It tries to create a virtualenv via pyhon3 -m venv but venv is not available on your localhost.  It then tries virtualenv but that is also not installed.  As a fallback we download virtualenv via curl, but alas curl is also not available on your system, so that also fails and the bootstrapper gives up.
Not sure what type of linux you are running, but something like a sudo apt install curl should help to resolve that problem.  You probably should remove the radical.pilot.sandbox subtree completely to start afresh after that.
Let us know hos that goes!
```

**Comment by andre-merzky** [comment]
@AlexReedy : do you have any updates on this?  Can we help?

**Comment by AlexReedy** [comment]
I did the curl install and it still hung but had to pivot to a different issue so I haven't diagnosed why it didn't work yet. I'll look at it more this week sometime

**Comment by andre-merzky** [comment]
Thanks - feel free to push over the new session.

**Comment by AlexReedy** [comment]
Also I may not be looking this up correctly, but it looks like that IP is somewhere in Germany?

**Comment by andre-merzky** [comment]
hey @AlexReedy - the ping error is a red herring I'm afraid: the bootstrapper tries to sync clocks for profiling purposes - but if NTP is not reachable it will proceed without clock syncs all right, so the error is ignored.

**Comment by AlexReedy** [comment]
@andre-merzky ok yea that's what I determined eventually too, wanted to keep it up just in case it was helpful though! Thanks for getting back on that

**Comment by andre-merzky** [comment]
Hi Alex - is this ticket still current or was it resolved with the module update?  If not, please do push a session for it.

**Comment by AlexReedy** [comment]
Hey Andre, this ticket is closed, the fix you guys put forward on the dev branch worked great!
