### ISSUE TITLE
Issue with using PSI/J as a launcher

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#2995]
Run RP and EnTK locally with PSI/J (0.9.0) installed (within our Tutorials docker container)

```
1689869094.588 : pmgr_launching.0000  : 10444 : 140192688629312 : ERROR    : failed to create psij executor
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/radical/pilot/pmgr/launching/psi_j.py", line 122, in can_launch
    self._jex[schema] = psij.JobExecutor.get_instance(schema)
  File "/opt/conda/lib/python3.9/site-packages/psij/job_executor.py", line 235, in get_instance
    instance = selected.ecls(url=url, config=config)
  File "/opt/conda/lib/python3.9/site-packages/psij/executors/local.py", line 215, in __init__
    self._reaper = _ProcessReaper.get_instance()
  File "/opt/conda/lib/python3.9/site-packages/psij/executors/local.py", line 123, in get_instance
    signal.signal(signal.SIGCHLD, _handle_sigchld)
  File "/opt/conda/lib/python3.9/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
1689869094.590 : pmgr_launching.0000  : 10444 : 140192688629312 : INFO     : use launcher SAGA for pilot pilot.0000
```

**Comment by andre-merzky** [comment]
Ah, bugger, thanks for catching this...

**Comment by mtitov** [comment]
resolved
