### ISSUE TITLE
Exception thrown on regular shut-down

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.pilot#310]
With the simple localhost example I get the following error on `holmes.cancres.nottingham.ac.uk`, a machine in Nottingham:

```
[Callback]: ComputePilot '5401823fa99a1905e7a11ee7' state: Failed.
pilot manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "local.py", line 148, in <module>
    umgr.wait_units()
  File "/users/ole/HT-BAC-Tools/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 654, in wait_units
    if  unit.state not in state :
  File "/users/ole/HT-BAC-Tools/lib/python2.7/site-packages/radical/pilot/compute_unit.py", line 239, in state
    cu_json = self._worker.get_compute_unit_data(self.uid)
  File "/users/ole/HT-BAC-Tools/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 157, in get_compute_unit_data
    self._initialized.wait()
  File "/usr/lib64/python2.7/threading.py", line 400, in wait
    self.__cond.acquire()
KeyboardInterrupt
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/users/ole/HT-BAC-Tools/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 267, in run
  File "/users/ole/HT-BAC-Tools/lib/python2.7/site-packages/radical/pilot/db/database.py", line 506, in get_compute_units
  File "/users/ole/HT-BAC-Tools/lib/python2.7/site-packages/pymongo/cursor.py", line 1058, in next
  File "/users/ole/HT-BAC-Tools/lib/python2.7/site-packages/pymongo/cursor.py", line 1002, in _refresh
  File "/users/ole/HT-BAC-Tools/lib/python2.7/site-packages/pymongo/cursor.py", line 915, in __send_message
  File "/users/ole/HT-BAC-Tools/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1207, in _send_message_with_response
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
```

Upon further investiagtion I see in the pilot log

```
2014-08-30 08:55:30,962 - radical.pilot.agent - INFO - Discovered execution environment: ['localhost']
2014-08-30 08:55:30,962 - radical.pilot.agent - ERROR - Error setting up execution environment: Not enough cores available (2) to satisfy allocation request (4).
2014-08-30 08:55:30,962 - radical.pilot.agent - ERROR - Error setting up execution environment: Not enough cores available (2) to satisfy allocation request (4).
```

This is due to the fact that the machine has only 2 cores, but the local examples requests 4. I have reverted the core-count in the example to 1. I think this should not be changed so it works for everyone. 

However, I am a bit baffled how radical pilot shuts down now. I never forced a system exit, so I expect the script to terminate without throwing any exceptions in this case.

**Comment by andre-merzky** [comment]
shutdown is cleaned up now.
