### ISSUE TITLE
Proxy server timed out

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.pilot#3285]
```
% cat ./radical.pilot.proxy.log
.....
1734067897.791 : radical.pilot.proxy  : 1597  : 140280397301312 : DEBUG    : req: {'cmd': 'register', 'args': [{'sid': 'rp.session.8620ca94-b913-11ef-a61d-0242ac110002'}], 'kwargs': {}}
1734067897.841 : radical.pilot.proxy  : 1597  : 140280397301312 : DEBUG    : rep: {'err': None, 'exc': None, 'res': {'proxy_control_pubsub': {'addr_pub': 'tcp://172.17.0.2:10002', 'addr_sub': 'tcp://172.17.0.2:
1734067909.610 : radical.pilot.proxy  : 1597  : 140280397301312 : DEBUG    : req: {'cmd': 'lookup', 'args': [{'sid': 'rp.session.8620ca94-b913-11ef-a61d-0242ac110002'}], 'kwargs': {}}
1734067909.610 : radical.pilot.proxy  : 1597  : 140280397301312 : DEBUG    : rep: {'err': None, 'exc': None, 'res': {'proxy_control_pubsub': {'addr_pub': 'tcp://172.17.0.2:10002', 'addr_sub': 'tcp://172.17.0.2:
1734068197.897 : radical.pilot.proxy  : 1597  : 140280407787072 : WARNING  : client rp.session.8620ca94-b913-11ef-a61d-0242ac110002 timed out
1734070444.426 : radical.pilot.proxy  : 1597  : 140280397301312 : DEBUG    : req: {'cmd': 'unregister', 'args': [{'sid': 'rp.session.8620ca94-b913-11ef-a61d-0242ac110002'}], 'kwargs': {}}
1734070444.428 : radical.pilot.proxy  : 1597  : 140280397301312 : ERROR    : command failed: {'cmd': 'unregister', 'args': [{'sid': 'rp.session.8620ca94-b913-11ef-a61d-0242ac110002'}], 'kwargs': {}}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/radical/utils/zmq/server.py", line 304, in _work
    rep = self._success(self._cbs[cmd](*args, **kwargs))
  File "/opt/conda/lib/python3.9/site-packages/radical/pilot/proxy.py", line 316, in _unregister
    raise RuntimeError('client %s not registered' % sid)
RuntimeError: client rp.session.8620ca94-b913-11ef-a61d-0242ac110002 not registered
1734070444.428 : radical.pilot.proxy  : 1597  : 140280397301312 : DEBUG    : rep: {'err': 'command failed: client rp.session.8620ca94-b913-11ef-a61d-0242ac110002 not registered', 'exc': 'Traceback (most recent 
1734070444.430 : radical.pilot.proxy  : 1597  : 140280579327808 : INFO     : stop proxy service
.....
```

Grace termination? or should it be reconnected after time out?

(*) current devel stack

**Comment by andre-merzky** [comment]
Let's discuss this - for now I increased the timeout to 24 hours in #3286

**Comment by mtitov** [comment]
resolved
