### ISSUE TITLE
Queue limit exceded

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#340]
When trying to schedule a pilot too big for the targeted queue I see:
```
2014:09:10 04:16:58 radical.pilot.MainProcess: [ERROR   ] Pilot launching failed: Error running job via 'qsub': node count (64) exceeds queue (normal) limit (32)
qsub: submit filter returned an error code, aborting job submission.
. Commandline was: SCRIPTFILE=`mktemp -t SAGA-Python-PBSJobScript.XXXXXX` &&  echo "
#!/bin/bash 
#PBS -V 
#PBS -o /home/mturilli/radical.pilot.sandbox/pilot-540fd09e20a6413bdc0ce7c4/AGENT.STDOUT 
#PBS -e /home/mturilli/radical.pilot.sandbox/pilot-540fd09e20a6413bdc0ce7c4/AGENT.STDERR 
#PBS -l walltime=0:30:00 
#PBS -q normal 
#PBS -A unc102 
#PBS -l nodes=64:ppn=32 
export    PBS_O_WORKDIR=/home/mturilli/radical.pilot.sandbox/pilot-540fd09e20a6413bdc0ce7c4 
mkdir -p  /home/mturilli/radical.pilot.sandbox/pilot-540fd09e20a6413bdc0ce7c4
cd        /home/mturilli/radical.pilot.sandbox/pilot-540fd09e20a6413bdc0ce7c4
/bin/bash -l default_bootstrapper.sh -n radicalpilot -s 540fd09820a6413bdc0ce7c1 -p 540fd09e20a6413bdc0ce7c4 -t 30 -d 10 -c 2048 -v 0.19 -m ec2-184-72-89-141.compute-1.amazonaws.com:27017  -i /usr/bin/python  -e 'module purge'  -e 'module load pgi'  -e 'module load mvapich2_ib'  -e 'module load gnubase'  -l TORQUE  -j SSH  -k MPIRUN_RSH  -x luve -b " > $SCRIPTFILE && /opt/torque/bin/qsub $SCRIPTFILE && rm -f $SCRIPTFILE (/home/mturilli/Virtualenvs/AIMES-CCGRID2015/local/lib/python2.7/site-packages/saga/adaptors/pbs/pbsjob.py +99 (log_error_and_raise)  :  raise exception(message))
Traceback (most recent call last):
  File "/home/mturilli/Virtualenvs/AIMES-CCGRID2015/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 457, in run
    pilotjob.run()
  File "/home/mturilli/Virtualenvs/AIMES-CCGRID2015/local/lib/python2.7/site-packages/saga/job/job.py", line 397, in run
    return self._adaptor.run (ttype=ttype)
  File "/home/mturilli/Virtualenvs/AIMES-CCGRID2015/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 51, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/mturilli/Virtualenvs/AIMES-CCGRID2015/local/lib/python2.7/site-packages/saga/adaptors/pbs/pbsjob.py", line 1087, in run
    self._id = self.js._job_run(self._api())
  File "/home/mturilli/Virtualenvs/AIMES-CCGRID2015/local/lib/python2.7/site-packages/saga/adaptors/pbs/pbsjob.py", line 612, in _job_run
    log_error_and_raise(message, saga.NoSuccess, self._logger)
  File "/home/mturilli/Virtualenvs/AIMES-CCGRID2015/local/lib/python2.7/site-packages/saga/adaptors/pbs/pbsjob.py", line 99, in log_error_and_raise
    raise exception(message)
NoSuccess: Error running job via 'qsub': node count (64) exceeds queue (normal) limit (32)
qsub: submit filter returned an error code, aborting job submission.
. Commandline was: SCRIPTFILE=`mktemp -t SAGA-Python-PBSJobScript.XXXXXX` &&  echo "
#!/bin/bash 
#PBS -V 
#PBS -o /home/mturilli/radical.pilot.sandbox/pilot-540fd09e20a6413bdc0ce7c4/AGENT.STDOUT 
#PBS -e /home/mturilli/radical.pilot.sandbox/pilot-540fd09e20a6413bdc0ce7c4/AGENT.STDERR 
#PBS -l walltime=0:30:00 
#PBS -q normal 
#PBS -A unc102 
#PBS -l nodes=64:ppn=32 
export    PBS_O_WORKDIR=/home/mturilli/radical.pilot.sandbox/pilot-540fd09e20a6413bdc0ce7c4 
mkdir -p  /home/mturilli/radical.pilot.sandbox/pilot-540fd09e20a6413bdc0ce7c4
cd        /home/mturilli/radical.pilot.sandbox/pilot-540fd09e20a6413bdc0ce7c4
/bin/bash -l default_bootstrapper.sh -n radicalpilot -s 540fd09820a6413bdc0ce7c1 -p 540fd09e20a6413bdc0ce7c4 -t 30 -d 10 -c 2048 -v 0.19 -m ec2-184-72-89-141.compute-1.amazonaws.com:27017  -i /usr/bin/python  -e 'module purge'  -e 'module load pgi'  -e 'module load mvapich2_ib'  -e 'module load gnubase'  -l TORQUE  -j SSH  -k MPIRUN_RSH  -x luve -b " > $SCRIPTFILE && /opt/torque/bin/qsub $SCRIPTFILE && rm -f $SCRIPTFILE (/home/mturilli/Virtualenvs/AIMES-CCGRID2015/local/lib/python2.7/site-packages/saga/adaptors/pbs/pbsjob.py +99 (log_error_and_raise)  :  raise exception(message))

2014:09:10 04:16:58 radical.pilot.MainProcess: [INFO    ] ComputePilot '540fd09e20a6413bdc0ce7c4' state changed from 'Launching' to 'Failed'.
```
Should we handle this error? If so, how? For example, I attempted to execute a 6144 BoT on 3 pilots. Two failed to be scheduled with the error above and one went through. In this case, I might have still been able to run all the tasks on a single pilot but that was not the point of the experiment so I killed the whole thing. Does this tell us that we need an explicit flag in the pilot descriptions to decide what to do in case of failure of that pilot? For example, just issue a warning or clean-exit the whole script?

**Comment by andre-merzky** [comment]
This topic is now partially covered by aimes.bundles.  We still may want to consider to provide a subset of that information in RP level, I thus keep this ticket open with lower priority.  Matteo, feel free to add / change requirements on this ticket, and to raise priority if you feel that is useful/necessary in the aimes context!

**Comment by andre-merzky** [comment]
Matteo, do you mind if we pass this topic fully to aimes.bundles?

**Comment by mturilli** [comment]
OK
