### ISSUE TITLE
shutdown issue

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#447]
```
...
[Callback]: ComputeUnit  '54802ef7a853781052e3e76a' state: Executing.
2014:12:04 10:59:51 radical.pilot.MainProcess: [INFO    ] Performing periodical health check for 54802ef1a853781052e3e767 (SAGA job id [pbs+ssh://hopper.nersc.gov/?ppn=24]-[8449895])
2014:12:04 10:59:51 radical.pilot.MainProcess: [INFO    ] pilot 54802ef1a853781052e3e767 seems alive and well
2014:12:04 10:59:51 radical.pilot.MainProcess: [DEBUG   ] write: [   19] [  176] (unset GREP_OPTIONS; /usr/common/usg/bin/qstat -f1 8449895 | grep -E -i '(job_state)|(exec_host)|(exit_status)|(ctime)|(start_time)|(comp_time)|(mtime)|(stime)|(qtime)|(etime)'\n)
2014:12:04 10:59:51 radical.pilot.MainProcess: [DEBUG   ] read : [   19] [  696] (    job_state = R\n    ctime = ... e = Thu Dec  4 01:53:05 2014\n)
2014:12:04 10:59:51 radical.pilot.MainProcess: [DEBUG   ] read : [   19] [   91] (    etime = Thu Dec  4 01:53:05 2014\n    start_time = Thu Dec  4 01:55:29 2014\nPROMPT-0->)
2014:12:04 11:00:02 radical.pilot.MainProcess: [DEBUG   ] write: [   18] [  176] (unset GREP_OPTIONS; /usr/common/usg/bin/qstat -f1 8449895 | grep -E -i '(job_state)|(exec_host)|(exit_status)|(ctime)|(start_time)|(comp_time)|(mtime)|(stime)|(qtime)|(etime)'\n)
2014:12:04 11:00:02 radical.pilot.MainProcess: [DEBUG   ] read : [   18] [  696] (    job_state = R\n    ctime = ... e = Thu Dec  4 01:53:05 2014\n)
2014:12:04 11:00:02 radical.pilot.MainProcess: [DEBUG   ] read : [   18] [   91] (    etime = Thu Dec  4 01:53:05 2014\n    start_time = Thu Dec  4 01:55:29 2014\nPROMPT-0->)
2014:12:04 11:00:48 radical.pilot.MainProcess: [INFO    ] ComputePilot '54802ef1a853781052e3e767' state changed from 'Active' to 'Done'.
[Callback]: ComputePilot '54802ef1a853781052e3e767' state: Done.
2014:12:04 11:00:48 radical.pilot.MainProcess: [ERROR   ] pilot manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/radical.pilot-0.21-py2.7.egg/radical/pilot/controller/pilot_manager_controller.py", line 311, in run
    self.call_callbacks(pilot_id, new_state)
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/radical.pilot-0.21-py2.7.egg/radical/pilot/controller/pilot_manager_controller.py", line 227, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "mpi_hopper_test.py", line 12, in pilot_state_cb
    sys.exit (1)
SystemExit: 1
2014:12:04 11:00:48 radical.pilot.MainProcess: [ERROR   ] pworker Thread-1 stops   launcher PilotLauncherWorker-1
2014:12:04 11:00:48 radical.pilot.MainProcess: [ERROR   ] launcher PilotLauncherWorker-1 stopping
2014:12:04 11:00:48 radical.pilot.MainProcess: [ERROR   ] launcher PilotLauncherWorker-1 stopped
2014:12:04 11:00:48 radical.pilot.MainProcess: [ERROR   ] pworker Thread-1 stopped launcher PilotLauncherWorker-1
Traceback (most recent call last):
  File "mpi_hopper_test.py", line 96, in <module>
    umgr.wait_units()
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/radical.pilot-0.21-py2.7.egg/radical/pilot/unit_manager.py", line 670, in wait_units
    time.sleep (0.1)
KeyboardInterrupt
2014:12:04 11:00:51 radical.pilot.MainProcess: [DEBUG   ] write: [   19] [  176] (unset GREP_OPTIONS; /usr/common/usg/bin/qstat -f1 8449895 | grep -E -i '(job_state)|(exec_host)|(exit_status)|(ctime)|(start_time)|(comp_time)|(mtime)|(stime)|(qtime)|(etime)'\n)
2014:12:04 11:00:51 radical.pilot.MainProcess: [DEBUG   ] read : [   19] [  696] (    job_state = R\n    ctime = ... e = Thu Dec  4 01:53:05 2014\n)
2014:12:04 11:00:51 radical.pilot.MainProcess: [DEBUG   ] read : [   19] [   91] (    etime = Thu Dec  4 01:53:05 2014\n    start_time = Thu Dec  4 01:55:29 2014\nPROMPT-0->)
2014:12:04 11:01:02 radical.pilot.MainProcess: [DEBUG   ] write: [   18] [  176] (unset GREP_OPTIONS; /usr/common/usg/bin/qstat -f1 8449895 | grep -E -i '(job_state)|(exec_host)|(exit_status)|(ctime)|(start_time)|(comp_time)|(mtime)|(stime)|(qtime)|(etime)'\n)
2014:12:04 11:01:02 radical.pilot.MainProcess: [DEBUG   ] read : [   18] [  696] (    job_state = C\n    ctime = ... e = Thu Dec  4 01:53:05 2014\n)
2014:12:04 11:01:02 radical.pilot.MainProcess: [DEBUG   ] read : [   18] [  154] (    etime = Thu Dec  4 01:53:05 2014\n    exit_status = 0\n    start_time = Thu Dec  4 01:55:29 2014\n    comp_time = Thu Dec  4 02:00:56 2014\nPROMPT-0->)
2014:12:04 11:01:51 radical.pilot.MainProcess: [DEBUG   ] write: [   19] [  176] (unset GREP_OPTIONS; /usr/common/usg/bin/qstat -f1 8449895 | grep -E -i '(job_state)|(exec_host)|(exit_status)|(ctime)|(start_time)|(comp_time)|(mtime)|(stime)|(qtime)|(etime)'\n)
2014:12:04 11:01:52 radical.pilot.MainProcess: [DEBUG   ] read : [   19] [  696] (    job_state = C\n    ctime = ... e = Thu Dec  4 01:53:05 2014\n)
2014:12:04 11:01:52 radical.pilot.MainProcess: [DEBUG   ] read : [   19] [  154] (    etime = Thu Dec  4 01:53:05 2014\n    exit_status = 0\n    start_time = Thu Dec  4 01:55:29 2014\n    comp_time = Thu Dec  4 02:00:56 2014\nPROMPT-0->)
```

The job is gone/done, but the app remains hanging here.

**Comment by andre-merzky** [comment]
pilot cancellation should be cleaned up now.
