### ISSUE TITLE
Broken Pipe hits again

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.pilot#465]
```
2014:12:22 16:06:36 radical.pilot.MainProcess: [DEBUG   ] saga.fs.File.copy ('file://localhost/users/ole/coam-on-archer/1_coco.log')
2014:12:22 16:06:36 22250  OutputFileTransferWorker-2 saga.ShellFile        : [DEBUG   ] flush: [   15] [     ] (flush pty read cache)
2014:12:22 16:06:36 22250  OutputFileTransferWorker-2 saga.ShellFile        : [DEBUG   ] run_sync: mkdir -p '/users/ole/coam-on-archer/'
2014:12:22 16:06:36 22250  OutputFileTransferWorker-2 saga.ShellFile        : [DEBUG   ] write: [   15] [   38] (mkdir -p '/users/ole/coam-on-archer/'\n)
2014:12:22 16:06:36 22250  OutputFileTransferWorker-2 saga.ShellFile        : [DEBUG   ] read : [   15] [   10] (PROMPT-0->)
2014:12:22 16:06:36 radical.pilot.MainProcess: [DEBUG   ] flush: [   14] [     ] (flush pty read cache)
2014:12:22 16:06:36 radical.pilot.MainProcess: [DEBUG   ] flush: [   18] [     ] (flush pty read cache)
2014:12:22 16:06:36 radical.pilot.MainProcess: [DEBUG   ] write: [   18] [  121] ( ls /work/e290/e290/oweidner/radical.pilot.sandbox/pilot-54983f33f8cdba56ea998d67/unit-54984098f8cdba56ea998d8b/coco.log\n)
2014:12:22 16:06:36 radical.pilot.MainProcess: [DEBUG   ] read : [   18] [  159] ( ls /work/e290/e290/oweidner/radical.pilot.sandbox/pilot-54983f33f8cdba56ea998d67/unit-54984098f8cdba56ea998d8b/coco.log\nCouldn't send packet: Broken pipe\n)
2014:12:22 16:06:36 radical.pilot.MainProcess: [ERROR   ] Output transfer failed: read from process failed '[Errno 5] Input/output error' : (s   --:-- ETA//users/ole/ExTASY-tools/lib/python2.7/site-p 100%  521     0.5KB/s   00:00    
sftp>  ls /work/e290/e290/oweidner/radical.pilot.sandbox/pilot-54983f33f8cdba56ea998d67/unit-54984098f8cdba56ea998d8b/coco.log
Couldn't send packet: Broken pipe
) (/users/ole/ExTASY-tools/lib/python2.7/site-packages/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
Traceback (most recent call last):
  File "/users/ole/ExTASY-tools/lib/python2.7/site-packages/radical/pilot/controller/output_file_transfer_worker.py", line 171, in run
    output_file.copy(saga.Url(abs_target), flags=copy_flags)
  File "/users/ole/ExTASY-tools/lib/python2.7/site-packages/saga/namespace/entry.py", line 276, in copy
    ret = self._adaptor.copy_self (tgt_url, flags, ttype=ttype)
  File "/users/ole/ExTASY-tools/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 51, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/users/ole/ExTASY-tools/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 1146, in copy_self
    files_copied = self.shell.obj.stage_from_remote (src.path, tgt.path, rec_flag)
  File "/users/ole/ExTASY-tools/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 929, in stage_from_remote
    raise ptye.translate_exception (e)
NoSuccess: read from process failed '[Errno 5] Input/output error' : (s   --:-- ETA//users/ole/ExTASY-tools/lib/python2.7/site-p 100%  521     0.5KB/s   00:00    
sftp>  ls /work/e290/e290/oweidner/radical.pilot.sandbox/pilot-54983f33f8cdba56ea998d67/unit-54984098f8cdba56ea998d8b/coco.log
Couldn't send packet: Broken pipe
) (/users/ole/ExTASY-tools/lib/python2.7/site-packages/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))

2014:12:22 16:06:36 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '54984098f8cdba56ea998d8b' state changed from 'StagingOutput' to 'Failed'.
[Callback]: ComputeUnit '54984098f8cdba56ea998d8b' state changed to Failed.
#######################
##       ERROR       ##
#######################
ComputeUnit 54984098f8cdba56ea998d8b has FAILED. Can't recover.
```

This is from A Nottingham lab machine to Archer using the latest RP release 0.23.

**Comment by andre-merzky** [comment]
Vivek, is this problem still popping up?

**Comment by vivek-bala** [comment]
It did come up a couple of times in the ExTASY jenkins tests. But no definite script to reproduce this.

**Comment by vivek-bala** [comment]
Actually it has come up in one of the last tests, http://ci.radical-project.org/job/ExTASY/EXTASY_HOST=archer,EXTASY_RADICAL_BRANCH=RADICAL_release,EXTASY_WORKFLOW=cocoamber,PYTHON=System-CPython-2.7/lastBuild/console

**Comment by andre-merzky** [comment]
The 'last' build has a different error (hard link failed), the build 2 hours ago which you might refer to does not have anything about a broken pip, AFAICS.  Which build number are you referring to?

Also, do you have the pty option in place as advised above?  If not, could you please give it a try, to see if that helps stabilizing things?

Thanks! :)

**Comment by vivek-bala** [comment]
Not sure if we are seeing the jenkins report. I believe the link points to ExTASY, it's been about a week since the last test.

```
2015:01:07 12:04:03 radical.pilot.MainProcess: [ERROR   ] Output transfer failed: read from process failed '[Errno 5] Input/output error' : (KB/s   --:-- ETA//var/lib/jenkins/shiningpanda/jobs/0226bc4a/ 100%  521     0.5KB/s   00:00    
sftp>  ls /work/e290/e290/vb224/radical.pilot.sandbox/pilot-54ad1fb9cec86a5a4267 52d5/unit-54ad209fcec86a5a426752e0/md0.ncdf
Couldn't send packet: Broken pipe
```

The test via Jenkins didn't have the pty option. Sorry about that ! I have added it now. Will reopen if the error pops up again.

**Comment by andre-merzky** [comment]
Thanks!
