### ISSUE TITLE
shared data staging example failure

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#485]
```
$ python io_staging_shared.py 
##########################
~/staging_area/shared_input_file.txt
##########################
Traceback (most recent call last):
  File "io_staging_shared.py", line 60, in <module>
    pilot.stage_in(sd_pilot)
  File "/home/vivek/Research/rp-test/local/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 483, in stage_in
    flags=saga.filesystem.CREATE_PARENTS)
  File "/home/vivek/Research/rp-test/local/lib/python2.7/site-packages/saga/filesystem/directory.py", line 95, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/home/vivek/Research/rp-test/local/lib/python2.7/site-packages/saga/namespace/directory.py", line 95, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/home/vivek/Research/rp-test/local/lib/python2.7/site-packages/saga/namespace/entry.py", line 89, in __init__
    url, flags, session, ttype=_ttype)
  File "/home/vivek/Research/rp-test/local/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/home/vivek/Research/rp-test/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 51, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/vivek/Research/rp-test/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 278, in init_instance
    self.initialize ()
  File "/home/vivek/Research/rp-test/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 337, in initialize
    raise saga.BadParameter ("invalid dir '%s': %s" % (self.url.path, out))
saga.exceptions.BadParameter: invalid dir '/~/staging_area': mkdir: cannot create directory ‘/~’: Permission denied
/bin/sh: 3: cd: can't cd to /~/staging_area
 (/home/vivek/Research/rp-test/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +337 (initialize)  :  raise saga.BadParameter ("invalid dir '%s': %s" % (self.url.path, out)))
^C^C^Z
```

**Comment by andre-merzky** [comment]
Apologies, seems I have broken this a while ago - will fix.

**Comment by marksantcroos** [comment]
Hi Vivek,

Fix has been pushed to the readthedocs branch.

Gr,

Mark
