### ISSUE TITLE
ru.get_version broken

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.pilot#502]
With RP installed from the devel branch, I don't get past the `import radical.pilot`:

```
python -c "import radical.pilot"
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/rp/lib/python2.7/site-packages/radical/pilot/__init__.py", line 26, in <module>
    from session import Session 
  File "/tmp/rp/lib/python2.7/site-packages/radical/pilot/session.py", line 22, in <module>
    from radical.pilot.unit_manager    import UnitManager
  File "/tmp/rp/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 21, in <module>
    from radical.pilot.controller   import UnitManagerController
  File "/tmp/rp/lib/python2.7/site-packages/radical/pilot/controller/__init__.py", line 10, in <module>
    from pilot_manager_controller import PilotManagerController
  File "/tmp/rp/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 26, in <module>
    from radical.pilot.controller.pilot_launcher_worker import PilotLauncherWorker
  File "/tmp/rp/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 27, in <module>
    version, version_detail, version_branch, sdist_name, sdist_path = ru.get_version ([root, pwd])
ValueError: need more than 3 values to unpack
``

**Comment by marksantcroos** [comment]
You have RU from devel too?

**Comment by oleweidner** [comment]
Nope. Judging from your question, I assume I need to install radical.utils from devel too in order to make it work? ;-)

**Comment by andre-merzky** [comment]
Yes.  It's the same error you saw when trying synapse.  The RP agent deployment changes required some changes in the version spec and version detection...

**Comment by oleweidner** [comment]
Hm. I'm sure I'm missing something, but I don't have a clue what. Please see below. Both packages are installed from 'devel' branch:

```
virtualenv /tmp/rpdevel
. /tmp/rpdevel/bin/activate

pip install --upgrade git+https://github.com/radical-cybertools/radical.utils.git@devel#egg=radical.utils
python -c 'import radical.utils; print radical.utils.version'
v0.8

pip install --upgrade git+https://github.com/radical-cybertools/radical.pilot.git@devel#egg=radical.pilot
python -c 'import radical.pilot; print radical.pilot.version'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/rpdevel/lib/python2.7/site-packages/radical/pilot/__init__.py", line 24, in <module>
    from url import Url
  File "/tmp/rpdevel/lib/python2.7/site-packages/radical/pilot/url.py", line 14, in <module>
    from saga import Url as sagaURL
  File "/tmp/rpdevel/lib/python2.7/site-packages/saga/__init__.py", line 46, in <module>
    version, version_detail, version_branch = ru.get_version ([root, pwd])
ValueError: too many values to unpack
```

**Comment by andre-merzky** [comment]
If you compare to the  first stack you posted, you'll see that it changed -- now its   not rp which calls the incompatible ru method, but it is saga....  It's turtles (aehm, devel branches) all the way down...
