### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#505]
This was reported by Taisung:

```
Traceback (most recent call last):

  File "launch_simulation_pattern_b_amber_2d.py", line 13, in <module>

    import radical.pilot

  File "/usr/people/taisung/myenv/lib/python2.7/site-packages/radical.pilot-0.23-py2.7.egg/radical/pilot/__init__.py", line 25, in <module>

    from url import Url

  File "/usr/people/taisung/myenv/lib/python2.7/site-packages/radical.pilot-0.23-py2.7.egg/radical/pilot/url.py", line 14, in <module>

    from saga import Url as sagaURL

  File "/usr/people/taisung/myenv/lib/python2.7/site-packages/saga_python-0.26-py2.7.egg/saga/__init__.py", line 46, in <module>

    version, version_detail, version_branch = ru.get_version ([root, pwd])

ValueError: too many values to unpack
```

Any ideas?

**Comment by andre-merzky** [comment]
Looks like a version inconsistency.  I assume, RPilot and RUtils are installed from devel branches, and SAGA from pypi or master?

**Comment by AntonsT** [comment]
That is what I thought. Just wanted to double check. Thanks!

**Comment by andre-merzky** [comment]
cheers!
