### ISSUE TITLE
Ctrl+c fails upon failure

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#506]
Test script fails. I try to get out of it with Ctrl+c but it does not return within 10 minutes:
```
2015:03:18 18:18:45 37709  MainThread   radical.pilot         : [INFO    ] got password prompt
Traceback (most recent call last):
  File "mpi_trestles_test.py", line 59, in <module>
    pilot = pmgr.submit_pilots(pdesc)
  File "/Users/mturilli/Virtualenvs/RP_TEST/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 371, in submit_pilots
    resource_config=resource_cfg)
  File "/Users/mturilli/Virtualenvs/RP_TEST/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 414, in register_start_pilot_request
    shell = sup.PTYShell(url, self._session, logger)
  File "/Users/mturilli/Virtualenvs/RP_TEST/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 242, in __init__
    posix=self.posix)
  File "/Users/mturilli/Virtualenvs/RP_TEST/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 195, in initialize
    self._initialize_pty (info['pty'], info)
  File "/Users/mturilli/Virtualenvs/RP_TEST/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 403, in _initialize_pty
    raise ptye.translate_exception (e)
saga.exceptions.AuthenticationFailed: prompted for unknown password (Password: ) (/Users/mturilli/Virtualenvs/RP_TEST/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +306 (_initialize_pty)  :  % match))
^C
```

**Comment by andre-merzky** [comment]
Would you happen to have the debug log available?  Client side should suffice, don't need the agent log.
Thanks!

**Comment by mturilli** [comment]
```
$ python mpi_trestles_test.py 
2015:03:18 18:18:43 37709  MainThread   radical               : [INFO    ] python.interpreter   version: 2.7.6 (default, Sep 9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
2015:03:18 18:18:43 37709  MainThread   radical               : [INFO    ] radical.utils        version: v0.8 (v0.8-10-gac54492@devel)
2015:03:18 18:18:43 37709  MainThread   saga                  : [INFO    ] saga-python          version: v0.26-3-g6322b9f@devel
2015:03:18 18:18:43 37709  MainThread   radical.pilot         : [INFO    ] radical.pilot        version: v0.23-390-gd21df38@devel
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.context.myproxy
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.context.myproxy for saga.Context API with URL scheme(s) ['myproxy://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.context.x509
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.context.x509 for saga.Context API with URL scheme(s) ['x509://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.context.ssh
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.context.ssh for saga.Context API with URL scheme(s) ['ssh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.context.userpass
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.context.userpass for saga.Context API with URL scheme(s) ['userpass://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.shell.shell_job
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.shell.shell_job for saga.job.Service API with URL scheme(s) ['fork://', 'local://', 'ssh://', 'gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.shell.shell_job for saga.job.Job API with URL scheme(s) ['fork://', 'local://', 'ssh://', 'gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.shell.shell_file
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.shell.shell_file for saga.namespace.Directory API with URL scheme(s) ['file://', 'local://', 'sftp://', 'gsisftp://', 'ssh://', 'gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.shell.shell_file for saga.namespace.Entry API with URL scheme(s) ['file://', 'local://', 'sftp://', 'gsisftp://', 'ssh://', 'gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.shell.shell_file for saga.filesystem.Directory API with URL scheme(s) ['file://', 'local://', 'sftp://', 'gsisftp://', 'ssh://', 'gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.shell.shell_file for saga.filesystem.File API with URL scheme(s) ['file://', 'local://', 'sftp://', 'gsisftp://', 'ssh://', 'gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.shell.shell_resource
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [WARNING ] Skipping adaptor saga.adaptors.shell.shell_resource: beta versions are disabled (v0.1.beta)
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.redis.redis_advert
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [WARNING ] Skipping adaptor saga.adaptors.redis.redis_advert 1: module loading failed: No module named redis
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.sge.sgejob
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.sge.sgejob for saga.job.Service API with URL scheme(s) ['sge://', 'sge+ssh://', 'sge+gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.sge.sgejob for saga.job.Job API with URL scheme(s) ['sge://', 'sge+ssh://', 'sge+gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.pbs.pbsjob
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.pbs.pbsjob for saga.job.Service API with URL scheme(s) ['pbs://', 'pbs+ssh://', 'pbs+gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.pbs.pbsjob for saga.job.Job API with URL scheme(s) ['pbs://', 'pbs+ssh://', 'pbs+gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.lsf.lsfjob
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.lsf.lsfjob for saga.job.Service API with URL scheme(s) ['lsf://', 'lsf+ssh://', 'lsf+gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.lsf.lsfjob for saga.job.Job API with URL scheme(s) ['lsf://', 'lsf+ssh://', 'lsf+gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.condor.condorjob
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.condor.condorjob for saga.job.Service API with URL scheme(s) ['condor://', 'condor+ssh://', 'condor+gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.condor.condorjob for saga.job.Job API with URL scheme(s) ['condor://', 'condor+ssh://', 'condor+gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.slurm.slurm_job
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.slurm.slurm_job for saga.job.Service API with URL scheme(s) ['slurm://', 'slurm+ssh://', 'slurm+gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.slurm.slurm_job for saga.job.Job API with URL scheme(s) ['slurm://', 'slurm+ssh://', 'slurm+gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.http.http_file
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.http.http_file for saga.namespace.Entry API with URL scheme(s) ['http://', 'https://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.http.http_file for saga.filesystem.File API with URL scheme(s) ['http://', 'https://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.aws.ec2_resource
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.aws.ec2_resource for saga.Context API with URL scheme(s) ['ec2://', 'ec2_keypair://', 'openstack://', 'eucalyptus://', 'euca://', 'aws://', 'amazon://', 'http://', 'https://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.aws.ec2_resource for saga.resource.Manager API with URL scheme(s) ['ec2://', 'ec2_keypair://', 'openstack://', 'eucalyptus://', 'euca://', 'aws://', 'amazon://', 'http://', 'https://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.aws.ec2_resource for saga.resource.Compute API with URL scheme(s) ['ec2://', 'ec2_keypair://', 'openstack://', 'eucalyptus://', 'euca://', 'aws://', 'amazon://', 'http://', 'https://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.loadl.loadljob
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.loadl.loadljob for saga.job.Service API with URL scheme(s) ['loadl://', 'loadl+ssh://', 'loadl+gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.loadl.loadljob for saga.job.Job API with URL scheme(s) ['loadl://', 'loadl+ssh://', 'loadl+gsissh://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Loading  adaptor saga.adaptors.globus_online.go_file
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.globus_online.go_file for saga.namespace.Directory API with URL scheme(s) ['go://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.globus_online.go_file for saga.namespace.Entry API with URL scheme(s) ['go://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.globus_online.go_file for saga.filesystem.Directory API with URL scheme(s) ['go://']
2015:03:18 18:18:43 37709  MainThread   saga.Engine           : [INFO    ] Register adaptor saga.adaptors.globus_online.go_file for saga.filesystem.File API with URL scheme(s) ['go://']
2015:03:18 18:18:43 37709  MainThread   saga.saga.adaptor.ssh : [INFO    ] ignore ssh key at /Users/mturilli/.ssh/config (no public key: /Users/mturilli/.ssh/config.pub)
2015:03:18 18:18:43 37709  MainThread   saga.saga.adaptor.ssh : [INFO    ] default ssh key at /Users/mturilli/.ssh/id_coursera
2015:03:18 18:18:43 37709  MainThread   saga.saga.adaptor.ssh : [INFO    ] default ssh key at /Users/mturilli/.ssh/id_rsa
2015:03:18 18:18:43 37709  MainThread   saga.saga.adaptor.ssh : [INFO    ] ignore ssh key at /Users/mturilli/.ssh/known_hosts (no public key: /Users/mturilli/.ssh/known_hosts.pub)
2015:03:18 18:18:43 37709  MainThread   saga.ContextSSH       : [INFO    ] init SSH context for key  at '/Users/mturilli/.ssh/id_coursera' done
2015:03:18 18:18:43 37709  MainThread   saga.DefaultSession   : [DEBUG   ] default context [saga.adaptor.ssh    ] : {'LifeTime' : '-1', 'Type' : 'ssh', 'UserCert' : '/Users/mturilli/.ssh/id_coursera.pub', 'UserKey' : '/Users/mturilli/.ssh/id_coursera'}
2015:03:18 18:18:43 37709  MainThread   saga.ContextSSH       : [INFO    ] init SSH context for key  at '/Users/mturilli/.ssh/id_rsa' done
2015:03:18 18:18:43 37709  MainThread   saga.DefaultSession   : [DEBUG   ] default context [saga.adaptor.ssh    ] : {'LifeTime' : '-1', 'Type' : 'ssh', 'UserCert' : '/Users/mturilli/.ssh/id_rsa.pub', 'UserKey' : '/Users/mturilli/.ssh/id_rsa'}
2015:03:18 18:18:43 37709  MainThread   radical.pilot         : [INFO    ] using database url  mongodb://54.221.194.147:24242/RP_testing_mturilli/
2015:03:18 18:18:43 37709  MainThread   radical.pilot         : [INFO    ] using database path RP_testing_mturilli/
2015:03:18 18:18:43 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for das4.fs2
2015:03:18 18:18:43 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for epsrc.archer
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for futuregrid.xray
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for futuregrid.echo
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for futuregrid.india
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for futuregrid.bravo
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for futuregrid.xray_ccm
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for futuregrid.delta
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for iu.bigred2
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for iu.bigred2_ccm
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for local.localhost
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for lrz.supermuc
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for ncar.yellowstone
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for ncsa.bw_ccm
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for ncsa.bw
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for nersc.hopper_ccm
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for nersc.hopper
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for nersc.edison
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for nersc.edison_ccm
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for radical.tutorial
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for rice.biou
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for rice.davinci
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for stfc.joule
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for xsede.stampede
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for xsede.trestles
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for xsede.gordon
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for xsede.blacklight
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] Loaded resource configurations for xsede.lonestar
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] New Session created{'uid': 'rp.session.Matteos-MacBook-Pro.local.mturilli.016512.0001', 'created': datetime.datetime(2015, 3, 18, 22, 18, 44, 85728), 'database_auth': None, 'database_name': 'radicalpilot', 'database_url': 'mongodb://54.221.194.147:24242/radicalpilot', 'connected': None}.
2015:03:18 18:18:44 37709  Thread-1     radical.pilot         : [DEBUG   ] Worker thread (ID: Thread-1[4522950656]) for PilotManager 5509f9c4dbbb46934dbe9a11 started.
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [DEBUG   ] saga.utils.PTYShell ('sftp://trestles.sdsc.xsede.org/')
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [DEBUG   ] PTYShell init <saga.utils.pty_shell.PTYShell object at 0x10d1662d0>
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] PTY prompt pattern: [\$#%>\]]\s*$
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [DEBUG   ] open master pty for [ssh] [amerzky@trestles.sdsc.xsede.org] amerzky: /usr/bin/env TERM=vt100  "/usr/bin/ssh" -t -o IdentityFile=/Users/mturilli/.ssh/id_coursera -o IdentityFile=/Users/mturilli/.ssh/id_rsa  -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_mturilli_%h_%p.amerzky.ctrl -o TCPKeepAlive=no  -o ServerAliveInterval=10 -o ServerAliveCountMax=20 amerzky@trestles.sdsc.xsede.org'
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [DEBUG   ] PTYProcess init <saga.utils.pty_process.PTYProcess object at 0x10ce68350>
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [INFO    ] running: /usr/bin/env TERM=vt100 /usr/bin/ssh -t -o IdentityFile=/Users/mturilli/.ssh/id_coursera -o IdentityFile=/Users/mturilli/.ssh/id_rsa -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_mturilli_%h_%p.amerzky.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 amerzky@trestles.sdsc.xsede.org
2015:03:18 18:18:44 37709  MainThread   radical.pilot         : [DEBUG   ] write: [    5] [   33] ( export PS1='$' ; set prompt='$'\n)
2015:03:18 18:18:44 37709  PilotLauncherWorker-1 radical.pilot         : [DEBUG   ] Connected to MongoDB. Serving requests for PilotManager 5509f9c4dbbb46934dbe9a11.
2015:03:18 18:18:45 37709  MainThread   radical.pilot         : [DEBUG   ] read : [    5] [   10] (Password: )
2015:03:18 18:18:45 37709  MainThread   radical.pilot         : [INFO    ] got password prompt
Traceback (most recent call last):
  File "mpi_trestles_test.py", line 59, in <module>
    pilot = pmgr.submit_pilots(pdesc)
  File "/Users/mturilli/Virtualenvs/RP_TEST/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 371, in submit_pilots
    resource_config=resource_cfg)
  File "/Users/mturilli/Virtualenvs/RP_TEST/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 414, in register_start_pilot_request
    shell = sup.PTYShell(url, self._session, logger)
  File "/Users/mturilli/Virtualenvs/RP_TEST/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 242, in __init__
    posix=self.posix)
  File "/Users/mturilli/Virtualenvs/RP_TEST/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 195, in initialize
    self._initialize_pty (info['pty'], info)
  File "/Users/mturilli/Virtualenvs/RP_TEST/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 403, in _initialize_pty
    raise ptye.translate_exception (e)
saga.exceptions.AuthenticationFailed: prompted for unknown password (Password: ) (/Users/mturilli/Virtualenvs/RP_TEST/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +306 (_initialize_pty)  :  % match))
^CTerminated: 15
```

**Comment by andre-merzky** [comment]
Thanks - its indeed hanging  at a passwd prompt.  I'll  add a timeout on SAGA layer.

**Comment by andre-merzky** [comment]
After closer inspection, the thread in question does  behave as expected -- it is the shutdown which makes trouble again, as the thread which is managing the shutdown is now gone.  I'm afraid that again has to wait until the refactoring -- I don't think I can sanely fix that without changing the API semantics.

At the moment, we should make sure that all example are catching errors, and then close the session orderly.  I'll keep this ticket open for that purpose.

**Comment by andre-merzky** [comment]
This is done now - shutdown errors beyond those changes fall  into the know 'fix later when refactoring the module' category :/
