### ISSUE TITLE
ssh tunnel error on archer

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#545]
```
2015-04-01 14:48:17,436 - radical.pilot.agent - INFO - Launching task 551bf71fbe5d6a3d9d9d8c09 via /fs4/e290/e290/gshannon/radical.pilot.sandbox/pilot-551bf659be5d6a3d9d9d8bf7/unit-551bf71fbe5d6a3d9d9d8c09/radical_pilot_cu_launch_script-jduqx9.sh in /fs4/e290/e290/gshannon/radical.pilot.sandbox/pilot-551bf659be5d6a3d9d9d8bf7/unit-551bf71fbe5d6a3d9d9d8c09
2015-04-01 14:50:11,956 - radical.pilot.agent - ERROR - ERROR in agent main loop: could not connect to 127.0.0.1:23000: [Errno 111] Connection refused. Traceback (most recent call last):
  File "radical-pilot-agent.py", line 2041, in run
    fields=[COMMAND_FIELD, 'state']
  File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 1674, in find_and_modify
    **kwargs)
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 437, in command
    uuid_subtype, compile_re, **kwargs)[0]
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 337, in _command
    for doc in cursor:
  File "build/bdist.linux-x86_64/egg/pymongo/cursor.py", line 1038, in next
    if len(self.__data) or self._refresh():
  File "build/bdist.linux-x86_64/egg/pymongo/cursor.py", line 982, in _refresh
    self.__uuid_subtype))
  File "build/bdist.linux-x86_64/egg/pymongo/cursor.py", line 906, in __send_message
    res = client._send_message_with_response(message, **kwargs)
  File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 1189, in _send_message_with_response
    sock_info = self.__socket(member)
  File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 916, in __socket
    "%s %s" % (host_details, str(why)))
AutoReconnect: could not connect to 127.0.0.1:23000: [Errno 111] Connection refused

```

happened in one of the EnMD runs during the beta testing session.  No other information, really - other concurrently running connections survived, later runs succeeded.

**Comment by marksantcroos** [comment]
Anything in agent.out or agent.err?

**Comment by andre-merzky** [comment]
Nothing beyond the above.  For the next couple of runs, the DB connection did not even get up (connection refused) -- it kind of looks like Gareth's account got locked, or specifically his ssh tunnels barfed up, but I don't think that this is technically possible on the level we are using MongoDB...

**Comment by marksantcroos** [comment]
The port acquisition is far from resilient.

If this was during a period that more people were using RP on Archer, its likely pointing to a problem in determining a free port.

**Comment by andre-merzky** [comment]
I am not sure how to progress on this one.  As far as I know this did not pop up anymore.  I am inclined to give this ticket a mercy-killing...

**Comment by marksantcroos** [comment]
This was not a problem of RP. Gareths account didnt have ssh keys set up.
