### ISSUE TITLE
RP 0.26 fails on stampede

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#562]
I tried the simple_bot example on stampede and it fails with the following error :-

```
2015:04:09 10:13:50 radical.pilot.MainProcess: [ERROR   ] DoesNotExist: file copy failed: mput  "//experiments/vivek
/enmd_new/lib/python2.7/site-packages/radical/pilot/bootstrapper/default_bootstrapper.sh" "/work/02734/vivek91/radi$
al.pilot.sandbox/pilot-552650cf23769c749075e142/default_bootstrapper.sh"
Uploading //experiments/vivek/enmd_new/lib/python2.7/site-packages/radical/pilot/bootstrapper/default_bootstrapper.$
h to /work/02734/vivek91/radical.pilot.sandbox/pilot-552650cf23769c749075e142/default_bootstrapper.sh
remote open("/work/02734/vivek91/radical.pilot.sandbox/pilot-552650cf23769c749075e142/default_bootstrapper.sh"): No 
such file or directory
sftp> 
2015:04:09 10:13:50 radical.pilot.MainProcess: [ERROR   ] [{'timestamp': datetime.datetime(2015, 4, 9, 10, 13, 41, $
60125), 'logentry': 'Using pilot agent /experiments/vivek/enmd_new/lib/python2.7/site-packages/radical/pilot/agent/$
adical-pilot-agent-multicore.py'}, {'timestamp': datetime.datetime(2015, 4, 9, 10, 13, 41, 263236), 'logentry': 'Us$
ng bootstrapper /experiments/vivek/enmd_new/lib/python2.7/site-packages/radical/pilot/bootstrapper/default_bootstra$
per.sh'}, {'timestamp': datetime.datetime(2015, 4, 9, 10, 13, 41, 264019), 'logentry': "Copying bootstrapper 'file:$
/localhost//experiments/vivek/enmd_new/lib/python2.7/site-packages/radical/pilot/bootstrapper/default_bootstrapper.$
h' to agent sandbox (sftp://stampede.tacc.utexas.edu/work/02734/vivek91/radical.pilot.sandbox/pilot-552650cf23769c7$
9075e142//default_bootstrapper.sh)."}, {'timestamp': datetime.datetime(2015, 4, 9, 10, 13, 50, 661320), 'logentry': 
'Pilot launching failed!'}]
Traceback (most recent call last):
  File "/experiments/vivek/enmd_new/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worke$
.py", line 436, in run
    bs_script.copy(bs_script_tgt, flags=saga.filesystem.CREATE_PARENTS)
  File "/experiments/vivek/enmd_new/local/lib/python2.7/site-packages/saga/namespace/entry.py", line 266, in copy
    return self._adaptor.copy_self (tgt, flags, ttype=ttype)
  File "/experiments/vivek/enmd_new/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in 
wrap_function
    return sync_function (self, *args, **kwargs)
  File "/experiments/vivek/enmd_new/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 1173
```

No pilot folders are created in remote machine either. While the same script works for gordon.

**Comment by andre-merzky** [comment]
Is that problem happening on every run?  Could you please send/upload a full debug log, and possibly some example code?  Thanks!

**Comment by vivek-bala** [comment]
debug log : https://gist.github.com/vivek-bala/a4e006e4df07f37db1cb
code : https://gist.github.com/vivek-bala/98783f57fbc8897b6c43

Yes, its been happening on every run.

**Comment by andre-merzky** [comment]
ah:

```
2015:04:09 10:37:41 radical.pilot.MainProcess: [DEBUG   ] read : [   15] [  139] (mkdir: cannot create directory `/work/02734/vivek91/radical.pilot.sandbox/pilot-5526566b23769c79114cc668/': Disk quota exceeded\nPROMPT-1->)
```

Disk quota :(

**Comment by vivek-bala** [comment]
Ah ok. Sry about that. Stampede doubled my file limit to 6M, but I still hit that. There seems to be an error with my account (is what stampede told me.).
