### ISSUE TITLE
Shutdown / teardown issue

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.pilot#568]
radical-pilot 0.28 release
priority - medium.

I see the following issue when running the EnsembleMD unit tests, probably due to an unclean shutdown and uncoordinated thread teardown:

```
----------------------------------------------------------------------
Ran 47 tests in 595.856s

FAILED (failures=3)
Exception in thread Thread-58:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/private/tmp/enmd/lib/python2.7/site-packages/radical.pilot-0.28-py2.7.egg/radical/pilot/controller/pilot_manager_controller.py", line 364, in run
    log="Pilot '%s' has terminated with state '%s'. CU canceled." % (pilot_id, new_state))
  File "/private/tmp/enmd/lib/python2.7/site-packages/radical.pilot-0.28-py2.7.egg/radical/pilot/db/database.py", line 520, in set_compute_unit_state
    ts = datetime.datetime.utcnow()
AttributeError: 'NoneType' object has no attribute 'datetime'
```

**Comment by andre-merzky** [comment]
cancellation should be cleaned up now.
