### ISSUE TITLE
Unknown resource key: exception v.s. state 'failed'

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.pilot#574]
Currently using a non-existing resource key results in an exception:

```
Traceback (most recent call last):
  File "examples/pipeline.py", line 140, in <module>
    cluster.allocate()
  File "/tmp/test/lib/python2.7/site-packages/radical.ensemblemd-0.2_101_g450194c-py2.7.egg/radical/ensemblemd/single_cluster_environment.py", line 136, in allocate
    self._pilot = pmgr.submit_pilots(pdesc)
  File "/private/tmp/test/lib/python2.7/site-packages/radical.pilot-0.28-py2.7.egg/radical/pilot/pilot_manager.py", line 316, in submit_pilots
    resource_cfg = self._session.get_resource_config(resource_key)
  File "/private/tmp/test/lib/python2.7/site-packages/radical.pilot-0.28-py2.7.egg/radical/pilot/session.py", line 575, in get_resource_config
    raise PilotException(error_msg)
radical.pilot.exceptions.PilotException: Resource key 'localhosts' is not known.
```

I think this should rather result into the pilot switching to state `failed` and an entry in the pilot log. Otherwise, one needs to have two code paths for radical-pilot error handling, one exception based and the other callback / state-based. AFAIK, exceptions are not really used anywhere else on API level?

**Comment by andre-merzky** [comment]
There is a mixture of state changes and raises in general, so changing that specific point would not alter much:

```
.../src/radical/pilot $ grep raise pilot_manager.py  | wc -l
6
.../src/radical/pilot $ grep raise *.py  | wc -l
60
```

Specifically, I find it useful to raise bad parameter exceptions as early as possible, and in general to raise exceptions as long as an API request is being validated.  Once it is accepted for execution / enactment / ..., (ie. once the call returns), then changing state is certainly the right thing to do.
