### ISSUE TITLE
CCM scheduler fails on hopper

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#577]
RP 0.28-devel
RU 0.28-devel
SP 0.28-devel

Description: I am submitting 3 pilots, ~320 cores each, one of these on hopper. I specified the tag 'nersc.hopper_ccm'. I get the following error from hopper.

From the DEBUG logs:
```
#!/bin/bash 
#PBS -V 
#PBS -o /scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016549.0000-pilot.0002/agent.out 
#PBS -e /scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016549.0000-pilot.0002/agent.err 
#PBS -l walltime=1:14:00 
#PBS -q regular 
#PBS -l nodes=14:ppn=24
export    PBS_O_WORKDIR=/scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016549.0000-pilot.0002 
mkdir -p  /scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016549.0000-pilot.0002
cd        /scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016549.0000-pilot.0002
export SAGA_PPN=24
```
```
/bin/bash -l pilot_bootstrapper.sh  -b 'radical.utils-0.28.tar.gz:saga-python-v0.28-3-gd01f143-devel.tar.gz:radical.pilot-v0.28-47-gd3bd063-devel.tar.gz' -c '320' -d '10' -g '/global/project/projectdirs/m2178/shared_pilot_ve_20141119' -j 'CCMRUN' -k 'MPIRUN_CCMRUN' -l 'TORQUE' -m '54.221.194.147:24242' -n 'mturilli_aimesexperiments' -o 'POPEN' -p 'pilot.0002' -q 'CONTINUOUS' -r '74' -s 'rp.session.ip-10-184-31-85.mturilli.016549.0000' -t 'multicore' -u 'use' -v 'installed' -e 'module load ccm' -e 'module load openmpi-ccm' -e 'module load python' -x 'lue'
```
```
2015:04:24 20:49:03 8865   PilotLauncherWorker-1 radical.pilot         : [DEBUG   ] write: [   30] [ 1450] (SCRIPTFILE=`mktemp -t SAGA-Pyt ... IPTFILE && rm -f $SCRIPTFILE\n)
2015:04:24 20:49:04 8865   PilotLauncherWorker-1 radical.pilot         : [DEBUG   ] read : [   30] [  133] (\n****  The nodes resource ("-l 14") is not supported on this platform.\n****  Job is not submitted. Please contact a consultant.\n\n)
2015:04:24 20:49:04 8865   PilotLauncherWorker-1 radical.pilot         : [DEBUG   ] read : [   30] [   70] (qsub: submit filter returned an error code, aborting job submission.\n)
2015:04:24 20:49:04 8865   PilotLauncherWorker-1 radical.pilot         : [DEBUG   ] read : [   30] [   10] (PROMPT-1->)
2015:04:24 20:49:04 8865   PilotLauncherWorker-1 saga.PBSJobService    : [ERROR   ] Error running job via 'qsub': 
****  The nodes resource ("-l 14") is not supported on this platform.
****  Job is not submitted. Please contact a consultant.
```

**Comment by marksantcroos** [comment]
Thanks for giving it a try.

A couple of issues here:
- Yet another SAGA PBS adapter issue. I've forked the PBS adapter into a TORQUE adapter and made an initial fix. This should have been detected automagically: #579
- You need to leave/set the queue to the default "ccm_queue" to make use of CCM on Hopper and Edison.
- My earlier work had focused on Edison, and the config entry for Hopper was non-optimal, that's now fixed.
- sshd on the MOM node is configured differently on Hopper than Edison, have instrumented the agent for that and changed the resource config for Hopper CCM accordingly.

Status Quo with latest commits to devel on SP and RP:
- APRUN test on Edison runs successfully
- APRUN test on Hopper runs successfully
- CCM test on Edison runs successfully
- CCM test on Hopper fails, but this is due to the MPI payload it seems, and might not be an issue for you. Will look at that later #580.

**Comment by mturilli** [comment]
Thank you Mark! Going to give it a spin and will report back to the ticket.

**Comment by mturilli** [comment]
I get some file copy errors:
```
PBS Job Id: 9105193.hopque01 
Job Name: SAGA-Python-TORQUEJobScript.bzeMRz 
Message: An error has occurred processing your job, see below. Post job file processing error; job 9105193.hopque01 on host 5136

Unable to copy file /global/u1/m/mturilli/9105193.hopque01.OU to /scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016551.0000-pilot.0002/agent.out, error 1
*** error from copy
/bin/cp: cannot create regular file `/scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016551.0000-pilot.0002/agent.out': No such file or directory
*** end error output

Unable to copy file /global/u1/m/mturilli/9105193.hopque01.ER to /scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016551.0000-pilot.0002/agent.err, error 1
*** error from copy
/bin/cp: cannot create regular file `/scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016551.0000-pilot.0002/agent.err': No such file or directory
*** end error output 
Exec host: 5136/0-23+5137/0-23+5086/0-23+5087/0-23+4992/0-23+4993/0-23+4319/0-23+4317/0-23+4130/0-23+4138/0-23+3537/0-23+4210/0-23+4211/0-23+4236/0-7
```

**Comment by marksantcroos** [comment]
I think this is #519 and should not effect the pilot run.

**Comment by mturilli** [comment]
The pilot failed. Looking at the logs the failure seems not related to #519. 

Here what I have found:
* Pilot fails after entering the state Running:

  ```
2015:04:26 00:54:55 22998  Thread-9     saga.TORQUEJobService : [INFO    ] Job monitoring thread updating Job [torque+ssh://hopper.nersc.gov/]-[9105193] (state: Running)
2015:04:26 00:55:12 22998  PilotLauncherWorker-1 radical.pilot         : [INFO    ] Performing periodical health check for pilot.0002 (SAGA job id [torque+ssh://hopper.nersc.gov/]-[9105193])
2015:04:26 00:55:12 22998  PilotLauncherWorker-1 radical.pilot         : [INFO    ] pilot pilot.0002 seems alive and well
2015:04:26 00:56:36 22998  Thread-1     radical.pilot         : [INFO    ] ComputePilot 'pilot.0002' state changed from 'PendingActive' to 'Failed'.
2015:04:26 00:56:36 22998  Thread-1     radical.pilot         : [DEBUG   ] [SchedulerCallback]: ComputePilot pilot.0002 changed to Failed
  ```
  Here the last logs of the thread:
  ```
[...]
2015:04:26 00:55:55 22998  Thread-9     saga.TORQUEJobService : [INFO    ] Job monitoring thread updating Job [torque+ssh://hopper.nersc.gov/]-[9105193] (state: Running)
2015:04:26 00:56:55 22998  Thread-9     radical.pilot         : [DEBUG   ] flush: [   30] [     ] (flush pty read cache)
2015:04:26 00:56:56 22998  Thread-9     saga.PTYShell         : [DEBUG   ] run_sync: unset GREP_OPTIONS; /usr/common/usg/bin/qstat -f1 9105193 | grep -E -i '(job_state)|(exec_host)|(exit_status)|(ctime)|(start_time)|(stime)|(mtime)'
2015:04:26 00:56:56 22998  Thread-9     radical.pilot         : [DEBUG   ] write: [   30] [  148] (unset GREP_OPTIONS; /usr/common/usg/bin/qstat -f1 9105193 | grep -E -i '(job_state)|(exec_host)|(exit_status)|(ctime)|(start_time)|(stime)|(mtime)'\n)
2015:04:26 00:56:56 22998  Thread-9     radical.pilot         : [DEBUG   ] read : [   30] [  251] (    job_state = R\n    ctime = Sat Apr 25 17:36:55 2015\n    exec_host = 5136/0-23+5137/0-23+5086/0-23+5087/0-23+4992/0-23+4993/0-23+4319/0-23+4317/0-23+4130/0-23+4138/0-23+3537/0-23+4210/0-23+4211/0-23+4236/0-7\n    mtime = Sat Apr 25 17:50:48 2015\n)
2015:04:26 00:56:56 22998  Thread-9     radical.pilot         : [DEBUG   ] read : [   30] [   43] (    start_time = Sat Apr 25 17:50:48 2015\n)
2015:04:26 00:56:56 22998  Thread-9     radical.pilot         : [DEBUG   ] read : [   30] [   10] (PROMPT-0->)
2015:04:26 00:56:56 22998  Thread-9     saga.TORQUEJobService : [INFO    ] Job monitoring thread updating Job [torque+ssh://hopper.nersc.gov/]-[9105193] (state: Running)
2015:04:26 00:57:56 22998  Thread-9     radical.pilot         : [DEBUG   ] flush: [   30] [     ] (flush pty read cache)
2015:04:26 00:57:56 22998  Thread-9     saga.PTYShell         : [DEBUG   ] run_sync: unset GREP_OPTIONS; /usr/common/usg/bin/qstat -f1 9105193 | grep -E -i '(job_state)|(exec_host)|(exit_status)|(ctime)|(start_time)|(stime)|(mtime)'
2015:04:26 00:57:56 22998  Thread-9     radical.pilot         : [DEBUG   ] write: [   30] [  148] (unset GREP_OPTIONS; /usr/common/usg/bin/qstat -f1 9105193 | grep -E -i '(job_state)|(exec_host)|(exit_status)|(ctime)|(start_time)|(stime)|(mtime)'\n)
2015:04:26 00:57:56 22998  Thread-9     radical.pilot         : [DEBUG   ] read : [   30] [  315] (    job_state = C\n    ctime = Sat Apr 25 17:36:55 2015\n    exec_host = 5136/0-23+5137/0-23+5086/0-23+5087/0-23+4992/0-23+4993/0-23+4319/0-23+4317/0-23+4130/0-23+4138/0-23+3537/0-23+4210/0-23+4211/0-23+4236/0-7\n    mtime = Sat Apr 25 17:57:05 2015\n    exit_status = 8\n    start_time = Sat Apr 25 17:50:48 2015\n)
2015:04:26 00:57:56 22998  Thread-9     radical.pilot         : [DEBUG   ] read : [   30] [   10] (PROMPT-0->)
2015:04:26 00:57:56 22998  Thread-9     saga.TORQUEJobService : [INFO    ] Job monitoring thread updating Job [torque+ssh://hopper.nersc.gov/]-[9105193] (state: Done)
  ```
* On hopper, I see:
  ```
radical.pilot.sandbox> ls -al *
rp.session.ip-10-184-31-85.mturilli.016549.0000-pilot.0002:
total 52
drwxr-x--- 2 mturilli mturilli  4096 Apr 24 13:48 .
drwxr-x--- 4 mturilli mturilli  4096 Apr 25 17:56 ..
-rwxr-x--- 1 mturilli mturilli 42065 Apr 24 13:48 pilot_bootstrapper.sh

ve_hopper:
[...]
  ```
  but in the home directory (?) I see the output and error log files:
  ```
-rw-------   1 mturilli mturilli  106370 Apr 25 17:56 9105193.hopque01.OU
-rw-------   1 mturilli mturilli    5449 Apr 25 17:56 9105193.hopque01.ER
  ```
  in the error log file, I see:
  ```
2015:04:25 17:56:35 31794  MainThread   radical.pilot.agent   : [ERROR   ] Error running agent: Not enough cores available (308) to satisfy allocation request (320).
Traceback (most recent call last):
  File "/scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016551.0000-pilot.0002/rp_install/bin/radical-pilot-agent-multicore.py", line 5564, in main
    session_id         = options.session_id
  File "/scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016551.0000-pilot.0002/rp_install/bin/radical-pilot-agent-multicore.py", line 5029, in __init__
    requested_cores = requested_cores)
  File "/scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016551.0000-pilot.0002/rp_install/bin/radical-pilot-agent-multicore.py", line 2101, in create
    return implementation(name, config, logger, requested_cores)
  File "/scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016551.0000-pilot.0002/rp_install/bin/radical-pilot-agent-multicore.py", line 2120, in __init__
    LRMS.__init__(self, name, config, logger, requested_cores)
  File "/scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016551.0000-pilot.0002/rp_install/bin/radical-pilot-agent-multicore.py", line 2065, in __init__
    % (str(cores_avail), str(requested_cores)))
ValueError: Not enough cores available (308) to satisfy allocation request (320).
2015:04:25 17:56:35 31794  MainThread   radical.pilot.agent   : [ERROR   ] Error running agent: Not enough cores available (308) to satisfy allocation request (320).
rm: cannot remove `/scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016551.0000-pilot.0002/agent.*': No such file or directory
rm: cannot remove `/scratch/scratchdirs/mturilli/radical.pilot.sandbox/rp.session.ip-10-184-31-85.mturilli.016551.0000-pilot.0002/unit.*': No such file or directory
NERSC_HOST: Undefined variable.
   ```

**Comment by marksantcroos** [comment]
> ValueError: Not enough cores available (308) to satisfy allocation request (320).

This is culprit, not sure why, let me look into that.

**Comment by marksantcroos** [comment]
Ok, hopper actually allows partial node allocation.
Quite surprisingly to me, as it doesn't normally allow a user to run more than 1 task per node ...

So this needs fixing in the agent, but that might take a bit.

As a workaround you could allocate multiples of whole nodes only.

**Comment by andre-merzky** [comment]
Hi Matteo - please give it a try with current devel.  Thanks!

**Comment by mturilli** [comment]
It seems to be working nicely. Thank you!
