### ISSUE TITLE
radicalpilot-cleanup

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#582]
When I use:
```
radicalpilot-cleanup -m close -d mongodb://00-000-000-000/dbname  -s my_session_name
```
I get this:

```
modes   : close
db url  : mongodb://00-000-000-000/dbname
session : my_session_name
mode    : close
Exception AttributeError: "'Session' object has no attribute '_uid'" in <bound method Session.__del__ of <radical.pilot.session.Session object at 0x7f1ac6696890>> ignored
Traceback (most recent call last):
  File "/home/treikalis/lol/bin/radicalpilot-cleanup", line 137, in <module>
    elif m == 'close': close_session (url, session) 
  File "/home/treikalis/lol/bin/radicalpilot-cleanup", line 79, in close_session
    rp.Session (database_url=dburl, session_uid=session).close ()
TypeError: __init__() got an unexpected keyword argument 'session_uid'
```

What should I do to close the session?

**Comment by andre-merzky** [comment]
Apologies, it seems we did not change a keyword there -- `session_uid` should be `uid`.  We'll fix that in the next release...

**Comment by andre-merzky** [comment]
fixed.
