### ISSUE TITLE
radical pilot fails on archer

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.pilot#632]
output:

```
python getting_started_remote.py 
timestamp zero: 1433276198.85
session id: rp.session.EugenHruskas-MacBook-Pro.local.eh.016588.0019
[Callback]: ComputePilot 'pilot.0000' state: Launching.
caught Exception: unexpected EOF (e you must disconnect immediately.
--------------------------------------------------------------------------------

ControlSocket /tmp/saga_ssh_eh_login.archer.ac.uk_22.eh22.ctrl already exists, disabling multiplexing
Received message too long 1903391841
) ((mux_client_request_session: session request failed: Session open refused by peer
--------------------------------------------------------------------------------
This is a private computing facility. Access to this system is limited to those
who have been granted access by the operating service provider on behalf of the
issuing authority and use is restricted to the purposes for which access was
granted. All access and usage are governed by the terms and conditions of access
agreed to by all registered users and are thus subject to the provisions of the
Computer Misuse Act, 1990 under which unauthorised use is a criminal offence.

If you are not authorised to use this service you must disconnect immediately.
--------------------------------------------------------------------------------

ControlSocket /tmp/saga_ssh_eh_login.archer.ac.uk_22.eh22.ctrl already exists, disabling multiplexing
Received message too long 1903391841
)) (/Users/eh/extasy/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +49 (translate_exception)  :  e = se.AuthorizationFailed (cmsg))
closing session
[Callback]: ComputePilot 'pilot.0000' state: Failed.
Traceback (most recent call last):
  File "getting_started_remote.py", line 198, in <module>
    session.close ()
  File "/Users/eh/extasy/lib/python2.7/site-packages/radical/pilot/session.py", line 305, in close
    pmgr.close (terminate=terminate)
  File "/Users/eh/extasy/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 199, in close
    time.sleep (1)
KeyboardInterrupt
```

**Comment by andre-merzky** [comment]
"Received message too long 1903391841"  Oops...
Would you mind  running again with setting `SAGA_VERBOSE=DEBUG` in your environment?  The resulting debug output is likely  somewhat large -- please upload it somewhere if it is too large to paste.

Thanks!

**Comment by marksantcroos** [comment]
And just to make sure, you can login with `ssh login.archer.ac.uk`?

**Comment by vivek-bala** [comment]
This error does not come up anymore. There was an older version of the entire stack on the system which might have led to this error. Think this can be closed.

**Comment by andre-merzky** [comment]
Thanks!
