### ISSUE TITLE
mongodb error: too many namespaces/collections (EC2)

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#633]
```
2015:06:03 12:04:46 7706   MainThread   radical.pilot         : [ERROR   ] session create failed
Traceback (most recent call last):
  File "/home/vivek/Research/enmd/local/lib/python2.7/site-packages/radical/pilot/session.py", line 225, in __init__
    db_name = database_name)
  File "/home/vivek/Research/enmd/local/lib/python2.7/site-packages/radical/pilot/db/database.py", line 105, in new
    dbs.create(sid, name, creation_time)
  File "/home/vivek/Research/enmd/local/lib/python2.7/site-packages/radical/pilot/db/database.py", line 147, in create
    "connected" : creation_time})
  File "/home/vivek/Research/enmd/local/lib/python2.7/site-packages/pymongo/collection.py", line 410, in insert
    _check_write_command_response(results)
  File "/home/vivek/Research/enmd/local/lib/python2.7/site-packages/pymongo/helpers.py", line 209, in _check_write_command_response
    raise OperationFailure(error.get("errmsg"), error.get("code"), error)
OperationFailure: too many namespaces/collections
```

**Comment by andre-merzky** [comment]
This should be  solved for now...
