### ISSUE TITLE
RP failes on rice.davinci

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#638]
agent.err reads:

```
which: no pip in (/opt/apps/openmpi/1.6.5-intel/bin:/opt/apps/intel/2013.1.046/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin:/opt/apps/moab/current/bin:/home/vb17/bin:/opt/apps/moab/current/bin:/home/vb17/bin:/opt/apps/moab/current/bin:/home/vb17/bin)
pilot_bootstrapper.sh: line 1230: unalias: pip: not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M 10 1957k   10  207k    0     0   269k      0  0:00:07 --:--:--  0:00:07  448k^M100 1957k  100 1957k    0     0  1475k      0  0:00:01  0:00:01 --:--:-- 1919k
pilot_bootstrapper.sh: line 573: unalias: pip: not found
pilot_bootstrapper.sh: line 734: unalias: pip: not found
Python 2.6.6
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pilot

```

**Comment by vivek-bala** [comment]
```
$ module load pythonlibs/python2.6
[vb17@login1 radical.pilot.sandbox]$ pip
-bash: pip: command not found


$ module load python3/3.2.1
[vb17@login1 radical.pilot.sandbox]$ pip
-bash: pip: command not found
```

Both python libraries on davinci don't seem to recognize the pip command

**Comment by vivek-bala** [comment]
the executable that is to be used with python3/3.2.1 seems to be "python3" and not "python"

**Comment by andre-merzky** [comment]
Alas, RP won't work with python3 :(

**Comment by marksantcroos** [comment]
I have access to this machine now, will look into it.

**Comment by andre-merzky** [comment]
Could you give it a try with the `devel-andre` branch?  I added pip installation to the bootstrapper there...

**Comment by vivek-bala** [comment]
I used devel-andre. I still get the same error:
```
which: no pip in (/opt/apps/openmpi/1.6.5-intel/bin:/opt/apps/intel/2013.1.046/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin:/opt/apps/moab/current/bin:/home/vb17/bin:/opt/apps/moab/current/bin:/home/vb17/bin:/opt/apps/moab/current/bin:/home/vb17/bin)
Python 2.6.6
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pilot
```

**Comment by andre-merzky** [comment]
Hi Vivek, 

I don't see a python 2.7 installed at all, only 2.6 and 3.x.  RP won't work with   either one I'm  afraid.  That pip is not available is not a problem -- the bootstrapper gets past that point and installs pip into the vritualenv...

Not sure what to do about the python version.  In principle we can make RP fit  for python3, but I doubt that this is something  which will stabilize quickly...  I can't remember  why we removed 2.6 support -- IIRC, some dependency hiccuped for us...

Mark, any comment?

**Comment by marksantcroos** [comment]
2.7.0 was released 5 years ago, it seems not too much to ask for.
2.6.X might just work for the agent though ...

I don't remember seeing an actual error for 2.6.X (not that I claim it will work though)

**Comment by andre-merzky** [comment]
2.6 bails out  when installing RP (because setup.py asks for 2.7).  We want to share more  code between agent and module in the future -- so I guess we either make sure it all works  with 2.6, or we ask  for 2.7 to be installed...

**Comment by marksantcroos** [comment]
> On 12 Jun 2015, at 22:19 , Andre Merzky <notifications@github.com> wrote:
> 
> 2.6 bails out when installing RP (because setup.py asks for 2.7). We want to share more code between agent and module in the future -- so I guess we either make sure it all works with 2.6, or we ask for 2.7 to be installed...

Right, I think there is nothing against letting the users ask to install 2.7 there though.

**Comment by TensorDuck** [comment]
I've talked with the RCSG here at Rice:
DaVinCI is currently being updated to SLURM, and it will be completed on July 7th. By then, Python 2.7.9 will be added as a module and set as the default.

Currently, you can access the slurm environment at: davinci-slurm.rcsg.rice.edu
If you have access to davinci, you would also have access to the davinci-slurm test server.

Unfortunately, they haven't made any queues available yet, and not all modules have been migrated over nor added, including Python2.7 and gromacs.

**Comment by andre-merzky** [comment]
What is the  state on this ticket?   Did the update happen, and did it resolve the issue?

**Comment by TensorDuck** [comment]
The update did happen. Not sure if issue has been resolved.

**Comment by andre-merzky** [comment]
Vivek, could you please  give it a try at some point?  Thanks!

**Comment by vivek-bala** [comment]
Python/2.7.9 is available. Can be loaded by first loading GCC/4.4.7 & OpenMPI/1.8.6

```
module load GCC/4.4.7 OpenMPI/1.8.6 Python/2.7.9
```

The scheduler is now SLURM and not PBS, I tried to simply add these to config file and give it a try. 

```
2015:09:17 11:39:54 5429   PilotLauncherWorker-1 radical.pilot         : [ERROR   ] Using bootstrapper /home/vb17/ves/myenv/lib/python2.7/site-packages/radical/pilot/bootstrapper/default_bootstrapper.sh
Copying bootstrapper 'file://localhost/home/vb17/ves/myenv/lib/python2.7/site-packages/radical/pilot/bootstrapper/default_bootstrapper.sh' to agent sandbox (<saga.filesystem.directory.Directory object at 0x7fd2062f7b10>).
Copying sdist 'file://localhost/home/vb17/ves/myenv/lib/python2.7/site-packages/radical/utils/radical.utils-0.35.tar.gz' to sandbox (sftp://davinci.rice.edu/scratch/vb17/radical.pilot.sandbox/rp.session.login2.davinci.rice.edu.vb17.016695.0001-pilot.0000/).
Copying sdist 'file://localhost/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/saga-python-0.35.tar.gz' to sandbox (sftp://davinci.rice.edu/scratch/vb17/radical.pilot.sandbox/rp.session.login2.davinci.rice.edu.vb17.016695.0001-pilot.0000/).
Copying sdist 'file://localhost/home/vb17/ves/myenv/lib/python2.7/site-packages/radical/pilot/controller/..//radical.pilot-0.35.tar.gz' to sandbox (sftp://davinci.rice.edu/scratch/vb17/radical.pilot.sandbox/rp.session.login2.davinci.rice.edu.vb17.016695.0001-pilot.0000/).
Pilot launching failed! (Error finding PBS tools: ERROR: 2015-07-08
ERROR: "pbsnodes" not supported. SLURM has replaced PBS
ERROR: See our documentation http://www.rcsg.rice.edu/
 (/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py +111 (log_error_and_raise)  :  raise exception(message)))
Traceback (most recent call last):
  File "/home/vb17/ves/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 650, in run
    js = saga.job.Service(js_url, session=self._session)
  File "/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py", line 552, in init_instance
    self.initialize()
  File "/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py", line 578, in initialize
    self._logger)
  File "/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py", line 111, in log_error_and_raise
    raise exception(message)
NoSuccess: Error finding PBS tools: ERROR: 2015-07-08
ERROR: "pbsnodes" not supported. SLURM has replaced PBS
ERROR: See our documentation http://www.rcsg.rice.edu/
 (/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/adaptors/torque/torquejob.py +111 (log_error_and_raise)  :  raise exception(message))

```

**Comment by marksantcroos** [comment]
You'll need to change the lrms to SLURM in the config too.

**Comment by vivek-bala** [comment]
Yes, I changed that too. The above error was after changing the lrms as well. Should I delete the existing ve in the sandbox on davinci ?

**Comment by marksantcroos** [comment]
Also the job manager endpoint?

**Comment by vivek-bala** [comment]
ah no, its still torque. Let me try that again.

**Comment by vivek-bala** [comment]
Changed endpoint to slurm+ssh and default queue to serial.

```
Traceback (most recent call last):
  File "getting_started_remote.py", line 143, in <module>
    pilot = pmgr.submit_pilots(pdesc)
  File "/home/vb17/ves/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 373, in submit_pilots
    resource_config=resource_cfg)
  File "/home/vb17/ves/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 430, in register_start_pilot_request
    shell = sup.PTYShell(url, self._session, logger)
  File "/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 243, in __init__
    self.pty_shell  = self.factory.run_shell  (self.pty_info)
  File "/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 444, in run_shell
    self._initialize_pty (sh_slave, info)
  File "/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 407, in _initialize_pty
    raise ptye.translate_exception (e)
saga.exceptions.NoSuccess: Insufficient system resources: Insufficient system resources: read from process failed '[Errno 5] Input/output error' : (Shared connection to davinci.rice.edu closed.
) ((Shared connection to davinci.rice.edu closed.
)) (/home/vb17/ves/myenv/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +64 (translate_exception)  :  e = se.NoSuccess ("Insufficient system resources: %s" % cmsg))
```

Note that I have running from the head node. Not sure if that matters.

**Comment by marksantcroos** [comment]
> Note that I have running from the head node. Not sure if that matters.

It might. Can you ssh to davinci.rice.edu from the headnode?

**Comment by vivek-bala** [comment]
```
(myenv)[vb17@login2 ~]$ ssh vb17@davinci.rice.edu
Last login: Thu Sep 17 13:43:51 2015 from davinci.rcsg.rice.edu
-----------------------------------------------------------------------
   Ken Kennedy Institute for Information Technology, Rice University
  ===================================================================
                 Unauthorized access is prohibited.

                              DAVINCI.RICE.EDU

       Questions and Problem Reports -> http://helpdesk.rice.edu
       Documentation and User News -> http://rcsg.rice.edu/davinci
-----------------------------------------------------------------------
[vb17@login2 ~]$
```

So I am trying to run the script from davinci to davinci.

**Comment by marksantcroos** [comment]
Yeah, but that should be no issue then.

Not sure what that error is about, I'll refer to Andre for that.

**Comment by vivek-bala** [comment]
Ok, this seems to have occurred previously with other resources as well #431 #181 . Incase that helps.

**Comment by TensorDuck** [comment]
Could it be that the default queue should be commons? Serial only allows 1-core jobs on davinci.

**Comment by marksantcroos** [comment]
> Could it be that the default queue should be commons? Serial only allows 1-core jobs on davinci.

I dont think it reaches the stage where that matters. But its a good point in general.

**Comment by vivek-bala** [comment]
Running from davinci to davinci failed. I then ran from biou to davinci, which launches the pilot and execution is successful. Also had to use commons queue. Testing with ```getting_started_remote.py```

Configuration used:

```
"davinci": {
        "description"                 : "The DAVinCI Linux cluster at Rice University (https://docs.rice.edu/confluence/display/ITDIY/Getting+Started+on+DAVinCI).",
        "notes"                       : "DAVinCI compute nodes have 12 or 16 processor cores per node.",
        "schemas"                     : ["ssh"],
        "ssh"                         :
        {
            "job_manager_endpoint"    : "slurm+ssh://davinci.rice.edu/",
            "filesystem_endpoint"     : "sftp://davinci.rice.edu/"
        },
        "lrms"                        : "SLURM",
        "default_queue"               : "commons",
        "agent_type"                  : "multicore",
        "agent_scheduler"             : "CONTINUOUS",
        "agent_spawner"               : "POPEN",
        "task_launch_method"          : "SSH",
        "mpi_launch_method"           : "MPIEXEC",
        "pre_bootstrap"               : ["module load GCC/4.4.7","module load OpenMPI/1.8.6","module load Python/2.7.9"],
        "valid_roots"                 : ["/dascratch"],
        "default_remote_workdir"      : "$SHARED_SCRATCH/$USER",
        "rp_version"                  : "local",
        "virtenv"                     : "%(global_sandbox)s/ve_davinci",
        "virtenv_mode"                : "create"
    }
```

**Comment by andre-merzky** [comment]
Hi guys, 

hard to say what causes the ssh error - the channel seems to get closed  very quickly.  Vivek, which branch  do you use?  Could you please try with devel, set `RADICAL_SAGA_VERBOSE=DEBUG` and `RADICAL_SAGA_PTY_VERBOSE=DEBUG`, and send the complete log file, and specifically what the PTY layer report on read/write.

**Comment by vivek-bala** [comment]
I think I might have missed something while reattempting. Works from davinci as well.

**Comment by andre-merzky** [comment]
Pfew! :)
