### ISSUE TITLE
mongodb AutoReconnect: [Errno 60] Operation timed out

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#662]
I think I might have had a bad network when this happened.
```
Exception in thread OutputFileTransferWorker-2:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/radical/pilot/controller/output_file_transfer_worker.py", line 83, in run
    "$push": {"statehistory": {"state": STAGING_OUTPUT, "timestamp": ts}}}
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/pymongo/collection.py", line 1738, in find_and_modify
    **kwargs)
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/pymongo/database.py", line 439, in command
    uuid_subtype, compile_re, **kwargs)[0]
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/pymongo/database.py", line 338, in _command
    for doc in cursor:
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/pymongo/cursor.py", line 1076, in next
    if len(self.__data) or self._refresh():
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/pymongo/cursor.py", line 1020, in _refresh
    self.__uuid_subtype))
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/pymongo/cursor.py", line 933, in __send_message
    res = client._send_message_with_response(message, **kwargs)
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1217, in _send_message_with_response
    raise AutoReconnect(str(e))
AutoReconnect: [Errno 60] Operation timed out
```

**Comment by andre-merzky** [comment]
see also #442

**Comment by andre-merzky** [comment]
I close this in favor of #442 -- we need proper reconnect.
