### ISSUE TITLE
dist files missing while combining extasy with saga and rp devel

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#663]
```
2015:07:22 12:22:05 87846  PilotLauncherWorker-1 radical.pilot         : [ERROR   ] Using bootstrapper /Users/mark/ExTASY-tools/lib/python2.7/site-packages/radical/pilot/bootstrapper/default_bootstrapper.sh
Copying bootstrapper 'file://localhost/Users/mark/ExTASY-tools/lib/python2.7/site-packages/radical/pilot/bootstrapper/default_bootstrapper.sh' to agent sandbox (<saga.filesystem.directory.Directory object at 0x106721990>).
Copying sdist 'file://localhost/Users/mark/ExTASY-tools/lib/python2.7/site-packages/radical/utils/radical.utils-v0.29-9-g3387b95-devel.tar.gz' to sandbox (sftp://stampede.tacc.utexas.edu/work/01740/marksant/radical.pilot.sandbox/rp.session.netbook.mark.016638.0059-pilot.0000/).
Copying sdist 'file://localhost/Users/mark/ExTASY-tools/lib/python2.7/site-packages/saga/saga-python-v0.29-12-g080fc98-devel.tar.gz' to sandbox (sftp://stampede.tacc.utexas.edu/work/01740/marksant/radical.pilot.sandbox/rp.session.netbook.mark.016638.0059-pilot.0000/).
Pilot launching failed! (file copy failed: stat /Users/mark/ExTASY-tools/lib/python2.7/site-packages/saga/saga-python-v0.29-12-g080fc98-devel.tar.gz: No such file or directory
sftp>  (/Users/mark/ExTASY-tools/lib/python2.7/site-packages/saga/utils/pty_shell.py +1010 (run_copy_to)  :  raise se.DoesNotExist._log (info['logger'], "file copy failed: %s" % str(out))))
Traceback (most recent call last):
  File "/Users/mark/ExTASY-tools/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 519, in run
    sandbox_tgt.copy(sdist_url, os.path.basename(str(sdist_url)))
  File "/Users/mark/ExTASY-tools/lib/python2.7/site-packages/saga/namespace/directory.py", line 353, in copy
    if url_2  :  return self._adaptor.copy (url_1, url_2, flags, ttype=ttype)
  File "/Users/mark/ExTASY-tools/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/Users/mark/ExTASY-tools/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 546, in copy
    files_copied = copy_shell.stage_to_remote (src.path, tgt.path, rec_flag)
  File "/Users/mark/ExTASY-tools/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 906, in stage_to_remote
    raise ptye.translate_exception (e)
DoesNotExist: file copy failed: stat /Users/mark/ExTASY-tools/lib/python2.7/site-packages/saga/saga-python-v0.29-12-g080fc98-devel.tar.gz: No such file or directory
sftp>  (/Users/mark/ExTASY-tools/lib/python2.7/site-packages/saga/utils/pty_shell.py +1010 (run_copy_to)  :  raise se.DoesNotExist._log (info['logger'], "file copy failed: %s" % str(out)))
```

**Comment by andre-merzky** [comment]
The dist files are created and placed during install.  How were extasy and dependencies installed -- can you provide some hints to reproduce it?  Thanks!

**Comment by marksantcroos** [comment]
Actually I can recreate it outside of extasy too.
```
VE=/tmp/freshve
virtualenv $VE
source $VE/bin/activate
cd $RP_SOURCE
pip install --upgrade .
```
Gives:
```
netbook:site-packages mark$ pwd
/Users/mark/Desktop/tmpve/lib/python2.7/site-packages
netbook:site-packages mark$ find . -name \*.tar.gz
./radical/pilot/radical.pilot-v0.34-265-gcd99d10-devel.tar.gz
netbook:site-packages mark$ 
```

I can add the saga-utils dist by going to local source of RU and installing from there.
```
./radical/utils/radical.utils-v0.29-9-g3387b95-devel.tar.gz
```

Same trick doesn't work for saga-python.

**Comment by marksantcroos** [comment]
Pfffff ... pip version problems it seems.

Using the same version as we fixed in the bootstrapper works ...  :(

**Comment by marksantcroos** [comment]
Note that this only fixes the manual install fix. It still doesnt install the saga-python dist directly.

**Comment by andre-merzky** [comment]
This means that the dist files are missing when SAGA is installed from pypi as a dependency?  Am I interpreting this correctly?

**Comment by marksantcroos** [comment]
Hmmm, now I'm lost. Can't reproduce the problem anymore with a downgraded pip. Maybe something was still lingering. I'll close for now.

**Comment by marksantcroos** [comment]
Hello post-now

**Comment by andre-merzky** [comment]
Closing for lack of activity - assumed obsolete.
