### ISSUE TITLE
false positive on failed transfer (and possibly more)

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#665]
(reported by Vivek)

Following the documentation that I shared you with this morning (http://extasy.readthedocs.org/en/extasy_0.2/). I noticed two issues. I have made the sandbox and the rp directory public in case you wanted to investigate directly. 

PWD: /work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016638.0008-pilot.0000

2 issues:

(1) During the simulation stage (unit.000001-unit.000016), the execution seems to exit prematurely. The log file suggests that it was returned code 0. The input file to this unit is "start.gro" (which you would find in the folder). The output file generated is "out.gro". The length of both the files is supposed to be same, but you would find that they are different in this case.

Not sure why this would happen, could this be the filesystem ? The unit doesn't see the entire "start.gro" file during execution and thus simulates some only part of the workload. 

(2) "unit.000017" is the pre-analysis step which basically converges the output of all the simulation instances into one file and then does a gromacs operation on them. This creates "tmpha.gro" (the file is created although the size of the file is incorrect due to (1)). This is(/has) copied to "unit.000000".

Looking at the agent.log:
2015-07-22 12:27:04,190 - radical.pilot.agent - ERROR - Copy'ed /work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016638.0008-pilot.0000/unit.000017/tmpha.gro to /work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016638.0008-pilot.0000/unit.000000/tmpha.gro - failure ([Errno 2] No such file or directory: u'/work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016638.0008-pilot.0000/unit.000017/tmpha.gro')

(i) the file "tmpha.gro" is actually there in unit.000017.
(ii) this doesn't cause a failure of the compute unit.

**Comment by marksantcroos** [comment]
Hi Vivek, here is an update.

I've been sucked deeper and deeper in a maze of problems with Stampede and RP and the combination of the two.

Although I'm still working on this, I will ask you to start converting the software to intel/15 if you haven't done/started that already.
There are serious issues with the default mvapich2 that you get with intel13.
Given that intel/15 will soon be the default I think its good to start migrating sooner than later.
(For details see https://portal.tacc.utexas.edu/user-guides/stampede/intel15)

I think by now I've had a successful run of the extasy tutorial with intel/15, although I'm not 100% sure as I dont know what the metrics for success are.

To be continued.

**Comment by vivek-bala** [comment]
Hey Mark,
I also got a successful run by simply moving to the intel/15 compiler for the gromacs stage (rp: 0.34v). I still use the intel/14 compiler for the lsdmap stage. I guess the issue might be with the intel/13* modules(?). I will test other kernels as well.

**Comment by marksantcroos** [comment]
Im very glad to hear that Vivek. I believe this will make it easier to work on the remaining issues (if any).

**Comment by vivek-bala** [comment]
So I tried to use the Amber-CoCo kernels and I run into the same error.
```
2015-07-30 12:34:39,782 - radical.pilot.agent - ERROR - Copy'ed /work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016646.0004-pilot.0000/unit.000001/md1.crd to /work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016646.0004-pilot.0000/unit.000000/md_1_1.crd - failure ([Errno 2] No such file or directory: u'/work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016646.0004-pilot.0000/unit.000001/md1.crd')
Traceback (most recent call last):
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/bin/radical-pilot-agent-multicore.py", line 4776, in run
    shutil.copyfile(abs_source, target)
  File "/opt/apps/intel13/python/2.7.9/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016646.0004-pilot.0000/unit.000001/md1.crd'
```
The 'md1.crd' file exists in the folder, but the file is not copied to the destination and execution is not halted. Similar situation as reported before.

Amber currently is only available with the intel/13* compiler on Stampede.

**Comment by marksantcroos** [comment]
> Amber currently is only available with the intel/13* compiler on Stampede.

Do you use a system provided Amber or a self-compiled? I believe @AntonsT has experience with building Amber?

**Comment by vivek-bala** [comment]
I am using the stampede provided amber/12 module. I think Antons uses the same on Stampede, although he might have experience building Amber.

**Comment by vivek-bala** [comment]
I installed amber/14 using the intel/15.0.2 compiler. I face the same issue now:

```
2015-07-30 17:15:43,369 - radical.pilot.agent - ERROR - Copy'ed /work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016646.0018-pilot.0000/unit.000001/md_1_1.crd to /work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016646.0018-pilot.0000/unit.000000/iter1/md_1_1.crd - failure ([Errno 2] No such file or directory: u'/work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016646.0018-pilot.0000/unit.000001/md_1_1.crd')
Traceback (most recent call last):
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/bin/radical-pilot-agent-multicore.py", line 4776, in run
    shutil.copyfile(abs_source, target)
  File "/opt/apps/intel13/python/2.7.9/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016646.0018-pilot.0000/unit.000001/md_1_1.crd'
```

**Comment by marksantcroos** [comment]
> File "/opt/apps/intel13/python/2.7.9/lib/python2.7/shutil.py", line 82, in copyfile

This seems to point towards intel13 still?

**Comment by vivek-bala** [comment]
I noticed that too. The agent loads the intel/15.0.2 compiler. I load the intel/15.0.2 in the compute unit as well. Not sure why/where would intel/13* would pop up (?).

**Comment by marksantcroos** [comment]
Maybe because of re-using the VE? Can you wipe out `/work/02734/vivek91/radical.pilot.sandbox/ve_stampede`?

**Comment by vivek-bala** [comment]
I tried that exactly. I still get the same error.

```
2015-07-30 17:30:34,382 - radical.pilot.agent - ERROR - Copy'ed /work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016646.0019-pilot.0000/unit.000001/md_1_1.crd to /work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016646.0019-pilot.0000/unit.000000/iter1/md_1_1.crd - failure ([Errno 2] No such file or directory: u'/work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016646.0019-pilot.0000/unit.000001/md_1_1.crd')
Traceback (most recent call last):
  File "/work/02734/vivek91/radical.pilot.sandbox/ve_stampede/rp_install/bin/radical-pilot-agent-multicore.py", line 4776, in run
    shutil.copyfile(abs_source, target)
  File "/opt/apps/intel15/python/2.7.9/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/work/02734/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016646.0019-pilot.0000/unit.000001/md_1_1.crd'
```

**Comment by marksantcroos** [comment]
At least its the right python :)

**Comment by marksantcroos** [comment]
Can you try switching from POPEN -> SHELL (or the other way around)?

**Comment by vivek-bala** [comment]
Sure ok. I was facing the module load error when using SHELL, I'll give it a try now.

**Comment by vivek-bala** [comment]
I am loading the same set of modules as before. Execution fails now with:
```
sander: error while loading shared libraries: libfftw3.so.3: cannot open shared object file: No such file or directory
```

cmd: https://gist.github.com/vivek-bala/78f3d0e311366ab0327b
(might not be the cmd of the same unit folder, but it should be similar)

I can reproduce this error if I don't load the fftw3 module.
```
$ module load intel/15.0.2
$ export AMBERHOME=/home1/02734/vivek91/modules/amber14
$ export PATH=$PATH:/home1/02734/vivek91/modules/amber14/bin
$ sander
sander: error while loading shared libraries: libfftw3.so.3: cannot open shared object file: No such file or directory
$ module load netcdf/4.3.3.1 
$ module load fftw3/3.3.4 
$ sander

  Error opening unit    6: File "mdout" exists (use -O to overwrite)
```

It seems like the fftw3* module is not being loaded in the CU environment.

**Comment by marksantcroos** [comment]
Now it becomes fishy again, because this might be the Stampede module/library issue playing up.

Can you move back to POPEN, and then the following line (https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L198) into
```
AGENT_MODE      = AGENT_THREADS
```

**Comment by marksantcroos** [comment]
(I'll be going offline now, if you give me something to reproduce I can look at it too)

**Comment by vivek-bala** [comment]
I'll try that now. In the mean time, I'll set something up for you to test.

**Comment by vivek-bala** [comment]
Fails similarily.
agent.log: https://gist.github.com/vivek-bala/42f981c920b5f5dedd9a

**Comment by marksantcroos** [comment]
Any luck with getting the application going with intel/15, anything I can assist with?

**Comment by vivek-bala** [comment]
Sorry for the delay mark. I now get the same error with gromacs-lsdmap again: CU fails during copying out the data (also does not fail). I am still using intel/15 (which seemed to fix the error). 
Documentation: http://extasy.readthedocs.org/en/extasy_0.2/pages/grlsd.html#running-on-stampede

Similar situation with coco-amber as well.

**Comment by vivek-bala** [comment]
I am frequently seeing the original error(first comment):

(1) During the simulation stage (unit.000001-unit.000016), the execution seems to exit prematurely. The log file suggests that it was returned code 0. The input file to this unit is "start.gro" (which you would find in the folder). The output file generated is "out.gro". The length of both the files is supposed to be same, but you would find that they are different in this case.

The solution was to move to intel/15*. But now I can reproduce this with intel/15* as well.

**Comment by vivek-bala** [comment]
Complete successful execution would give us an output file of the same size as the input file size. Input filename: "start.gro", output filename: "out.gro"

**Comment by marksantcroos** [comment]
Confirmed to work by Vivek is the following:
```
[06/08/15 23:15:59] Mark Santcroos: in /Users/mark/ExTASY-tools/lib/python2.7/site-packages/radical/ensemblemd/kernel_plugins/md
[06/08/15 23:16:03] Mark Santcroos: I think I changed
[06/08/15 23:16:13] Mark Santcroos:             "pre_exec"      : ["module load python", "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/apps/intel/15/composer_xe_2015.2.164/mkl/lib/intel64/:/opt/apps/intel/15/composer_xe_2015.2.164/compiler/lib/intel64/:/opt/apps/intel15/python/2.7.9/lib/"],
[06/08/15 23:16:53] Mark Santcroos: thats in pre_grlsd_loop.py
[06/08/15 23:17:07] Mark Santcroos: and in gromacs.py
[06/08/15 23:17:07] Mark Santcroos:             "pre_exec" : ["module load TACC","module load intel/15.0.2","module load boost", "module load gromacs","module load python"],
```

**Comment by vivek-bala** [comment]
Also, this is using the SHELL spawner for Stampede.

**Comment by vivek-bala** [comment]
I get the failed transfer error with amber-coco on supermic as well.

```
2015-08-11 13:47:15,279 - radical.pilot.agent - ERROR - Copy'ed /worka/work/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016658.0024-pilot.0000/unit.000001/md1.crd to /work/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016658.0024-pilot.0000/unit.000000/md_1_1.crd - failure ([Errno 2] No such file or directory: u'/worka/work/vivek91/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016658.0024-pilot.0000/unit.000001/md1.crd'
```

I switched the spawner from 'POPEN' to 'SHELL' and this error is fixed.

**Comment by marksantcroos** [comment]
Yeah, POPEN+PROCESSES is broken on all machines. Either use SHELL+PROCESSES or POPEN+THREADS.

**Comment by andre-merzky** [comment]
POPEN+PROCESSES is fixed in the hotfix/popen branch

**Comment by marksantcroos** [comment]
Vivek, the hotfix/popen branch is now merged into devel. So you don't longer need to use SHELL with all the Stampede problems that come with that hopefully. At you convenience, please do some testing of it works now.

**Comment by andre-merzky** [comment]
This ticket has collected a number of different topics, and I am thus closing it and ask you to re-open individual tickets as needed.  Having said that, the main topics (popen and ignored staging errors) should be addressed by now in devel (or pending pull requests).
