### ISSUE TITLE
support for running the agent with anaconda

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#669]
E.g. on SuperMUC.

**Comment by marksantcroos** [comment]
I managed to create a "conda environment" and pre-installed all software there (which was a little nightmare).
Then with some hackery I was able to have the bootstrapper use this, as the bootstrapper assumes virtualenv.
I guess we need support for "conda" in the bootstrapper and make that configurable.

**Comment by drelu** [comment]
Are there any instructions for this? I am trying to run it with Anaconda on the Radical VM and get:

Python 2.7.6
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aluckow/radical.pilot.sandbox/rp.session.ip-10-184-31-85.aluckow.016663.0008-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/__init__.py", line 20, in <module>
    from scheduler import *
  File "/home/aluckow/radical.pilot.sandbox/rp.session.ip-10-184-31-85.aluckow.016663.0008-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/scheduler/__init__.py", line 14, in <module>
    from direct_submission import DirectSubmissionScheduler
  File "/home/aluckow/radical.pilot.sandbox/rp.session.ip-10-184-31-85.aluckow.016663.0008-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/scheduler/direct_submission.py", line 16, in <module>
    from radical.pilot.utils.logger        import logger
  File "/home/aluckow/radical.pilot.sandbox/rp.session.ip-10-184-31-85.aluckow.016663.0008-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/__init__.py", line 2, in <module>
    from db_connection_info import DBConnectionInfo
  File "/home/aluckow/radical.pilot.sandbox/rp.session.ip-10-184-31-85.aluckow.016663.0008-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/db_connection_info.py", line 9, in <module>
    from pymongo import *
  File "/home/aluckow/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pymongo/__init__.py", line 90, in <module>
    from pymongo.common import (MIN_SUPPORTED_WIRE_VERSION,
  File "/home/aluckow/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pymongo/common.py", line 21, in <module>
    from pymongo.auth import MECHANISMS
  File "/home/aluckow/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pymongo/auth.py", line 17, in <module>
    import hmac
  File "/home/aluckow/anaconda/lib/python2.7/hmac.py", line 8, in <module>
    from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest

How can you force the agent to use the conda python? Need it for sci-kit, numpy, pandas, iPython...

**Comment by marksantcroos** [comment]
Currently you can't. Anaconda's virtual environments are incompatible with the regular virtualenv.

As long as you are not forced to use Anaconda as on SuperMUC, you can use the normal python installation and install the packages yourself.

**Comment by andre-merzky** [comment]
I consider this solved - anaconda related problems should result in new tickets, basic support is implemented.
