### ISSUE TITLE
RP v0.34 simple_bot.py fails on Comet

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#686]
I had previously ran Replica Exchange NAMD use-case on using EnsembleMD but notice that the pilots Failed shortly after becoming PendingActive. 
I then ran simple_bot.py as I suspected it was a problem with Radical Pilot. Below are some of the outputs.

agent.err (agent.out produced the same output)

```
[mingtha@comet-ln3 rp.session.lucille1.mingtaiha.016664.0016-pilot.0000]$ cat agent.err
Python 2.7.9
2015:08:17 12:36:39 12352  MainThread   saga                  : [INFO    ] saga-python          version: 0.29
2015:08:17 12:36:39 12352  MainThread   radical.pilot.agent   : [INFO    ] Using RADICAL-Utils version 0.29
2015:08:17 12:36:39 12352  MainThread   radical.pilot.agent   : [INFO    ] Using RADICAL-SAGA  version 0.29
2015:08:17 12:36:39 12352  MainThread   radical.pilot.agent   : [INFO    ] Using RADICAL-Pilot version v0.34 ($Id$)
2015:08:17 12:36:39 12352  MainThread   radical.pilot.agent   : [INFO    ] Trying to load config file ...
2015:08:17 12:36:39 12352  MainThread   radical.pilot.agent   : [INFO    ] \Agent config:
{'blowup_factor': {'Agent': 1,
                   'ExecWatcher': 1,
                   'ExecWorker': 1,
                   'Scheduler': 1,
                   'StageinWorker': 1,
                   'StageoutWorker': 1,
                   'UpdateWorker': 1,
                   'execution_queue': 1,
                   'schedule_queue': 1,
                   'stagein_queue': 1,
                   'stageout_queue': 1,
                   'update_queue': 1,
                   'watch_queue': 1},
 'bulk_collection_time': 1.0,
 'db_poll_sleeptime': 0.1,
 'drop_clones': {'Agent': 1,
                 'ExecWatcher': 1,
                 'ExecWorker': 1,
                 'Scheduler': 1,
                 'StageinWorker': 1,
                 'StageoutWorker': 1,
                 'UpdateWorker': 1,
                 'execution_queue': 1,
                 'schedule_queue': 1,
                 'stagein_queue': 1,
                 'stageout_queue': 1,
                 'update_queue': 1,
                 'watch_queue': 1},
 'heartbeat_interval': 10,
 'max_io_loglength': 1024,
 'number_of_workers': {'ExecWorker': 1,
                       'StageinWorker': 1,
                       'StageoutWorker': 1,
                       'UpdateWorker': 1},
 'queue_poll_sleeptime': 0.1,
 'staging_area': 'staging_area',
 'staging_scheme': 'staging'}


2015:08:17 12:36:39 12352  MainThread   radical.pilot.agent   : [ERROR   ] Error running agent: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/mingtha/radical.pilot.sandbox/ve_comet/rp_install/bin/radical-pilot-agent-multicore.py", line 5495, in main
    options.mongodb_auth)
  File "/home/mingtha/radical.pilot.sandbox/ve_comet/rp_install/lib/python2.7/site-packages/radical/pilot/utils/misc.py", line 271, in get_mongodb
    mongo_client = pymongo.MongoClient(mongodb_url)
  File "/home/mingtha/radical.pilot.sandbox/ve_comet/lib/python2.7/site-packages/pymongo/mongo_client.py", line 377, in __init__
    raise ConnectionFailure(str(e))
ConnectionFailure: [Errno 111] Connection refused
2015:08:17 12:36:39 12352  MainThread   radical.pilot.agent   : [ERROR   ] Error running agent: [Errno 111] Connection refused
2015:08:17 12:36:39 12352  MainThread   radical.pilot.agent   : [ERROR   ] cannot log error state in database!
```

**Comment by marksantcroos** [comment]
How did you run this?
Comet isn't even supposed to be working on RP v0.34 as it is not in the config file ... :-)

**Comment by mingtaiha** [comment]
I checked this [xsede.json](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/xsede.json) in the configs folder and I see comet is listed at the end. 

Is this not the correct config file to check? If so, which config file lists resources are supported?

**Comment by marksantcroos** [comment]
As you can see in the url, that is in the devel branch.
The config in v0.34 is at https://github.com/radical-cybertools/radical.pilot/blob/v0.34/src/radical/pilot/configs/xsede.json

**Comment by mingtaiha** [comment]
Ok I see. I'll pull the devel branch and see how that goes then. Thanks!

**Comment by marksantcroos** [comment]
That leaves the question how you ended up on comet in the first place.
Did you run on the head node?  (thats the only explanation I have)

Note that you also need SAGA devel.

**Comment by mingtaiha** [comment]
I am currently running on this version of RP (0.34-269-g4c43bbc@devel) which I believe is the current devel, and not 0.34, so I misspoke in the title (sorry)

I'm not sure that I ran on the head node, but I will get SAGA devel and try again.

**Comment by andre-merzky** [comment]
The usual mode is that RP is installed on your laptop, and you  run from there -- and only the pilot agent is submitted to the remote cluster by RP.  Running on the headnode directly is not recommended, and might get you into trouble with the admins...

You may want to sit down with one of the other students for an hour or so, and let them show you how to run the RP examples and tutorials?

**Comment by andre-merzky** [comment]
Ming, how is it going with Comet, any updates?
