### ISSUE TITLE
Simple Bot example fails branch feature/yarn_devel_merge

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#703]
I am trying to run the simple bot example from the feature/yarn_devel_merge branch and I am getting this error:

Traceback (most recent call last):
  File "simple_bot.py", line 7, in <module>
    import radical.pilot as rp
  File "/home/hadoop/RadicalPilotDevEnv/local/lib/python2.7/site-packages/radical/pilot/__init__.py", line 20, in <module>
    from .scheduler  import *
  File "/home/hadoop/RadicalPilotDevEnv/local/lib/python2.7/site-packages/radical/pilot/scheduler/__init__.py", line 14, in <module>
    from direct_submission import DirectSubmissionScheduler
  File "/home/hadoop/RadicalPilotDevEnv/local/lib/python2.7/site-packages/radical/pilot/scheduler/direct_submission.py", line 16, in <module>
    from ..utils    import logger
  File "/home/hadoop/RadicalPilotDevEnv/local/lib/python2.7/site-packages/radical/pilot/utils/__init__.py", line 21, in <module>
    logger = ru.get_logger('radical.pilot')
AttributeError: 'module' object has no attribute 'get_logger'

**Comment by marksantcroos** [comment]
As this is basically the devel branch, you also need the devel branches from saga and utils.

**Comment by iparask** [comment]
Forgot to pull.....

Thanks!
