### ISSUE TITLE
Cannot publish new CU state

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#707]
Hello guys,

When I am trying to update a CU state from Execution Pending to Executing I get the error below in the executing watcher log file:

```
2015-09-07 02:38:55,781: agent.0.AgentExecutingWatcher_POPEN.0: agent.0.AgentExecutingComponent_POPEN.0: Watcher        : DEBUG   : Trying to update CU state
2015-09-07 02:38:55,781: agent.0.AgentExecutingWatcher_POPEN.0: agent.0.AgentExecutingComponent_POPEN.0: Watcher        : ERROR   : Error in ExecWorker watch loop (<subprocess.Popen object at 0x7f2e0408c750> is not JSON serializable)
Traceback (most recent call last):
  File "/home/hadoop/radical.pilot.sandbox/rp.session.HadoopVM.hadoop.016685.0012-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 4596, in _watch
    action = self._check_running()
  File "/home/hadoop/radical.pilot.sandbox/rp.session.HadoopVM.hadoop.016685.0012-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 4636, in _check_running
    self.advance(cu, rp.EXECUTING, publish=True, push=False)
  File "/home/hadoop/radical.pilot.sandbox/rp.session.HadoopVM.hadoop.016685.0012-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 599, in advance
    self.publish('state', unit)
  File "/home/hadoop/radical.pilot.sandbox/rp.session.HadoopVM.hadoop.016685.0012-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 645, in publish
    p.put (topic, m)
  File "/home/hadoop/radical.pilot.sandbox/rp.session.HadoopVM.hadoop.016685.0012-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/pubsub.py", line 322, in put
    data = json.dumps(msg)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <subprocess.Popen object at 0x7f2e0408c750> is not JSON serializable
2015-09-07 02:40:22,919: agent.0.AgentExecutingWatcher_POPEN.0: agent.0.AgentExecutingComponent_POPEN.0: agent.0.AgentExecutingComponent_POPEN.0.subscriber: INFO    : received shutdown command
```

You can find what I do here: https://github.com/radical-cybertools/radical.pilot/blob/feature/yarn_devel_merge/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L4636

I you have an idea why this happens please tell me and I will see what I did break

**Comment by andre-merzky** [comment]
Hi Iannis, 

the error comes from the 'proc' object which is attached to the CU -- that cannot be transferred between different components for multiple reasons (json serialization being one of them).  At this point you should not need that object anymore though, so please remove it from the CU instance.  This should be similar to this line:

https://github.com/radical-cybertools/radical.pilot/blob/feature/yarn_devel_merge/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L4667

Thanks, Andre.

**Comment by iparask** [comment]
Thank you! That was it!
