### ISSUE TITLE
UnboundLocalError: local variable 'pwd' referenced before assignment

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#730]
I got this error with one of jenkins tests for extasy-0.1. ExTASY 0.1 uses rp 0.35 (pypi).
This is while running on Stampede. T
```
2015:09:17 03:40:53 18089  InputFileTransferWorker-1 radical.pilot         : [ERROR   ] Error: local variable 'pwd' referenced before assignment
Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/d6fd35c2/virtualenvs/dc4281b1/local/lib/python2.7/site-packages/radical/pilot/controller/input_file_transfer_worker.py", line 133, in run
    session=self._session)
  File "/var/lib/jenkins/shiningpanda/jobs/d6fd35c2/virtualenvs/dc4281b1/local/lib/python2.7/site-packages/saga/filesystem/directory.py", line 95, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/var/lib/jenkins/shiningpanda/jobs/d6fd35c2/virtualenvs/dc4281b1/local/lib/python2.7/site-packages/saga/namespace/directory.py", line 95, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/var/lib/jenkins/shiningpanda/jobs/d6fd35c2/virtualenvs/dc4281b1/local/lib/python2.7/site-packages/saga/namespace/entry.py", line 89, in __init__
    url, flags, session, ttype=_ttype)
  File "/var/lib/jenkins/shiningpanda/jobs/d6fd35c2/virtualenvs/dc4281b1/local/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/d6fd35c2/virtualenvs/dc4281b1/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/d6fd35c2/virtualenvs/dc4281b1/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 288, in init_instance
    self._logger)
  File "/var/lib/jenkins/shiningpanda/jobs/d6fd35c2/virtualenvs/dc4281b1/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    self.initialize ()
  File "/var/lib/jenkins/shiningpanda/jobs/d6fd35c2/virtualenvs/dc4281b1/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 323, in initialize
    self.logger.warning ("local cd to %s failed" % pwd)
UnboundLocalError: local variable 'pwd' referenced before assignment
```

Full log: http://ci.radical-project.org/job/ExTASY-0.1/117/EXTASY_BRANCH=0.1-devel,EXTASY_HOST=stampede,EXTASY_WORKFLOW=gromacslsdmap,PYTHON=System-CPython-2.7/consoleFull

This is not repeatable, the next build is successful.

**Comment by andre-merzky** [comment]
This is resolved in devel now.  Thanks!
