### ISSUE TITLE
Getting started local example fails with devel stack

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#731]
rp version: v0.35-378-g4772d5c@devel
saga version: v0.35-12-ga30251f@devel
utils version: v0.35-21-gb42c319@devel

```
Traceback (most recent call last):
  File "getting_started_local.py", line 8, in <module>
    import radical.pilot as rp
  File "/home/antons/rpdev35/local/lib/python2.7/site-packages/radical/pilot/__init__.py", line 20, in <module>
    from .scheduler  import *
  File "/home/antons/rpdev35/local/lib/python2.7/site-packages/radical/pilot/scheduler/__init__.py", line 14, in <module>
    from direct_submission import DirectSubmissionScheduler
  File "/home/antons/rpdev35/local/lib/python2.7/site-packages/radical/pilot/scheduler/direct_submission.py", line 16, in <module>
    from ..utils    import logger
  File "/home/antons/rpdev35/local/lib/python2.7/site-packages/radical/pilot/utils/__init__.py", line 21, in <module>
    logger = ru.get_logger('radical.pilot')
  File "/home/antons/rpdev35/local/lib/python2.7/site-packages/radical/utils/logger.py", line 141, in get_logger
    logger.setLevel(level)
  File "/usr/lib/python2.7/logging/__init__.py", line 1128, in setLevel
    self.level = _checkLevel(level)
  File "/usr/lib/python2.7/logging/__init__.py", line 187, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'info'
```

**Comment by andre-merzky** [comment]
This has been fixed on the utils layer.  Thanks!
