### ISSUE TITLE
Archer cannot compile gtod on the fly because...

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#733]
```
CC-2136 craycc: ERROR in command line
  Unable to obtain a Cray Compiling Environment License.
```

duh!

Changing the bootstrapper to use `/usr/bin/cc` helps to get gtod in place, but then `pip install pyzmq` failes again due to compilation issues:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016696.0002-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/__init__.py", line 20, in <module>
    from .scheduler  import *
  File "/work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016696.0002-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/scheduler/__init__.py", line 14, in <module>
    from direct_submission import DirectSubmissionScheduler
  File "/work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016696.0002-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/scheduler/direct_submission.py", line 16, in <module>
    from ..utils    import logger
  File "/work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016696.0002-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/__init__.py", line 5, in <module>
    from queue              import *
  File "/work/e290/e290/merzky/radical.pilot.sandbox/rp.session.cameo.merzky.016696.0002-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 3, in <module>
    import zmq
  File "/work/e290/shared/shared_pilot_ve_20150916/lib/python2.7/site-packages/zmq/__init__.py", line 49, in <module>
    _libzmq = ctypes.CDLL(bundled[0], mode=ctypes.RTLD_GLOBAL)
  File "/work/y07/y07/cse/python/2.7.6/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /work/e290/shared/shared_pilot_ve_20150916/lib/python2.7/site-packages/zmq/libzmq.so)
```

Mark, do you have any additional module loads in your bashrc?

**Comment by marksantcroos** [comment]
Yes:
```
module switch PrgEnv-cray PrgEnv-gnu
```

**Comment by andre-merzky** [comment]
right.  Should we add that to the pilot env then?

**Comment by marksantcroos** [comment]
Given that ORTE is build with GNU too, thats probably not unsafe to do.
