### ISSUE TITLE
env_removables not defined on None

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.pilot#770]
```
 18 2015-09-29 14:57:23,515: agent_0.AgentExecutingComponent_SHELL.0.child: agent_0.AgentExecutingComponent_SHELL.0: MainThread     : INFO    : Discovered launch command: ''.
 19 2015-09-29 14:57:23,516: agent_0.AgentExecutingComponent_SHELL.0.child: agent_0.AgentExecutingComponent_SHELL.0: MainThread     : ERROR   : LaunchMethod cannot be used: Launch command not found     for LaunchMethod 'LaunchMethodMPIEXEC'!
 20 Traceback (most recent call last):
 21   File "/home/iparask/radical.pilot.sandbox/rp.session.iparask-virtual-machine.iparask.016707.0006-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 1240, in create
 22     return impl(cfg, logger)
 23   File "/home/iparask/radical.pilot.sandbox/rp.session.iparask-virtual-machine.iparask.016707.0006-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 1499, in __init__
 24     LaunchMethod.__init__(self, cfg, logger)
 25   File "/home/iparask/radical.pilot.sandbox/rp.session.iparask-virtual-machine.iparask.016707.0006-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 1207, in __init__
 26     raise RuntimeError("Launch command not found for LaunchMethod '%s'" % self.name)
 27 RuntimeError: Launch command not found for LaunchMethod 'LaunchMethodMPIEXEC'
 28 2015-09-29 14:57:23,517: agent_0.AgentExecutingComponent_SHELL.0.child: agent_0.AgentExecutingComponent_SHELL.0: MainThread     : ERROR   : loop exception
 29 Traceback (most recent call last):
 30   File "/home/iparask/radical.pilot.sandbox/rp.session.iparask-virtual-machine.iparask.016707.0006-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 613,     in run
 31     self.initialize_child()
 32   File "/home/iparask/radical.pilot.sandbox/rp.session.iparask-virtual-machine.iparask.016707.0006-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 4072, in initialize_child
 33     for r in self._mpi_launcher.env_removables + self._task_launcher.env_removables:
 34 AttributeError: 'NoneType' object has no attribute 'env_removables'
```

mpi launch method is set to `MPIEXEC` which might not exist on the machine, task_launcher is `FORK`.

**Comment by marksantcroos** [comment]
That one of them could not exist was indeed not on my radar.

**Comment by andre-merzky** [comment]
Yeah, same here ...

I pushed a fix.  Alas, I made the mistake to push to the release branch.  Forgot '-b' on checkout...  Sorry for that, I would appreciate if you could review it, obviously...
