### ISSUE TITLE
v0.36.RC1@detached-v0.36.RC1 getting_started_remote.py fails on Blue Waters

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.pilot#786]
Error is:
```
2015-10-02 13:41:44,701: radical.pilot       : MainProcess                     : Thread-1       : INFO    : ComputePilot 'pilot.0000' state changed from 'PendingActive' to 'Failed'.
2015-10-02 13:41:44,701: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : pilot manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/antons/rp36/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 328, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/antons/rp36/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 249, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "getting_started_remote.py", line 115, in pilot_state_cb
    sys.exit (1)
SystemExit: 1
```

and pilot size is 64 cores this time.

[terminal](https://gist.github.com/AntonsT/65329cd83b49eae5e673)

[debug](https://gist.github.com/AntonsT/632c8d58eec999060de1)

[sandbox](https://github.com/AntonsT/rp-logs/blob/master/rp.session.antons-pc.antons.016710.0028-pilot.0000.tar.gz)

**Comment by andre-merzky** [comment]
Thanks Antons!

Would you mind trying again,  but set `RADICAL_PILOT_PROFILE=TRUE` before?  The error may be related to an issue Mark just fixed on devel.  Thanks!

**Comment by AntonsT** [comment]
will do

**Comment by AntonsT** [comment]
It works after setting `RADICAL_PILOT_PROFILE=TRUE`

**Comment by marksantcroos** [comment]
> It works after setting RADICAL_PILOT_PROFILE=TRUE

Good, then devel will work for you too.
