### ISSUE TITLE
rtd build broken for 0.36

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#812]
https://readthedocs.org/projects/radicalpilot/builds/3384318/

```
Running Sphinx v1.3.1
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/radicalpilot/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radicalpilot/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 126, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radicalpilot/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radicalpilot/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radicalpilot/envs/latest/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 105, in <module>
    resources_rst.write("{0}\n\n".format(resource_config["description"]))
KeyError: 'description'

Exception occurred:
  File "conf.py", line 105, in <module>
    resources_rst.write("{0}\n\n".format(resource_config["description"]))
KeyError: 'description'
The full traceback has been saved in /tmp/sphinx-err-BGgizU.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
* Generating resource configuration docs: resources.rst
* using tag: release
 * agent_default.json
   * agent_default.agent_layout
```

**Comment by andre-merzky** [comment]
Thanks Mark.  This is actually fixed in one of the doc branches -- I'll try to cherry-pick it back to RTD...

**Comment by andre-merzky** [comment]
fixed in latest release.
