### ISSUE TITLE
rp 0.36 failing when using "archer_aprun"

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#814]
I switched to use "archer_aprun" in the config file (I renamed archer_aprun, archer to archer,archer_new to keep the naming same across enmd as well. So now I call "aprun_archer" as "archer"). I also changed the module load during bootstrap to ```module load python-compute/2.7.6-ucs4```. I get the following error:

bootstrap_1.out:
```
Unpacking ./radical.pilot-v0.36.RC1-72-gdd8889c-devel
  Running setup.py egg_info for package from file:///fs4/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016716.0014-pilot.0000/radical.pilot-v0.36.RC1-72-gdd8889c-devel
    /fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/site-packages/setuptools/dist.py:291: UserWarning: The version specified ('v0.36.RC1-72-gdd8889c@devel') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    version: v0.36.RC1-72-gdd8889c@devel (v0.36.RC1-72-gdd8889c@devel)

    warning: no files found matching '*.json'
    warning: no files found matching '*.sh'
Requirement already satisfied (use --upgrade to upgrade): saga-python in ./rp_install/lib/python2.7/site-packages (from radical.pilot==v0.36.RC1-72-gdd8889c-devel)
Requirement already satisfied (use --upgrade to upgrade): radical.utils in ./rp_install/lib/python2.7/site-packages (from radical.pilot==v0.36.RC1-72-gdd8889c-devel)
Requirement already satisfied (use --upgrade to upgrade): pymongo==2.8 in /fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/site-packages (from radical.pilot==v0.36.RC1-72-gdd8889c-devel)
Requirement already satisfied (use --upgrade to upgrade): python-hostlist in /fs4/e290/shared/shared_pilot_ve_20150429/lib/python2.7/site-packages (from radical.pilot==v0.36.RC1-72-gdd8889c-devel)
Downloading/unpacking netifaces (from radical.pilot==v0.36.RC1-72-gdd8889c-devel)
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement netifaces (from radical.pilot==v0.36.RC1-72-gdd8889c-devel)
No distributions at all found for netifaces (from radical.pilot==v0.36.RC1-72-gdd8889c-devel)
Storing complete log in /home/e290/e290/vb224/.pip/pip.log
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't install radical.pilot-v0.36.RC1-72-gdd8889c-devel/! Lets see how far we get ...

---------------------------------------------------------------------

 (/fs4/e290/shared/shared_pilot_ve_20150429/bin/python)
PYTHONPATH: /work/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016716.0014-pilot.0000/rp_install/lib/python2.7/site-packages::/work/y07/y07/cse/python/modules/cython/0.21.1/lib/python2.7/site-packages:/work/y07/y07/cse/mpi4py/1.3.1/lib/python2.7/site-packages:/opt/cray/sdb/1.0-1.0501.48084.4.48.ari/lib64/py:/usr/local/packages/cse/bolt/0.6/modules
utils :  v0.36.RC1-1-g0b30c97@devel /work/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016716.0014-pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/__init__.pyc
saga  :  v0.36.RC1-6-gf09c9ee@devel /work/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016716.0014-pilot.0000/rp_install/lib/python2.7/site-packages/saga/__init__.pyc
pilot :
install failed!
--------------------------------------------------------------------------------

```

bootstrap_1.err:
```
Python 2.7.6
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pilot
~                                  
```

**Comment by marksantcroos** [comment]
Can you try with the same static VE as the regular archer entry?

**Comment by marksantcroos** [comment]
And there are probably some more entries from the archer entry that you want to move over.

**Comment by vivek-bala** [comment]
The initial archer entry (with ORTE) started successfully. It took a lot of time and failed with an error.

**Comment by vivek-bala** [comment]
CU error (while using ORTE):
```
ModuleCmd_Use.c(231):ERROR:64: Directory '/opt/modules/packages-archer' not found
packages-archer(19):ERROR:102: Tcl command execution failed: module use --append /opt/modules/packages-archer
```

**Comment by vivek-bala** [comment]
> And there are probably some more entries from the archer entry that you want to move over.

Oh ! ok. I thought it was the same as the one in 0.35 and hence should work as is. What entries should I moving over/editing ?

**Comment by marksantcroos** [comment]
> What entries should I moving over/editing ?

Roughly speaking the difference should be:
- `*_launch_method` ORTE -> APRUN
- `agent_config` -> `default`
- `pre_bootstrap_1` can likely be reduced to `"module load python-compute/2.7.6"` only
- You can probably do without `pre_bootstrap_2` altogether

**Comment by marksantcroos** [comment]
> CU error (while using ORTE):

Can we not discuss this in this ticket, its confusing enough already.

**Comment by vivek-bala** [comment]
Ok, let me give it a try.

> CU error (while using ORTE):
> Can we not discuss this in this ticket, its confusing enough already.

Agreed.

**Comment by vivek-bala** [comment]
Still the same error. Although I do see the ```radical.pilot-v0.36.RC1-72-gdd8889c-devel``` tarball downloaded and untarred.

config:

```
"archer": {
        "description"                 : "The EPSRC Archer Cray XC30 system (https://www.archer.ac.uk/)",
        "notes"                       : "Always set the ``project`` attribute in the ComputePilotDescription or the pilot will fail.",
        "schemas"                     : ["ssh"],
        "mandatory_args"              : ["project"],
        "ssh"                         :
        {
            "job_manager_endpoint"    : "pbspro+ssh://login.archer.ac.uk/",
            "filesystem_endpoint"     : "sftp://login.archer.ac.uk/"
        },
        "default_queue"               : "standard",
        "lrms"                        : "PBSPRO",
        "agent_type"                  : "multicore",
        "agent_scheduler"             : "CONTINUOUS",
        "agent_config"                : "default",
        "agent_spawner"               : "POPEN",
        "agent_launch_method"         : "APRUN",
        "task_launch_method"          : "APRUN",
        "mpi_launch_method"           : "APRUN",
        "forward_tunnel_endpoint"     : "10.60.0.52",
        "pre_bootstrap_1"             : ["module load python-compute/2.7.6-ucs4"],
        # choosing this module fixes #587
        "default_remote_workdir"      : "/work/`id -gn`/`id -gn`/$USER",
        "valid_roots"                 : ["/work"],
        "virtenv"                     : "/work/e290/shared/shared_pilot_ve_20150429/",
        "virtenv_mode"                : "use",
        "rp_version"                  : "debug"
    }
```

**Comment by marksantcroos** [comment]
You didnt change the virtenv

**Comment by marksantcroos** [comment]
And wrong python.

**Comment by vivek-bala** [comment]
Oops wrong python. What should be the value of virtenv ?

**Comment by marksantcroos** [comment]
The same as the archer entry.

**Comment by vivek-bala** [comment]
bootstrap_1.err:
```
Python 2.7.6
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016716.0020-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/__init__.py", line 20, in <module>
    from .scheduler  import *
  File "/work/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016716.0020-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/scheduler/__init__.py", line 14, in <module>
    from direct_submission import DirectSubmissionScheduler
  File "/work/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016716.0020-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/scheduler/direct_submission.py", line 16, in <module>
    from ..utils    import logger
  File "/work/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016716.0020-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/__init__.py", line 17, in <module>
    from queue              import *
  File "/work/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016716.0020-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 3, in <module>
    import zmq
  File "/work/e290/shared/shared_pilot_ve_20150924/lib/python2.7/site-packages/zmq/__init__.py", line 49, in <module>
    _libzmq = ctypes.CDLL(bundled[0], mode=ctypes.RTLD_GLOBAL)
  File "/work/y07/y07/cse/python/2.7.6/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /work/e290/shared/shared_pilot_ve_20150924/lib/python2.7/site-packages/zmq/libzmq.so)
```

bootstrap_1.out:
```
Successfully installed radical.pilot
Cleaning up...
#
# SUCCESS
#
# -------------------------------------------------------------------

---------------------------------------------------------------------

 (/work/e290/shared/shared_pilot_ve_20150924/bin/python)
PYTHONPATH: /work/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016716.0020-pilot.0000/rp_install/lib/python2.7/site-packages::/work/y07/y07/cse/pycairo/1.10.0//lib/python2.7/site-packages:/work/y07/y07/cse/pygobject/2.21.3/lib/python2.7/site-packages:/work/y07/y07/cse/pygtk/2.24.0//lib/python2.7/site-packages/gtk-2.0:/work/y07/y07/cse/yaml/pyyaml/3.11/lib/python2.7/site-packages:/work/y07/y07/cse/python/modules/cython/0.21.1/lib/python2.7/site-packages:/work/y07/y07/cse/mpi4py/1.3.1/lib/python2.7/site-packages:/opt/cray/sdb/1.0-1.0501.48084.4.48.ari/lib64/py:/usr/local/packages/cse/bolt/0.6/modules
utils :  v0.36.RC1-1-g0b30c97@devel /work/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016716.0020-pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/__init__.pyc
saga  :  v0.36.RC1-6-gf09c9ee@devel /work/e290/e290/vb224/radical.pilot.sandbox/rp.session.ip-10-184-31-85.vivek.016716.0020-pilot.0000/rp_install/lib/python2.7/site-packages/saga/__init__.pyc
pilot :
install failed!
```

Not sure what the "failed" refers to. rp seems to have installed successfully.

**Comment by marksantcroos** [comment]
> Not sure what the "failed" refers to. rp seems to have installed successfully.

OSError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /work/e290/shared/shared_pilot_ve_20150924/lib/python2.7/site-packages/zmq/libzmq.so)

**Comment by marksantcroos** [comment]
Also use the following line from the archer entry:
```
            "module switch PrgEnv-cray PrgEnv-gnu",
```

**Comment by vivek-bala** [comment]
Ok that worked. The complete agent config:

```
"archer": {
        "description"                 : "The EPSRC Archer Cray XC30 system (https://www.archer.ac.uk/)",
        "notes"                       : "Always set the ``project`` attribute in the ComputePilotDescription or the pilot will fail.",
        "schemas"                     : ["ssh"],
        "mandatory_args"              : ["project"],
        "ssh"                         :
        {
            "job_manager_endpoint"    : "pbspro+ssh://login.archer.ac.uk/",
            "filesystem_endpoint"     : "sftp://login.archer.ac.uk/"
        },
        "default_queue"               : "standard",
        "lrms"                        : "PBSPRO",
        "agent_type"                  : "multicore",
        "agent_scheduler"             : "CONTINUOUS",
        "agent_config"                : "default",
        "agent_spawner"               : "POPEN",
        "agent_launch_method"         : "APRUN",
        "task_launch_method"          : "APRUN",
        "mpi_launch_method"           : "APRUN",
        "forward_tunnel_endpoint"     : "10.60.0.52",
        "pre_bootstrap_1"             : ["module load python-compute/2.7.6","module switch PrgEnv-cray PrgEnv-gnu"],
        # choosing this module fixes #587
        "default_remote_workdir"      : "/work/`id -gn`/`id -gn`/$USER",
        "valid_roots"                 : ["/work"],
        "virtenv"                     : "/work/e290/shared/shared_pilot_ve_20150924/",
        "virtenv_mode"                : "use",
        "rp_version"                  : "debug"
    }
```

**Comment by andre-merzky** [comment]
Is there a reason though to still use aprun (apart from comparing to ORTE)?

**Comment by vivek-bala** [comment]
Currently, the aprun mode is faster than the ORTE method. I think it might be better to use that for the tutorials (at least for enmd).

**Comment by marksantcroos** [comment]
> Ok that worked. The complete agent config:

Thanks for checking, committed to devel!

**Comment by vivek-bala** [comment]
I also encountered an issue with ORTE mode during execution. I'll open another ticket for that.

**Comment by andre-merzky** [comment]
Interesting that aprun is faster for you than ORTE.  Thanks for the reply!
