### ISSUE TITLE
Error using RP 0.36 on Archer (aprun): flushing failed

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.pilot#817]
I ran into this following error (haven't run into this before) now:

```
..2015-10-08 21:00:38,375: radical.saga.pty    : MainProcess                     : Thread-9       : ERROR   : flushing failed
Traceback (most recent call last):
  File "/experiments/vivek/extasy_tut/extasy2/myenv/local/lib/python2.7/site-packages/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/experiments/vivek/extasy_tut/extasy2/myenv/local/lib/python2.7/site-packages/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (time = Thu Oct  8 21:54:50 2015
PROMPT-0->    job_state = R
    ctime = Thu Oct  8 21:53:18 2015
    exec_host = mom1/296*0
    mtime = Thu Oct  8 21:54:51 2015
    stime = Thu Oct  8 21:54:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/experiments/vivek/extasy_tut/extasy2/myenv/local/lib/python2.7/site-packages/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
```

**Comment by vivek-bala** [comment]
Nevermind, I think this was from remote host.
