### ISSUE TITLE
SystemExit stacktrace in component shutdown

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#830]
Hello guys,

I got this error in the feature/yarn branch:

```
2015-10-12 21:28:10,759: agent_0.SchedulerYarn.0.child: agent_0.SchedulerYarn.0         : MainThread     : ERROR   : loop error
Traceback (most recent call last):
  File "/home/iparask/radical.pilot.sandbox/rp.session.HadoopVM.hadoop.016720.0038-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 642, in run
    unit = input.get_nowait(1000) # timeout in microseconds
  File "/home/iparask/radical.pilot.sandbox/rp.session.HadoopVM.hadoop.016720.0038-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 551, in get_nowait
    if _uninterruptible(self._q.poll, flags=zmq.POLLIN, timeout=timeout):
  File "/home/iparask/radical.pilot.sandbox/rp.session.HadoopVM.hadoop.016720.0038-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 42, in _uninterruptible
    return f(*args, **kwargs)
  File "/home/iparask/radical.pilot.sandbox/ve_chameleon/lib/python2.7/site-packages/zmq/sugar/socket.py", line 501, in poll
    evts = dict(p.poll(timeout))
  File "/home/iparask/radical.pilot.sandbox/ve_chameleon/lib/python2.7/site-packages/zmq/sugar/poll.py", line 101, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1625)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:1958)
    PyErr_CheckSignals()
  File "/home/iparask/radical.pilot.sandbox/rp.session.HadoopVM.hadoop.016720.0038-pilot.0000/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 587, in sigterm_handler
    sys.exit()
SystemExit
```

I do not know if it is because of the merge. Any ideas?

**Comment by andre-merzky** [comment]
Hi Iannis -- that stack in itself might not man much: it says the code got a sigterm, but that is expected in some cases  during shutdown.  Are there any error messages around in the agent logs?  Why did you consider the agent failing, apart from that stack trace?

**Comment by iparask** [comment]
Hmmmmmm...... Okay stupid me...... I just found a bug in my implementation.... I thought this was it. Sorry. Closing

**Comment by andre-merzky** [comment]
No worries -- I love tickets which end up to be *other* people's bugs :D

**Comment by marksantcroos** [comment]
This really requires a different resolution. `loop error` and a stacktrace dont sound like a smooth shutdown.
Can't we catch SystemExit and be silent?

**Comment by marksantcroos** [comment]
This is addressed in fix/shutdown_race.
