### ISSUE TITLE
RP-0.36 fails on Archer while job is still in queue

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#839]
with:

```
job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:20:26,154: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:21:26,194: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:21:26,194: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:22:26,233: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:22:26,233: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:23:26,269: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:23:26,270: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:24:26,307: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:24:26,307: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:25:26,333: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:25:26,333: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:26:26,403: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:26:26,404: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:27:26,427: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:27:26,428: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:28:26,431: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:28:26,432: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:29:26,437: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:29:26,438: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:30:26,441: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:30:26,442: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:30:37,756: radical.saga.pty    : MainProcess                     : Thread-4       : ERROR   : flushing failed
Traceback (most recent call last):
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
Traceback (most recent call last):
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/adaptors/pbspro/pbsprojob.py", line 72, in run
    new_job_info = self.js._job_get_info(job_id, reconnect=False)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/adaptors/pbspro/pbsprojob.py", line 824, in _job_get_info
    % (self._commands['qstat']['path'], qstat_flag, pid))
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_shell.py", line 647, in run_sync
    self.pty_shell.flush ()
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
2015-10-14 20:30:53,943: radical.saga.pty    : MainProcess                     : Thread-3       : ERROR   : flushing failed
Traceback (most recent call last):
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
Traceback (most recent call last):
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/adaptors/pbspro/pbsprojob.py", line 72, in run
    new_job_info = self.js._job_get_info(job_id, reconnect=False)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/adaptors/pbspro/pbsprojob.py", line 824, in _job_get_info
    % (self._commands['qstat']['path'], qstat_flag, pid))
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_shell.py", line 647, in run_sync
    self.pty_shell.flush ()
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
2015-10-14 20:31:26,449: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:31:26,449: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:31:37,817: radical.saga.pty    : MainProcess                     : Thread-4       : ERROR   : flushing failed
Traceback (most recent call last):
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
Traceback (most recent call last):
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/adaptors/pbspro/pbsprojob.py", line 72, in run
    new_job_info = self.js._job_get_info(job_id, reconnect=False)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/adaptors/pbspro/pbsprojob.py", line 824, in _job_get_info
    % (self._commands['qstat']['path'], qstat_flag, pid))
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_shell.py", line 647, in run_sync
    self.pty_shell.flush ()
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
2015-10-14 20:31:54,001: radical.saga.pty    : MainProcess                     : Thread-3       : ERROR   : flushing failed
Traceback (most recent call last):
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
Traceback (most recent call last):
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/adaptors/pbspro/pbsprojob.py", line 72, in run
    new_job_info = self.js._job_get_info(job_id, reconnect=False)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/adaptors/pbspro/pbsprojob.py", line 824, in _job_get_info
    % (self._commands['qstat']['path'], qstat_flag, pid))
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_shell.py", line 647, in run_sync
    self.pty_shell.flush ()
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
2015-10-14 20:32:26,460: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:32:26,461: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:32:37,870: radical.saga.pty    : MainProcess                     : Thread-4       : ERROR   : flushing failed
Traceback (most recent call last):
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
Traceback (most recent call last):
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/adaptors/pbspro/pbsprojob.py", line 72, in run
    new_job_info = self.js._job_get_info(job_id, reconnect=False)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/adaptors/pbspro/pbsprojob.py", line 824, in _job_get_info
    % (self._commands['qstat']['path'], qstat_flag, pid))
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_shell.py", line 647, in run_sync
    self.pty_shell.flush ()
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
2015-10-14 20:32:37,870: radical.saga.cpi    : MainProcess                     : Thread-4       : ERROR   : too many monitoring errors -- stopping job monitoring thread
2015-10-14 20:32:54,060: radical.saga.pty    : MainProcess                     : Thread-3       : ERROR   : flushing failed
Traceback (most recent call last):
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
Traceback (most recent call last):
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/adaptors/pbspro/pbsprojob.py", line 72, in run
    new_job_info = self.js._job_get_info(job_id, reconnect=False)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/adaptors/pbspro/pbsprojob.py", line 824, in _job_get_info
    % (self._commands['qstat']['path'], qstat_flag, pid))
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_shell.py", line 647, in run_sync
    self.pty_shell.flush ()
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->    job_state = Q
    ctime = Wed Oct 14 20:24:50 2015
    mtime = Wed Oct 14 20:24:50 2015
PROMPT-0->Shared connection to login.archer.ac.uk closed.
) (/home/antons/repex-archer/local/lib/python2.7/site-packages/saga_python-0.36-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
2015-10-14 20:32:54,060: radical.saga.cpi    : MainProcess                     : Thread-3       : ERROR   : too many monitoring errors -- stopping job monitoring thread
2015-10-14 20:33:26,479: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:33:26,479: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:34:26,480: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:34:26,480: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:35:26,490: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:35:26,491: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:36:26,511: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
2015-10-14 20:36:26,511: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : pilot pilot.0000 seems alive and well
2015-10-14 20:37:26,524: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: INFO    : Performing periodical health check for pilot.0000 (SAGA job id [pbspro+ssh://login.archer.ac.uk/]-[3213637])
```

**Comment by marksantcroos** [comment]
Hmmmm, ARCHER was in maintenance yesterday, could it have been intermittent network / host issues?
I can't make much else out of it.

**Comment by andre-merzky** [comment]
Yeah, same here, can't really  wrap my head around those stacks.  Does the problem persist?

**Comment by AntonsT** [comment]
>Hmmmm, ARCHER was in maintenance yesterday, could it have been intermittent network / host issues?

I don't know. If I was able to get job to queue this should not be an issue, right?

>Does the problem persist?

Can't answer right now. I just wanted to post it here in case it might be helpful for debugging.

**Comment by andre-merzky** [comment]
Please do give it another try -- possibly during the user-friendly UK office hours, as Mark suggested.  Thanks!

**Comment by andre-merzky** [comment]
Antons,   is this still an issue?

**Comment by antonst** [comment]
Can't reproduce it as of now

**Comment by marksantcroos** [comment]
I propose to close and attribute it to the network. At least the error is recorded now for future generations to find and relate to.

Ideally we can cope with effects like this, in reality there is only so much we can do.

**Comment by marksantcroos** [comment]
Thanks for checking and reporting though!

**Comment by antonst** [comment]
You are welcome Mark
