### ISSUE TITLE
exception (most likely raised during interpreter shutdown) signature.py 'NoneType' object is not callable

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#855]
```
(ve)[marksant@workflow examples]$ python getting_started_00.py 

================================================================================
 Getting Started (RP version 0.37.3)                                            
================================================================================

create session rp.session.workflow.iu.xsede.org.marksant.016727.0007          ok
read config                                                                   ok

--------------------------------------------------------------------------------
submit pilots                                                                   

create pilot manager                                                          ok
create pilot description                                                       \
create pilot description [local.localhost:64]                                 ok
                                                                              ok
submit 1 pilot(s) .                                                           ok

--------------------------------------------------------------------------------
submit units                                                                    

create unit manager                                                           ok
add 1 pilot(s)                                                                ok
create 128 unit description(s)
        ........................................................................
        ........................................................              ok
submit 128 unit(s)
        ........................................................................
        ........................................................              ok

--------------------------------------------------------------------------------
gather results                                                                  

wait for 128 unit(s)
        +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++|
        +++++++++++++++++++++++++++++++++++++++++++++++++++++++++             ok

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.workflow.iu.xsede.org.marksant.016727.0007          \
close pilot manager                                                            \
wait for 1 pilot(s) *                                                         ok
                                                                              ok
close unit manager                                                            ok
session lifetime: 40.7s                                                       ok

--------------------------------------------------------------------------------

Exception in thread Thread-8 (most likely raised during interpreter shutdown):
 Exception in thread Thread-9 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/opt/radical/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/home/marksant/ve/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line 120, in run
  File "/home/marksant/ve/lib/python2.7/site-packages/radical/utils/signatures.py", line 456, in signature_check
  File "/home/marksant/ve/lib/python2.7/site-packages/radical/utils/signatures.py", line 216, in check
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by andre-merzky** [comment]
I am closing this one as shutdown now looks very differently.  Thanks.
