### ISSUE TITLE
getting started 11 failing

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.pilot#857]
Not sure from which page that is actually linked (or is it not supposed to work?)

```
(ve)[marksant@workflow examples]$ python getting_started_11.py 

================================================================================
 Getting Started (RP version 0.37.5)                                            
================================================================================


--------------------------------------------------------------------------------
profile analysis                                                                

fetch profiles, create data frames, plot
        + rp.session.cameo.merzky.016716.0004.prof
Traceback (most recent call last):
  File "getting_started_11.py", line 77, in <module>
    myplot()
  File "getting_started_11.py", line 33, in myplot
    profiles   = rpu.fetch_profiles(sid=sid, skip_existing=True);    report.progress() 
  File "/home/marksant/ve/lib/python2.7/site-packages/radical/pilot/utils/session.py", line 70, in fetch_profiles
    prof_file = saga.filesystem.File(client_profile, session=session)
  File "/home/marksant/ve/lib/python2.7/site-packages/saga/filesystem/file.py", line 86, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/home/marksant/ve/lib/python2.7/site-packages/saga/namespace/entry.py", line 89, in __init__
    url, flags, session, ttype=_ttype)
  File "/home/marksant/ve/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/home/marksant/ve/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/marksant/ve/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 1007, in init_instance
    self.initialize ()
  File "/home/marksant/ve/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 1056, in initialize
    raise saga.DoesNotExist("File does not exist: '%s' - %s" % (self.url.path, out))
saga.exceptions.DoesNotExist: File does not exist: '/home/marksant/ve/share/radical.pilot/examples/rp.session.cameo.merzky.016716.0004.prof' -  (/home/marksant/ve/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +1056 (initialize)  :  raise saga.DoesNotExist("File does not exist: '%s' - %s" % (self.url.path, out)))
(ve)[marksant@workflow examples]$ 
```

**Comment by andre-merzky** [comment]
That is not linked indeed, and is not yet supposed to  work.  I should remove it before the tutorial (and clean out the examples in general).

**Comment by andre-merzky** [comment]
done - thanks!
