### ISSUE TITLE
Netiface error when running examples on localhost

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#880]
I tried to run the examples in the Radical Pilot tutorial, but I always encounter an error when I get the pilot gets to the step: ugmr.wait_units()

```
2015-10-28 12:21:03,752: agent_0.bootstrap_3 : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
2015-10-28 12:21:03,752: agent_0.bootstrap_3 : MainProcess                     : MainThread     : INFO    :                      pid: 11193
2015-10-28 12:21:03,753: agent_0.bootstrap_3 : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2015-10-28 12:21:03,753: agent_0.bootstrap_3 : MainProcess                     : MainThread     : INFO    : start
2015-10-28 12:21:04,800: agent_0.bootstrap_3 : MainProcess                     : MainThread     : ERROR   : Error running agent: agent_0
Traceback (most recent call last):
  File "/home/mingtaiha/radical.pilot.sandbox/rp.session.lucille1.mingtaiha.016736.0005-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 6139, in bootstrap_3
    nodeip = LRMS.hostip(cfg.get('network_interface'))
  File "/home/mingtaiha/radical.pilot.sandbox/rp.session.lucille1.mingtaiha.016736.0005-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 2459, in hostip
    ip = netifaces.ifaddresses(pref)[af][0]['addr']
KeyError: 2
2015-10-28 12:21:04,802: agent_0.bootstrap_3 : MainProcess                     : MainThread     : ERROR   : FAILED startup
2015-10-28 12:21:04,802: agent_0.bootstrap_3 : MainProcess                     : MainThread     : ERROR   :   File "/home/mingtaiha/radical.pilot.sandbox/rp.session.lucille1.mingtaiha.016736.0005-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 6139, in bootstrap_3
    nodeip = LRMS.hostip(cfg.get('network_interface'))
  File "/home/mingtaiha/radical.pilot.sandbox/rp.session.lucille1.mingtaiha.016736.0005-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 2459, in hostip
    ip = netifaces.ifaddresses(pref)[af][0]['addr']
```

**Comment by marksantcroos** [comment]
Can you paste the output of `ifconfig` here?

**Comment by mingtaiha** [comment]
Here's the ifconfig

```
mingtaiha@lucille1:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr 30:65:ec:70:5d:48  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:6517 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6517 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1547776 (1.5 MB)  TX bytes:1547776 (1.5 MB)

wlan0     Link encap:Ethernet  HWaddr 5c:93:a2:9a:a7:11  
          inet addr:192.168.239.171  Bcast:192.168.239.255  Mask:255.255.248.0
          inet6 addr: fe80::5e93:a2ff:fe9a:a711/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:714 errors:0 dropped:0 overruns:0 frame:0
          TX packets:259 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:195616 (195.6 KB)  TX bytes:53264 (53.2 KB)

```

**Comment by marksantcroos** [comment]
That explains it ...
Temporary workaround would be to plug in a cable :-)
Let me think about the real solution though ...

**Comment by mingtaiha** [comment]
Alright thanks!

**Comment by marksantcroos** [comment]
Btw, besides the auto-detection (with room for improvement), the interface can be specified in the agent config. There are a couple of ways to change the agent config, but probably the most straight forward is the following.

You can make a copy of src/radical/pilot/configs/agent_default.json and add an entry with the name of the appropriate interface :
```
    # interface for binding zmq to
    "network_interface"    : "wlan0",
```

You then have to let RP know that it should use that file that you just created as the agent config by setting an environment variable:
```
export RADICAL_PILOT_AGENT_CONFIG="/path/to/file/you/created"
```

After that it should pick up the right interface when you rerun your example.

**Comment by andre-merzky** [comment]
Shouldn't that go to the resource config?  Then it's also easier to augment that with a partial overwrite in `~/.radical/pilot/configs/resource_local.json`:

``` 
{
    "localhost" : {
        "network_interface" : "wlan0"
    }
}
```

**Comment by andre-merzky** [comment]
This has been addressed -- this should now work more reliably.  Please reopen if the problem persists.
