### ISSUE TITLE
/feature/osgng : Failed with file transfer error

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.pilot#891]
Here are the versions of the relevant software:

rp-version: 0.34, feature/osgng
saga: 0.37
utils: 037

I tried to examples/getting_started_osg.py. It failed with the following error:

```
Traceback (most recent call last):
  File "/home/mingtaiha/ve.aimes/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 724, in run
    pilotjob.run()
  File "/home/mingtaiha/ve.aimes/local/lib/python2.7/site-packages/saga/job/job.py", line 462, in run
    return self._adaptor.run (ttype=ttype)
  File "/home/mingtaiha/ve.aimes/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/mingtaiha/ve.aimes/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py", line 1099, in run
    self._id = self.js._job_run(self.jd)
  File "/home/mingtaiha/ve.aimes/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py", line 464, in _job_run
    self._handle_file_transfers(jd)
  File "/home/mingtaiha/ve.aimes/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py", line 608, in _handle_file_transfers
    raise Exception('Condor accepts only filenames (without paths) as FileTransfer targets: %s' % target)
```

Full Error message available upon request.

**Comment by marksantcroos** [comment]
You need SAGA branch feature/osg.

**Comment by mingtaiha** [comment]
I installed that branch and there seems to be no errors. Thanks!
