### ISSUE TITLE
rp installation fails

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#901]
Hello,
I am trying to install radicalpilot 0.37 and  I encountered the following error.

```
Traceback (most recent call last):
File "<string>", line 1, in <module>

File "/Users/giorgos/ve/build/radical.pilot/setup.py", line 131, in <module>
version, version_detail, sdist_name = get_version (mod_root)
File "/Users/giorgos/ve/build/radical.pilot/setup.py", line 120, in get_version
raise RuntimeError ('Could not extract/set version: %s' % e)

RuntimeError: Could not extract/set version: [Errno 2] No such file or directory: 'dist/radical.pilot-0.37.10.tar.gz'

Cleaning up...
Command /Users/giorgos/ve/bin/python -c "import setuptools;__file__='/Users/giorgos/ve/build/radical.pilot/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/b2/mk4fzhh14gn4c8mdt7rs46nh0000gn/T/pip-m20VLf-record/install-record.txt --single-version-externally-managed --install-headers /Users/giorgos/ve/include/site/python2.7 failed with error code 1 in /Users/giorgos/ve/build/radical.pilot
Storing complete log in /Users/giorgos/.pip/pip.log
```

**Comment by andre-merzky** [comment]
How are you trying to install, and what python distribution are you trying to use?  If you have an anaconda based distribution, please try again with devel.  Thanks!

**Comment by georgeha** [comment]
I am trying to install from master branch. I followed the instructions from the website (http://radicalpilot.readthedocs.org/en/stable/installation.html#requirements). Ι don't have anaconda, devel branch appears to work for me.

**Comment by andre-merzky** [comment]
Thanks!

Would you mind sending the output of the following commands, and also to send the exact sequence of commands  you have been using?  Thanks!

```
# uname -a
# python -V
# pip --version
# python -c 'import setuptools as s; print s.__version__'
# python -c 'import distutils as d; print d.__version__'
```

**Comment by georgeha** [comment]
#uname -a
Darwin gxatz.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
#python -V
Python 2.7.5
#pip --version
pip 7.1.2 from /Library/Python/2.7/site-packages (python 2.7)
#python -c 'import setuptools as s; print s.__version__'
0.6c12
#python -c 'import distutils as d; print d.__version__'
2.7.5

exact sequence of commands: 
virtualenv --system-site-packages $HOME/ve
source $HOME/ve/bin/activate
pip install radical.pilot
failed so then I tried:
pip install --upgrade pip==1.4.1
pip install --upgrade setuptools==0.6c11
pip install radical.pilot

**Comment by andre-merzky** [comment]
Would you mind trying once more without `--system-site-packages`, please?  I have no idea yet why the above would fail... :/

**Comment by georgeha** [comment]
it works! :) 
thank you andre

**Comment by andre-merzky** [comment]
Well, that is great :)  But if you don't mind, I would still like to dig a little, to understand what actually happened...

Could you run the above commands again, please, to see what (if anything) changed?

Thanks!

**Comment by georgeha** [comment]
Sure!
I activated the environment I created and run the commands.

#uname -a
Darwin gxatz.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
#python -V
Python 2.7.5
#pip --version
pip 1.5.6 from /Users/giorgos/ve2/lib/python2.7/site-packages (python 2.7)
#python -c 'import setuptools as s; print s.__version__'
3.6
#python -c 'import distutils as d; print d.__version__'
2.7.5

**Comment by iparask** [comment]
I also encountered the same error in a clean VE on the Amazon VM we have. For some reason the code in the if statement is not executed. On the other hand on my laptop in a clean VE everything installed as expected.

Just in case:
```
(BecksteinEnv)iparask@ip-10-184-31-85:~/experiments/LeafletFinder/Iteration2$ python -V
Python 2.7.6
(BecksteinEnv)iparask@ip-10-184-31-85:~/experiments/LeafletFinder/Iteration2$ pip --version
pip 7.1.2 from /home/iparask/BecksteinEnv/local/lib/python2.7/site-packages (python 2.7)
(BecksteinEnv)iparask@ip-10-184-31-85:~/experiments/LeafletFinder/Iteration2$ python -c 'import setuptools as s; print s.__version__'
18.2
(BecksteinEnv)iparask@ip-10-184-31-85:~/experiments/LeafletFinder/Iteration2$ python -c 'import distutils as d; print d.__version__'
2.7.6
````

**Comment by andre-merzky** [comment]
Iannis -- would you mind sending the exact commands to reproduce this on the VM?  Then I should hopefully be able to track this down...  Thanks!

**Comment by iparask** [comment]
There you go:

```
iparask@ip-10-184-31-85:~$ virtualenv RPinstTest
New python executable in RPinstTest/bin/python
Installing setuptools, pip, wheel...done.
iparask@ip-10-184-31-85:~$ source RPinstTest/bin/activate
(RPinstTest)iparask@ip-10-184-31-85:~$ pip install radical.pilot
Collecting radical.pilot
/home/iparask/RPinstTest/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting pymongo==2.8 (from radical.pilot)
Collecting radical.utils (from radical.pilot)
Collecting netifaces (from radical.pilot)
Collecting saga-python (from radical.pilot)
Collecting ntplib (from radical.pilot)
Collecting setproctitle (from radical.pilot)
Collecting pyzmq (from radical.pilot)
Collecting python-hostlist (from radical.pilot)
Collecting colorama (from radical.utils->radical.pilot)
Collecting apache-libcloud (from saga-python->radical.pilot)
  Using cached apache_libcloud-0.19.0-py2.py3-none-any.whl
Collecting backports.ssl-match-hostname (from apache-libcloud->saga-python->radical.pilot)
Installing collected packages: pymongo, colorama, radical.utils, netifaces, backports.ssl-match-hostname, apache-libcloud, saga-python, ntplib, setproctitle, pyzmq, python-hostlist, radical.pilot
Successfully installed apache-libcloud-0.19.0 backports.ssl-match-hostname-3.4.0.2 colorama-0.3.3 netifaces-0.10.4 ntplib-0.3.3 pymongo-2.8 python-hostlist-1.14 pyzmq-15.0.0 radical.pilot-0.37.10 radical.utils-0.38 saga-python-0.38.1 setproctitle-1.1.9
/home/iparask/RPinstTest/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
(RPinstTest)iparask@ip-10-184-31-85:~$ cd RP
RPinstTest/ RPnew/      
(RPinstTest)iparask@ip-10-184-31-85:~$ cd RP
RPinstTest/ RPnew/      
(RPinstTest)iparask@ip-10-184-31-85:~$ cd RP
RPinstTest/ RPnew/      
(RPinstTest)iparask@ip-10-184-31-85:~$ cd RPinstTest/
bin/     include/ lib/     local/   share/   
(RPinstTest)iparask@ip-10-184-31-85:~$ cd RPinstTest/
bin/     include/ lib/     local/   share/   
(RPinstTest)iparask@ip-10-184-31-85:~$ cd RPinstTest/
bin/     include/ lib/     local/   share/   
(RPinstTest)iparask@ip-10-184-31-85:~$ cd RPinstTest/
bin/     include/ lib/     local/   share/   
(RPinstTest)iparask@ip-10-184-31-85:~$ cd RPinstTest/lib/python2.7/
distutils/     encodings/     lib-dynload/   site-packages/ 
(RPinstTest)iparask@ip-10-184-31-85:~$ cd RPinstTest/lib/python2.7/site-packages/radical
radical/                         radical.pilot-0.37.10.dist-info/ radical.utils-0.38.dist-info/    
(RPinstTest)iparask@ip-10-184-31-85:~$ cd RPinstTest/lib/python2.7/site-packages/radical
radical/                         radical.pilot-0.37.10.dist-info/ radical.utils-0.38.dist-info/    
(RPinstTest)iparask@ip-10-184-31-85:~$ cd RPinstTest/lib/python2.7/site-packages/radical/pilot/
(RPinstTest)iparask@ip-10-184-31-85:~/RPinstTest/lib/python2.7/site-packages/radical/pilot$ ls
agent                          compute_pilot.pyc             configs        controller      __init__.pyc       resource_config.py   session.pyc             tests             utils
bootstrapper                   compute_unit_description.py   constants.py   db              logentry.py        resource_config.pyc  staging_directives.py   types.py          VERSION
compute_pilot_description.py   compute_unit_description.pyc  constants.pyc  exceptions.py   logentry.pyc       scheduler            staging_directives.pyc  types.pyc
compute_pilot_description.pyc  compute_unit.py               context.py     exceptions.pyc  pilot_manager.py   SDIST                states.py               unit_manager.py
compute_pilot.py               compute_unit.pyc              context.pyc    __init__.py     pilot_manager.pyc  session.py           states.pyc              unit_manager.pyc
(RPinstTest)iparask@ip-10-184-31-85:~/RPinstTest/lib/python2.7/site-packages/radical/pilot$ 
```

**Comment by andre-merzky** [comment]
Uhm, I don't see any error in what you pasted?

**Comment by iparask** [comment]
There is no error. But if you check the ls I did in the end there is no tarball.

That is what causes the error that George reported at the beginning

**Comment by andre-merzky** [comment]
Ah, I see,  right.  That is different than the error in the ticket though, which seems to hit during installation time, right?

**Comment by andre-merzky** [comment]
Well, I can confirm Iannis' problem on the VM.  It seems there is something changed wrt. the python installation, it now seems to build wheels:

```
Building wheels for collected packages: radical.pilot
  Running setup.py bdist_wheel for radical.pilot
...
```

This should be fixed in devel, with the check for `bdist_wheel` in setup.py.  I have no fucking clue why python would behave differently now -- probably some change in distutils or pip or whatever...  FWIW, things install clean from a local clone of the master branch, and that should be the same as the pypi version - but what do I know, I can't claim to understand what difference that would make to pip/setuptools/disutils/pypi/python ...  If you don't mind, please install from a local clone for now, and lets see how things got after the `bdist_wheel` change is released....

**Comment by andre-merzky** [comment]
ticket dies of old age...
