### ISSUE TITLE
Pilot launching failed (Could not detect shell prompt (timeout) on Stampede

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#909]
I try to run a RP script and it gives this error:

```
2015-11-23 01:13:32,323: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: ERROR   : Using bootstrapper /home/iparask/BecksteinEnv/lib/python2.7/site-packages/radical/pilot/bootstrapper/default_bootstrapper.sh
Copying bootstrapper 'file://localhost/home/iparask/BecksteinEnv/lib/python2.7/site-packages/radical/pilot/bootstrapper/default_bootstrapper.sh' to agent sandbox (<saga.filesystem.directory.Directory object at 0x7f1e41188a10>).
Copying sdist 'file://localhost/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/radical/utils/radical.utils-0.38.tar.gz' to sandbox (sftp://stampede.tacc.utexas.edu/work/03170/tg824689/radical.pilot.sandbox/rp.session.ip-10-184-31-85.iparask.016762.0005-pilot.0000/).
Copying sdist 'file://localhost/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/saga/saga-python-0.38.1.tar.gz' to sandbox (sftp://stampede.tacc.utexas.edu/work/03170/tg824689/radical.pilot.sandbox/rp.session.ip-10-184-31-85.iparask.016762.0005-pilot.0000/).
Copying sdist 'file://localhost/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/radical/pilot/controller/..//radical.pilot-v0.37.10-master.tar.gz' to sandbox (sftp://stampede.tacc.utexas.edu/work/03170/tg824689/radical.pilot.sandbox/rp.session.ip-10-184-31-85.iparask.016762.0005-pilot.0000/).
Writing agent configuration to file '/tmp/rp_agent_cfg_B2j9gB.json'.
Copying agent configuration file 'file://localhost/tmp/rp_agent_cfg_B2j9gB.json' to sandbox (sftp://stampede.tacc.utexas.edu/work/03170/tg824689/radical.pilot.sandbox/rp.session.ip-10-184-31-85.iparask.016762.0005-pilot.0000/).
Submitting SAGA job with description: {'Project': 'TG-MCB090174', 'Executable': '/bin/bash', 'TotalPhysicalMemory': None, 'WorkingDirectory': '/work/03170/tg824689/radical.pilot.sandbox/rp.session.ip-10-184-31-85.iparask.016762.0005-pilot.0000/', 'Queue': 'development', 'Environment': {}, 'WallTimeLimit': 60, 'Arguments': ['-l bootstrap_1.sh', " -d 'radical.utils-0.38.tar.gz:saga-python-0.38.1.tar.gz:radical.pilot-v0.37.10-master.tar.gz' -m 'create' -p 'pilot.0000' -r 'local' -s 'rp.session.ip-10-184-31-85.iparask.016762.0005' -v '/work/03170/tg824689/radical.pilot.sandbox/ve_stampede' -a 'multicore' -e 'module purge' -e 'module load TACC' -e 'module load intel/15.0.2' -e 'module load python/2.7.9' -e 'module unload xalt' -e 'source ~train00/ssi_sourceme' -e 'export TACC_DELETE_FILES=TRUE' -w 'export PATH=$PATH' -w 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH'"], 'ProcessesPerHost': None, 'Error': 'bootstrap_1.err', 'Output': 'bootstrap_1.out', 'TotalCPUCount': 16}
Pilot launching failed! (Could not detect shell prompt (timeout) (/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +285 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)")))
Traceback (most recent call last):
  File "/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 736, in run
    pilotjob.run()
  File "/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/saga/job/job.py", line 462, in run
    return self._adaptor.run (ttype=ttype)
  File "/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 1207, in run
    self._id = self.js._job_run (self.jd)
  File "/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 600, in _job_run
    self.shell.write_to_remote (src=slurm_script, tgt=tgt)
  File "/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 843, in write_to_remote
    raise ptye.translate_exception (e)
NoSuccess: Could not detect shell prompt (timeout) (/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +285 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
2015-11-23 01:13:33,011: radical.pilot       : MainProcess                     : Thread-1       : INFO    : ComputePilot 'pilot.0000' state changed from 'Launching' to 'Failed'.
2015-11-23 01:13:33,011: radical.pilot       : MainProcess                     : Thread-1       : INFO    : [Callback]: ComputePilot 'pilot.0000' state: Failed.
2015-11-23 01:13:33,012: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : pilot manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 335, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/iparask/BecksteinEnv/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "leaflet_finder.py", line 34, in pilot_state_cb
    sys.exit (1)
SystemExit: 1
```
There aren't any log files in the sandbox.

**Comment by marksantcroos** [comment]
Thats on SAGA level. Can you please provide output with `RADICAL_SAGA_VERBOSE=DEBUG`?

**Comment by andre-merzky** [comment]
outdated.
