### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.pilot#930]
Hello,

I try to run using the spark branch 00_getting_started.py and I get the following error. Any ideas?

Thank you

================================================================================
 Getting Started (RP version v0.37.10)                                          
================================================================================

                                                                             err
2015-12-16 16:24:35,245: radical.pilot       : MainProcess                     : MainThread     : ERROR   : session create failed
Traceback (most recent call last):
  File "/Users/giorgos/spark_env/lib/python2.7/site-packages/radical/pilot/session.py", line 136, in __init__
    ru.reset_id_counters(prefix=['pmgr', 'umgr', 'pilot', 'unit', 'unit.%(counter)06d'])
AttributeError: 'module' object has no attribute 'reset_id_counters'
Traceback (most recent call last):
  File "00_getting_started.py", line 37, in <module>
    session = rp.Session()
  File "/Users/giorgos/spark_env/lib/python2.7/site-packages/radical/pilot/session.py", line 156, in __init__
    % (self._dburl, ex))  
radical.pilot.exceptions.PilotException: Couldn't create new session (database URL 'mongodb://localhost:27017/george' incorrect?): 'module' object has no attribute 'reset_id_counters

**Comment by marksantcroos** [comment]
You need the devel branch of radical.utils (generally you need the devel branch of saga and radical.utils for every non released version of RP)

**Comment by georgeha** [comment]
Thanks mark!
