### ISSUE TITLE
SuperMIC pilots fails with compute_unit module error

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#932]
Reproduced with both master and devel. When submitting two pilots on SuperMIC the first fails with:
```
Python 2.7.7 :: Continuum Analytics, Inc.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/worka/work/mturilli/radical.pilot.sandbox/ve_supermic/rp_install/lib/python2.7/site-packages/radical/pilot/__init__.py", line 26, in <module>
    
  File "/worka/work/mturilli/radical.pilot.sandbox/ve_supermic/rp_install/lib/python2.7/site-packages/radical/pilot/session.py", line 23, in <module>
    from .unit_manager    import UnitManager
  File "/worka/work/mturilli/radical.pilot.sandbox/ve_supermic/rp_install/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 25, in <module>
    from .compute_unit import ComputeUnit
ImportError: No module named compute_unit
```
The second executes normally.

**Comment by andre-merzky** [comment]
Matteo, I think supermic is working by now?

**Comment by andre-merzky** [comment]
closing as outdated.
