### ISSUE TITLE
allocation problem

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.pilot#939]
Hi, 
radical.pilot doesn't allocate for me, but just sometimes. Everything worked just before and I didn't changing anything in between. I was running this with tmux, and internet connection was working. Can you help me what this means?

```
Starting Allocation2016-01-02 14:11:44,340: radical.pilot       : MainProcess                     : MainThread     : ERROR   : session create failed
Traceback (most recent call last):
  File "/Users/eh/myenv5/lib/python2.7/site-packages/radical/pilot/session.py", line 150, in __init__
    dburl = dburl)
  File "/Users/eh/myenv5/lib/python2.7/site-packages/radical/pilot/db/database.py", line 54, in __init__
    mongo, db, _, _, _ = ru.mongodb_connect(str(dburl))
  File "/Users/eh/myenv5/lib/python2.7/site-packages/radical/utils/misc.py", line 93, in mongodb_connect
    mongo = pymongo.MongoClient (host=host, port=port, ssl=ssl)
  File "/Users/eh/myenv5/lib/python2.7/site-packages/pymongo/mongo_client.py", line 377, in __init__
    raise ConnectionFailure(str(e))
ConnectionFailure: timed out
Traceback (most recent call last):
  File "01_static_gromacs_lsdmap_loop.py", line 239, in <module>
    cluster.allocate()
  File "/Users/eh/myenv5/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 157, in allocate
    self._session = radical.pilot.Session(database_url=self._database_url)
  File "/Users/eh/myenv5/lib/python2.7/site-packages/radical/pilot/session.py", line 165, in __init__
    % (self._dburl, ex))  
AttributeError: 'Session' object has no attribute '_dburl
```

**Comment by vivek-bala** [comment]
Hey, what mongodb url are you using ?

**Comment by andre-merzky** [comment]
hi @euhruska -- the specific error message you see (`'Session' object has no attribute '_dburl'`) has recently been fixed, but is not yet release I believe.  Vivek is right though -  the underlying problem is likely related to the MongoDB setup.

**Comment by euhruska** [comment]
it's 'mongodb://ec2-54-221-194-147.compute-1.amazonaws.com:24242/vivek'

**Comment by andre-merzky** [comment]
Ah - I am afraid we had to take that MongoDB instance down for a while.  Vivek may be able to help you with a different instance, or give you a pointer on how to run your own.  Another alternative if using the free tier of `http://mongolab.com`.

**Comment by euhruska** [comment]
I will try my own MongoDB instance

**Comment by andre-merzky** [comment]
Ok,  I'll close this ticket then for the time being.  Please don't hesitate to open a new one if you have trouble with the setup!

**Comment by euhruska** [comment]
Looks like it works now

**Comment by andre-merzky** [comment]
Excellent - thanks for the confirmation!
