### ISSUE TITLE
can't pass database url

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.pilot#948]
Tried to pass with:
```
export RADICAL_PILOT_DBURL="dburl"
```

and export directly:
```
session = radical.pilot.Session(database_url=dburl)
```

result:
```
================================================================================
 Getting Started (RP version v0.39.RC1)                                         
================================================================================

                                                                             err
2016-01-21 21:18:59,288: radical.pilot       : MainProcess                     : MainThread     : ERROR   : session create failed
Traceback (most recent call last):
  File "/home/antons/ve/local/lib/python2.7/site-packages/radical/pilot/session.py", line 138, in __init__
    ru.reset_id_counters(prefix=['pmgr', 'umgr', 'pilot', 'unit', 'unit.%(counter)06d'])
AttributeError: 'module' object has no attribute 'reset_id_counters'
Traceback (most recent call last):
  File "00_getting_started.py", line 39, in <module>
    session = rp.Session()
  File "/home/antons/ve/local/lib/python2.7/site-packages/radical/pilot/session.py", line 166, in __init__
    % (self._dburl, ex))  
radical.pilot.exceptions.PilotException: Couldn't create new session (database URL 'None' incorrect?): 'module' object has no attribute 'reset_id_counters'
```

**Comment by marksantcroos** [comment]
This looks more like a version mismatch than anything to do with database.
How did you install?

**Comment by marksantcroos** [comment]
And what's the output of the following commands?
```
radical-utils-version
radicalpilot-version
sagapython-version
```

**Comment by marksantcroos** [comment]
We need a RU release.

**Comment by andre-merzky** [comment]
Ah bugger, the multi-session-fix :/  Thanks, I'll prepare a release candidate tag and update the test protocol...
