### ISSUE TITLE
03_multiple_pilots.py fails on BlueWaters

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.pilot#953]
RP 0.39RC1
OS X 10.11.3

```
2016-01-25 16:03:58,923: radical.saga.pty    : MainProcess                     : PilotLauncherWorker-1: ERROR   : unexpected EOF (exec: /usr/bin/gsissh: No such file or directory
Couldn't send packet: Broken pipe
) (/Users/mturilli/Virtualenvs/RP_0.39/lib/python2.7/site-packages/saga/utils/pty_process.py +606 (read)  :  raise se.NoSuccess ("unexpected EOF (%s)" % self.tail))
Traceback (most recent call last):
  File "/Users/mturilli/Virtualenvs/RP_0.39/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 261, in _initialize_pty
    n, match = pty_shell.find (prompt_patterns, delay)
  File "/Users/mturilli/Virtualenvs/RP_0.39/lib/python2.7/site-packages/saga/utils/pty_process.py", line 790, in find
    raise ptye.translate_exception (e, "(%s)" % data)
NoSuccess: unexpected EOF (exec: /usr/bin/gsissh: No such file or directory
Couldn't send packet: Broken pipe
) (/Users/mturilli/Virtualenvs/RP_0.39/lib/python2.7/site-packages/saga/utils/pty_process.py +606 (read)  :  raise se.NoSuccess ("unexpected EOF (%s)" % self.tail))
```
Note that gsissh is installed via homebrew and is located at ```/usr/local/bin/gsissh```

**Comment by marksantcroos** [comment]
Whats the output of `gsisftp bw.ncsa.illinois.edu` in the same window?

**Comment by mturilli** [comment]
```
$ gsisftp bw.ncsa.illinois.edu
exec: /usr/bin/gsissh: No such file or directory
Connection closed
```
It seems we have found a bug with homebrew then ;)

**Comment by marksantcroos** [comment]
Try `export GLOBUS_LOCATION=/usr/local/bin`

**Comment by mturilli** [comment]
```
$ export GLOBUS_LOCATION=/usr/local/bin
 gsisftp bw.ncsa.illinois.edu
/usr/local/bin/etc/ssh not found.
exec: /usr/local/bin/bin/gsissh: No such file or directory
Connection closed
$ export GLOBUS_LOCATION=/usr/local
$ gsisftp bw.ncsa.illinois.edu
/usr/local/etc/ssh not found.
/usr/local/etc/ssh not found.

Access by OTP or Two Factor Certificate Authority only.
Use myproxy-logon -s tfca.ncsa.illinois.edu -p 7512 for gsissh access.
gsissh or ssh -o PreferredAuthentications=keyboard-interactive for otp access.

Connected to bw.ncsa.illinois.edu.
sftp>
```

**Comment by marksantcroos** [comment]
> $ export GLOBUS_LOCATION=/usr/local

Right, sorry for that.

**Comment by marksantcroos** [comment]
FWIW: the globus toolkit "download" is pretty decent for OSX nowadays.

**Comment by mturilli** [comment]
Test passed with ```export GLOBUS_LOCATION=/usr/local```
