### ISSUE TITLE
MPI example: Forced shutdown of application 

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [radical-cybertools/radical.pilot#961]
When running the `mpi_tasks.py` example, the process terminates with exit code `0` but I get the following when running it right out of the box:

```
`On mpi_tasks.py, get forced shutdown of application because CU couldn't start.` 
`Error:`
`stderr:`
`Pilot cannot start compute unit:`
`no launcher (mpi=True)`
`Traceback (most recent call last):`
    `File "/home/nrs76/radical.pilot.sandbox/rp.session.ip-10-184-31-85.nrs76.016832.0013-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line     3782, in work`
`raise RuntimeError("no launcher (mpi=%s)" % cu['description']['mpi'])`
`RuntimeError: no launcher (mpi=True)`
`2016-02-01 21:50:57,177: radical.pilot       : MainProcess                     : Thread-3       : ERROR   : unit manager controller thread caught system exit -- forcing application shutdown`

`Traceback (most recent call last):`
    `File "/home/nrs76/envs/yo/local/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 261, in run self.call_unit_state_callbacks(unit_id, new_state)`
    `File "/home/nrs76/envs/yo/local/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 198, in call_unit_state_callbacks`
        `cb(self._shared_data[unit_id]['facade_object'], new_state)`
    `File "mpi_tasks.py", line 46, in unit_state_cb`
        `sys.exit(2)`
`SystemExit: 2`
```

**Comment by andre-merzky** [comment]
Hi Nikhil, 

first of all : with triple backticks ``` on a single line you can mark the begin and and of a quotes section, then you  don't need to mark every line in a ticket :)

```
begin of code section
still code
the end is near
```

But, second and more on topic: this seems indeed be caused by running the MPI example agains a backend where no mpirun is available (`no launcher (mpi=True)`).  Feel free to  ignore that test result then!

Thanks, Andre.
