### ISSUE TITLE
Problem with ssh verification

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [radical-cybertools/radical.pilot#964]
My problem is with running RP with my current ssh configuration. I have been able to set up password-less ssh to Stampede, and I am able to get in using the standard ssh command and an alias that I have for it. I have only one ssh key pair, and I have added the following to my `/etc/ssh/ssh_config`:

```
`Host stampede.tacc.utexas.edu`
        `Hostname stampede.tacc.utexas.edu`
        `User tg826231`

Despite all of this, I cannot run an RP script or an EnMD script. I keep getting an error that says that my ssh credentials could not be verified. Here is the error:

`        |2016-02-16 17:46:03,937: radical.saga.cpi    : MainProcess`
`PilotLauncherWorker-1: ERROR   : NoSuccess: Couldn't get job id from submitted job! sbatch`
`output:`
`-----------------------------------------------------------------`
`              Welcome to the Stampede Supercomputer              `
`-----------------------------------------------------------------`

`--> Verifying valid submit host (login4)...OK`
`--> Verifying valid jobname...OK`
`--> Enforcing max jobs per user...OK`
`--> Verifying availability of your home dir (/home1/03324/tg826231)...OK`
`--> Verifying availability of your work dir (/work/03324/tg826231)...OK`
`--> Verifying availability of your scratch dir (/scratch/03324/tg826231)...OK`
`--> Verifying valid ssh keys...`

`Unable to verify ssh configuration. Please update your ssh key`
`configuration or contact TACC consulting for assistance.`

`removed `tmp_M1xsaK.slurm'`

`2016-02-16 17:46:03,987: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: `
`ERROR   : Using bootstrapper /home/shenoy/envs/scaling/lib/python2.7/site-packages/radical/pilot`
`/bootstrapper/bootstrap_1.sh`
`Copying bootstrapper 'file://localhost/home/shenoy/envs/scaling/lib/python2.7/site-packages/radical`
`/pilot/bootstrapper/bootstrap_1.sh' to agent sandbox (<saga.filesystem.directory.Directory object at 0x7f5658674750>).`
`Copying sdist 'file://localhost/home/shenoy/envs/scaling/local/lib/python2.7/site-packages/radical/utils/radical.utils-0.40.tar.gz' to sandbox (sftp://stampede.tacc.utexas.edu/work/03324/tg826231/radical.pilot.sandbox/rp.session.shenoy-ThinkPad-T410.shenoy.016847.0007-pilot.0000/).`
`Copying sdist 'file://localhost/home/shenoy/envs/scaling/local/lib/python2.7/site-packages/saga/saga-python-0.40.1.tar.gz' to sandbox (sftp://stampede.tacc.utexas.edu/work/03324/tg826231/radical.pilot.sandbox/rp.session.shenoy-ThinkPad-T410.shenoy.016847.0007-pilot.0000/).`
Copying sdist 'file://localhost/home/shenoy/envs/scaling/local/lib/python2.7/site-packages/radical/pilot/controller/..//radical.pilot-0.40.1.tar.gz' to sandbox (sftp://stampede.tacc.utexas.edu/work/03324/tg826231/radical.pilot.sandbox/rp.session.shenoy-ThinkPad-T410.shenoy.016847.0007-pilot.0000/).
Writing agent configuration to file '/tmp/rp_agent_cfg_dirIRhSPg/agent_0.cfg'.
Copying agent configuration file 'file://localhost/tmp/rp_agent_cfg_dirIRhSPg/agent_0.cfg' to sandbox (sftp://stampede.tacc.utexas.edu/work/03324/tg826231/radical.pilot.sandbox/rp.session.shenoy-ThinkPad-T410.shenoy.016847.0007-pilot.0000/).
Submitting SAGA job with description: {'Project': 'TG-MCB090174', 'Executable': '/bin/bash', 'TotalPhysicalMemory': None, 'WorkingDirectory': '/work/03324/tg826231/radical.pilot.sandbox/rp.session.shenoy-ThinkPad-T410.shenoy.016847.0007-pilot.0000/', 'Queue': 'development', 'Environment': {}, 'WallTimeLimit': 15, 'Arguments': ['-l bootstrap_1.sh', " -d 'radical.utils-0.40.tar.gz:saga-python-0.40.1.tar.gz:radical.pilot-0.40.1.tar.gz' -m 'create' -p 'pilot.0000' -r 'local' -s 'rp.session.shenoy-ThinkPad-T410.shenoy.016847.0007' -v '/work/03324/tg826231/radical.pilot.sandbox/ve_stampede' -b 'default' -a 'multicore' -e 'module purge' -e 'module load TACC' -e 'module load intel/15.0.2' -e 'module load python/2.7.9' -e 'module unload xalt' -e 'source ~train00/ssi_sourceme' -e 'export TACC_DELETE_FILES=TRUE' -w 'export PATH=$PATH' -w 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH'"], 'ProcessesPerHost': None, 'Error': 'bootstrap_1.err', 'Output': 'bootstrap_1.out', 'CandidateHosts': None, 'TotalCPUCount': 64}
Pilot launching failed! (Couldn't get job id from submitted job! sbatch output:
-----------------------------------------------------------------
              Welcome to the Stampede Supercomputer              
-----------------------------------------------------------------

--> Verifying valid submit host (login4)...OK
--> Verifying valid jobname...OK
--> Enforcing max jobs per user...OK
--> Verifying availability of your home dir (/home1/03324/tg826231)...OK
--> Verifying availability of your work dir (/work/03324/tg826231)...OK
--> Verifying availability of your scratch dir (/scratch/03324/tg826231)...OK
--> Verifying valid ssh keys...

Unable to verify ssh configuration. Please update your ssh key
configuration or contact TACC consulting for assistance.

removed `tmp_M1xsaK.slurm'
 (/home/shenoy/envs/scaling/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py +626 (_job_run)  :  " sbatch output:\n%s" % out)))
Traceback (most recent call last):
  File "/home/shenoy/envs/scaling/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 782, in run
    pilotjob.run()
  File "/home/shenoy/envs/scaling/local/lib/python2.7/site-packages/saga/job/job.py", line 462, in run
    return self._adaptor.run (ttype=ttype)
  File "/home/shenoy/envs/scaling/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/shenoy/envs/scaling/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 1213, in run
    self._id = self.js._job_run (self.jd)
  File "/home/shenoy/envs/scaling/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 626, in _job_run
    " sbatch output:\n%s" % out)
NoSuccess: Couldn't get job id from submitted job! sbatch output:
-----------------------------------------------------------------
              Welcome to the Stampede Supercomputer              
-----------------------------------------------------------------

--> Verifying valid submit host (login4)...OK
--> Verifying valid jobname...OK
--> Enforcing max jobs per user...OK
--> Verifying availability of your home dir (/home1/03324/tg826231)...OK
--> Verifying availability of your work dir (/work/03324/tg826231)...OK
--> Verifying availability of your scratch dir (/scratch/03324/tg826231)...OK
--> Verifying valid ssh keys...

Unable to verify ssh configuration. Please update your ssh key
configuration or contact TACC consulting for assistance.

removed `tmp_M1xsaK.slurm'
 (/home/shenoy/envs/scaling/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py +626 (_job_run)  :  " sbatch output:\n%s" % out))
/2016-02-16 17:46:04,431: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : [Callback]: ComputePilot 'pilot.0000' failed -- calling exit
2016-02-16 17:46:04,432: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/home/shenoy/envs/scaling/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 236, in call_callbacks
    cb_func(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/shenoy/envs/scaling/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 251, in _default_pilot_error_cb
    sys.exit(1)
SystemExit: 1
`
```

**Comment by andre-merzky** [comment]
[quick note: triple backticks create block quote in ticket messages:

```
` ` `
 text goes here (remove spaces around backticks though!)
` ` `
```

To your problem: 

```
Verifying valid ssh keys...

Unable to verify ssh configuration. Please update your ssh key
configuration or contact TACC consulting for assistance.
```

This looks like a problem on stampede itself, not on the connection from your laptop to stampede.  Do you have any specific ssh setup or files on stampede?   It might indeed be worthwhile to contact TACC support, as the message suggests...

**Comment by Nikhil-Shenoy** [comment]
No, I don't have anything special on Stampede.

**Comment by andre-merzky** [comment]
Yeah, then please open a ticket on TACC/XSEDE, and let us know what comes out of that...  Thanks!

**Comment by andre-merzky** [comment]
Closing due to lack of feedback.
