### ISSUE TITLE
get_logger

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.pilot#982]
I tried installing the current devel, and something with the get_logger is wrong.

```
Traceback (most recent call last):
  File "00_getting_started.py", line 11, in <module>
    import radical.pilot as rp
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/radical/pilot/__init__.py", line 20, in <module>
    from .scheduler  import *
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/radical/pilot/scheduler/__init__.py", line 14, in <module>
    from direct_submission import DirectSubmissionScheduler
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/radical/pilot/scheduler/direct_submission.py", line 16, in <module>
    from ..utils    import logger
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/radical/pilot/utils/__init__.py", line 11, in <module>
    logger = ru.get_logger('radical.pilot')
AttributeError: 'module' object has no attribute 'get_logger'
```

**Comment by andre-merzky** [comment]
Please do also install the devel versions of radical.utils and saga-python.  We often develop those layers concurrently -- and you happen to hit a point where RP depends on an RU level API change.  Sorry for that!

**Comment by marksantcroos** [comment]
Can you provide the output of:
``` bash
radicalpilot-version 
radical-utils-version 
sagapython-version 
```

**Comment by shantenujha** [comment]
Andre -- this is not  a desirable situation. Would it be better to guide euhruska to an earlier version of RP ?

**Comment by vivek-bala** [comment]
Hey Eugene, just out of curiosity, any particular reason why you are interested in the devel branch of RP (as EnsembleMD installs the stable RP version) ? Just that devel might be changing quite frequently and (possibly) throw you into more errors.

**Comment by andre-merzky** [comment]
@shantenujha 

We are pretty confident that this is a version mixup.  `get_logger()` is [defined](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/__init__.py#L24) in RU.  It is actually also released since [v0.36](https://github.com/radical-cybertools/radical.utils/blob/v0.36/src/radical/utils/__init__.py) (September '15), which seems to indicate that the used RU version is older than that.

Yes, we could point to an earlier version -- but until we know what specific SAGA and RU versions are installed, its hard to say which one.  So Mark's request for the version info makes sense.  Either we are able to pinpoint why the utils version mismatches, or we can otherwise point to a valid version.

**Comment by andre-merzky** [comment]
I agree: if possible use the released version.  But @vivek, the last couple of [releases](https://github.com/radical-cybertools/radical.pilot/blob/v0.36/src/radical/pilot/session.py#L82) of RP also use `get_logger()`, so that switch in itself will not help to resolve the problem I think.

**Comment by euhruska** [comment]
my versions:
radicalpilot-version 
v0.40.1-22-ge1f4683@devel
radical-utils-version 
v0.40-10-g031caad@devel
sagapython-version 
v0.40.1-3-ge00612b@devel

I wanted to rp for profiling/scaling of NTL9

**Comment by andre-merzky** [comment]
Hmm, that does not match the error :(  Your original message indicates that utils are picked up from `/usr/local/Cellar/python/2.7.9/` -- is that indeed the path you installed to (opposed to some  virtualenv or so)?

**Comment by vivek-bala** [comment]
@euhruska Just wanted to mention that if this is related to the experiments for the extasy paper, EnsembleMD can give you the profiling data (as discussed via email earlier).

**Comment by euhruska** [comment]
Yep, it's installed in /usr/local/Cellar/python/2.7.9/ via git clone and python setup.py install.
@vivek-bala the gromacs-lsdmap workflow or simple example workflow give this error.
Interestingly, when in virtualenv, it works.

**Comment by andre-merzky** [comment]
@euhruska I'm glad to hear it works in the virtualenv!

If you still want to dig into why the system install fails, would you please send the output of these commands:

```
$ python
>>> import radical.utils as ru
>>> ru.version_detail
>>> ru.__file__
>>> dir(ru)
>>> import radical.pilot as rp
>>> rp.version_detail
>>> rp.__file__
```

I assume that the RP import will again fail, but I hope the commands before tell us where it tries to pull the bogus RU from...

Thanks, Andre.

**Comment by euhruska** [comment]
Ok, that helped. I found another 0.35 installation along the 0.40 version. I hard deleted all of them and reinstalled. Now it works. Though I have no idea why the   0.40 version didn't overwrite the 0.35 installation.

**Comment by vivek** [comment]
You got wrong vivek:)

**Comment by euhruska** [comment]
But something is still wrong:
```RADICAL_ENMD_VERBOSE=debug python 00_getting_started.py

================================================================================
 Getting Started (RP version v0.40.1)                                           
================================================================================

new session: [rp.session.EugenHruska.local.eh.016871.0006]                     \
database   : [mongodb://eh22:a3Qv*zs0@ds037185.mongolab.com:37185/clementigroup]
        ok
read config                                                                   ok

--------------------------------------------------------------------------------
submit pilots                                                                   

create pilot manager                                                          ok
create pilot description [local.localhost:64]                                 ok
submit 1 pilot(s) .                                                           ok

--------------------------------------------------------------------------------
submit units                                                                    

create unit manager                                                           ok
add 1 pilot(s)                                                                ok
create 128 unit description(s)
        ........................................................................
        ........................................................              ok
submit 128 unit(s)
        ........................................................................
        .......2016-03-11 11:17:33,589: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: ERROR   : Using bootstrapper /usr/local/lib/python2.7/site-packages/radical.pilot-0.40.1-py2.7.egg/radical/pilot/bootstrapper/bootstrap_1.sh
Copying bootstrapper 'file://localhost/usr/local/lib/python2.7/site-packages/radical.pilot-0.40.1-py2.7.egg/radical/pilot/bootstrapper/bootstrap_1.sh' to agent sandbox (<saga.filesystem.directory.Directory object at 0x10e06efd0>).
Copying sdist 'file://localhost/usr/local/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/radical.utils-v0.40-10-g031caad-devel.tar.gz' to sandbox (file://localhost/Users/eh/radical.pilot.sandbox/rp.session.EugenHruska.local.eh.016871.0006-pilot.0000/).
Pilot launching failed! (copy (file://localhost/usr/local/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/radical.utils-v0.40-10-g031caad-devel.tar.gz -> file://localhost/Users/eh/radical.pilot.sandbox/rp.session.EugenHruska.local.eh.016871.0006-pilot.0000/radical.utils-v0.40-10-g031caad-devel.tar.gz) failed (1): (out: cp: /usr/local/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/radical.utils-v0.40-10-g031caad-devel.tar.gz: No such file or directory
) (err: None) (/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/saga_python-0.40.1-py2.7.egg/saga/adaptors/shell/shell_file.py +531 (copy)  :  % (src, tgt, ret, out, err))))
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/radical.pilot-0.40.1-py2.7.egg/radical/pilot/controller/pilot_launcher_worker.py", line 592, in run
    sandbox_tgt.copy(sdist_url, os.path.basename(str(sdist_url)))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/saga_python-0.40.1-py2.7.egg/saga/namespace/directory.py", line 353, in copy
    if url_2  :  return self._adaptor.copy (url_1, url_2, flags, ttype=ttype)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/saga_python-0.40.1-py2.7.egg/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/saga_python-0.40.1-py2.7.egg/saga/adaptors/shell/shell_file.py", line 531, in copy
    % (src, tgt, ret, out, err))
NoSuccess: copy (file://localhost/usr/local/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/radical.utils-v0.40-10-g031caad-devel.tar.gz -> file://localhost/Users/eh/radical.pilot.sandbox/rp.session.EugenHruska.local.eh.016871.0006-pilot.0000/radical.utils-v0.40-10-g031caad-devel.tar.gz) failed (1): (out: cp: /usr/local/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/radical.utils-v0.40-10-g031caad-devel.tar.gz: No such file or directory
) (err: None) (/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/saga_python-0.40.1-py2.7.egg/saga/adaptors/shell/shell_file.py +531 (copy)  :  % (src, tgt, ret, out, err)))
...2016-03-11 11:17:33,627: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : [Callback]: ComputePilot 'pilot.0000' failed -- calling exit
.....2016-03-11 11:17:33,627: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/radical.pilot-0.40.1-py2.7.egg/radical/pilot/controller/pilot_manager_controller.py", line 236, in call_callbacks
    cb_func(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/radical.pilot-0.40.1-py2.7.egg/radical/pilot/pilot_manager.py", line 251, in _default_pilot_error_cb
    sys.exit(1)
SystemExit: 1
.exit requested

--------------------------------------------------------------------------------
finalize                                                                        

closing session rp.session.EugenHruska.local.eh.016871.0006                    \
close pilot manager                                                            \
wait for 1 pilot(s) -                                                         ok
                                                                              ok
close unit manager                                                            ok
session lifetime: 8.0s                                                        ok

--------------------------------------------------------------------------------
```

**Comment by andre-merzky** [comment]
@vivek : Oops!  Sorry for that, have a nice day! :)

**Comment by andre-merzky** [comment]
> Ok, that helped. I found another 0.35 installation along the 0.40 version. I hard deleted all of them and reinstalled. Now it works. Though I have no idea why the 0.40 version didn't overwrite the 0.35 installation.

Great, glad we found it!  Alas, I can't answer the 'why' -- python deployment remains a source of surprises it seems :P

**Comment by vivek** [comment]
Guys, can you remove me from your list? You are using wrong vive’s github handle.

**Comment by andre-merzky** [comment]
> But something is still wrong:

I think I can clarify that part: You will have to use `pip install` for our software stack -- other routes (`easy_install`, 'python setup.py install` etc) will miss to create some files which we need for remote reployment in radical.pilot.  We do support anaconda nowadays, but that part has not seen some exposure, yet: if you use anaconda, please let us know what commands you run, and we'll look into it.  Otherwise, I'll have to ask you to please try again with `pip`.  

Let us know how it goes! :)

**Comment by andre-merzky** [comment]
Hey @vivek - apologies again:/

Please go to https://github.com/radical-cybertools/radical.pilot/issues/982 and use the `unsubscribe` button on the right side.   I don't think we can unsubscribe you otherwise (or at least I don't know how...)

Best, Andre.
