### ISSUE TITLE
Multinode Spark fails on Stampede

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.pilot#985]
I am getting this error when I try to run the feature/spark on Stampede

```
2016-03-20 18:58:59,867: agent_0.bootstrap_3 : MainProcess                     : MainThread     : ERROR   : Error running agent: agent_0
Traceback (most recent call last):
  File "/work/03170/tg824689/radical.pilot.sandbox/ve_stampede/rp_install/bin/radical-pilot-agent-multicore.py", line 7893, in bootstrap_3
    agent = AgentWorker(cfg)
  File "/work/03170/tg824689/radical.pilot.sandbox/ve_stampede/rp_install/bin/radical-pilot-agent-multicore.py", line 7103, in __init__
    rpu.Worker.__init__(self, 'AgentWorker', cfg)
  File "/work/03170/tg824689/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 917, in __init__
    Component.__init__(self, ctype, cfg)
  File "/work/03170/tg824689/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 163, in __init__
    self._log = ru.get_logger(log_name, log_tgt, self._debug)
  File "/work/03170/tg824689/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/utils/logger.py", line 232, in get_logger
    level = level.upper()
AttributeError: 'int' object has no attribute 'upper'
```

I am starting to think that it is version problem. What version are you using for RADICAL-Utils and SAGA-Python?

**Comment by georgeha** [comment]
>>> import radical.utils as ru
>>> print ru.version
0.40
>>> import saga
>>> print saga.version
0.40.1

**Comment by iparask** [comment]
Okay. I am using the same. Tell me what you need to debug it.

**Comment by andre-merzky** [comment]
Hmm, @antonst reported something similar today.  Let me look into this.  What is the output of:

```
$ env | grep VERBOSE
$ env | grep LOG
```

for you?   Thanks!

**Comment by andre-merzky** [comment]
George, could you please try the radical.utils branch `fix/rp_985`?  Thanks, Andre.

**Comment by iparask** [comment]
I hope you mean offline:

```
login3.stampede(7)$ env | grep VERBOSE
login3.stampede(8)$ env | grep LOG
LOGNAME=tg824689
```

**Comment by andre-merzky** [comment]
Yes, antons reported that in a skype chat.  Thanks for the reply (And sorry for mixing up who reported! :) )  The RU branch I pointed to above should fix it, or so I hope.  Please let me know that indeed works, and I'll prepare a hotfix release for RU.

**Comment by georgeha** [comment]
Hi Andre,

Both the radical.utils fix/rp_985 and devel branch work for me.

**Comment by iparask** [comment]
Okay, the fix branch worked for me also!

**Comment by andre-merzky** [comment]
Great - I'll close this ticket the, and we'll release RU in a short while.

Thanks, Andre.
